### ISSUE TITLE
Feature: apply exec() or lean({virtuals: true}).exec() by default

### ISSUE THREAD

**Issue by kyrylkov** [Automattic/mongoose#10017]
It would be great to have a config option so that all methods are executed by default with `exec()` or `lean({virtuals: true}).exec()`.

In this way, they won't have to be appended to every call, which looks extremely verbose for no good reason.

**Comment by vkarpov15** [comment]
There's no need to add `exec()` so if you're using [async/await](https://asyncawait.net/) or [promises](https://masteringjs.io/tutorials/fundamentals/promise). The only benefit of using `exec()` is for better [async stack trace](https://thecodebarbarian.com/async-stack-traces-in-node-js-12) support because of how V8 handles custom thenables. For example, the below queries work fine:

```javascript
const doc = await Model.findOne();

Model.findOne().then(doc => console.log(doc));
```
