### ISSUE TITLE
Feature: Using AWS IAM Authentication with MongoDB in Atlas

### ISSUE THREAD

**Issue by dsaydon90** [Automattic/mongoose#10106]
Will you support AWS IAM Authentication with MongoDB in Atlas like MongodB client 4.4 has?

![image](https://user-images.githubusercontent.com/22152786/113590407-47657380-963b-11eb-80c9-d4074f609c07.png)
![image](https://user-images.githubusercontent.com/22152786/113590645-927f8680-963b-11eb-9f55-45d81c269bd6.png)

FYI - When I'm trying to initialize new mongoose client with the following uri params `autoSource=%24external&authMechanism=MONGODB-AWS`, I'm getting the error:
```
(node:2590) UnhandledPromiseRejectionWarning: MongoParseError: Invalid source `admin` for mechanism `MONGODB-AWS` specified.
    at applyAuthExpectations (/node_modules/mongodb/lib/core/uri_parser.js:376:15)
    at parseConnectionString (/node_modules/mongodb/lib/core/uri_parser.js:723:5)
    at QueryReqWrap.callback (/node_modules/mongodb/lib/core/uri_parser.js:120:7)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:205:10)
```

more here: 
https://docs.atlas.mongodb.com/security/manage-iam-roles/
https://www.youtube.com/watch?v=99iV9lCctrU
https://docs.mongodb.com/drivers/node/fundamentals/authentication/mechanisms/#mongodb-aws

mongoose version: 5.12.3
node version: v14.15.5

**Comment by vkarpov15** [comment]
Mongoose doesn't need to do anything to support AWS IAM auth, the MongoDB Node driver handles that for us. The issue is that your connection string is incorrect, note that the error message says "Invalid source **`admin`** for mechanism". That means the auth mechanism is supported, you're just using it incorrectly. You need to set `authSource=%24external` instead of `authSource=admin` in your connection string.
