### ISSUE TITLE
Save or update on concurrency error

### ISSUE THREAD

**Issue by tryhardest** [Automattic/mongoose#10136]
We came across a serious problem on the backend that will require some big changes to a lot of the current backend logic in our code so worth asking here first. We mostly use mongoose’s “save” method for updating changed documents, but we’re likely to have problems with that due to concurrency.

This answer describes the problem well: https://stackoverflow.com/a/57834827/7987987.

 I see this problem when I run on my local server, and it most often affects sending chat messages and posting new status updates. So it seems to me that it’s going to hamper an important part of the experience of using the app. Given how much of the backend logic will have to change were wondering best approach and if that's removing Mongoose. Changing all the places that use "save" to instead use "update" is one option.

There's a lot of associated logic, the save method allows you to do some things in code that "update" doesn't allow. So it's the associated logic that will eat up most of the time. And we have a hook for "save" that affects users, and there are some differences in the equivalent "update" hook that will need to be handled to port over the associated logic.

It appears optimistic concurrency is already on by default in the recent versions of mongoose, because that's the error I've been getting and it's the same behavior described in the article (throwing an error instead of trying to persist the update).

Is there no workaround to using the "save" method. It always has that issue of different versions throwing errors.

Thanks.

**Comment by vkarpov15** [comment]
[Optimistic concurrency is **not** on by default](https://thecodebarbarian.com/whats-new-in-mongoose-5-10-optimistic-concurrency.html), you need to enable it:

```javascript
const userSchema = Schema({
  status: {
    type: String,
    required: true,
    enum: ['PENDING', 'APPROVED', 'REJECTED']
  },
  avatar: {
    type: String,
    required: function() {
      return this.status === 'APPROVED';
    },
    validate: str => str == null || str.startsWith('https://')
  }
}, { optimisticConcurrency: true });
```

Does that help your issue? It's hard to understand what you're looking for if you don't specify what the expected behavior is - are you looking to disable concurrency control entirely because it is throwing errors, or are you looking to enable stricter concurrency control?

**Comment by CodeWithOz** [comment]
Thanks, the ideal is to remove the concurrency problems entirely. Am I correct in saying that using `Model.updateOne` (or `Model.updateMany`) would achieve that? Even if the concurrency controls are made more or less strict, I think the problem is that different versions of the same document will have problems syncing up if their properties are changed and `Model.prototype.save` is used to persist those changes.

**Comment by Textras** [comment]
@vkarpov15 that hopefully sums it up better? ^

**Comment by vkarpov15** [comment]
If you want to disable Mongoose's concurrency controls entirely, just do:

```javascript
const userSchema = Schema({
  status: {
    type: String,
    required: true,
    enum: ['PENDING', 'APPROVED', 'REJECTED']
  },
  avatar: {
    type: String,
    required: function() {
      return this.status === 'APPROVED';
    },
    validate: str => str == null || str.startsWith('https://')
  }
}, { versionKey: false });
```
