### ISSUE TITLE
How to insert data in reverse order in the create method

### ISSUE THREAD

**Issue by MadShura** [Automattic/mongoose#10151]
i found when use find() method  
return a arr sorted by time 
the model.create() method   is like arr.prototype.push() method  
but i want it like arr.prototype.unshift() method  
that i can use find() without sort({date:-1}) to sort the arr 
and t think is more efficient 
how can i do ?

i'm noob with broken english
thanks! have a good day!

**Comment by MadShura** [comment]
Mongoose-version      "mongoose": "^5.11.15",

**Comment by vkarpov15** [comment]
@MadShura if you don't use `sort()`, `find()` will return documents in [natural order](https://docs.mongodb.com/manual/reference/method/cursor.sort/#std-label-return-natural-order). In other words, order isn't guaranteed when you use `find()` without `sort()`, so your question isn't valid because `create()` doesn't necessarily add to the "end" of a collection.
