### ISSUE TITLE
Nest array search two syntax inconsistent behaviour

### ISSUE THREAD

**Issue by josephwong13** [Automattic/mongoose#10255]
NodeJS: v12.14.1
Mongoose: ^5.12.9
Mongo: 4.4.6

Behaviour: When trying to query the second element of an array field, the following two syntax return different result:

```
await Restaurant.find(
        {
            "grades.1": { 
                "grade": "A",
                "date": new Date("2014-08-11T00:00:00Z"),
                "score": 9
            }
        }
    ).lean()
    
```

The above query return nothing, while the following return one element:

```
await Restaurant.find(
        {
            "grades.1.grade": "A",
            "grades.1.date": new Date("2014-08-11T00:00:00Z"),
            "grades.1.score": 9
        }
    )
```

The expected result is both syntax should return the same result.

I find this issue when doing this exercise, to reproduce, insert the document to DB and try running the query:
https://www.w3resource.com/mongodb-exercises/mongodb-exercise-23.php

The expected document to be found:

```
{
    "_id" : ObjectId("60a0934844a0dc6633397998"),
    "address" : {
        "building" : "26",
        "coord" : [ 
            -73.9693615, 
            40.7658603
        ],
        "street" : "East   63 Street",
        "zipcode" : "10065"
    },
    "borough" : "Manhattan",
    "cuisine" : "American ",
    "grades" : [ 
        {
            "date" : ISODate("2015-01-12T00:00:00.000Z"),
            "grade" : "A",
            "score" : 10
        }, 
        {
            "date" : ISODate("2014-08-11T00:00:00.000Z"),
            "grade" : "A",
            "score" : 9
        }, 
        {
            "date" : ISODate("2014-01-14T00:00:00.000Z"),
            "grade" : "A",
            "score" : 13
        }, 
        {
            "date" : ISODate("2013-02-07T00:00:00.000Z"),
            "grade" : "A",
            "score" : 10
        }, 
        {
            "date" : ISODate("2012-04-30T00:00:00.000Z"),
            "grade" : "A",
            "score" : 11
        }
    ],
    "name" : "Club Macanudo (Cigar Bar)",
    "restaurant_id" : "40526406"
}
```

**Comment by Kamikadze4GAME** [comment]
Hi @josephwong13

This is expected behavior.
Please read MongoDB docs about [querying nested/embedded objects](https://docs.mongodb.com/manual/tutorial/query-embedded-documents/#match-an-embedded-nested-document) and [querying objects in array](https://docs.mongodb.com/manual/tutorial/query-array-of-documents/#query-for-a-document-nested-in-an-array) 

> Equality matches on the whole embedded/nested document require an **exact** match of the specified document, **including the field order**.

**Comment by vkarpov15** [comment]
@Kamikadze4GAME is correct, this is expected behavior on the MongoDB server. 

The below code finds documents where `grades.1` is exactly equal to the given object, including key order and types:

```
await Restaurant.find(
        {
            "grades.1": { 
                "grade": "A",
                "date": new Date("2014-08-11T00:00:00Z"),
                "score": 9
            }
        }
    ).lean()
```

The below code finds documents where `grades.1.grade` is the given value, `grades.1.date` is the given value, and `grades.1.score` is the given value. The keys can be in any order, and `grades.1` can have additional keys as well.

```
await Restaurant.find(
        {
            "grades.1.grade": "A",
            "grades.1.date": new Date("2014-08-11T00:00:00Z"),
            "grades.1.score": 9
        }
    )
```

**Comment by josephwong13** [comment]
Thanks a lot guys for the detailed explanation!
