### ISSUE TITLE
Mongoose pre middleare

### ISSUE THREAD

**Issue by crossLineApex** [Automattic/mongoose#10256]
I found out that arrow function can still be not used in pre middleware in mongoose, version 5.12.6 

Here's the code: 
```
userSchema.pre("save", async function (next) {
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
});
```
or am I doing something wrong ?

**Comment by IslandRhythms** [comment]
we need a lot more than just the hook to attempt to repro this.

**Comment by vkarpov15** [comment]
@crossLineApex my best guess is that you're having issues because you're trying to use `this` in an arrow function. [Here's why `this` is tricky with arrow functions](https://masteringjs.io/tutorials/fundamentals/arrow#why-not-arrow-functions), and why you shouldn't use arrow functions in cases where you expect the framework to bind the correct value of `this`.
