### ISSUE TITLE
[MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version

### ISSUE THREAD

**Issue by kyrylkov** [Automattic/mongoose#10285]

**Comment by kakarot-dev** [comment]
i have the same prob

**Comment by fabraga** [comment]
Happening to me too. It must be from this latest version of mongoose (5.12.11) because I updated to it today. I never placed option [returnOriginal] though.

**Comment by fabraga** [comment]
Happening to me too. It must be from this latest version of mongoose (5.12.11) because I updated this today. I never placed option [returnOriginal] though.

**Comment by Jacint96** [comment]
Happening to me on mongoose (5.12.10) aswell

**Comment by IslandRhythms** [comment]
I'm gonna need a repro script from somebody because I can't reproduce it but enough of you are reporting this issue to cause concern.

**Comment by PathToLife** [comment]
Hi just got it as well, narrowed it down to this

index.ts
```
import mongoose, { Schema } from 'mongoose'
import { MongoMemoryServer } from 'mongodb-memory-server'

const deprecateMe = new Schema({
    hello: Schema.Types.String,
})

const DeprecateMe = mongoose.model('yolo', deprecateMe)

const run = async () => {
    const mms = new MongoMemoryServer()
    const uri = await mms.getUri()
    await mongoose.connect(uri, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        useFindAndModify: false,
    })

    await DeprecateMe.findByIdAndUpdate(undefined, {
        hello: '',
    })
}
run().then()
```

my package.json
```
    "mongoose": "^5.12.11",
    "mongodb-memory-server": "^6.9.6",
    "ts-node": "^10.0.0",
    "typescript": "^4.2.4"
```

Hope this helps, thanks for the awesome work :) lemme know if need more help

**Comment by silentjohnny** [comment]
The deprecation was introduced in the latest MongoDB driver:

"Currently, the driver supports the option returnOriginal for findOneAndUpdate, instead of the returnDocument option outlined in the CRUD spec. We should add support for returnDocument, and deprecate the returnOriginal flag."

see https://jira.mongodb.org/browse/NODE-1812

**Comment by IslandRhythms** [comment]
Ok so a couple things,
1. only able to repro on 5.12.11
2. We will be pathcing shortly

**Comment by fabraga** [comment]
> returnDocument

Can you teach us how to fix it in the node_modules while we wait for the updates?

**Comment by Roger-Heathcote** [comment]
I am getting this all of a sudden even though I've never used the "new" option or "returnOriginal". I use findOneAndUpdate in a number of places without problem. The single instance that is triggering this warning is this...

```
	await this.findOneAndUpdate(
		{ownerId, listId},
		{$push: {ordering: mongoose.Types.ObjectId(itemId)}},
		{upsert: true}
	)
```

It also happens if I remove the third parameter entirely. FYI I have {useFindAndModify: false} set in my connection string. I tried reverting to 5.12.10 and the problem disappeared.

**Comment by vkarpov15** [comment]
@Roger-Heathcote please make sure you've upgraded to the latest version of Mongoose (v5.12.13 as of this writing). If you're still experiencing this issue, please open a new issue and follow the issue template.
