### ISSUE TITLE
LeanDocument typings contain undefined property id in intellisense

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#10282]
**Do you want to request a *feature* or report a *bug*?**

**bug**

**What is the current behaviour?**

LeanedDocument exposes `id` property which indeed is not the case when you `.lean()` the document

![image](https://user-images.githubusercontent.com/28386721/119340535-443c4a80-bcb0-11eb-9b6e-4c5094550f89.png)

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Create a mongoose typescript project
2. lean any document
3. Try to access the `.id` property. You will see in the IntelliSense but when you console.log it, this would be undefined

```JSON
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "./dist",
    "strict": true,
    "noImplicitAny": true,
    "typeRoots": ["./ctypings", "./node_modules/@types"],
    "types": ["express", "express-session", "process", "express-request-id"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": ["node_modules", "./node_modules", "./node_modules/*", "./node_modules/@types/node/index.d.ts"],
  "include": ["src/**/*.ts", "ctypings/**/*.ts"]
}
```

**What is the expected behaviour?**

Omit the `id` from LeanDocument

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

The problem is with `@types/mongoose`, version of that is 5.10.3

**Comment by tbhaxor** [comment]
@IslandRhythms If i can know the repo, maybe I can help in this

**Comment by tbhaxor** [comment]
The possible solution could be

```ts
Omit<T, keyof Document> & { _id?: Types.ObjectId, __v?: number }
```

**Comment by vkarpov15** [comment]
I looked into this a bit more and there isn't much we can do about this. The reason is that your document can have a user-defined `id` type, and there's no way for `LeanDocument` to conditionally strip out `id` only if `id` is inherited from `Document` as opposed to user-defined.

This is one of the reasons why our [TypeScript docs](https://mongoosejs.com/docs/typescript.html) recommend not using `extends Document`:

```typescript
// We recommend replacing this:
interface Store extends Document { ... }

// With this:
interface Store { ... }
```

Makes it much easier for Mongoose to infer the correct type when using `lean()`.
