### ISSUE TITLE
"createdAt" timestamp in a sub-document gets re-written on update operation of parent document

### ISSUE THREAD

**Issue by tareqdayya** [Automattic/mongoose#10301]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I try to update a document by passing the document as a whole, its  array of subdocuments will update their `createdAt` props––given a subdocument schema with timestamps enabled.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const run = async () => {
  const childScema = new mongoose.Schema({
    childValue: String,
  }, { timestamps: true });

  const parentSchema = new mongoose.Schema({
    parentValue: String,
    children: [childScema],
  });

  const ParentModel = mongoose.model('Parent', parentSchema);

  // create document with children
  const document = new ParentModel({ parentValue: 'parent value', children: [{ childValue: 'child value' }] });
  await document.save();
  console.log('document:', document);

  // front-end client returns updated document
  const newDocumentFromClient = {...document.toJSON(), parentValue: 'updated by client' };
  // update by passing whole document
  await ParentModel.updateOne({ _id: document._id }, newDocumentFromClient);

  // find doc after update
  const updatedDoc = await ParentModel.findById(document._id);
  console.log('updatedDoc:', updatedDoc); // logs subdocument array with "createdAt" timestamps changed
}

run();
```

**What is the expected behavior?**
for the `createdAt` field not to update since child documents were not updated.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`"mongoose": "^5.12.11",
node: v15.12.0
mongoDB: v4.4.1`

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior. `ParentModel.updateOne({ _id: document._id }, newDocumentFromClient)` becomes a `$set` on `children`, so you're overwriting the entire array and getting new timestamps. And Mongoose has no way of diffing in this case, because the document being updated might not be in memory.

If you're relying on Mongoose to diff the object for you, I'd recommend using [`save()`](https://masteringjs.io/tutorials/mongoose/save) instead of [`updateOne()`](https://mongoosejs.com/docs/api/document.html#document_Document-updateOne). Check out [updating documents in Mongoose](https://masteringjs.io/tutorials/mongoose/update) for more info.
