### ISSUE TITLE
Cannot use typescript generics for mongoose Model

### ISSUE THREAD

**Issue by Vegita2** [Automattic/mongoose#10359]
**Do you want to request a *feature* or report a *bug*?**
Could be a bug, or I'm using it wrong

**What is the current behavior?**
I get type errors when using generics with the provided typescript definitions

**If the current behavior is a bug, please provide the steps to reproduce.**

```typescript
import { FilterQuery, Model } from 'mongoose';

interface Group {
  groupId: string;
}

interface User extends Group {
  firstName: string;
  lastName: string;
}

export abstract class BaseService {
  
  private groupId = 'group1';
  
  // Works as expected when explicitly using "User", no type errors
  async replaceOne(id: string, obj: User, model: Model<User>): Promise<User | null> {
    
    const newObj = new model(obj).toObject();
    newObj.groupId = this.groupId;
    
    const findQuery: FilterQuery<User> = {
      _id: id,
      groupId: this.groupId,
    };
    
    await model.replaceOne(findQuery, newObj);
    return model.findOne(findQuery).lean();
    
  }
  
  // Replacing "User" with a generic that implements the same interface, typescript complains about types
  async replaceOneGeneric<T extends Group>(id: string, obj: T, model: Model<T>): Promise<T | null> {
    
    const newObj = new model(obj).toObject();
    newObj.groupId = this.groupId; // type error
    
    const findQuery: FilterQuery<T> = {
      _id: id,
      groupId: this.groupId,
    };  // type error
    
    await model.replaceOne(findQuery, newObj); // type error: newObj is not assignable to ...
    return model.findOne(findQuery).lean();
    
  }
}

```

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "strict": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "database"
  ],
  "include": [
    "src",
    "test",
    ".eslintrc.js"
  ]
}

```

**What is the expected behavior?**
The first function `replaceOne` works as expected when using the `User` interface with autocomplete etc. 
The second function `replaceOneGeneric` uses a generic instead of `User`, because it only cares about the `groupId`, but in this case typescript complains about the `groupId` and `FilterQuery` assignment.

From my understanding it should work in both cases

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node.js: 14.16.1
mongoose: 5.12.13
typescript: 4.3.2

**Comment by vkarpov15** [comment]
Unfortunately, this is a limitation in TypeScript that we can't reasonably work around. The issue is that TypeScript isn't particularly good at letting us infer what keys a generic type has. For example, try compiling the below code.

```javascript
  async replaceOneGeneric<T extends Group>(id: string, obj: T, model: Model<T>): Promise<T | null> {
    type T2 = { [K in keyof T]: T[K] };
    const test: T2 = { _id: id };
  }
```

You'll get the below error:

```
Type '{ _id: string; }' is not assignable to type 'T2'.
  Object literal may only specify known properties, and '_id' does not exist in type 'T2'.
```

The reason why according to https://github.com/microsoft/TypeScript/issues/43281 is that, just because `T extends Group`, does **not** mean that `T` has a `groupId` property that is the correct type. For example, `type MyType = Group & { groupId: number }` satisfies `MyType extends Group` even though `groupId` has a different type.

I'd recommend structuring this sort of service as a [static](https://mongoosejs.com/docs/typescript/statics.html) on your `Group` class instead of using generics.

**Comment by vkarpov15** [comment]
I took a closer look, and, realistically, the best you can do with the pattern you're using is what's shown below.

```typescript
  async replaceOneGeneric<T extends Group>(id: string, obj: Group, model: Model<any>): Promise<T | null> {

    const newObj = new model(obj).toObject();
    newObj.groupId = this.groupId; // type error

    const findQuery: FilterQuery<Group> = {
      _id: id,
      groupId: this.groupId,
    };  // type error

    await model.replaceOne(findQuery, newObj);
    return model.findOne(findQuery).lean();

  }
```

This isn't ideal because of the `Model<any>` of course. But using `Model<Group>` gets messy because `Model<User>` doesn't extend `Model<Group>`. Ideally, if we switch to the approach in #10345 this should be improved.
