### ISSUE TITLE
PopulatedDoc is returning any as type

### ISSUE THREAD

**Issue by AnthonyLzq** [Automattic/mongoose#10432]
**Do you want to request a *feature* or report a *bug*?**

Possibly, a bug.

**What is the current behavior?**

According to the [docs](https://mongoosejs.com/docs/typescript/populate.html) `PopulatedDoc` is used to define fields that may or not be populated, but when I follow the instructions, the type I thought would be `SomeType | ObjectId` is resulting to be `any`.

**If the current behavior is a bug, please provide the steps to reproduce.**
```typescript
import { Document, model, PopulatedDoc, Schema, Types } from 'mongoose'

interface IProduct extends Document {
  description: string
  image: Buffer
  name: string
  price: number
  producer: Types.ObjectId
  stock: number
}

interface IProductAndStock extends Document {
  price: number
  product: PopulatedDoc<IProduct & Document>
  stock: number
}
```
![image](https://user-images.githubusercontent.com/43073718/124868423-5f73c880-df85-11eb-853b-d7f26a76fc8f.png)

My `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "allowJs": true,
    "outDir": "./dist/",
    "rootDir": "./src/",
    "downlevelIteration": true,
    "strict": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "sourceMap": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["./src/"],
  "exclude": ["node_modules", "**/*.test.ts"]
}
```
**What is the expected behavior?**

I think it should return type `IProduct | ObjectId`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- Node.js: 14.17.1
- Mongoose: 5.13.2
- MongoDB: 4.4.6

**Comment by mjfwebb** [comment]
Unfortunately, this is likely not a bug, but I do feel like it should definitely be considered a problem.

The docs (https://mongoosejs.com/docs/typescript/populate.html) state "You as the developer are responsible for enforcing strong typing between populated and non-populated docs.".

It feels like there's little point in using mongoose's types when it means I have to write additional functions to enforce strong typing. I may as well just revert to using the old DefinitelyTyped types.

I think there is a fundamental failure in the system where a programmer is having to write additional functions for Typescript to work.

**Comment by baohuynhlam** [comment]
This issue is likely because your `IProduct` interface already extends "Document". And then inside `PopulateDoc<>`, you do another `& Document`. I don't know if that is a bug or a feature, but if you remove one `Document`, i.e `PopulatedDoc<IProduct>` or `IProduct` (not extends Document), the typing kinda works again

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior, due to the fact that, if you use `extends Document`, `_id` is `any` by default. So `PopulatedDoc<IProduct & Document>` becomes `IProduct | any`.

Two workarounds:

1) Explicitly declare `IProduct` 's `_id` type:

```typescript
interface IProduct extends Document {
  _id: Types.ObjectId
  description: string
  image: Buffer
  name: string
  price: number
  producer: Types.ObjectId
  stock: number
}
```

2) Don't use `extends Document` or `& Document`

Random aside: `_id` is `any` by default in order to support the `extends Document` pattern. If we did `_id?: ObjectId`, any class that `extends Document` would have to have `_id` as an ObjectId.

**Comment by baohuynhlam** [comment]
I actually found that the `Document` interface accepts generics, and the first generic is the type of the `_id` field. so another way is to do `extends Document <Types.ObjectId>`. The way I usually do `PopulatedDoc` is
```
type ProductDocument = IProduct & Document <Types.ObjectId>;

// Then in reference field
product: PopulatedDoc<ProductDocument>
```
However, due to Mongoose's auto cast from string to ObjectId, you can actually pass string to an ObjectId field, that would be perfectly valid code, but Typescript will complain that `'string' is not assignable to ObjectId`. If you want to pass string to ObjectId fields, you will need to use `Document<Types.ObjectId | string>`, or not passing string at all, and call the `ObjectId` constructor before passing the field

**Comment by AnthonyLzq** [comment]
> Unfortunately this is expected behavior, due to the fact that, if you use `extends Document`, `_id` is `any` by default. So `PopulatedDoc<IProduct & Document>` becomes `IProduct | any`.
> 
> Two workarounds:
> 
> 1. Explicitly declare `IProduct` 's `_id` type:
> 
> ```ts
> interface IProduct extends Document {
>   _id: Types.ObjectId
>   description: string
>   image: Buffer
>   name: string
>   price: number
>   producer: Types.ObjectId
>   stock: number
> }
> ```
> 
> 1. Don't use `extends Document` or `& Document`
> 
> Random aside: `_id` is `any` by default in order to support the `extends Document` pattern. If we did `_id?: ObjectId`, any class that `extends Document` would have to have `_id` as an ObjectId.

Well, I've tried both approaches, the first one still returns `any` as type, proofs for the first suggestion:
![image](https://user-images.githubusercontent.com/43073718/129649398-9ec6853e-3840-4e0c-9d42-5614fcd35081.png)

For the second one (or at least what I understood, same as in the [docs](https://mongoosejs.com/docs/typescript/populate.html)): 
![image](https://user-images.githubusercontent.com/43073718/129649615-66e49ffe-5c4e-4b1d-9acb-f95bc4e05000.png)

I've probably misunderstood something, right?

**Comment by AnthonyLzq** [comment]
> I also found that the `Document` interface accepts generics, and the first generic is the type of the `_id` field. so another way is to do `Document <Types.ObjectId>`. The way I usually do `PopulatedDoc` is
> 
> ```
> type ProductDocument = IProduct & Document <Types.ObjectId>;
> 
> // Then in reference field
> product: PopulatedDoc<ProductDocument>
> ```
> 
> However, due to Mongoose's auto cast from string to ObjectId, you can actually pass string to an ObjectId field, that would be perfectly valid code, but Typescript will complain that `'string' is not assignable to ObjectId`. If you want to pass string to ObjectId fields, you will need to use `Document<Types.ObjectId | string>`, or not passing string at all, and call the `ObjectId` constructor before passing the field

Thanks for your suggestion, but unfortunately I'm getting inconsistent results, when I do what you suggest I got `PopulatedDoc<ProductDocument, Types.ObjectId | undefined>` as type, then I can't access to any property that is supposed to be in the populated doc. I'm not sure what should I do, maybe I can just end up using something like: `Types.ObjectId | IProduct` and then using `as`. I tried to get the same result than in the [docs](https://mongoosejs.com/docs/typescript/populate.html):

> Below is a simplified implementation of the `PopulatedDoc` type. It takes 2 generic parameters: the populated document type `PopulatedType`, and the unpopulated type `RawId`. RawId defaults to an ObjectId.
> ```typescript
> type PopulatedDoc<PopulatedType, RawId = Types.ObjectId> = PopulatedType | RawId;
> ```

But I failed :(

**Comment by baohuynhlam** [comment]
@AnthonyLzq can you try this
```ts
interface IProduct {
  _id: Types.ObjectId; // This line is actually optional because later will declare type of `_id` field inside Document's generics
  description: string;
  producer: Types.ObjectId;
}

interface IProductDocument = IProduct & Document<Types.ObjectId>

interface IProductAndStock {
  product: PopulateDoc<IProductDocument>;
  stocker: number;
}
```

My understanding is that your issue was because mismatch between `IProduct` and `Document` type. Firstly, I recommended your interfaces do not extend `Document`, which just makes it easier to deal with IMO. Secondly, your `IProduct._id` has a type of `ObjectId`, therefore, when you extend (or union) the `mongoose.Document` type, you need to define the `_id` type as a generic too - in other words, use `Document<Types.ObjectId` instead of `Document<any>` if you want to explicitly type your `id` field

**Comment by AnthonyLzq** [comment]
You mean:

```typescript
type IProductDocument = IProduct & Document<Types.ObjectId>
```

Instead of:
> ```typescript
> interface IProductDocument = IProduct & Document<Types.ObjectId>
> ```

Right?

**Comment by AnthonyLzq** [comment]
> @AnthonyLzq This is what I have been using in my app - can you try this
> 
> ```ts
> interface IProduct {
>   _id: Types.ObjectId; // This line is actually optional because later will declare type of `_id` field inside Document's generics
>   description: string;
>   producer: Types.ObjectId;
> }
> 
> interface IProductDocument = IProduct & Document<Types.ObjectId>
> 
> interface IProductAndStock {
>   product: PopulateDoc<IProductDocument>;
>   stocker: number;
> }
> ```
> 
> My understanding is that your issue was because mismatch between `IProduct` and `Document` type. Firstly, I recommended your interfaces do not extend `Document`, which just makes it easier to deal with IMO. Secondly, your `IProduct._id` has a type of `ObjectId`, therefore, when you extend (or union) the `mongoose.Document` type, you need to define the `_id` type as a generic too - in other words, use `Document<Types.ObjectId>` instead of `Document<any>` if you want to explicitly type your `_id` field

Well for some strange reason yesterday didn't work, now it does, thanks. Although I will still need to use `as` since I now have `ObjectId | IProductDocument` type.
