### ISSUE TITLE
readFileSync, ENAMETOOLONG, sslCA and DocumentDB

### ISSUE THREAD

**Issue by acomito** [Automattic/mongoose#10488]
I know mongoose doesn't support DocumentDB, so I'm not expecting anything from the mongoose team here-- but I thought this would be a good place to post since many mongoose users are probably using DocumentDB/CosmoDB (when they can't use mongo itself).

I have a pem file provided by AWS when you create your documentDB instance.

```
const sslCA = fs.readFileSync(__dirname + "/rds-combined-ca-bundle.pem");

const options = {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  ssl: true,
  sslValidate: true,
  sslCA,
}
```

Everything I'm finding online says "just pass the pem file to mongoose, bro" but that's all I'm doing and mongoose is throwing this error.

Yet I get a ENAMETOOLONG because the pem/cert file is too big I guess? it's only 96 lines long.

 If I remove maybe 20-30 lines, it doesn't throw the error. 
 
 Is there any solution here? So it seems the aws provided cert is right at the top of what node can handle with readFileSync?
 
 Has anyone had trouble with other certs? is it just AWS is providing stupidly long pem files?
 
 I wish I could just use atlas but I can't 😭

**Comment by neno76** [comment]
I have the same issue. how we can fix this issue ?

**Comment by mizhac** [comment]
Hi, check this config:  https://docs.aws.amazon.com/documentdb/latest/developerguide/connect_programmatically.html

the problem is caused by not using TLS correctly

Test this config 
Connection String: tls=true

Example:
```
let dbURI = 'mongodb://user:password@dns.cluster-endpoint.us-west-2.docdb.amazonaws.com:27017/database?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&authSource=admin'

const filePath = path.join(__dirname, 'file.pem')
mongoose.connect(dbURI, {
    ssl             : true,
    sslValidate     : false,
    useCreateIndex  : true,
    useFindAndModify: false,
    sslCA: fs.readFileSync(filePath)
  })
```

When i use TLS, useNewUrlParser not set in config.
When TLS is disabled, is possible use useNewUrlParser in config


```
let dbURI = 'mongodb://user:password@dns.cluster-endpoint.us-west-2.docdb.amazonaws.com:27017/database?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&authSource=admin'

const filePath = path.join(__dirname, 'file.pem')
mongoose.connect(dbURI, {
    ssl             : true,
    sslValidate     : false,
    useCreateIndex  : true,
    useFindAndModify: false,
    sslCA: fs.readFileSync(filePath),
    useNewUrlParser: true
  })
```

**Comment by acomito** [comment]
Somebody said it was the file path was too long, and so I should store it as multiple env variables (in secrets manager, or similar)

**Comment by vkarpov15** [comment]
The issue is that the `sslCA` option should be the **path to the CA file**, not the contents of the file. The MongoDB driver runs `readFileSync()` for you under the hood: https://github.com/mongodb/node-mongodb-native/blob/fbdc7c86b4b610a8be8bac6a222ec53355ec410e/lib/operations/connect.js#L254-L258, so you're getting ENAMETOOLONG because the MongoDB node driver is treating the contents of your CA file as a file path.

**Comment by itsjoekent** [comment]
I just arrived here because of the same issue, thank you @vkarpov15 for pointing that out because the Mongoose documentation is incorrect 

![Screen Shot 2021-09-09 at 5 20 23 PM](https://user-images.githubusercontent.com/897368/132764266-bd057905-5d29-474d-bea9-a284b4be27d0.png)
