### ISSUE TITLE
Bug: @types/mongodb installed by Mongoose causing conflicts, Model Schema errors 

### ISSUE THREAD

**Issue by 0x-cygnet** [Automattic/mongoose#10535]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The Mongoose library installs the @types/mongodb library (deprecated) which now appears to be causing conflicts.

Possibly this is related to the work being done here?
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54510

I am not able to compile code that has previously worked without issue and now get the following errors:

<img width="545" alt="Screen Shot 2021-08-02 at 6 27 22 PM" src="https://user-images.githubusercontent.com/5743472/127935767-96ebd099-6a7e-4623-ba22-ce2d787584d2.png">

_Argument of type 'Schema<Document<any, any, any>, Model<any, any, any>, undefined, any>' is not assignable to parameter of type 'Schema<UserDoc, UserModel, undefined, unknown>'.
  Types of property 'plugin' are incompatible.
    Type '(fn: (schema: Schema<Document<any, any, any>, Model<Document<any, any, any>, {}, {}>, undefined, {}>, opts?: any) => void, opts?: any) => Schema<...>' is not assignable to type '(fn: (schema: Schema<UserDoc, Model<UserDoc, {}, {}>, undefined, {}>, opts?: any) => void, opts?: any) => Schema<UserDoc, UserModel, undefined, unknown>'.
      Types of parameters 'fn' and 'fn' are incompatible.
        Types of parameters 'schema' and 'schema' are incompatible.
          Type 'Schema<Document<any, any, any>, Model<Document<any, any, any>, {}, {}>, undefined, {}>' is not assignable to type 'Schema<UserDoc, Model<UserDoc, {}, {}>, undefined, {}>'.
            Types of property 'static' are incompatible._

It should be important to note that when I delete the node_modues/@types/mongodb directory in the local project (installed as a dependency by Mongoose) the type errors resolve.

Link to the failing code can be found here:
https://github.com/0x-cygnet/ticketing/blob/main/auth/src/models/user.ts

**What is the expected behavior?**
Should compile without errors as it did a week ago and no changes have been made to the codebase, repo or dependencies since.

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**
Node = 16.3.0
npm = 7.6.3
Mongoose = 5.13.5 (upgraded from 5.12.11 and saw no difference or change in behavior).

**Comment by hasezoey** [comment]
> Possibly this is related to the work being done here?

i can definitely say that this issue is not related to that, because all references to `@types/mongodb` i could find in your project was pinned to `3.5` (around `^3.5.x`), and that issue you mentioned only affects `@types/mongodb` version `4.0.0` and `mongodb` `4.0.0` and above

---

there are some issues with your code:
- you try to do `extends mongoose.Document`, which is not recommended (or supported), see https://github.com/Automattic/mongoose/issues/10520#issuecomment-892073876
- you try to do `extends mongoose.Model`, which is basically the same reason as the one above, also see https://github.com/Automattic/mongoose/issues/10520#issuecomment-892073876

after fixing the mentioned issues above, changing the following line to the one after, will result in it working:

```ts
// from
const userSchema = new mongoose.Schema(
// to
const userSchema: mongoose.Schema<UserDoc> = new mongoose.Schema( 
```

<details>
<summary>Full Modified File</summary>

```ts
import mongoose from 'mongoose';
import { Password } from '../services/password';

// An interface that describes the properties
// that are requried to create a new User
interface UserAttrs {
  email: string;
  password: string;
}

// An interface that describes the properties
// that a User Model has
interface UserInterface {
  build(attrs: UserAttrs): UserDoc;
}

type UserModel = mongoose.Model<UserDoc>;

// An interface that describes the properties
// that a User Document has
interface UserInterface {
  email: string;
  password: string;
}

type UserDoc = mongoose.Document & UserInterface;

const userSchema: mongoose.Schema<UserDoc> = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true
    },
    password: {
      type: String,
      required: true
    }
  },
  {
    toJSON: {
      transform(doc, ret) {
        ret.id = ret._id;
        delete ret._id;
        delete ret.password;
        delete ret.__v;
      }
    }
  }
);

userSchema.pre('save', async function(done) {
  if (this.isModified('password')) {
    const hashed = await Password.toHash(this.get('password'));
    this.set('password', hashed);
  }
  done();
});

userSchema.statics.build = (attrs: UserAttrs) => {
  return new User(attrs);
};

const User = mongoose.model<UserDoc, UserModel>('User', userSchema);

export { User };
```

</details>

---

PS: some recommendations:
- next time you provide such an long error, i would recommend to put it into a code block (see [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) for more)
- if you should provide a reproduction repository again, it would be helpful to have a lock-file (from npm, yarn, pnpm, or any other)
- if you should provide a reproduction repository again, it would be helpful if it would already be at the latest version of the mentioned package (this case `mongoose`)

**Comment by hasezoey** [comment]
> So, my question is why would removing the @types/mongodb library from the local project suppress or correct the types errors I am seeing?

probably because somewhere in the chain mongodb's types are used, and when it cannot be found, it will be replaced with `any` (and if you dont open mongoose's type-file, no error about it will be displayed)

> Diffing an installation using a pinned 5.13.4 vs 5.13.5 shows exact same @types/mongodb (as you've mentioned), however, the main difference is here in mongoose/index.d.ts at lines 2497-2499

this is related to #10515, by reducing (and probably improving) types / restrictions

> Also, with 5.13.4 @types/node": "14.x || 15.x" is installed and in 5.13.5 that library is omitted entirely.

for that, the commit 28b1aa33fd6c7ad302cf1cb574d548844335c158 is responsible, but it seems like that was just a band-aid fix for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54479 (restricting `@types/node` version to 14 / 15)

> Also, if this is a breaking change, is it documented?

here in mongoose it seems like type updates are not seen as "minor" or "major" (semver), but yes the changes are documented in [`History.md`](https://github.com/Automattic/mongoose/blob/master/History.md) (mongoose's Changelog)

---

btw, did the mentioned fixes work for you?

**Comment by vkarpov15** [comment]
I took a closer look and the easiest solution here is to add the DocType generic to the user schema definition:

```javascript
const userSchema = new mongoose.Schema<UserDoc>( ... )
```

I haven't been able to figure out why v5.13.5 causes this issue yet, but will look into it a bit more.

**Comment by 0x-cygnet** [comment]
> btw, did the mentioned fixes work for you?

Apologies @hasezoey , I did not see your inquiry at the bottom. No, the recommendation did not work in full. The type errors were resolved in the editor, however, the tests failed at the `userSchema.statics` function.

> I took a closer look and the easiest solution here is to add the DocType generic to the user schema definition:
> 
> ```js
> const userSchema = new mongoose.Schema<UserDoc>( ... )
> ```
> 
> I haven't been able to figure out why v5.13.5 causes this issue yet, but will look into it a bit more.

@vkarpov15, yes, your suggestion to add the DocType both resolves the type error as well as the failing tests. I very much appreciate your looking into this.
