### ISSUE TITLE
Docker build fails with @types/mongoose like ObjectID

### ISSUE THREAD

**Issue by gokhanmelma** [Automattic/mongoose#10532]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have an issue while building the node application on docker. It was building fine before but since last Friday ( 30/07/2021 ), I got the issues with mongodb. Building the application on local environment is fine. The issue is just from docker build.

![image](https://user-images.githubusercontent.com/49041460/127804201-57fda3fe-1710-4e3f-9212-b7298b44c393.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

I just run this command to build the app on docker:
`docker-compose build && docker-compose up -d`

_docker-compose.yml_

```
...
mongo:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always
...
```

_Dockerfile_

```
FROM node:14
COPY . .
RUN npm install --production && npm run build
EXPOSE 3000
CMD ["npm", "start"]
```

_tsbase.json_

```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "declaration": true,
    "target": "ES2017"
  }
}
```

_tsconfig.json_

```
{
  "extends": "./tsbase",
  "compilerOptions": {
    "outDir": "./dst"
  },
  "include": [
    "src/**/*"
  ]
}
```

**What is the expected behavior?**
It should build fine on docker.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node `14`
Mongoose `^4.11.8`
MongoDB `4.2`
@types/mongoose `^4.7.21`

> I found that [mongo:4.2](https://hub.docker.com/layers/mongo/library/mongo/4.2/images/sha256-9ed8cbdf7f6fe44b3671e34501c1e137347481ec156cfa54f01afec5d882b270?context=explore) image was updated 6 days ago on docker hub. In addition, I am on Mac

**Comment by hasezoey** [comment]
for types issues below mongoose version 5.10.19, you need to report it in https://github.com/DefinitelyTyped/DefinitelyTyped/ (though, probably not much will happen there anymore)

---

it seems like `@types/mongoose` from your version tried to use the official `mongodb` types, which is provided since mongodb 4.0 (rewrite to complete typescript) (which is not supported in mongoose below 6.0) and the types `@types/mongodb` probably got deprecated (being a stub package for that version), and since the version for `@types/mongodb` is not pinned in `@types/mongoose` at version `4.7.21`, it will use the latest (the stub package)

[See UNPKG `@types/mongodb`](https://unpkg.com/browse/@types/mongoose@4.7.21/package.json) for reference

workarounds:
- update to a later mongoose version (like 5.13.5)
- try to pin the `@types/mongodb` version (and also `mongodb` itself) to the version used by mongoose in `4.11.8`

**Comment by gokhanmelma** [comment]
Hey @hasezoey,

This helped me a lot. I added `@types/mongodb": "^2.2.28"` and it worked. Thank you so much!!

**Comment by vkarpov15** [comment]
@hasezoey is right, it looks like `@types/mongoose@4` uses `"@types/mongodb": "*",`, which means it gets the latest version of `@types/mongodb`.
