### ISSUE TITLE
Timing out on requests when importing mongoose models from another project with Lerna 

### ISSUE THREAD

**Issue by Nikola-Milovic** [Automattic/mongoose#10580]
Node 15.4
Mongoose 5.11.15

My setup, monorepo with [Lerna to help managing dependencies](https://github.com/lerna/lerna), I have a packages directory and shared directory. In my shared directory I have my mongoose models. (I have 3 servers that all require to access these models and I don't know of a better way to share them with typescript and nodejs)

Here is my entry point to this shared/models package
```
import * as CampaignModel from "./Campaign";
import * as JobModel from "./Job";

export { CampaignModel , JobModel};
```

It works, I can use my documents but probably with the way mongoose is implemented the underlying db isn't accessed. Not sure what is happening, I import the model like so `import { CampaignModel } from "models";` and use it, but I keep getting timeout errors, presumably because they don't reside in the same project. 

Lerna root 
|-packages  has serviceA (nodejs app)
|-shared has models (package with exported models) , has its own package.json
 

Is there a fix for this or a workaround? Really thought I was being clever with this  :laughing:

**Comment by TrejGun** [comment]
your approach definitely works
I have implemented it a couple of years ago
please show the code of how you regifter models inside the connection

PS learna is dead you can look at https://nrwl.io/

**Comment by vkarpov15** [comment]
Hard to tell without looking at your code, but my best guess is that you're exporting models from one package, and then calling `mongoose.connect()` from another package with a different copy of the Mongoose module. Couple of workarounds:

1) Export schemas rather than models from `shared`
2) Export a function instead of models from `shared` as shown below

```javascript
// Replace:
export default model('Campaign', campaignSchema);

// With:
export default function(conn) {
  return conn.model('Campaign', campaignSchema);
}
```

The problem is that, if you use `mongoose.model()` to define models and `mongoose.connect()` to connect to MongoDB, you need to make sure `mongoose` refers to the same object, and that often isn't the case if you're using sibling packages in lerna.
