### ISSUE TITLE
findOneAndUpdate working even after it is removed

### ISSUE THREAD

**Issue by adarrshpaul** [Automattic/mongoose#10719]
###  Bug

The [docs](https://mongoosejs.com/docs/deprecations.html#findoneandupdate)  tells me that **findOneAndUpdate** is removed.

I've tried running queries **findOneAndUpdate** and it just works fine. 
` why it is working just fine ` Isn't it removed according to docs ? 

Edit: I've installed the latest mongoose version - 6.0.5
Other configurations :        
        Node-Version: 14.17.3
        MongoDB-Version: 4.2.10

**Comment by sean-daley** [comment]
I'd wait for the official response but I think that deprecation page may be wrong? It looks like before 6.0 there used to be a `useFindAndModify` setting which depending on the value would change the behavior of calls like findOneAndUpdate behind the scenes. If it was false it would call mongodb.findOneAndUpdate() directly otherwise if it was true they redirected the mongoose findOneAndUpdate to their findAndModify call.

`useFindAndModify` was removed though and that value is always treated as false going forward so I assume that means the mongoose findOneAndUpdate now just always passes through to mongodb.findOneAndUpdate.

At least that's how I think I'm interpreting it.

**Comment by sean-daley** [comment]
I think this is resolved by the doc update done in https://github.com/Automattic/mongoose/commit/73e461e421acd274baeada8cb80a71f4998166bb

**Comment by vkarpov15** [comment]
`useFindAndModify` is removed. `findOneAndUpdate()` is not.
