### ISSUE TITLE
The `new` keyword appears in records

### ISSUE THREAD

**Issue by yahiarefaiea** [Automattic/mongoose#10808]
I'm not sure if this is a question or something wrong with my code, but this is the first time I see the `new` keyword in front of the `ObjectId("")`

I'm running:
MongoDb: v4.4.5
Mongoose: 6.0.6
NodeJS: v14.17.0

And this is an example of the current behavior:
```
[{
  _id: new ObjectId("615461cb6f3081661dfd0634"),
  title: 'SAMPLE_TITLE',
  __v: 0
}]
```

This happens when I get all records from the database even those records that I already have long ago. So how is it possible to show the `new` keyword?

But, when using express for example and send the records `res.send()` and view them with a browser, both the `new` and the `ObjectId()` keywords disappear. (which's normal behavior to hide them I guess)

But my question is, is having the `new` keyword in front of the `ObjectId()` is normal behavior since Mongoose v6 or even v5? Because I haven't noticed something like this before and it weird so I had to come here and ask.

And if there are more details I can provide, please let me know.

Thanks in advance ^^

**Comment by yahiarefaiea** [comment]
The issue has been confirmed (if it was ever an issue)
I tested this on an older project that has Mongoose v5.8.4.
I `console.log` the result and it was without the `new ObjectId()` keywords.
```
[{
  _id: 61546880e9677e33c093eb09,
  title: 'GG',
  __v: 0
}]
```

Then I updated Mongoose to v6.0.6 and removed the below options (since mongoose won't run having them)
```
mongoose.connect(dbUrl, {
  // useNewUrlParser: true,
  // useCreateIndex: true,
  // useUnifiedTopology: true
})
```
And the issue again appears.
Is this an issue or it's normal behavior?

**Comment by yahiarefaiea** [comment]
From the docs ([here](https://mongoosejs.com/docs/migrating_to_6.html#objectid-valueof)), I found this:

> Mongoose now adds a valueOf() function to ObjectIds. This means you can now use == to compare an ObjectId against a string.

Is it related to my issue?

**Comment by vkarpov15** [comment]
This is expected behavior in v4.x of the MongoDB Node driver, but it _only_ affects how your documents look `console.log()` output. You don't get `new ObjectId(...)` if you, say, pass a document to [Express' `res.json()` function](https://masteringjs.io/tutorials/express/json). In other words, this is a purely cosmetic change to make `console.log()` output more copy/pastable given that `ObjectId` is now an [ES6 class](https://masteringjs.io/tutorials/fundamentals/class), and shouldn't affect anything else.

The `valueOf()` change is not related.
