### ISSUE TITLE
[6.x] Error when run jest tests

### ISSUE THREAD

**Issue by rafaneri** [Automattic/mongoose#10844]
Hi, after migrate my mongoose package from 5.13.8 to 6.0.9, my tests are broken, how the below image:

![image](https://user-images.githubusercontent.com/7685408/135953912-d061102b-1031-4c91-abd1-754c30aca0bc.png)

I'm using the mongoose 6.0.9, MongoDB 4.1.2 and @types/mongodb 3.6.20.

![image](https://user-images.githubusercontent.com/7685408/135954013-df3ceaf2-cce3-4903-8262-0b02c2814a6b.png)

Tks!

**Comment by sean-daley** [comment]
Try removing `@types/mongodb` and see if that fixes it? From the mongodb 4.x migration guide:
https://github.com/mongodb/node-mongodb-native/blob/4.1/docs/CHANGES_4.0.0.md

```
Typescript
We've migrated the driver to Typescript! Users can now harness the power of type hinting and intellisense in editors that support it to develop their MongoDB applications. Even pure JavaScript projects can benefit from the type definitions with the right linting setup. Along with the type hinting there's consistent and helpful docs formatting that editors should be able to display while developing. Recently we migrated our BSON library to TypeScript as well, this version of the driver pulls in that change.
```

**Comment by IslandRhythms** [comment]
I ran npm test just fine

**Comment by vkarpov15** [comment]
The issue is that, for some reason, Jest is trying to bundle `node_modules/mongodb/src`, which contains TS files that aren't really meant to be compiled. I found a couple of workarounds that might work:

1. Add babel-jest as suggested here: https://newbedev.com/jest-syntaxerror-cannot-use-import-statement-outside-a-module . This will allow Jest to correctly handle the TS code in the MongoDB driver.
2. rename `src` to a different dir. Your project compiles fine with `src2`, for example. That's because Jest is picking up _all_ `src` dirs, including `node_modules/mongodb/src`, and ignoring `modulePathIgnorePatterns`.
3. `rm -rf ./node_modules/mongodb/src/*` . This isn't ideal, but at least removes the offending code.
