### ISSUE TITLE
Schema.options.toObject.transform runs for every findOne query

### ISSUE THREAD

**Issue by AbuchiKings** [Automattic/mongoose#10873]
I am running "mongoose@6.0.9" and Node@14.17.6

#### Do you want to request a feature or report a bug?

I believe it is a bug given that this behaviour wasn't present in 5.11.11

#### What is the current behavior?

When creating schema, I am using the ```toObject.transform```  options to strip fields like  __v before presenting to users. I have noticed that whenever I set a ```toObject.transform``` function, it runs in all ```findOne```  queries

#### If the current behavior is a bug, please provide the steps to reproduce.

My code:
```
const schema = new mongoose.Schema({
  name: String,
  place: String
});

 if (!schema.options.toObject) schema.options.toObject = {};
schema.options.toObject.transform = function (doc, ret, options) {
     console.log('ret:', ret)
     delete ret.__v;
     delete ret.place;
     return ret;
 }

const model = mongoose.model("Model", schema);

async function findDocument() {
  await model.create({name: "Abel", place:"Istanbul"})
  const test= await model.findOne({name: "Abel"});
  
  console.log(test) // returns  object with _id and name. I need to prevent transform from running
}
With the transform function commented out, findOne query returns a Mongo document complete with fields
```

**Comment by vkarpov15** [comment]
@deistermatheus is right, `console.log(test)` calls the transform implicitly, [here's the relevant code in Mongoose](https://github.com/Automattic/mongoose/blob/f37577d632184351aa635db1c0425da7e9667f11/lib/document.js#L3984). `console.log()` calls `require('util').inspect()`, which looks for the `inspect()` function. So this is expected behavior. `transform` is **not** called on `findOne()`.
