### ISSUE TITLE
TS docs issues with PopulatedDocs and subdocs

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#10949]
https://github.com/Automattic/mongoose/issues/10617#issuecomment-949580395

**Comment by rongem** [comment]
@vkarpov15: Thank you for your last comment, it provided the missing link. I was able to migrate to Mongoose 6 now.

To recap the missing parts in documentation:

While for the user document (interface) in Mongoose 5 string types as MongoIds worked, in Mongoose 6 you either have to use Types.ObjectId (if you don't want to populate) or PopulatedDoc<OtherUserDocument, Types.ObjectId> as type for your Ids.

In the Schema Definition, both variants have to be set as Schema.Types.ObjectId.

The difference between Schema.Types.ObjectId and Types.ObjectId should be explained somewhere, since it is not intuitive.
