### ISSUE TITLE
Aggregation returns empty array !

### ISSUE THREAD

**Issue by fetahokey** [Automattic/mongoose#11013]
**Request a *feature***
> According to the mongodb documentation <html>
<body>

$out | Writes the resulting documents of the aggregation pipeline to a collection. To use the $out stage, it must be the last stage in the pipeline.
-- | --

</body>
</html>

the `$out` stage is working perfectly and writing new collection, i'm using `append` function  `.append({ $out: "aggr_out" })` to place it in the last stage.

**The current behavior**
 - Saving new collection to the database
 - Returning an empty array in the `callback ` function

**Expected behavior**
- Return the aggregate result

**Versions of Node.js, Mongoose, and MongoDB**
- node.js  ` v14.17.3 (LTS)`
- mongoose `v5.13.13`
- mongoDB
  -  db version `v4.0.23`
    - git version: `07c6611b38d2aacbdb1846b688db70b3273170fb`
    - build environment:
        - distmod: `debian92`
        - distarch: `x86_64`
        - target_arch: `x86_64`

**Code**
![aggregate](https://user-images.githubusercontent.com/32603079/143229298-3855b0d8-5880-4a2c-a4aa-3c966d5bffd5.png)

**Comment by Kamikadze4GAME** [comment]
Hello @fetahokey

It looks like an expected behavior. MongoDB server returns empty array of the last stage is $out. I found only one place in the [documentation](https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/) where this is reminded:

> **Returns**:
A cursor to the documents produced by the final stage of the aggregation pipeline operation, or if you include the explain option, the document that provides details on the processing of the aggregation operation.
***If the pipeline includes the $out operator, aggregate() returns an empty cursor. See $out for more information.*** // <-- HERE

**Comment by fetahokey** [comment]
@Kamikadze4GAME , thank you 🙏
