### ISSUE TITLE
use slice for a collection

### ISSUE THREAD

**Issue by vavanv** [Automattic/mongoose#11125]
I am trying to use slice for a logs collection but stuck with the path for the root

```
  async getLog(): Promise<ILog[]> {
    return await LogModel.find().slice('**THAT_SHOULD_BE_HERE????**', [1, 3]);
  }





const LogSchema: Schema = new Schema({
  email: { type: String, required: true, unique: false },
  date: { type: Date, default: Date.now },
  action: { type: String, required: true },
  message: { type: String, required: transduce },
});

export interface ILog extends Document {
  email: string;
  date: Date;
  action: string;
  message: string;
}

export const LogModel: Model<ILog> = model<ILog>('logs', LogSchema);
```

**Comment by IslandRhythms** [comment]
`slice(start,end)`

**Comment by vavanv** [comment]
it gives error
```
src/repository/LogRepository.ts:14:40 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

  return await LogModel.find().slice(1, 3);
```

**Comment by IslandRhythms** [comment]
Forgive me, I thought you were attempting to use the javascript default slice.

So from I can tell, you're attempting to get a smaller subset from all the documents in your model. You would want to use the `skip` and `limit` functions. `slice` needs a path argument, which is why it tells you to use `where()` when you don't provide one. An alternative is to use the `lean` option, which would then allow you to use JavaScript's `slice` function.

`await LogModel.find().lean().slice()`

**Comment by DavideViolante** [comment]
Just a curiosity, when the .slice mongoose function is useful instead of skip limit or js slice?!

**Comment by vavanv** [comment]
skip looks like has a performance issue for big data. Was just curious to compare performance with slice and skip

**Comment by vkarpov15** [comment]
`slice()` is **not** a replacement for skip/limit. `slice()` only works with array properties, see https://docs.mongodb.com/manual/reference/operator/projection/slice/ . In other words, you need to provide a path to `slice()`.
