### ISSUE TITLE
Mongoose 6: exec() on await still necessary?

### ISSUE THREAD

**Issue by hansemannn** [Automattic/mongoose#11123]
Hi there! Prior to upgrading to Mongoose 6, I'd like to quickly check if the `exec()` call for promises is still necessary. I am asking because the manual `mongoose.Promise = Promise` does not seem to necessary anymore, so I was hoping that the stack trace behavior has also been addressed (see [this docs](https://mongoosejs.com/docs/promises.html#should-you-use-exec-with-await)). Thanks in advance!

**Comment by IslandRhythms** [comment]
The migration guide doesn't mention anything about changing `exec()`. The doc you link states a good reason to use `exec()` however it is not necessary.

**Comment by vkarpov15** [comment]
The stack trace behavior has not changed, recommendation for Mongoose 6 is the same as Mongoose 5: `exec()` gives you slightly better stack traces with `await`, so you should use `exec()`. But your code will work fine without `exec()`.

**Comment by indraraj26** [comment]
Hi @vkarpov15,

Can we add this enhancement for our next major release.

Lets drop .exec()

**Comment by hansemannn** [comment]
Thanks for the clarification! Yep, dropping it and changing the under the hood API to properly unbox stack traces would be a really helpful change for cleaner code!

**Comment by vkarpov15** [comment]
@indraraj26 right now we don't have a good path forward on removing `exec()` but keeping stack traces. We did some experiments in #9100 to leverage async stack traces, but decided against that approach because async stack traces aren't standard. Definitely open to suggestions though :+1:

**Comment by indraraj26** [comment]
lets stick to the `exec` for now as i understood we do use `exec` to get better stack trace what files and what went wrong. but we may think for below implementation if it is feasible to do it.

Can we add check whether it is callable by promise then add .exec function to it (closure).

You may add one global variable that will turn on/off `exec()` feature via `mongoose.set()`.

One we get to know that it is working in all situation (even in production apps via feedback) then we can make it default `exec()` feature `true`

Thank you VK for managing this great ORM.

**Comment by vkarpov15** [comment]
"Can we add check whether it is called by promise then add .exec function to it" <-- [that's what we already do](https://github.com/Automattic/mongoose/blob/0ad0d949eb62979b3127d2cc4f75aaa603f7c753/lib/query.js#L4737-L4739). The issue is that the JavaScript runtime handles custom `then()` functions slightly differently when it comes to stack traces, versus when you `await` on a fully fledged promise.

One option would be to make query `extends Promise`, but that would be a bit messy because queries are "cold" (don't start executing until you `exec()`) whereas promises are "hot" (start executing immediately when created). I suspect mixing these two paradigms will cause issues.
