### ISSUE TITLE
multiple mongoose connection

### ISSUE THREAD

**Issue by Nandhakumar7** [Automattic/mongoose#11145]
need to add multiple mongoose connection,
In our app scenario, We have N number of organization, So every organization need to have separate Database, 
Is this possible with mongoose?

I have tried with normal  mongoose connect, and createConnection methods to implement multiple connection , But getting, Pool connection erros if send more than 250 request.

**Comment by Uzlopak** [comment]
What is a "database" for you?

The mongodb instance is the database server. An instance contains one or many databases, and in each database you can have one or many collections. With connect you connect to a mongodb instance. Within the connection you can use various databases, as far as the credentials allow it.

When you connect to mongo it doesn't use 1 connection but multiple connections being a connection pool. By default it is set to 100 connections. The server also allows for x-amount of connections. So if you connect multiple times to the same database instance each connection pool adds up. So it could be that you get the connection pool error by your nodejs service as it is maybe limited or because the mongo server can not handle more connections. Keep in mind that mongo can only process one command per connection at the same time. So it is blocking. To avoid that the mongo is the bottleneck, you need a connection pool. If your mongo instance can handle 65000 connections, then creating per organisation a mongo connection would mean that your mongo instance will get thousands of connections. You can set the - it think- maxPoolSize to increase the amount connections of one connection pool.

If you want to do a separation of data by organisation you would usually use one mongo database instance and one database and multiple collections per organisation. If you want to use different databases you would actually instantiate a new environment of your services, where the new environment would have its specific database credentials. 

But accessing multiple databases  within one environment - in my opinion - indicates a wrong architecture and separation of data. What is the point to have different databases with different credentials if one service is accessing them all.

**Comment by thegoldgoat** [comment]
> What is the point to have different databases with different credentials if one service is accessing them all.

I think this is not the goal of @Nandhakumar7.

What they probably want is to have a different database for each organization, something like:

```js
mongoose.connect('mongodb://localhost:27017/organization1');
mongoose.connect('mongodb://localhost:27017/organization2');
mongoose.connect('mongodb://localhost:27017/organization3');
```

What they are probably missing is that a single MongoDB instance can host multiple database ('organization1', 'organization2', 'organization3', [...])

I think that mongoose can have a single connection to a single instance that can access all the database programmatically

**Comment by Uzlopak** [comment]
Well. I wrote my post to clarify what "database" could mean. Also credentials are handled per instance and not per database, afaik. So...
But I will wait till @Nandhakumar7  answers...

**Comment by Nandhakumar7** [comment]
@Uzlopak Thank You for a Explanation.
Yes @thegoldgoat, Almost, that's what we want.
What is the current behavior?
We try to implement with both connect and createConnection methods,
     - In connect method getting pool connection error more than 250 request
     - In createConnection method, may suit for us, But the thing is, we are using feathersJs and Every Connection Schema Registration is costly operation for us.

What is the expected behavior?
For Every Req Need to open new connection with respective database and close the connection when the request is completed.
Eg:
    req-1 comes from org-1 user => open new connection with org-1 database => close the connection when operation is done
    req-N comes from org-N user => open new connection with org-N database => close the connection when operation is done
And,also multiple organization able to work at same time.
And is this possible in connect method create multiple connections at a time without closing connection?..

Versions
- mongoose:5.13.13
- feather:3.3.1

**Comment by thegoldgoat** [comment]
Why do you need to close the connection each time a request is fulfilled? This gives bad performance.

I suggest 2 approaches:

1. Connect to all the orgs database at startup, then during a request resolve the connection for the corresponding org
2. During a request, check if already connected to the corresponding org, if already connected reuse that connection otherwise try to connect

For both cases, use `createConnection`, I think you also need to inject the schemas.

Store the connections in a map, so that during requests you can do something like `connectionMap.get(orgNameString)` to get the corresponding connection

Regarding the error you receive, I guess you need to increment the [connection pool](https://mongoosejs.com/docs/connections.html#connection_pools)

**Comment by Uzlopak** [comment]
Well obviously the approach doesn't scale well if you have thousands of organizations. So even if you do what thegoldcoat recommends, you will have the same issue just later.

**Comment by vkarpov15** [comment]
@thegoldgoat 's comments in https://github.com/Automattic/mongoose/issues/11145#issuecomment-1002463836 are correct for a small number of organizations. If the number of orgs is less than roughly 1000, you should use a separate connection for each org and resolve which connection to use at runtime.

If the number of orgs is larger, you should use [`useDb()`](https://mongoosejs.com/docs/api/connection.html#connection_Connection-useDb).

```javascript
const db = mongoose.connection.useDb(organizationDbName, { useCache: true });
```
