### ISSUE TITLE
Lodash `_.isEmpty()` With `new Types.ObjectId()` As A Parameter Returns True

### ISSUE THREAD

**Issue by mjhuh263** [Automattic/mongoose#11152]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After upgrading to v6.1.4, the lodash method `_.isEmpty()` used with an objectId as a parameter results  **true** when the result should be false.

**If the current behavior is a bug, please provide the steps to reproduce.**
Pass an ObjectId as a parameter to the lodash `_.isEmpty()` method.

example code
```
// v5.10.9 - results false
_.isEmpty(Types.ObjectId('someId'))
// v6.1.4 - results true
_.isEmpty(new Types.ObjectId('someId'))
```

**What is the expected behavior?**
Previous versions return `false` as an output value while `6.1.4` returns `true`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- NodeJs: v14.15.4
- Mongoose: v6.1.4
- MongoDB: v4.2

**Comment by IslandRhythms** [comment]
@vkarpov15 Bug is confirmed, but I don't know if its an us issue or a them issue.

**Comment by mjhuh263** [comment]
@vkarpov15 Hi thanks for your comment :) 
I experienced this issue while migrating some old projects. 
I have to throw an error if a field is empty or invalid. 

But since the `_.isEmpty()`method returns true, the error occurs even though a valid ObjectId is passed. 

Here is an example code: 
```typescript
const example = (a: string | Types.ObjectId) => {
  if (typeof a === 'string') {
    // 💡 issue
    if (_.isEmpty(new Types.ObjectId(a))|| !Types.ObjectId.isValid(a)) {
      throw new Error('Error.');
    }
  }
  // ... code continues
};
```
I would really appreciate it if I could get a workaround on this issue! 
Thank you🙏

**Comment by vkarpov15** [comment]
An ObjectId is never empty, it always contains some value. So you should be able to do:

```javascript
if (!(a instanceof Types.ObjectId) && (_.isEmpty(a)|| !Types.ObjectId.isValid(a))) {
    throw new Error('Error.');
  }
```

**Comment by markstos** [comment]
I recommend adding a note about this to 6.x migration guide:

https://mongoosejs.com/docs/6.x/docs/migrating_to_6.html

This issue was hard to track down in a big project. Lodash is extremely popular, so there are likely still people upgrading to Mongoose 6 with this complication. 

(We are upgrading to Mongoose 6 and not 8 right now as there are so many things breaking in a project of our size, that it's easier to complete multiple smaller upgrades each with fewer breakages than to upgrade from 5 to 8 directly. Others are likely still doing the same).
