### ISSUE TITLE
Schema types of arrays of subdocuments are not type-checked

### ISSUE THREAD

**Issue by mpsijm** [Automattic/mongoose#11241]
**Do you want to request a *feature* or report a *bug*?**
Bug :bug: 

**What is the current behavior?**
Schema types of arrays of subdocuments are not type-checked.

**If the current behavior is a bug, please provide the steps to reproduce.**
```ts
import { Document, Schema, Types, ObjectId } from "mongoose";

interface Book {
  _id: string;
  name: string;
  labels?: Array<{label: string; value: string}>;
}

new Schema<Book & Document<Book>>({
  _id: {type: String, required: true},
  name: {type: Number, required: true}, // Type error, as expected: Number !== String
  labels: [
    {
      label: {type: String, required: true},
      value: {type: Number, required: true}, // Expected type error here, because Number !== String
    }
  ],
});
```
It does not seem to matter whether `Book.labels` is typed as optional or not.

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEQgYwK4gKYDsYA0cAymgBbYgCGRAKgJ5jYDORA8gEYBW2aMAkgBM4AXzgAzKBBBwARCAi4A5hAjNssgNwAobcHzYo4qmmxwAQqoDWibXDgB9YIIBccZjCj6lO+7io4bh5eyr5wADZUHNjhzAD8bgCCUFBU9AA8CJHR4UGe3ppwAG5U4RjYeSFKIgB8OiK6uNgA7iTklFTplhA2AGQo6Fh4MF3WNTUAFAh2js5uCDCMFST5ykRQ2ACOGMAbrnCe5SIEM-6BiItMbgByWNFQ61s7e26H2MdwAPSfcAxMcIYpA84FRmACAB5MPjYfa3ED3OAAQgAvMiVlUZtkYsw3ABtGb2ab2YkRKIxeaXZbEVZKR7bXYw15QI4nEn2EplZYLJY3O6GOnPRkHZnvIjfOAAUUhvBgMIOSwBKWgcAoGyI0TQVAw6jgcIRKLR1IxJIa9gAuicRABKHRAA

**What is the expected behavior?**
(see comments in reproduction example)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 16
Mongoose 6.1.7
MongoDB 5.0.5
TypeScript 4.5.4

**Comment by vkarpov15** [comment]
We did some digging, and unfortunately we can't work around this without making `type` a required key in `SchemaTypeOptions` and reverting the changes we made related #9927.

The crux of the issue is https://github.com/Automattic/mongoose/blob/master/types/index.d.ts#L1254-L1263: because `SchemaTypeOptions` currently has no required properties, `labels: [{ label: String }]` gets picked up as an array of `SchemaTypeOptions`, which isn't correct. Unless you're using a custom `typeKey`, `labels: [{ label: String }]` should be an array of `SchemaDefinition`... but we can't enforce `type` in `SchemaTypeOptions` because we need to somehow support custom `typeKey`.

To get better type checking, you can use `as` to force Mongoose to consider `labels` as a `SchemaDefinition`:

```ts
import { Document, Schema, SchemaDefinition, Types, ObjectId } from "mongoose";

interface Labels {
  label: string;
  value: string;
}

interface Book {
  _id: string;
  name: string;
  labels?: Array<Labels>;
}

new Schema<Book & Document<Book>>({
  _id: {type: String, required: true},
  name: {type: Number, required: true}, // Type error, as expected: Number !== String
  labels: [{
    label: {type: String, required: true},
    value: {type: Number, required: true}, // Type error, Number !== String
  } as SchemaDefinition<Labels>],
});
```

I tried looking into potentially using [mapped types](https://www.reddit.com/r/typescript/comments/e6vezs/how_to_define_an_interface_for_an_object_whose/) for improved typeKey support, but that doesn't look like mapped types support defining other properties "A mapped type may not declare properties or methods."
