### ISSUE TITLE
Self populating doesn't work in 6.1.8

### ISSUE THREAD

**Issue by AndreyKomin** [Automattic/mongoose#11289]
```
const historySchema = new mongoose.Schema(
  {
    plan: Object,
    parents: [this],
    isDeleted: Boolean,
    isDraft: Boolean,
  },
  {
    timestamps: true,
  }
)

export default mongoose.model("history", historySchema)
```

Look at `parents`. It worked perfectly in ```^5.13.14``` but not in ```^6.1.8```.
I tried some ways to make it work but unfortunately without any effect.

**Comment by vkarpov15** [comment]
What is `this` in your example?

Also, what is the expected behavior versus the observed behavior?

**Comment by AndreyKomin** [comment]
Think that `this` is referring to itself.

I want to do `await History.findById(historyId).populate("parents")` and with the example above it worked perfectly in ```^5.13.14```. So I was able to populate another `history` items in `parents`, referring to itself in the Schema.

Now, in `^6.1.8` it no longer work

**Comment by vkarpov15** [comment]
"this is referring to itself" <-- no idea what this means. I suspect that `this` is either null or global object.

Please provide a complete repro script that demonstrates the behavior you're seeing.

**Comment by vkarpov15** [comment]
@AndreyKomin the script as written worked by accident, and isn't a feature that Mongoose supports. The problem is that, in your script, Mongoose 5 interpretted `[this]` to be `[]`, an array of any type. The correct way to define your schema is as follows:

```javascript
const historySchema = new mongoose.Schema({
  data: String,
  parents: [{ type: mongoose.ObjectId, ref: 'history' }],
})
```

In Mongoose 6, we also don't fall back to using the `History` model when using `Query.prototype.populate()`. We'll add a note to our migration guide about this. But, in the meantime, please change how `parents` is defined in your schema and that should fix this issue.
