### ISSUE TITLE
Add a codecoverage Workflow

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11308]
@vkarpov15 
Please add a codecoverage Workflow.

E.g. coveralls.io

I am Not a collaborator to activate or atleast send you an invite to activate the 3rd party tool.

If you activate it , I can supply the correct configuration for the workflow.

**Comment by vkarpov15** [comment]
Unfortunately we can't use coveralls because I don't have access to Automattic's org. Unlikely that we'll get the access we need to use coveralls.

What do you think about just dumping coverage output to a database collection like in #11616 and building our own UI to display coverage history? In the meantime, we should be able to store coverage in GitHub workflow artifacts.
