### ISSUE TITLE
if password contains @ field connection is not getting established

### ISSUE THREAD

**Issue by veekshith-gandhi** [Automattic/mongoose#11444]

**Comment by Uzlopak** [comment]
That is odd. Should be actually handled by the mongo driver. This indicates, that the is some issue there.

**Comment by AbdelrahmanHafez** [comment]
@Uzlopak 
Mongoose/mongo handles it correctly when user/pass are passed inside the options object, the following script works:
```js
'use strict';
import mongoose from 'mongoose';
const { Schema } = mongoose;
import assert from 'node:assert';


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test_password', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    user: 'potato_monster',
    pass: '@!:#AX123654',
    authSource: 'test_password'
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });

  const User = mongoose.model('User', userSchema);

  assert.ok(await User.create({ name: 'Potato Monster' }));
  console.log(mongoose.version);
  console.log('All assertions passed.');
}
```

It becomes an issue when we include the password inside the mongo URI, and the password includes special characters:
You can see why this becomes an issue parsing the following:
```js
mongodb://potato_monster:@!:#AX123654@localhost:27017/test_password
```
Has to be turned into the following so the mongo driver can handle it.
```js
`mongodb://potato_monster:${encodeURIComponent('@!:#AX123654')}@localhost:27017/test_password`
```

I'd recommend passing credentials inside the options instead of relying on a full mongo URI.
It would be interesting if we could introduce a workaround to parsing special characters in passwords/usernames though. 
@Uzlopak What do you think?

**Comment by Uzlopak** [comment]
I would also use urlencoding under the hood

**Comment by AbdelrahmanHafez** [comment]
How would you tell which `:` or `@` is part of the password and which one is part of the mongo uri syntax?

I think it could become error-prone, but I am not completely against it.
Feel free to come up with a solution to that and we can discuss it in more detail.

**Comment by Uzlopak** [comment]
I did not think about the mongo url but when you pass it as a Object with distinctive password. But if you pass a mongoUrl than I think it is the implementors responsibility to provide a well formed url.

**Comment by AbdelrahmanHafez** [comment]
Password in an object is already handled by the driver.
I don't think we should/can do the url encoding in mongoose as well, AFAIK encoding password twice will result in an incorrect output.

**Comment by Uzlopak** [comment]
If it is already handled gracefully by the driver than we should not add it. 
So in conclusion i still think it is in responsibility of the implementer to provide a well formed mongoUri
