### ISSUE TITLE
Feature: validate property in the case of discriminator

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#11454]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It accepts the value whether the `__t` (discriminator) is as it defined in the `ref` property or not.

**What is the expected behavior?**
It should reject the value if the `__t` (discriminator) is not as defined in the `ref` property.

```typescript
// User model has two models (Fan and Star) as the discriminator.

// Room Schema
@Prop({ type: Schema.Types.ObjectId, ref: Fan.name })
fan: Fan

// Save a Room document with a Star ID instead of a Fan ID
const roomObj = new Room();
roomObj.fan = new Types.ObjectId("STAR_ID");

roomModel.create(roomObj);
```

The `create()` should throw a validation error because the given ID references to a document with a different `__t` (discriminator).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 6.2.3

**Comment by vkarpov15** [comment]
Unfortunately there isn't much Mongoose validation can do here because the `Fan` document might not exist in memory, or in MongoDB, when validation is running. And we avoid implementing validators in core Mongoose that rely on properties that aren't in the document.

You can implement this as a `pre('save')` hook.
