### ISSUE TITLE
One model, 2 connection pools

### ISSUE THREAD

**Issue by HamLiveDev** [Automattic/mongoose#11472]
Hello, I've tried reading all the docs I could find prior to posting this. I have a nodejs library which gets utilized by both realtime and batch processing code (each with its own connection pool). I'd like the mongoose model objects in each function to use either the batch processing (slow) connection pool or the real-time connection pool.

The only way I saw to do this is to export 2 models, each tied to one of the 2 connections. I'm wondering if there's a more elegant way to tell a model which connection to use?

Thanks!

**Comment by manojsethi** [comment]
I guess [useDb](https://mongoosejs.com/docs/api/connection.html#connection_Connection-useDb) should help here.

**Comment by vkarpov15** [comment]
You'd need 2 models unfortunately. `useDb()` still requires you to register models in the new connection. We enforce that there's exactly one connection per model, because otherwise what would happen if the model's connection switched in the middle of `populate()`?

One pattern I've seen is refactoring it so that, instead of exporting a model, you export a function that takes a connection name. Something like:

```javascript
const connections = require('../connections');
const userSchema = require('./userSchema');

module.exports = function User(connName) {
  if (!connections[connName].models.User) {
    connections[connName].model('User', userSchema);
  }
  return connections[connName].model('User');
};
```

So instead of doing `await User.findOne()`, you'd do `await User('realtime').findOne()`. Does that make sense?
