### ISSUE TITLE
Support updating getters of document in updateOne method

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#11490]
**Do you want to request a *feature* or report a *bug*?**

**FEATURE**

**What is the current behavior?**

When the current document is updated via `.updateOne()` method it doesn't update the getter fields of the same. So if suppose we use the field later in the code then it will might cause the issue. 

**If the current behavior is a bug, please provide the steps to reproduce.**

It is not a bug, but still I can provide you a code where I faced this issue recently

```js
const user = await User.create() // add user details here

const address = new Address();
const billing = new BillingDetails();

address.billing = billing._id;

await Promise.all([
    user.updateOne({ $push: { billings: billing._id } }),
    address.save(),
    billing.save(), 
    stripe.customers.create(c => { 
      user.updateOne({ $set: { stripeId: c.id } })
    })
])

console.log(user.billings) // []
console.log(user.stripeId) // undefined
```

**What is the expected behavior?**

Support the updation of getters when updateOne call is succeeds to save time and have cleaner code like the above

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by Uzlopak** [comment]
I think this is actually not a good pattern. Imagine multiple processes modify the same document and you just assume the content of the document instead of reloading from the database. I am not an ORM Specialist so I don't know how other ORMs handle such cases, but I would prefer reloading the document from the database layer instead of just changing the value in the logic layer.

**Comment by tbhaxor** [comment]
@Uzlopak I totally agree with you. As you can see I am using updateOne two times in the example but changing different fields. Usually devs change the same field after applying some logic (so basically not in same execution flow but different after accessing getters).

We can have an option in the updateOne to whether or not apply this changes to the document. One the most used keyword from Python ecosystem `inplace` can be used. Which when set to true, updates the fields in the current document. Updating field doesn't mean to refetch the whole document again but to manually update the particular fields removing the network overhead.

I am too not a pro ORM developer but faced this issue and thought others might be getting this.

**Comment by Uzlopak** [comment]
Just to verify what you suggest:

We add an additional option to the mutating operations called inplace and that would mean that you instruct to the ORM to modify the Object Instance in-memory. 

I assume that this is kind of hard to implement, because we need to basically implement the same mongodb server side logic for the mongodb operators in the client side. But I think it is a good feature request.
