### ISSUE TITLE
CI/CD, automatically publish nightly builds, releases

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11782]
I am currently building ci/cd pipelines. I already achieved automatical publishing nightly and next and version release to npm after the ci pipeline is running. I am still improving some aspects. I have to see how i can automate the changelog creation based on the release notes.

You can see it here:
https://github.com/cthulhu-oidc/olsontimezone

I was wondering if we have the necessity for autoreleasing mongoose. It would only need an automated npm token as repo secret to get publishing done.

I guess that the only unsolved issue would be the search in the docs.

**Comment by simllll** [comment]
As an interesting side aspect, nightly deployments bload the "index" npm file a lot, we have some serious issues with that in the meantime, because a regular npm install of a specific package version first downloads the index file, with all the tags and other things in there. This index file has now a size of several megabytes already, which leads to slower installs (especially if you have a lot of packages ;-)). Even though I would say this is actually a problem of npm, it's still something to consider when thinking about automatic daily releases ;-)
