### ISSUE TITLE
Mongoose not saving documents properly.

### ISSUE THREAD

**Issue by CoderSudaWuda** [Automattic/mongoose#11824]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
I try to save a document to a model, but it fails.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/CoderSudaWuda/fe49bd2926ea086330627c92c6c8f049

**What is the expected behavior?**
The document should be saved properly

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v16.15.0
Mongoose: v6.3.2

Footage of it not working: https://streamable.com/8we3rn

**Comment by CoderSudaWuda** [comment]
Full code: https://github.com/CoderSudaWuda/mafia-backend

**Comment by vkarpov15** [comment]
I took a closer look and the most reasonable explanation I have is that your `MONGO_URI` environment variable is incorrect here: https://github.com/CoderSudaWuda/mafia-backend/blob/c11c2bd619035e7e5637495fea14999b60befbcf/server/Base.js#L10 . If it is saving without error, odds are you're connecting to your local MongoDB rather than Atlas.

Please modify @AbdelrahmanHafez 's repro script to demonstrate this issue. Otherwise, not much we can do without your configs.

**Comment by CoderSudaWuda** [comment]
the reason wasnt any of that lol...
`Lobby.markModified('players')` did the trick for me.
