### ISSUE TITLE
Consider enforcing Commit Message style

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#11860]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

It seems like currently the commit message is all over the place, so maybe consider enforcing commit message style by adding a section to `CONTRIBUTING.md` and enforcing it with something like `commitlint` in a pre-commit hook, this should also make it easier for bots (like mongoose release bot) to parse commit messages.

Also from what i can tell the currently most used consistent style is similar to the angular style, so maybe just adopt that.

PS: i was not sure if i should open this as a issue or as a discussion, so i just made a issue so it can still be transferred to a discussion.

**Comment by vkarpov15** [comment]
I've used commitlint in the past, and disliked it, because it is tricky to modify commit messages once you've already committed them. Commit messages being all over the place unfortunately comes with the territory of being an open source project with a lot of outside contributors.

Also worth noting: our release bot doesn't parse commit messages. It just pulls from the changelog, which we generate manually from our GitHub milestones.

**Comment by hasezoey** [comment]
> because it is tricky to modify commit messages once you've already committed them

then they should be enforced before even being commited, like through pre-commit hooks, my usual setup is: husky + lint-staged + commitlint (+ eslint), explanation on why so many:
- [husky](https://www.npmjs.com/package/husky): commitable git-hooks (and slightly more cross-platform compatability)
- [lint-staged](https://www.npmjs.com/package/lint-staged): run many js scripts against the staged files and on non-0 exit, deny a hook
- [commitlint](https://www.npmjs.com/package/commitlint): lint the commit messages against a config
- [eslint](https://www.npmjs.com/package/eslint): lint the staged code to make sure not styling errors are present in the commit

though sadly if you should decide to use them, you will maybe have to use a older version of them, because some have already switched to a nodejs14+ requirement, and even though they may be dev-dependencies, package managers will still complain

**Comment by vkarpov15** [comment]
There's a few problems with husky. 1) doesn't run if you commit through GitHub UI, 2) adds an extra dev dependency to maintain, 3) extra friction for outside contributors. I know I had a fair amount of trouble making my first contributions [here](https://github.com/temporalio/sdk-typescript) because of commitlint.

I'm leaning no for this issue. But I won't turn down outside contributions if someone's feeling particularly motivated to set this up.
