### ISSUE TITLE
Reconnection Fails with mongoose 6.4.0

### ISSUE THREAD

**Issue by Yvonne-shopback** [Automattic/mongoose#11972]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

16.13.2

### MongoDB server version

4.4

### Description

Mongoose 6.3.0, 6.3.8 and 6.4.0 have issue on reconnection mechanism. 
The reconnect mechanism is not working.
After emitting a 'disconnected' event, there should be a 'reconnected' event.
But waiting for 15min, the mongoose did not emit any event.
The logs were like this 
```
{
  level: 'info',
  message: 'MongoDB event - disconnected',
  metadata: {},
  label: 'dbs.providers.mongoose',
  timestamp: '2022-06-22T11:42:29.738Z'
}
{
  level: 'error',
  message: 'Original Request URL: /whale/settings. MongoNotConnectedError: Client must be connected before running operations',
  metadata: {},
  label: 'middleware.errorHandler',
  timestamp: '2022-06-22T11:58:03.923Z'
}
```
We tried to downgrade mongoose to 5.13.14, and it worked well with successful reconnection.

### Steps to Reproduce

This is the connection options we set:
```js
  const connectOptions = {
    user: xxx,
    pass: xxx,
    authSource: admin,
    keepAlive: true,
    family: 4,
    serverSelectionTimeoutMS: 30000,
    autoCreate: false,
  };
```
The listener:
```js
const initializeMongooseListener = () => {
  mongoose.connection.on('connected', () => {
    logger.info('MongoDB event - connected');
    registerToRelease(() => mongoose.connection.close(), 'MongoDB');
  });
  mongoose.connection.on('reconnected', () => {
    logger.info('MongoDB event - reconnected');
  });
  mongoose.connection.on('disconnected', () => {
    mongoose.connection.close();
    logger.info('MongoDB event - disconnected');
  });
  mongoose.connection.on('error', (err) => {
    logger.error(`MongoDB event - error: ${err}`);
  });
};
```
Initialize mongoDb connection
```js
initializeMongooseListener();
mongoose
  .connect(connectUri, connectOptions)
  .then(() => {
    app.listen(listenPort, () => {
      logger.debug(`Extension-Service: Listening on port ${listenPort}`);
    });
  })
  .catch((err) => {
    logger.error(`MongoDB Initialization Error: ${err}`);
  });
```
After starting our express app and confirming that the mongoDb initial connection was built,
I turned off the mongo server manually.
The listener will emit a 'disconnected' event, but no corresponding 'reconnected' event was emitted afterwards.
We've been waiting for 15min, but the mongoose did not apply any reconnection operation.

### Expected Behavior

Mongoose should reconnect to mongo server after the disconnection.

**Comment by vkarpov15** [comment]
Mongoose 6 does handle automatically reconnecting. However, because you're calling `close()` in your 'disconnected' handler, you're telling Mongoose to close the connection when you lose connectivity, which means Mongoose will never try to reconnect. I'm not sure why you're calling `close()` in `on('disconnected')`?

Worth noting: the 'disconnected' event is purely for debugging and monitoring in Mongoose 6. You do **not** need to do anything in the 'disconnected' event handler to make Mongoose 6 try to reconnect forever. That's because, in Mongoose 6, the MongoDB driver will attempt to retry every operation for up to `serverSelectionTimeoutMS` milliseconds, regardless of whether connectivity was lost or not.
