### ISSUE TITLE
Schema method gets called in graphql resolver

### ISSUE THREAD

**Issue by angelhodar** [Automattic/mongoose#12231]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey everyone, so I have a question regarding schema methods with graphql. I have a graphql model that has a boolean field, with the same name as a method I have in my mongoose schema related to that graphql model. For example lets say I have graphql type:

```.graphql
type ExampleUser {
   hasCompleteProfile: Boolean
}
```

And this mongoose code:

```js
const exampleUser = new Schema({
   ...schemaFields
});

// Rest...

exampleUser.methods.hasCompleteProfile = function () {
 const test = someChecks() // Returns true of false
 return test
}
```

So if I make a graphql query like this:

```graphql
query getUserInfo($id: ID!) {
  user(id: $id) {
    hasCompleteProfile
```

The hasCompleteProfile gets correctly assigned with true or false with the return value of the schema method. Why is this happening? What makes this work under the hood? What happens if the schema method function returns a Promise or makes a .then call inside?

**Comment by vkarpov15** [comment]
Hard to tell without a full repo, but I suspect `hasCompleteProfile` is showing up as a [resolver](https://www.apollographql.com/docs/apollo-server/data/resolvers/), which should be fine. [Apollo supports async resolvers](https://www.apollographql.com/docs/apollo-server/data/resolvers/#return-values), so should be fine if schema method returns a promise.

Can you share a more complete repro?

I'll close this for now since there isn't much more we can do without more code samples.
