### ISSUE TITLE
Unique index validation error not throwing

### ISSUE THREAD

**Issue by mgcrea** [Automattic/mongoose#1225]
I'm using this schema with latest npm mongoose:

```
var schema = new Schema({

    _id: Schema.ObjectId,
    email: {type: String, required: true, unique: true}

});
```

If I try to save a email that is already in db, I expect to get a `ValidationError` like if a `required` field is omitted. However this is not the case, I get a `MongoError: E11000 duplicate key error index`.

Which is not a validation error (happens even if I remove the unique:true).

**Comment by lukejacksonn** [comment]
I had this issue and it was due to already existing duplicate values in my index (as pointed out in aheckmann's comment on Feb 1, 2013). I was reading from here http://mongoosejs.com/docs/api.html#schematype_SchemaType-required where it mentions the error, but fails to mention about already exiting duplicates preventing the uniques index from being created in the first place. Might be worth updating the doc to mention this too!

**Comment by ahmedkrdzalic** [comment]
Can we make a custom message option for this error just like we can handle the "**require**" attribute? 
I am willing to contribute to the project.

**Comment by vkarpov15** [comment]
@ahmedkrdzalic we opened a new issue to track that feature request. In the meantime, please check out this plugin: https://www.npmjs.com/package/mongoose-beautiful-unique-validation
