### ISSUE TITLE
Mongoose Slack Channel is not Accessible

### ISSUE THREAD

**Issue by rainrisa** [Automattic/mongoose#12291]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Try to open http://slack.mongoosejs.io/ 

![image](https://user-images.githubusercontent.com/108156134/185243822-7278aad1-bbc6-41a9-bb9f-f1a65cd5c3f3.png)

**Comment by rainrisa** [comment]
Does the mongoose team have no plans to create a Telegram group instead of Slack Channel?

**Comment by vkarpov15** [comment]
@rainrisa we've been considering creating a discord now that Slack is moving toward a "pay per user" model.

**Comment by hasezoey** [comment]
> we've been considering creating a discord now that Slack is moving toward a "pay per user" model.

is there already one in the works, or would it be ok to create and add a PR adding it to all required places?

**Comment by vkarpov15** [comment]
@hasezoey I'd like to hold off on creating a discord for now, unless you feel very strongly about it.

@rainrisa since the old slack.mongoosejs.io looks like it is gone for good, we put up a new one. You can now request an invite to our slack channel at https://slack.mongoosejs.io/ . Just please be patient, sending invites is currently a manual process.
