### ISSUE TITLE
Callback Interfaces removed in mongo driver 4.9.0?

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#12331]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

https://github.com/fastify/fastify-mongodb/issues/191#issuecomment-1227374029

Do we need to take some action?

**Comment by Eomm** [comment]
No, I don't think so: we bumped a major for it: https://github.com/fastify/fastify-mongodb/releases/tag/v4.0.0

I think the user hit an old tutorial with the v3.x interface actually

**Comment by hasezoey** [comment]
i think removing callbacks is a breaking change, and i dont see anything related in the [node-mongodb-native changelog 4.9.0](https://github.com/mongodb/node-mongodb-native/blob/main/HISTORY.md#490-2022-08-18)

also, looking into [typedoc for 4.1](https://mongodb.github.io/node-mongodb-native/4.1/classes/Collection.html#find) then it seems like the type did not change since 4.0

**Comment by vkarpov15** [comment]
It looks like the referenced issue is concerned that `collection.find()` doesn't accept a callback as the 2nd param. Which is true. But also it looks like that is also true in MongoDB Node driver 4.8, so I don't think this is a breaking change in 4.9.

Either way, not a Mongoose issue.
