### ISSUE TITLE
Mongoose 5.13.5 has node_moduels/@types/mongodb version 3.6

### ISSUE THREAD

**Issue by Amitcoh1** [Automattic/mongoose#12428]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.5

### Node.js version

16.17

### MongoDB version

4.9.1

### Operating system

Windows

### Issue

Inside the mongoose node_modules I have a folder of node_modules holds the @types/mongodb of version 3.6 somehow.

This causing me issues with:

```
let objects: mongodb.FindCursor<TCacheItem<K, T>> ->> return FindCursor/AbstractCursor
While:
 objects = await this._collection.find({}).project({_id: 0}); --> return Cursor
```
 
The find function comes from the 
`node-mongodb-native/3.6/api/Collection.html#find`

Any explanation?

Thanks!

**Comment by IslandRhythms** [comment]
Can you upgrade to latest mongoose version?

**Comment by hasezoey** [comment]
i dont quite understand the issue, but just some notes:
mongodb 3.6 does not have its own types so there is a `@types/mongodb` package, only since mongodb 4.0 does it have its own types

from what i can tell, `.find` in mongodb is meant to return a `Cursor`, which in 4.0 got renamed to `FindCursor`

i also dont quite understand the context of the code-sample supplied, but assuming from the types, you are trying to assign a mongodb 3.6 type to a mongodb 4.0 types, which are not compatible
if you want to use mongodb 4.0, you need to upgrade mongoose to at least 6.0 (or downgrade your own mongodb package to 3.6)
