### ISSUE TITLE
Typescript subdocument does not have sudocument type

### ISSUE THREAD

**Issue by hoangbn** [Automattic/mongoose#12610]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.0

### Node.js version

16.18.0

### MongoDB server version

5.x

### Description

Previously, subdocuments had `SubDocument` type. The below used to work:

### Steps to Reproduce

```ts
const nestedSchema = new Schema({
  prop: String
})

const parentSchema = new Schema({
  nested: {
    type: nestedSchema,
    default: {}
  }
})

const ParentModel = model("Test", parentSchema);

const setNested = async () => {
  const parent = await ParentModel.findOne();
  parent.nested.set({
    prop: "prop value"
  })
}
```

### Expected Behavior

`parent.nested` used to be a subdocument and parent.nested.set(values) was allowed

**Comment by vkarpov15** [comment]
Unfortunately inferred schema types don't take subdocuments into account currently, and implementing that will be tricky because, if we make `nested` a subdocument, then `parent.nested = { prop: 'prop value' }` will no longer work. Here's a couple of workarounds:

1. Use top-level `set()` instead: `parent.set('nested', { prop: 'prop value' })`
2. Explicitly type out `parentSchema` as follows

```ts
import { Schema, model, Types, InferSchemaType } from 'mongoose';

const nestedSchema = new Schema({
  prop: String
})

type ParentType = {
  nested: Types.Subdocument<Types.ObjectId> & InferSchemaType<typeof nestedSchema>
}

const parentSchema = new Schema<ParentType>({
  nested: {
    type: nestedSchema,
    default: {}
  }
})

const ParentModel = model("Test", parentSchema);

const setNested = async () => {
  const parent = await ParentModel.findOne();
  parent.nested.set({
    prop: "prop value"
  })
}
```
