### ISSUE TITLE
ObjectId is different from Type.ObjectId

### ISSUE THREAD

**Issue by DuJiming** [Automattic/mongoose#12711]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

6.7.2

### Node.js version

18.7.0

### MongoDB version

6.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0.1

### Issue

I want parse string to ObjectId, and Previous versions are OK

"@nestjs/common": "^7.6.15"
"mongoose": "^5.11.12"

but there are some type errors when i upgrade version

"@nestjs/common": "^9.2.0"
"mongoose": "^6.7.2"

code: 

```typescript
import { PipeTransform, Injectable, BadRequestException } from '@nestjs/common';
import { Types } from 'mongoose';

@Injectable()
export class ParseObjectIdPipe implements PipeTransform<any, Types.ObjectId> {
  transform(value: any): Types.ObjectId {
    const validObjectId: boolean = Types.ObjectId.isValid(value);
    if (!validObjectId) {
      throw new BadRequestException('Invalid ObjectId');
    }
    return Types.ObjectId.createFromHexString(value);
  }
}
```

error:

`type "import("/***/node_modules/bson/bson").ObjectID" Missing attribute in "_id"，but type "import("mongoose").Types.ObjectId" is required in。`

I have to use 
```typescript
import { PipeTransform, Injectable, BadRequestException } from '@nestjs/common';
import { Types } from 'mongoose';
import { ObjectId } from 'bson';

@Injectable()
export class ParseObjectIdPipe implements PipeTransform<any, ObjectId> {
  transform(value: any): ObjectId {
    const validObjectId: boolean = Types.ObjectId.isValid(value);
    if (!validObjectId) {
      throw new BadRequestException('Invalid ObjectId');
    }
    return Types.ObjectId.createFromHexString(value);
  }
}
```
to fix it
Is that right？

I saw a problem like me

https://github.com/Automattic/mongoose/issues/12537

**Comment by DuJiming** [comment]
I saw a problem like me

https://github.com/Automattic/mongoose/issues/12537

**Comment by hasezoey** [comment]
> type "import("/***/node_modules/bson/bson").ObjectID" Missing attribute in "_id"，but type "import("mongoose").Types.ObjectId" is required in。

are you sure you are using `Types.ObjectId` everywhere and not from `bson` directly? because mongoose's ObjectId is compatible with bson's, but not the other way around - at least in terms of types, because mongoose adds a extra property `_id`.

also did you already check that you not accidentally have multiple versions of `mongoose` installed? (`yarn why mongoose` / `npm ls mongoose`)

**Comment by IslandRhythms** [comment]
```typescript
import { PipeTransform, Injectable, BadRequestException } from '@nestjs/common';
import { Types } from 'mongoose';
import { ObjectId } from 'bson';

@Injectable()
export class ParseObjectIdPipe implements PipeTransform<any, ObjectId> {
  transform(value: any): ObjectId {
    const validObjectId: boolean = Types.ObjectId.isValid(value);
    if (!validObjectId) {
      throw new BadRequestException('Invalid ObjectId');
    }
    return Types.ObjectId.createFromHexString(value);
  }
}
/*
@Injectable()
export class ParseObjectIdPipe implements PipeTransform<any, Types.ObjectId> {
  transform(value: any): Types.ObjectId {
    const validObjectId: boolean = Types.ObjectId.isValid(value);
    if (!validObjectId) {
      throw new BadRequestException('Invalid ObjectId');
    }
    return Types.ObjectId.createFromHexString(value);
  }
}
*/
```

**Comment by DuJiming** [comment]
> > type "import("/***/node_modules/bson/bson").ObjectID" Missing attribute in "_id"，but type "import("mongoose").Types.ObjectId" is required in。
> 
> are you sure you are using `Types.ObjectId` everywhere and not from `bson` directly? because mongoose's ObjectId is compatible with bson's, but not the other way around - at least in terms of types, because mongoose adds a extra property `_id`.
> 
> also did you already check that you not accidentally have multiple versions of `mongoose` installed? (`yarn why mongoose` / `npm ls mongoose`)

I think I can roughly understand that both types can be used, but only one can be used. I can't mix them. I was just wondering why the types are incompatible after upgrading

for example `Types.ObjectId.createFromHexString()` return `bson.ObjectId`

Thanks for the reminder

**Comment by DuJiming** [comment]
like this, The introduction of `Type.ObjectId` is completely unnecessary

```js
import { PipeTransform, Injectable, BadRequestException } from '@nestjs/common';
import { ObjectId } from 'bson';

@Injectable()
export class ParseObjectIdPipe implements PipeTransform<any, ObjectId> {
  transform(value: any): ObjectId {
    const validObjectId: boolean = ObjectId.isValid(value);
    if (!validObjectId) {
      throw new BadRequestException('Invalid ObjectId');
    }
    return ObjectId.createFromHexString(value);
  }
}
```

**Comment by hasezoey** [comment]
>  I was just wondering why the types are incompatible after upgrading

that is because back then the mongoose `ObjectId` interface did not add the helper `_id` as a type yet

https://github.com/Automattic/mongoose/blob/c44d521e18d292817a37c9c1623721da52a249f6/index.d.ts#L1749

but now it does and the type is not defined as optional, so the types are only one-way compatible in terms of types

https://github.com/Automattic/mongoose/blob/0eda12a77d5cd9ed4b9ec54f49af218373fcc666/types/types.d.ts#L82-L84

i dont know if the `_id` helper at runtime is a added by mongoose or bson, if it is bson then they could update their types to include it so mongoose's type can be two-way compatible again

> for example Types.ObjectId.createFromHexString() return bson.ObjectId

just as a note, you can also just use `new Types.ObjectId(string)` which will also create a new ObjectId instance from the hex string (with the proper mongoose type)

**Comment by DuJiming** [comment]
> new Types.ObjectId(string)

yes `new Types.ObjectId(string)` is better , think you

**Comment by vkarpov15** [comment]
I took a closer look and @hasezoey is right, this is due to the `_id` getter. Here's a simpler repro script that doesn't involve nestjs:

```ts
import { Types } from 'mongoose';
import { ObjectId } from 'bson';

function foo(value: any): Types.ObjectId {
  return ObjectId.createFromHexString(value);
}
```

Mongoose adds an [`_id` getter to ObjectIds](https://github.com/Automattic/mongoose/blob/9d7bf10606e567990969aabe130f16b896e2d29b/lib/index.js#L267-L277) to make it more convenient to work with populated paths, so you can use `.path._id` to get the `_id` of the document regardless of whether it is populated. But there's no good way for Mongoose to add additional properties to a MongoDB class in TypeScript, so Mongoose's `ObjectId` type extends from MongoDB driver's.

@hasezoey is right, no need to mix bson ObjectId and Mongoose ObjectId anyway. You can do `new Types.ObjectId()`. Or `Types.ObjectId.createFromHexString()` if you really want.
