### ISSUE TITLE
Mongoose returns the object, but it is not saved in the DB.

### ISSUE THREAD

**Issue by damianlluch** [Automattic/mongoose#12801]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Good morning. I have a little problem with some scripts that I have to put some things by hand in a mongo DB (with a specific table). Where I save through a script, mongoose responds me with the object id, but when you go to look for it in the database, the document is not created...
```{
  hashTags: [],
  royalties: [],
  currency: 'ETH',
  isHidden: false,
  isLazyMinting: false,
  isActive: true,
  collectionId: new ObjectId("639a7b66aed9155a25628183"),
  name: 'zaraza',
  categoryId: new ObjectId("6262781114fe9d42f307ff2e"),
  description: 'zaraza',
  subCategoryId: new ObjectId("626288042b35c9c6f73ad62d"),
  networkId: new ObjectId("6351633df02dc84d971fcbfb"),
  tokenId: '0000000000000000000000000000000000000000000000000000000000000001',
  ipfsURI: 'ipfs://',
  type: 'erc1155',
  shareCount: 0,
  _id: new ObjectId("639b389f45c046b00b2531b0"),
  __v: 0
}
{
  hashTags: [],
  royalties: [],
  currency: 'ETH',
  isHidden: false,
  isLazyMinting: false,
  isActive: true,
  collectionId: new ObjectId("639a7b66aed9155a25628183"),
  name: 'zaraza',
  categoryId: new ObjectId("6262781114fe9d42f307ff2e"),
  description: 'zaraza',
  subCategoryId: new ObjectId("626288042b35c9c6f73ad62d"),
  networkId: new ObjectId("6351633df02dc84d971fcbfb"),
  tokenId: '0000000000000000000000000000000000000000000000000000000000000002',
  ipfsURI: 'ipfs://',
  type: 'erc1155',
  shareCount: 0,
  _id: new ObjectId("639b389f45c046b00b2531b1"),
  __v: 0
}
```

Anybody have it happen? it's a bd with mongo.cloud secondary nodes.
Greetings!

**Comment by IslandRhythms** [comment]
Please provide a script of what you are doing.

**Comment by damianlluch** [comment]
````
import { connection } from "../db.connection";
import { Item } from "../bulk/schemas/item.schema";
import mongoose, { Types } from "mongoose";

const MULTI_ADS = new Item({
  collectionId: new Types.ObjectId("639a7b66aed9155a25628183"),
  subCategoryId: new Types.ObjectId("626288042b35c9c6f73ad62d"),
  categoryId: new Types.ObjectId("6262781114fe9d42f307ff2e"),
  networkId: new Types.ObjectId("6351633df02dc84d971fcbfb"),
  name: 'zaraza',
  description: 'zaraza',
  tokenId: "0000000000000000000000000000000000000000000000000000000000000001",
  imageKey: '',
  ipfsURI: 'ipfs://',
  type: 'erc1155',
  hashTags: [],
  royalties: [],
  currency: 'ETH',
  isHidden: false,
  isLazyMinting: false,
  isActive: true,
  shareCount: 0,

});
const DOUBLE_POWER = new Item({
  collectionId: new Types.ObjectId("639a7b66aed9155a25628183"),
  subCategoryId: new Types.ObjectId("626288042b35c9c6f73ad62d"),
  categoryId: new Types.ObjectId("6262781114fe9d42f307ff2e"),
  description: 'zaraza',
  name: 'zaraza',
  networkId: new Types.ObjectId("6351633df02dc84d971fcbfb"),
  tokenId: "0000000000000000000000000000000000000000000000000000000000000002",
  imageKey: '',
  ipfsURI: 'ipfs://',
  type: 'erc1155',
  hashTags: [],
  royalties: [],
  currency: 'ETH',
  isHidden: false,
  isLazyMinting: false,
  isActive: true,
  shareCount: 0,


});


export const createAdsItem = async (params: any) => {
  try {
    await connection();
    let doublePowerCreated;
    let multiAdsCreated;
    const session = await mongoose.startSession();
    await session.withTransaction(async () => {
      console.log("CREATING WOONKLY POWER ITEMS");

      

      multiAdsCreated = await Item.create([MULTI_ADS], {
        session,
      });

      doublePowerCreated = await Item.create([DOUBLE_POWER], {
        session,
      });


      await session.endSession();
    });
    console.log(multiAdsCreated[0]);
    console.log(doublePowerCreated[0]);
  } catch (error) {
    console.log("!! [Error] ", error);
  }
};

createAdsItem({});

```

**Comment by IslandRhythms** [comment]
Ok so: It seems you are importing a schema, which if thats the case then the below is incorrect.
Instead of doing `new Item({})`, simply do `{}`.
The only time you should really be mention a schema is when you are defining the model or the schema is a property on another schema.

> const MULTI_ADS = new Item({
  collectionId: new Types.ObjectId("639a7b66aed9155a25628183"),
  subCategoryId: new Types.ObjectId("626288042b35c9c6f73ad62d"),
  categoryId: new Types.ObjectId("6262781114fe9d42f307ff2e"),
  networkId: new Types.ObjectId("6351633df02dc84d971fcbfb"),
  name: 'zaraza',
  description: 'zaraza',
  tokenId: "0000000000000000000000000000000000000000000000000000000000000001",
  imageKey: '',
  ipfsURI: 'ipfs://',
  type: 'erc1155',
  hashTags: [],
  royalties: [],
  currency: 'ETH',
  isHidden: false,
  isLazyMinting: false,
  isActive: true,
  shareCount: 0,

});
const DOUBLE_POWER = new Item({
  collectionId: new Types.ObjectId("639a7b66aed9155a25628183"),
  subCategoryId: new Types.ObjectId("626288042b35c9c6f73ad62d"),
  categoryId: new Types.ObjectId("6262781114fe9d42f307ff2e"),
  description: 'zaraza',
  name: 'zaraza',
  networkId: new Types.ObjectId("6351633df02dc84d971fcbfb"),
  tokenId: "0000000000000000000000000000000000000000000000000000000000000002",
  imageKey: '',
  ipfsURI: 'ipfs://',
  type: 'erc1155',
  hashTags: [],
  royalties: [],
  currency: 'ETH',
  isHidden: false,
  isLazyMinting: false,
  isActive: true,
  shareCount: 0,
});

**Comment by vkarpov15** [comment]
@damianlluch are you sure you're looking in the right collection? Can you please provide how you're defining your `Item` model and what collection you're looking in?

**Comment by damianlluch** [comment]
hello thank you, to those who responded. The problem was that I had the call to endSession inside the withTransaction, that's why I didn't save the object.
