### ISSUE TITLE
Aggregation query does not return virtual field?

### ISSUE THREAD

**Issue by pzppzz** [Automattic/mongoose#12863]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.5

### Node.js version

16.8

### MongoDB version

4.9.1

### Operating system

None

### Issue

Aggregation query does not return virtual field?

**Comment by Uzlopak** [comment]
Virtual field from a mongo schema?

**Comment by pzppzz** [comment]
> Virtual field from a mongoose schema?
yeah

**Comment by vkarpov15** [comment]
Expected behavior, Mongoose doesn't hydrate aggregation results, because aggregation results often change the format of documents in the schema. If your aggregation produces something that looks like a document, you can hydrate it using [`Model.hydrate()`](https://mongoosejs.com/docs/api/model.html#model_Model-hydrate):

```javascript
const res = await Model.aggregate([{ $match: { name: 'test' } }]).then(res => res.map(doc => Model.hydrate(doc));
```
