### ISSUE TITLE
Is it possible to share a ClientSession in different apps?

### ISSUE THREAD

**Issue by nbusser** [Automattic/mongoose#12917]
# Prerequisites

- [X] I have written a descriptive issue title

- Mongoose version: 6.7.1

- Node.js version: 16.10

- MongoDB version: 4.4.18

# Issue

## Setting

I'm building an app using microservice architecture.  
I need at some point to pass a mongoose session (and its transaction) to another microservice.  
Thus, if a single error happens in one microservice, I can rollback all the changes made by all the microservices.

#### Sending ClientSession

I first tried to send directly ClientSession object to my microservice.  
However, since ClientSession is not serializable, I cannot send it properly.  
Received error:
```
ERROR   HttpError [InternalServerError]: Converting circular structure to JSON
    --> starting at object with constructor 'MongoClient'
    |     property 's' -> object with constructor 'Object'
    |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
    --- property 'client' closes the circle
```

#### Sending Transaction

I then tried to send transaction started by my session in microservice A and to attach it to a freshly created session on microservice B.

Microservice A:
```typescript
const session = await mongoose.startSession();
mongoose.startTransaction();

const { transaction } = session;

try {
  await callMicroserviceB(transaction);
  await session.commitTransaction();
} catch (e) {
  await session.abortTransaction();
} finally {
  await session.endSession();
}
```

Microservice B:
```typescript
const { transaction } = event;

const session =  await mongoose.startSession();
session.transaction = transaction;

... // Microservice code

await session.endSession();
```

When performing any query on a Model, I receive the following error:
```
Error: session.transaction.transition is not a function
```

Is there a way to share a ClientSession or a Transaction?

**Comment by IslandRhythms** [comment]
Why only send over the transaction? why not the whole session? Did you try sending the whole session and seeing if you had any luck that way?

**Comment by nbusser** [comment]
Yes I tried to send the whole session as I describe in section "Sending ClientSession". I cannot actually serialize the session :/

**Comment by IslandRhythms** [comment]
Nope, not possible. Sorry

**Comment by nbusser** [comment]
That's a clear answer, thank you.  
Can you give me an insight into the technical reason it is not possible?

**Comment by Uzlopak** [comment]
If you open a Session in mongo it has not a identifier provided by the server. The identifier is made by the Client. In mongo native driver it generates a uuid-v4 to keep the reference to the session in memory. 

The SessionPool is stored within an app/container. So even within the same microservice instances, you could have issues, as the SessionPool is not shared between the instances. So you would need some kind of shared SessionPool. So maybe, it is possible, if you create a SessionPool which can be used by multiple services. So e.g. write a SessionPool class, which uses redis or a new SessionStore microservice. And then you could share it.

But I personally assume, that your design is fault in the beginning. If you have data which is shared over multiple services, than it indicates, that you "cut" your database wrong. So maybe those entities you try to manage are actually belonging together, so you have actually rearrange the responsibilities of your microservices. 

E.g. at a previous employer we had "resources", which were called "form", "flow", "lexicon" and a container resource called "project" etc.. While we hade a service-lexicon, a sevice-flow, a sevice-project, it was basically wrong design, as we had always issues when we wanted to clone a project. So the result was to redesign those microservices into one service-resources. 

Sharing the transaction session id between microservices is actually indicating, that you try the wrong appoach for microsevices, because you are basically tightly coupling the microservices by the use of the mongo-session. You should consider to apply the SAGA-pattern. 
https://microservices.io/patterns/data/saga.html
https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/saga/saga

**Comment by nbusser** [comment]
Thank you so much for your instructive reply.

You are right, I realized that my microservices design is not adapted for this context.  
I actually changed my whole flow to be handled by the same microservice and use the same mongo session.
