### ISSUE TITLE
unique constraint failing on the field

### ISSUE THREAD

**Issue by arunkumar413kadari** [Automattic/mongoose#12973]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

4.13.14

### Node.js version

14

### MongoDB version

5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Issue

Hi Team,

I have a field that initially allowed to have duplicate values but now if I mark it as `unique: true` the app throws the below error. Any idea on how to enforce unique constraint on a field?

` "uncaughtException: E11000 duplicate key error collection`

Thanks,
Arun

**Comment by anuragphadnis** [comment]
This happens when you have nonunique values in the field where you want to apply the unique constraint. Please check your database for nonunique values. Now since you want to enforce this unique field one way could be to update the fields in the MongoDB database and ensure that no duplicate fields exist.

**Comment by arunkumar413kadari** [comment]
@anuragphadnis Thanks for the information.
