### ISSUE TITLE
Bug: Anti-pattern with usage of class/prototype inheritance

### ISSUE THREAD

**Issue by titanism** [Automattic/mongoose#12971]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.9.0

### Node.js version

16.x

### MongoDB server version

4.4, 5.x

### Description

The logic in `mongoose/lib/connection.js` calls `this.doClose`.  However this is an anti-pattern to call a function that one _assumes_ exists due to inheritance and usage.

<https://github.com/Automattic/mongoose/blob/8d9df24c1f4696d56a4c7d240d5bcedf6a008154/lib/connection.js#L1013-L1025>

We discovered this when we tried to make a custom connection by requiring `const Connection = require('mongoose/lib/connection');` as one might anticipate to be able to do.  However you _actually_ need to require the native connection class instead as `const Connection = require('mongoose/lib/drivers/node-mongodb-native/connection');`.

Otherwise when you disconnect, an error will be thrown of `this.doClose` is not a function, since you require'd the wrong class.  This is an anti-pattern.

**Comment by vkarpov15** [comment]
Can you let me know why you're trying to create a custom connection? You should only use `createConnection()` to create connections.

I suppose one thing we could do is just add a `doClose()` method on the connection base class that just throws an unimplemented error. Not a huge issue since you shouldn't instantiate the base connection class anyway.
