### ISSUE TITLE
Filter out duplicate documents returned by Mongo

### ISSUE THREAD

**Issue by mistval** [Automattic/mongoose#13168]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

MongoDB can [return the same document more than once](https://www.mongodb.com/docs/manual/core/read-isolation-consistency-recency/#cursor-snapshot) from a cursor under some circumstances. I have witnessed this behavior and have seen it cause surprising issues.

I propose that the mongoose `find()` function should filter out duplicate (same `_id`) documents, taking only the one most recently returned by the cursor.

If it's agreed that this would be in-scope for mongoose, I would also be interested in implementing it myself.

### Motivation

This behavior of MongoDB is not well known. It can cause problems in some cases, and is never desirable (at least not in the context of the mongoose `find()` function).

Although this is "just how the database works", I think patching over that ugly detail is within the scope of mongoose as I understand it. Like how the `__v` field exists to save us from ourselves.

### Example

You have a producer-consumer architecture where the consumer queries MongoDB for jobs to work on. Due to this behavior of MongoDB, you wind up processing the same job twice. Whoops!

**Comment by vkarpov15** [comment]
I'm not sure what Mongoose can do to solve this. We could maybe store a set of `_id` properties that have come out of a query cursor and filter out any duplicates, but I don't think that would be good default behavior because it would be very memory intensive. May cause OOM errors with large data sets.

Not saying no necessarily, but curious to hear about what you had in mind for how to prevent duplicates.

**Comment by mistval** [comment]
Hi Valerli, thanks for your response. My inclination would be to do what you say: have a Set, iterate over the results, add their `_id`s to the set, and skip any whose `_id` is already in the set. Like you say, it would have a cost in terms of memory, and CPU too.

**Comment by vkarpov15** [comment]
The problem is that we try to avoid any cases where Mongoose holds on to memory for an extended period of time. I can potentially see the `new Set()` approach as a plugin, but I think it is a bit risky to make this default behavior for Mongoose because of the memory cost. Especially since developers typically work with cursors when working with large result sets.
