### ISSUE TITLE
Collation not ignoring casing or diacritics

### ISSUE THREAD

**Issue by romankoulak** [Automattic/mongoose#13179]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

6.9.2

### Node.js version

16.18

### MongoDB version

0.0.0

### Operating system

Windows

### Issue

I have set a collation in my mongoose schema to
```
{ collation: { locale: "cs", strength: 1 } }
```
but it doesn't seem to ignore casing or diacritics when trying to find documents that include a substring (with $regex)
```
items = await Item.find({
      $or: [{ name: { $regex: substring } }, { OENumber: { $regex: substring } }],
    });
```
In my DB i have documents with names like "Café" or "café" but when looking for documents where name contains a substring "cafe", i get an empty array instead of these two documents. Tried different locales like en_US but nothing changed.

**Comment by romankoulak** [comment]
> Please check with mongo compass or studio3T or your favorite mongo client if the collatoin was set properly, to determine if the collatoin was set properly.

Even in mongo compass a simple query like 
```
{name: {$regex: "cafe", $options: "i"}}
```
with collation {locale: "en_US", strength:1} doesn't find a document with name "Café". What am i missing ?

**Comment by vkarpov15** [comment]
Try dropping the `Item` model's underlying collection, set `mongoose.set('autoCreate', true)`, and try again. If the underlying collection already exists, Mongoose won't update the collection's collation when you set `collation` on your schema. That's because MongoDB doesn't support updating an existing collection's collation, you need to drop the collection first. See https://stackoverflow.com/questions/48840147/how-to-view-or-modify-collation-options-set-on-a-mongodb-collection.
