### ISSUE TITLE
bulkWrite with empty array holding the query in 7.0.4 version. 

### ISSUE THREAD

**Issue by ashishtorum** [Automattic/mongoose#13289]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.4

### Node.js version

18.x

### MongoDB server version

6.x

### Description

We had the below query and it was working till yesterday but in the last Mongoose update it stop working.
   `await Users.bulkWrite(data, option);` Sometime we had empty array inside data.  

### Steps to Reproduce

Try to bulk write empty array

**Comment by cauli** [comment]
I've been hit by a similar issue, I'm using NestJS (@nestjs/mongoose) and the bug appeared when bumping from their v8 to v9.  In my case "@nestjs/mongoose": "9.0.3" -> "9.2.2". 

I'm not sure yet of what is the root cause, but the behavior changed, and it matches the OP's description.

Basically, passing an empty array `[]` used to return a BulkWriteResult, but now it just hangs, meaning that none of the Promise results is called (`.then`, `.catch` or `.finally`):

```
      console.log("Starting");
      myModel
        .bulkWrite([], {
          ordered: false,
        })
        .then((result) => {
          {
            console.log("Successful", result);
          }
        })
        .catch((e) => {
          console.log("Error");
          console.error(e);
        })
        .finally(() => {
          console.log("Finally");
        });
```

On the console, we will see only `Starting`, no matter how much you wait.

Of course, it's a bit silly to `.bulkWrite` with an empty array, but what makes this bug bad and difficult to debug is a caller is `await`ing here, it will never throw an error, or respond anything. Request/flow of the of the application just halts forever.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  console.log('starting')
  try {
 await Test
    .bulkWrite([], {
      ordered: false,
    })
} catch (e) {
 console.log("Error");
 console.error(e);
}
Test
    .bulkWrite([], {
      ordered: false,
    }).then(res => console.log('res is', res))
    console.log('Done')
}

run();
```

**Comment by thaoula** [comment]
Hi @vkarpov15,

We recently upgraded from Mongoose 7.0.3 to 7.3.0 and we have encountered this issue today. We are using MongoDB 6.0.6.

If you send an empty array to bulkWrite the call will never yield after awaiting it. 

Regards,
Tarek

**Comment by vkarpov15** [comment]
@thaoula can you please open a new issue and provide a standalone repro script that demonstrates the issue you're seeing? @IslandRhythms ' script doesn't hang, so can you please modify that script to show the issue?
