### ISSUE TITLE
Allow string as type in interfaces for ObjectId

### ISSUE THREAD

**Issue by rkreienbuehl** [Automattic/mongoose#13288]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Because we need ObjectIds as strings in our application, I want to use the approach of #6996. This is great, but has one downside. We define interfaces for our models and also use them in the frontend. to achieve this to work, I have to define an id as `string | mongoose.Types.ObjectId`, otherwise the model has the following error:
```ts
Type '{ type: typeof mongoose.Schema.Types.ObjectId; ref: string; }' is not assignable to type 'SchemaDefinitionProperty<string>'.
  Types of property 'type' are incompatible.
    Type 'typeof ObjectId' is not assignable to type 'typeof Mixed | StringSchemaDefinition'.
      Type 'typeof ObjectId' is not assignable to type 'typeof Mixed'.
        Types of property 'schemaName' are incompatible.
          Type '"ObjectId"' is not assignable to type '"Mixed"'.ts(2322)
```
It would be nice if I could define the id as `string` in the interface and in the model define it as `type: Schema.Types.ObjectId`.

### Motivation

cleaner interfaces

### Example

Interface:
```ts
export interface ITestInterface {
  _id: string;
  test: string;
}
```

Schema:
```ts
export const testInterfaceSchema = new Schema<
  ITestInterface
>(
  {
    test: {
      type: Schema.Types.ObjectId,
      ref: 'TestInterface',
    },
  }
);
```

**Comment by rkreienbuehl** [comment]
In a short test I did, it was enough when I changed the following in the file `schematypes.d.ts`
```ts
class SchemaTypeOptions<T> {
    type?: T extends string
      ? StringSchemaDefinition
      ...
```
to:
```ts
class SchemaTypeOptions<T> {
    type?: T extends string
      ? StringSchemaDefinition | ObjectIdSchemaDefinition
      ...
```
I will make a pull request

**Comment by vkarpov15** [comment]
Copying my comments from #13404 

I don't think this is the approach we want to take to support https://github.com/Automattic/mongoose/issues/13288. Because this change as written would allow defining documents where the document interface says string but the schema says ObjectId even if you don't use mongoose.ObjectId.get(v => v != null ? v.toString() : v);

So while this change does unblock your use case, I also think this introduces behavior that many would consider a bug. I'll look for alternatives.

Here are a couple of potential workarounds:

1) Force TypeScript to accept `type: ObjectId` in place of a string as follows:

```ts
import { Schema, SchemaDefinitionProperty } from 'mongoose';
  
export interface ITestInterface {
  _id: string;
  test: string;
}

export const testInterfaceSchema = new Schema<
  ITestInterface
>(
  {
    test: {
      type: Schema.Types.ObjectId,
      ref: 'TestInterface',
    } as unknown as SchemaDefinitionProperty<string>,
  }
);
~ 
```

2) The more idiomatic approach is to use Mongoose's `TMethodsAndOverrides` generic param for models and schemas. The first generic parameter to schema, the raw document type, represents the structure of the document _as it is stored in MongoDB_. So in your case, `_id: Types.ObjectId` is more correct than `_id: string`. Here's an example of how to set it so that `_id` is an objectid in your raw interface, but a string in your Mongoose documents:

```ts
import { Schema, Model, Types, model } from 'mongoose';
  
export interface ITestInterface {
  _id: Types.ObjectId;
  test: string;
}

export type TestModelType = Model<ITestInterface, {}, { _id: string }>;

export const testInterfaceSchema = new Schema<
  ITestInterface,
  TestModelType,
  { _id: string }
>(
  {
    _id: 'ObjectId',
    test: String
  }
);

const Test = model<ITestInterface, TestModelType>('Test', testInterfaceSchema);
const doc = new Test({ _id: new Types.ObjectId('0'.repeat(24)), test: 'foo' });
doc._id; // string
```
