### ISSUE TITLE
some new warnings on [MONGODB DRIVER]

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#13391]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.1.0

### Node.js version

20.1.0

### MongoDB server version

5.3.0

### Typescript version (if applicable)

5.0.4

### Description

2 new warnings when using mongoose v7

(node:338) [MONGODB DRIVER] Warning: keepAlive is a deprecated option: Will not be able to turn off in the future.
(node:338) [MONGODB DRIVER] Warning: keepAliveInitialDelay is a deprecated option: Will not be configurable in the future.

- [ ] keepAlive
- [ ] keepAliveInitialDelay

### Steps to Reproduce

just use mongoose v7

### Expected Behavior

do not show any warning

**Comment by vkarpov15** [comment]
Are you setting the `keepAlive` and `keepAliveInitialDelay` options? Because Mongoose doesn't set those.

[The MongoDB Node driver is deprecating those options](https://jira.mongodb.org/browse/NODE-5190). The recommended approach is to remove those options, because `keepAlive` defaults to true in Mongoose >= 5.2.0 anyway.

**Comment by sibelius** [comment]
We can close this, we were using this only on tests, it was helping with timeouts on tests

Should we just remove or is there some replacement?

**Comment by vkarpov15** [comment]
Just remove it. `keepAlive: true` does nothing since keepAlive is true by default, and there isn't really much need to set `keepAliveInitialDelay`. We had that option in the connection docs just as a copy/paste.

If you have problems with timeouts in your tests after removing these options, please post a note here and we'll help you debug.
