### ISSUE TITLE
Ref type docs missing

### ISSUE THREAD

**Issue by sanjarcode** [Automattic/mongoose#13400]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.1.1

### Node.js version

16.17.0

### MongoDB version

6.0.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

What are the implications of types if set on a ref, is missing?
Location: https://github.com/Automattic/mongoose/blob/ecb0249545670678c3d215f31bc0f2f85280559f/docs/populate.md?plain=1#L36

**Comment by vkarpov15** [comment]
@sanjarcode we'll adjust the docs, this warning is a bit overzealous. There aren't significant implications of adding `ref` to a particular property. We just advise using ObjectIds for refs for consistency because MongoDB generates ObjectIds for `_id` by default, so if you prefer numbers or UUID buffers you need to be careful that you're consistently generating numbers or UUIDs for ids. This was more important in older versions of Mongoose before `setDefaultsOnInsert` was enabled by default.

**Comment by sanjarcode** [comment]
Or just add a link.

Actually, I just wanted to know the reason behind such a warning/feature and no link/reason is mentioned. 

More specifically, I wanted to know the scenarios when you'd need types, like you explained @vkarpov15
