### ISSUE TITLE
Getting TooManyLogicalSessions from mongo due to high number of sessions in production enviroment

### ISSUE THREAD

**Issue by Pw-Saurabh** [Automattic/mongoose#13882]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.2.2

### Node.js version

16.20.0

### MongoDB version

6.0.10

### Operating system

Linux

### Issue

We recently faced an issue in our production environment MongoServerError: Unable to add session ID={sessionId} into the cache because the number of active sessions is too high. And service was getting killed with errorCode TooManyLogicalSessions.  also we were unable to [kill all the session](https://www.mongodb.com/docs/manual/reference/command/killAllSessions/#mongodb-dbcommand-dbcmd.killAllSessions) because mongo shell connection was not getting established.

Further with the mongo team help we got to know following things 
1. It is possible to notice that the number of open cursors started to increase.
2. The number of active sessions also started to increase but not so intense

we also got the logs from mongo team 

`{"t":{"$date":"2023-09-18T04:10:53.937Z"},"s":"I","c":"QUERY","id":20528,"ctx":"LogicalSessionCacheRefresh","msg":"Killing cursor as part of killing session(s)","attr":{"cursorId":3110656031645690000}}`

`{"t":{"$date":"2023-09-19T11:42:02.122+00:00"},"s":"I",  "c":"CONTROL",  "id":20715,   "ctx":"conn600090","msg":"Unable to add session into the cache, too many active sessions","attr":{"sessionId":{"id":{"$uuid":"{uuid}"},"uid":{"$binary":{"base64":"{base64id}","subType":"0"}}},"sessionCount":1000000,"maxSessions":1000000}}`

So i wanted to know following things
1. we are not using any transaction in our application code so how these sessions are getting created. Is mongoose done that internally ?
2. if it is managed by mongooes then why didn't it clear the sessions by itself.
3. and can we check any possible bugs' mongoose has related to this issue.
4. how can we avoid this to happen again and is there any why we can kill sessions which are not active for long time ?
5. any recommendation you guys can suggest we will appreciate that. 

thanks.

**Comment by vkarpov15** [comment]
Mongoose itself does not create any sessions implicitly. However, the [MongoDB Node driver creates a new session automatically for every operation](https://github.com/mongodb/node-mongodb-native/blob/3932260d2cf81898a2ce6fc75f6ea8d8a1694a45/src/operations/execute_operation.ts#L112-L117). The [MongoDB Node driver does clean up the implicit session after use](https://github.com/mongodb/node-mongodb-native/blob/3932260d2cf81898a2ce6fc75f6ea8d8a1694a45/src/operations/execute_operation.ts#L201-L203), given that you said the number of open cursors is increasing, I suspect the root cause is the high number of open cursors.

Do you have any idea why the number of cursors is increasing?

**Comment by vkarpov15** [comment]
Might be related to #13829
