### ISSUE TITLE
Docs Typo: `pathsToValidate` > `pathsOrOptions`

### ISSUE THREAD

**Issue by titanism** [Automattic/mongoose#14003]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

all

### Node.js version

all

### MongoDB server version

all

### Description

`pathsToValidate` is used in the codebase but the docs say `pathsOrOptions` right now

we should also add the note from `lib/document.js` of:

> list of paths to validate. If set, Mongoose will validate only the modified paths that are in the given list.

References: <https://github.com/search?q=repo%3AAutomattic%2Fmongoose%20pathsOrOptions&type=code>

### Steps to Reproduce

see above

**Comment by vkarpov15** [comment]
Oh I think the issue is that you're mixing up `Document.prototype.validate()`, which has a `pathsToValidate` parameter; with `Model.validate()`, which has a `pathsOrOptions` parameter.

* `list of paths to validate. If set, Mongoose will validate only the modified paths that are in the given list.` is from `Document.prototype.validate()` docs
* `pathsOrOptions` is a parameter to `Model.validate()`.

`Model.validate()` is the static function that lets you validate an arbitrary object against the model's schema. `Document.prototype.validate()` is a method that runs validation on a document, which is an instance of a model.
