### ISSUE TITLE
This expression is not callable.

### ISSUE THREAD

**Issue by amit548** [Automattic/mongoose#14025]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.3

### Node.js version

18.18.0

### MongoDB version

5.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

![image](https://github.com/Automattic/mongoose/assets/36206377/009f9b8d-beac-44d9-b96e-8cf63dbd0823)

How can I fix this issue?

**Comment by vkarpov15** [comment]
Add an explicit type for `this` in your middleware function signature. Or do `postSchema.pre('findOne')`. Mongoose isn't able to infer the type of `this` if you're using regular expressions in middleware.

It also looks like you're trying to automatically populate every time you query. I recommend using [mongoose-autopopulate](https://npmjs.com/package/mongoose-autopopulate) for that instead of writing it yourself.

**Comment by amit548** [comment]
I used ts-error ignore in my vscode
