### ISSUE TITLE
RangeError: Maximum call stack size exceeded when trying to use Types.ObjectId in tests

### ISSUE THREAD

**Issue by Stanys-dev** [Automattic/mongoose#14179]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.2 | 6.12.3

### Node.js version

16.20.2

### MongoDB server version

6.0.12

### Typescript version (if applicable)

4.9.5 | 5.3.3

### Description

I get RangeError when trying to run tests which includes models with Types.ObjectId.

### Steps to Reproduce

Repo: https://github.com/Stanys-dev/mongoose-range-error

### Expected Behavior

Tests should run without error

**Comment by vkarpov15** [comment]
This issue is very strange; only happens when importing `getModelToken()`, and only in Jest. I can `import nestJSMongoose from '@nestjs/mongoose'` or `import { Document } from '@nestjs/mongoose'` fine, and I can also `import { getModelToken } from '@nestjs/mongoose'` in `src/model.ts`. But importing then using `getModelToken` from the test file itself triggers this error.

The ideal solution would be for you to use any testing framework other than Jest. Jest does a lot of strange monkeypatching of globals and imports, it is more of a separate JavaScript runtime than a testing framework. We strongly recommend using anything else.

Another workaround is to avoid using `getModelToken()`, with the way you're using `getModelToken()` you can just replace it with a simple one-liner (see https://github.com/nestjs/mongoose/blob/586f6e0820ee7124bb240d3ded21c9af7cb98de0/lib/common/mongoose.utils.ts#L6):

```ts
beforeEach(async () => {
  const app: TestingModule = await Test.createTestingModule({
    controllers: [AppController],
    providers: [
      AppService,
      {
        provide: 'UserModel', // <-- same thing as getModelToken(User.name)
        useValue: {
          create: jest.fn(),
        },
      },
    ],
  }).compile();

  appController = app.get<AppController>(AppController);
});

```

I wish we had a better solution, but we've already spent hours debugging this to no avail; we will just have to chalk this up to Jest's quirks. The only thing we've been able to find is this code in bson:

```ts
export {
  Binary,
  BSONRegExp,
  BSONSymbol,
  Code,
  DBRef,
  Decimal128,
  Document,
  Double,
  Int32,
  Long,
  Map,
  MaxKey,
  MinKey,
  ObjectId,
  Timestamp
} from 'bson';
```

compiles to something like the following:

```javascript
Object.defineProperty(exports, "ObjectId", { enumerable: true, get: function () { return bson_1.ObjectId; } });
```

For some reason, Jest is compiling the TypeScript into a case where `bson_1` is equal to `exports`. Changing to `export const ObjectId = BSON.ObjectId;` works fine.
