### ISSUE TITLE
Cant use collection.stats() anymore

### ISSUE THREAD

**Issue by justoverclockl** [Automattic/mongoose#14175]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.2

### Node.js version

18.17.0

### MongoDB server version

atlas

### Description

i can't use anymore

`const clientSize = await myModel.collection.stats()`

### Steps to Reproduce

call the method and see the error.

**Comment by sean-daley** [comment]
My guess is this is due to the Mongo 6 driver update reported in the 8.x migration log. Given that "A Mongoose collection is a thin wrapper around a [MongoDB Node.js driver collection]" (from the mongoose docs on model.collection)

There is a separate Mongo readme about changes to the v6 driver here:
https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0

That document has the following section in it:
```
collection.stats() removed
The collStats command is deprecated starting in server v6.2 so the driver is removing its bespoke helper in this major release. The collStats command is still available to run manually via await db.command(). However, the recommended migration is to use the [$collStats aggregation stage](https://www.mongodb.com/docs/current/reference/operator/aggregation/collStats/).

The following interfaces associated with this API have also been removed: CollStatsOptions and WiredTigerData.
```

**Comment by vkarpov15** [comment]
@sean-daley is right, this is due to the MongoDB Node driver removing the `stats()` method. You should use `MyModel..aggregate( [ { $collStats: { count: { } } } ] )` instead
