### ISSUE TITLE
different behavior of arrays in 6.x when compared to 5.x

### ISSUE THREAD

**Issue by rohanricky** [Automattic/mongoose#14244]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.5

### Node.js version

18.12.1

### MongoDB server version

3.6.6

### Description

Repro Script:
```
const mongoose = require('mongoose');
const util = require('util')
console.log(mongoose.version)
let Schema = mongoose.Schema
var eventSchema = new Schema({
  name: { type: String },
  arr: { type: Array, patch: true },
})

var Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  let eventObj = new Event({ name: 'event object', arr: ['x', 'y', 'z'] })
  eventObj.save(function (err, eventObj) {
    console.log(util.types.isProxy(eventObj['arr']))
    eventObj['arr'].push('8')
    console.log(eventObj['arr'])
    eventObj['arr'].push({
      $each: ['a'],
      $position: 3
    })
    console.log(eventObj['arr'])
    eventObj['arr'].push({
      $each: ['b'],
      $position: 2
    })
    console.log(eventObj['arr'])
    eventObj['arr'].push({
      $each: ['c'],
      $position: 1
    })
    console.log(eventObj['arr'])
  })
}
run();
```

### Steps to Reproduce

Output with 5.12.5
``` 
false
['x', 'y', 'z', '8']
['x', 'y', 'z', 'a', '8']
```

Output with 6.12.5
```
true
[ 'x', 'y', 'z', '8' ]
```

### Expected Behavior

Expected behavior same as output with 5.12.5

**Comment by vkarpov15** [comment]
The issue is that, in Mongoose 6, Mongoose throws the following error on `eventObj['arr'].push({ $each: ['a'], $position: 3 })`:

```
MongooseError: Cannot call `Array#push()` multiple times with different `$position`
    at Proxy.push (/mongoose/lib/types/array/methods/index.js:687:15)
    at /gh-14244.js:18:21
    at /mongoose/lib/model.js:5361:18
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Emitted 'error' event on Function instance at:
    at /mongoose/lib/model.js:5363:15
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

```

Which is correct: you cannot call `push()` multiple times with different `$position` arguments. In Mongoose 5, you get the same error, just on `eventObj['arr'].push({ $each: ['b'], $position: 2 })`, which is why the last 2 `console.log(eventObj['arr'])` calls don't execute. 

The fact that Mongoose 5 doesn't throw an error on the first `push()` with `$position` is problematic, because if you `save()` after `eventObj['arr'].push({ $each: ['a'], $position: 3 })` Mongoose 5 will execute the following update, which doesn't include '8':

```
events.updateOne({ _id: ObjectId("65a14da76426c0e707381953") }, { '$push': { arr: { '$each': [ 'a' ], '$position': 3 } }, '$inc': { __v: 1 }}, { session: null })
```

We will make it so that calling `push()` multiple times with a different `$position` just overwrites the entire array.
