### ISSUE TITLE
Bug while creating document

### ISSUE THREAD

**Issue by gioimtg2003** [Automattic/mongoose#14413]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.3

### Node.js version

v21.5.0

### MongoDB server version

7.05

### Description

I tried to create document but it gave error Error - ValidationError: Description: Path `Description` is required

### Steps to Reproduce

**Model**
```js
let Order = new mongoose.Schema({
  Description: {
        type: String,
        required: true
    },
};
let data = {Description : description ?? ""}; 
let order = new SchemaOrder(data);
//error
let newOrder = await order.save();
```

**Comment by sean-daley** [comment]
I’m guessing it’s because your document is passing in an empty string for description. A required string means it has a value (and the empty string is not considered a value).  You have a few options I think including.
1. https://mongoosejs.com/docs/api/schematype.html#SchemaType.checkRequired() (You can change the behavior of that check globally)
2. What we’ve done at my company for these is make it not required and put in a default of ‘’ in th schema so that it always gets a value.

probably other solutions too but those are the two main ones I know about.

**Comment by donoftime2018** [comment]
My question is. In the line `let data = {Description : description ?? ""}; `, where does the identifier 'description.' Moreover, you haven't declared any path in the schema called 'description.'

**Comment by vkarpov15** [comment]
[Empty string `""` fails the `required` check for strings in Mongoose](https://mongoosejs.com/docs/api/schemastring.html#SchemaString.prototype.checkRequired()) by default. If you want to allow empty strings to pass `required` validator for strings, run the following code when your program starts.

```javascript
// Allow empty strings to pass `required` check
mongoose.Schema.Types.String.checkRequired(v => v != null);
```
