### ISSUE TITLE
Using `watch` only sends insertion events, not delete or update

### ISSUE THREAD

**Issue by AlexanderEpolite** [Automattic/mongoose#14524]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.3.1

### Node.js version

20

### MongoDB version

7.0.8

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Issue

The following code is only logging when an `insertion` event happens; however, delete and update events are not being sent in the "change" listener.

Let me know if I'm doing something wrong.

```typescript
const s = Member.watch([
    {
        $match: {"fullDocument.user_id": user_id, "operationType": {$in: ["insert", "update", "delete"]}},
    }
]);

s.on("change", (change) => {
    console.log(change);
});
```

**Comment by FaizBShah** [comment]
If you remove the options object in the watch() function, is it working?

**Comment by AlexanderEpolite** [comment]
> If you remove the options object in the watch() function, is it working?

@FaizBShah it works when I have this:
```ts
const s = Member.watch();
```

But not with this:
```ts
const s = Member.watch([
    {
        $match: {"fullDocument.user_id": user_id},
    }
]);
```

Any clue what might be causing it?  I'm probably going to just switch to once watch stream anyways to save resources.

**Comment by FaizBShah** [comment]
Im not too familiar with the type of the argument passed in the `.watch()` function, but according to this [doc](https://mongodb.github.io/node-mongodb-native/4.9/classes/Collection.html#watch:~:text=%7B%20%24match%3A%20%7B%20operationType%3A%20%27insert%27%20%7D%20%7D), the `operationType` field should be in the second object, not in the first. Basically, the issue is with the incorrect object structure of the argument.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  user_id: mongoose.Schema.Types.ObjectId,
  name: String
});


const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect(process.env.MONGOOSECONNECTIONSTRING);
  await mongoose.connection.dropDatabase();
  const userId = new mongoose.Types.ObjectId();
  const s = Test.watch([
    {
      $match: {"fullDocument.user_id": userId },
    }
  ]);

  s.on('change', (change) => console.log('change', change))

  const doc = await Test.create({
    user_id: userId,
    name: 'Test Testerson'
  });

  const res = await Test.updateOne({ _id: doc._id }, { name: 'Test' });
  console.log('what is res', res);
  console.log('done');
}

run();
```

**Comment by vkarpov15** [comment]
This is expected behavior, you need to set the [`fullDocument` option to `watch()`](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html#updates-and-the-fulldocument-option) in order for the `fullDocument` property to show up on updates and deletes. Use the following syntax:

```javascript
const s = Member.watch([
    {
        $match: {"fullDocument.user_id": user_id, "operationType": {$in: ["insert", "update", "delete"]}},
    }
], { fullDocument: 'updateLookup' });
```
