### ISSUE TITLE
Query recursive model with discriminator not working with string ref id filter

### ISSUE THREAD

**Issue by nikzanda** [Automattic/mongoose#14664]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.1

### Node.js version

20.10.0

### MongoDB server version

6.0.2

### Typescript version (if applicable)

5.4.5

### Description

Reproduction link: https://stackblitz.com/edit/stackblitz-starters-ypt8r8?file=src%2Findex.ts

I have a model named “Node” with two discriminators, “ParentNode” and “ChildNode” respectively. The ChildNode subclass has a “parentNode” property of type ObjectId, which refers to the “ParentNode” subclass. I noticed that when querying the Node model by the “parentNode” field using a string id, the query does not work. However, it works when using the ObjectId. In MongoDB, this use case is correct. But in Mongoose, when querying a model by an ObjectId property using only a string value, the query works just as well. Therefore, I expect the same behavior for subModels.

The `nodeQueryResult1` does not work, while `nodeQueryResult2` does
![image](https://github.com/Automattic/mongoose/assets/71180446/a1a0a185-4269-4d47-b15a-171750323590)

Both `projectQueryResult1` and `projectQueryResult2` work as expected.
![image](https://github.com/Automattic/mongoose/assets/71180446/17a4e5bc-4e47-4459-966e-e4a8438ad9cd)

Please note that the `nodeQueryResult1` query does not work when passing an id of string type, while the `projectQueryResult` query works with both a string type id and an ObjectId type id.
![Screenshot 2024-06-12 at 11 45 47](https://github.com/Automattic/mongoose/assets/71180446/16e04232-0910-48ce-9e5c-328ae22cd565)

### Steps to Reproduce

Clone the repository locally, compile the TypeScript code and run the command:

```sh
npx tsc && node --experimental-specifier-resolution=node dist/index.js`
```

### Expected Behavior

I expect that if I can query any model by a reference property of type ObjectId using a string value, I should also be able to query a subclass in the same manner.

**Comment by vkarpov15** [comment]
This is expected behavior. `parentNode` is not a property on `Node` model, so Mongoose doesn't do any casting on that property. So `{ parentNode: { $in: [parentNode._id] } }` will work as expected, because `parentNode._id` is an ObjectId and Mongoose doesn't strip out unknown keys from query filters by default. But `{ parentNode: { $in: [parentNode.id] } }` won't work, because Mongoose won't cast `parentNode.id` (type string) to ObjectId.

There are a couple of workarounds:

1) Specify the discriminator key using the following syntax. If you explicitly specify you're looking for nodes of type `ChildNode`, Mongoose will be able to infer that `parentNode` should be an ObjectId:

```ts
  const nodeQueryResult1 = Node.find({
    kind: 'ChildNode',
    parentNode: {
      $in: [parentNode.id],
    },
  });

```

2) Explicitly convert `parentNode.id` to an ObjectId:

```ts
  const nodeQueryResult1 = Node.find({
    parentNode: {
      $in: [new mongoose.Types.ObjectId(parentNode.id)],
    },
  });
```
