### ISSUE TITLE
Private PKG: MongooseError: Operation `users.findOne()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by Sagar2011** [Automattic/mongoose#14683]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.2.4

### Node.js version

20.10.0

### MongoDB version

7

### Operating system

macOS

### Issue

Facing Error for this while connecting to mongodb (locally hosted) via mongoose.

I have created a custom pkg names as bifrost and updated the connection as:

```
import {connect, disconnect, ConnectOptions} from 'mongoose';

export class MongoConnection {
  private config: string;
  private connectOptions: ConnectOptions;

  constructor(config: string, connectOptions: ConnectOptions) {
    this.config = config;
    this.connectOptions = connectOptions;
  }

  public async connect() {
    console.log('Connecting to Mongo Server ...', this.config);
    try {
      return connect(this.config, this.connectOptions);
    } catch (err) {
      console.error('Database connection error:', err);
      throw err; // Rethrow the error after logging it
    }
  }

  public async close() {
    try {
      await disconnect();
      console.log('Database connection closed');
    } catch (err) {
      console.error('Error closing MongoDB connection:', err);
    }
  }
}
```
And imported this pkg in the sample service
```
import {ConnectOptions, model, Schema} from 'mongoose';
import { MongoConnection } from 'bifrost';

async function connect() {
    const option: ConnectOptions = {
        maxPoolSize: 5,
        connectTimeoutMS: 30000
    }
    const mong = new MongoConnection('url', option);
    const n = await mong.connect();

    console.log(`check connection`, n.connection.readyState)
    const user = new Schema({
        name: String,
        age: Number
    })

    const User = model('User', user);
    console.log(`check connection`, n.connection.readyState)
    return User.findOne({}).exec();
}

connect().then(console.log).catch(console.error);
```

NOTE: I have used correct url here so ignore it.

Weird:

When I direct use mongoose in the service its working but using private pkg is not working tried all solution nothing work.

mongoose: 8.2.4 node: 20.10.0

attaching: https://stackoverflow.com/questions/78658859/private-pkg-mongooseerror-operation-users-findone-buffering-timed-out-afte

**Comment by vkarpov15** [comment]
What's the output from `npm list mongoose`? Most likely explanation is that you have two separate copies of the Mongoose module due to version incompatibilities.

When you do `const mong = new MongoConnection('url', option);`, you have `mong` which internally references the `bifrost` package's copy of `import mongoose from 'mongoose'`. But then you're creating the `User` model on the client package's `import mongoose from 'mongoose'` copy of Mongoose.

Likely the cleanest workaround would be to do the following: `const User = n.model('User', user);` - use `n.model()` because `n` is the `bifrost` package's copy of the Mongoose package.

You should also review our guide to [sharing schemas between projects](https://mongoosejs.com/docs/shared-schemas.html)
