### ISSUE TITLE
In which case the ID field is automatically converted to ObjectId?

### ISSUE THREAD

**Issue by nvmnghia** [Automattic/mongoose#14688]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7

### Node.js version

20

### MongoDB version

7

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

24.04

### Issue

In `findOne()`, I can pass `_id` or any other ID fields as string, and Mongoose seems to auto convert them to `ObjectId`. However, this doesn't apply to aggregation. Is there a general rule for this auto conversion?

**Comment by vkarpov15** [comment]
Yes. Mongoose casts queries and documents to match your schemas. But [Mongoose does not cast aggregations by default](https://mongoosejs.com/docs/api/model.html#Model.aggregate()) because aggregations can change the shape of the data.

![image](https://github.com/Automattic/mongoose/assets/1620265/36d5473e-2f2f-49a8-a37c-18fc8d4df85f)
