### ISSUE TITLE
Validators not working even when explicitly switched on

### ISSUE THREAD

**Issue by danielAsaboro** [Automattic/mongoose#14725]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.1

### Node.js version

v20.14.0

### MongoDB server version

7.0.11

### Description

Validators don't work when i find by id and update event when it's shows internally that they've been set to true.

### Steps to Reproduce

```js
// preceeding code removed for brevity

   duplicate: {
      type: Schema.ObjectId,
      ref: "Polling_Unit_Result",
    },
    authorId: {
      type: Schema.ObjectId,
      required: [true, "Please submit an editor Id for authorization"],
    },

// code after removed for brevity


pollingUnitResultSchema.pre("findOneAndUpdate", function (next) {
  console.log(this.options.runValidators); // logs out true

  console.log("its crazy out here");

  this.options.runValidators = true;
  console.log(this.options.runValidators); // logs out true
  next();
});
```

```js
   const updatedResult = await PollingUnitResult.findOneAndUpdate(
      { _id: req.params.id },
      processedData, // bunch of data that doesn't include 'authorId'
      {
        new: true,
        runValidators: true,
        setDefaultsOnInsert: true,
        upsert: true,
        context: "query",
      }
    );
```

### Expected Behavior

I expect that authorId field will error out when it isn't submitted....

**Comment by vkarpov15** [comment]
[Update validators only run on updated paths](https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths) - if `authorId` isn't in the update, update validators won't throw an error, because Mongoose doesn't know if the document in the db has `authorId` or not.

You can use `await PollingUnitResult.validate(processedData);` to validate `processedData` against the `PollingUnitResult` model's schema, does that help?
