### ISSUE TITLE
Library Type Matching Issue on WebStorm

### ISSUE THREAD

**Issue by Vasile-Peste** [Automattic/mongoose#14741]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.4.4

### Node.js version

20

### MongoDB version

7

### Operating system

macOS

### Issue

Hello,

<img width="747" alt="Screenshot 2024-07-11 at 18 09 25" src="https://github.com/Automattic/mongoose/assets/13590581/f8f23ecd-9619-4d7a-9e2a-9fab449e098f">

I'm using WebStorm 2024.1.5

"mongoose": "^8.4.4",
"@types/mongoose": "^5.11.97",

I don't understand if it's an issue of Mongoose or the IDE, but basically it happens only with Mongoose: for every method, it's like all the optional parameters are marked as required

Can someone help me?
Thanks!

**Comment by vkarpov15** [comment]
Why do you have `@types/mongoose` installed? That might be causing some issues.

**Comment by Vasile-Peste** [comment]
> Why do you have `@types/mongoose` installed? That might be causing some issues.

I also tried without it but the issue persists

**Comment by vkarpov15** [comment]
Does this issue occur when you compile with TypeScript or is it just your IDE? As a general rule, we don't debug autocomplete issues in IDEs, especially since our [TypeScript types do define 0-3 argument overrides for Model.findOne()](https://github.com/Automattic/mongoose/blob/1972f7f04ce92bcef097a40d7c223122e56fb029/types/models.d.ts#L448-L471).

If this causes trouble for you, you can use `Poll.findOne({ _id: pollId }, null, { lean: true, session: mongoSession })` instead of chaining `.lean().session()`.
