### ISSUE TITLE
Model.deleteOne() delete the first document of the collection if no conditions are matched

### ISSUE THREAD

**Issue by kappuccino** [Automattic/mongoose#14898]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.6.3

### Node.js version

20.10

### MongoDB server version

6.0.15

### Description

the model function deleteOne() seems to not delete a document if no document match the condition, but delete the first item of the collection

### Steps to Reproduce

create 3 objects with {"name": 'object 1'}, {"name": "object 2"}
try await Model.deleteOne({foo: 'bar'}) (be sure {foo: 'bar'} does not map to any document

### Expected Behavior

No document should be deleted if the conditions don't match any document

**Comment by hunkydoryrepair** [comment]
you should show what the Schema for you Model is, because this is almost certainly known behavior.

if `foo` is not part of the defined Schema, mongoose will not include it in the filter passed to mongodb, in which case, you are just sending `Model.deleteOne({})` to mongoose. If using Typescript, I think it should warn you about the type mismatch.

**Comment by kappuccino** [comment]
of course this make sense !! my bad :(
Thank you for the clarification, 
I close the issue, because this is not a bug of couse, looks like more of a trap :)

**Comment by hunkydoryrepair** [comment]
It's trapped me before. a bit scary
