### ISSUE TITLE
Compatibility - MongoDB 8.0

### ISSUE THREAD

**Issue by lokacoding** [Automattic/mongoose#14934]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi,
is mongoose 8.7.0 already compatible with MongoDB 8.0?
On the mongoose Website onlx 7.X Version from 2023 are listed.

**Comment by hunkydoryrepair** [comment]
This is primarily a feature of the underlying mongodb driver.

Mongodb nodejs driver 6.9 added full support for MongoDB 8.0, but it has been compatible since version 5.
Mongoose 8.7 uses mongodb driver 6.9, and all versions release in 2024 have used mongodb driver 5.9.2 or higher.
The older versions won't support all the new features, however.

It's a bit bleeding edge, and both Mongoose 8.7 and mongodb driver 6.9 have showstopper bugs (IMO), since they hang indefinitely in some situations (writing large documents when under load). I would wait another month until those issues are ironed out before moving beyond mongoose 8.2.x

**Comment by vkarpov15** [comment]
Yes, Mongoose 8.7 is compatible with MongoDB server 8.0. For full MongoDB server 8.0 support, you should use Mongoose `^8.7`.

https://www.mongodb.com/docs/drivers/node/current/compatibility/ indicates that MongoDB Node driver 6.9 is required for full MongoDB server 8 support, so that's Mongoose 8.7.

**Comment by lawrenceong** [comment]
Mongoose 8.7.0 is hanging sometimes for me when using transactions.  Downgrading to 8.6.x fixes it.  May create a separate issue for it, but it looks a little unstable with mongodb 6.9.0.

**Comment by vkarpov15** [comment]
@lawrenceong please open a separate issue with a repro script or some code samples that demonstrate the code that's hanging
