### ISSUE TITLE
Performance Issue with withTransaction API Causing Prolonged Execution and 502 Errors

### ISSUE THREAD

**Issue by deepsangani97271** [Automattic/mongoose#14939]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.7.0

### Node.js version

20.11.1

### MongoDB server version

8.0.0

### Typescript version (if applicable)

5.5.3

### Description

When using the withTransaction API with Mongoose to handle transactions, I’m encountering significant delays that ultimately result in 502 errors. However, when I handle transactions manually (starting, committing, and aborting), the same operations complete successfully and within expected timeframes. This suggests an inefficiency or potential bug within withTransaction.

### Steps to Reproduce

1. Start a transaction using session.withTransaction.
2. Perform multiple database operations within the transaction, including create, update, and delete across various collections.
3. Observe that the transaction takes considerably longer than expected, sometimes leading to a 502 error in the backend.

### Expected Behavior

The withTransaction API should handle transactions efficiently, ensuring all operations are either committed or rolled back in a timely manner without introducing unexpected delays.

### Observed Behavior

Prolonged transaction times, resulting in 502 errors.
The issue does not occur with manual transaction handling (startTransaction, commitTransaction, and abortTransaction).
Delays are more noticeable under higher loads or with concurrent transactions.

**Comment by vkarpov15** [comment]
Without code samples, there's no way we'll be able to repro this issue. The issue report is too vague.

One thing you could try to narrow this down would be to try running your workload without transactions, and see if you still observe the same performance degradation. The performance degradation could in theory be within `withTransaction()`, but it may also be due to other Mongoose internals, or even in the MongoDB server itself.
