### ISSUE TITLE
Typescript testing

### ISSUE THREAD

**Issue by richardsimko** [Automattic/mongoose#15017]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

This is a request to improve the testing of TypeScript types. In the last year our team has experienced multiple issues where breaking type changes have been shipped as part of patch or minor versions, all of which involve very basic use cases and are issues which I personally would think should be caught by CI.

### Motivation

Fewer accidental breaking changes

### Example

Here are a few examples of issues that I mean:

#14026
#14062
#14282
#14974

Since most issues are resolved rapidly there might be more which our team hasn't encountered as they have been fixed by the time we try to upgrade.

**Comment by richardsimko** [comment]
I'm happy to help out with this but since I'm not familiar with the project I'd need some pointers on how it could/should be set up.

**Comment by hasezoey** [comment]
Mongoose typescript tests are in [`test/types`](https://github.com/Automattic/mongoose/tree/master/test/types), try to find a test file which is related to your case and put it in a function with the github issue (if there is one) or a proper function name.
(personally i would prefer a more descriptive function name, or at least a comment explaining what it tests)

For cases which "should just work" not much more modification that a reproduction case is necessary, but if you want to be more exact use the helper types `expectType`, `expectAssignable` and `expectError`. (as for how to use them, i recommend to look at existing tests)

And to run those tests run `npm run test-tsd` locally.

Also typescript types are quite complicated and big and somewhat restrictive whereas mongoose (at runtime) allows a wide variety of ways it could be interacted with, so it is likely not possible to catch all issues.

From my experience, types in mongoose are "second class" and could be changed in any version, though it felt like that since 7.x it had become more stabilized (at least in terms of breakage in patch versions).

**Comment by richardsimko** [comment]
Thanks for the guidance, I'll make sure to check that out and add some additional test cases!

**Comment by vkarpov15** [comment]
I'm sorry you've experienced issues with our TypeScript types. You're always welcome to contribute test cases as @hasezoey described to help us make sure we don't break patterns that you rely on.

As a general rule of thumb, when we fix a bug we add a test, so you'll see that we added TypeScript tests to cover #1402 and #14282.
