### ISSUE TITLE
Mongoose 8.8.x is not compatible with MongoDB 3.6

### ISSUE THREAD

**Issue by arnaudruffin** [Automattic/mongoose#15070]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.8.x

### Node.js version

 v20.9.0

### MongoDB server version

3.6

### Description

Since version 8.8.x we see that nodejs driver has been updated to 6.10 (see [this commit](https://github.com/Automattic/mongoose/commit/de3da48e7ccb0378bfe00996f6f6261b0b833f7d))

MongoDb driver [documentation]( https://www.mongodb.com/docs/drivers/node/current/compatibility/) specifies that support for MongoDB 3.6 is deprecated in Node.js driver v6.9 and dropped after that.
If we try to use Mongoose 8.8.x anyway on a 3.6 mongo it raises errors like : `Server at 0.0.0.0:xxxx reports maximum wire version 6, but this version of the Node.js Driver requires at least 7 (MongoDB 4.0)`

The documentation on mongoose capabilities https://mongoosejs.com/docs/compatibility.html still says that 3.6 should work. 

The doc should be updated or the dependency should be downgraded.

### Steps to Reproduce

Install MongoDB 3.6. Try to use it with mongoose 8.8

**Comment by vkarpov15** [comment]
I'm sorry for the trouble, but there isn't anything Mongoose can do about this other than update our docs. While I personally disagree with the practice of dropping support for versions in minor releases, the MongoDB Node driver did that in v6.10: https://github.com/mongodb/node-mongodb-native/blob/main/HISTORY.md#6100-2024-10-21, and doing so isn't entirely unreasonable given that MongoDB 3.6 has been EOL since April 2021. And I don't want to ship a major Mongoose release for this sort of change.

I would recommend either pinning Mongoose 8.7 or upgrading to MongoDB 4, I'm sorry for the trouble.

**Comment by arnaudruffin** [comment]
No worry, we already pinned a 8.7. But a documentation update would be nice :)
