### ISSUE TITLE
mongodb as a peerDependency

### ISSUE THREAD

**Issue by f3oall** [Automattic/mongoose#15073]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Move `mongodb` to `peerDependency`

### Motivation

Hey guys, can we move `mongodb` to a `peerDependency`? The issue is, I'm working on a wrapper around `mongoose`, and I need types from `mongodb`, so currently I need to import `mongoose/node_modules/mongodb` to keep the versions in sync.

Is there any specific reason, why it's not a peerDependency?

**Comment by vkarpov15** [comment]
We're not going to move mongodb to a peerDependency for the foreseeable future. Since peer dependencies aren't automatically installed, we don't want to make developers have to list mongodb as a dependency if they don't need to.

The easiest workaround would be for you to list a compatible version of mongodb in your package.json:

```
"dependencies": {
  "mongoose": "8.8",
  "mongodb": "~6.10.0"
}
```

npm should resolve it so that Mongoose uses the same copy of the npm module as your application.
