### ISSUE TITLE
Remove schema reserved words

### ISSUE THREAD

**Issue by j** [Automattic/mongoose#1653]
There has to be a way to not have any reserved words.  I'm working with existing data which has "options" as a key.  Welp, that happens to be a reserved key in schemas and throws an error for me.  Granted, I can probably map this some other way, or if mongoose allowed for field name mapping (which is a separate issue), I feel that the use of the word "option" or "options" is a common word.

Anyway, what do you think?

**Comment by hasezoey** [comment]
This issue is a duplicate (of the later) #9010, which was fixed by #10414, which was released in 6.0.0 (or `6.0.0-rc2`).

The mentioned PR "only" changed that the reserved keywords are not a error anymore, but a warning, but should still resolve this issue.

I think this can be closed @vkarpov15 , @IslandRhythms @Uzlopak 

PS: this issue should also maybe be added to the correct milestone, if closed
