### ISSUE TITLE
Windows 7 x64  npm install mongoose  Error

### ISSUE THREAD

**Issue by bahtou** [Automattic/mongoose#1757]
> kerberos@0.0.3 install C:\Users\<name>\Documents\webDev\self\week1\less\node_module
s\mongoose\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:980:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\<name>\Documents\webDev\self\week1\less
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT

> bson@0.2.2 install C:\Users\<name>\Documents\webDev\self\week1\less\node_modules\mo
ngoose\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:980:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\<name>\Documents\webDev\self\week1\less
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\<name>\Documents\webDev\self\week1\less\npm-debug.log
npm ERR! not ok code 0

not sure where to start?
any suggestions?

**Comment by looterz** [comment]
Same issue on Windows 10 x64 and Debian 7 Wheezy.

**Comment by vkarpov15** [comment]
@looterz can you post the npm output please?

**Comment by looterz** [comment]
The issue seems to stem from an unmet peer dependency.
[code]
looter@LOOTER c:\projects\mongo-test
$ npm i mongoose --save
npm WARN engine mongoose@4.3.3: wanted: {"node":">=0.6.19"} (current: {"node":"5.1.2-nightly201512091c1c1a0f2b","npm":"3.3.3"})
npm WARN engine mongoose@4.3.3: wanted: {"node":">=0.6.19"} (current: {"node":"5.1.2-nightly201512091c1c1a0f2b","npm":"3.3.3"})
npm WARN engine hooks-fixed@1.1.0: wanted: {"node":">=0.4.0"} (current: {"node":"5.1.2-nightly201512091c1c1a0f2b","npm":"3.3.3"})
npm WARN engine bson@0.4.19: wanted: {"node":">=0.6.19"} (current: {"node":"5.1.2-nightly201512091c1c1a0f2b","npm":"3.3.3"})
npm WARN engine bson@0.4.20: wanted: {"node":">=0.6.19"} (current: {"node":"5.1.2-nightly201512091c1c1a0f2b","npm":"3.3.3"})
mongo-test@1.0.0 c:\projects\mongo-test
└─┬ mongoose@4.3.3
  ├── async@0.9.0
  ├── bson@0.4.19
  ├── hooks-fixed@1.1.0
  ├── kareem@1.0.1
  ├─┬ mongodb@2.1.0
  │ ├── es6-promise@3.0.2
  │ ├── UNMET PEER DEPENDENCY kerberos@~0.0
  │ ├─┬ mongodb-core@1.2.26
  │ │ └── bson@0.4.20
  │ └─┬ readable-stream@1.0.31
  │   ├── core-util-is@1.0.2
  │   ├── inherits@2.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.31
  ├── mpath@0.1.1
  ├── mpromise@0.5.4
  ├─┬ mquery@1.6.3
  │ ├── bluebird@2.9.26
  │ └── debug@2.2.0
  ├── ms@0.7.1
  ├── muri@1.0.0
  ├── regexp-clone@0.0.1
  └── sliced@0.0.5

npm WARN EPEERINVALID mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPACKAGEJSON mongo-test@1.0.0 No description
npm WARN EPACKAGEJSON mongo-test@1.0.0 No repository field.
[/code]

Here is the install log for installing kerberos
[code]
looter@LOOTER c:\projects\mongo-test
$ npm i kerberos --save

> kerberos@0.0.17 install c:\projects\mongo-test\node_modules\kerberos
> (node-gyp rebuild) || (exit 0)


looter@LOOTER c:\projects\mongo-test\node_modules\kerberos
$ if not defined npm_config_node_gyp (node "C:\Users\loote\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v5.1.2-nightly201512091c1c1a0f2b/node-v5.1.2-nightly201512091c1c1a0f2b-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (C:\Users\loote\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:244:14)
gyp ERR! stack     at emitOne (events.js:83:20)
gyp ERR! stack     at Request.emit (events.js:170:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\loote\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1008:10)
gyp ERR! stack     at emitOne (events.js:78:13)
gyp ERR! stack     at ClientRequest.emit (events.js:170:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:422:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:312:20)
gyp ERR! stack     at emitOne (events.js:78:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\loote\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\projects\mongo-test\node_modules\kerberos
gyp ERR! node -v v5.1.2-nightly201512091c1c1a0f2b
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
mongo-test@1.0.0 c:\projects\mongo-test
└─┬ kerberos@0.0.17
  └── nan@2.0.9

npm WARN EPACKAGEJSON mongo-test@1.0.0 No description
npm WARN EPACKAGEJSON mongo-test@1.0.0 No repository field.
[/code]
