### ISSUE TITLE
QueryStream drops data if event is set late

### ISSUE THREAD

**Issue by seanodell** [Automattic/mongoose#1907]
I ran into an issue where QueryStream#on("data") misses records if the event is configured late. Below are steps to replicate:

First, populate a test database with a number of records to iterate over (execute in MongoDB shell):

```
test_db = db.getMongo().getDB("test");

test_db.test.remove();

for ( var index = 0; index < 30000; index++) {
  test_db.test.insert({
    index : index,
    value : Math.floor((Math.random() * 10000) + 1)
  });
}
```

Then, using QueryStream, iterate over all records:

```
var host = 'localhost';
var port = 27017;
var db = 'test';
var timeout = 200;

var mongoose = require('mongoose');

var conn = mongoose.createConnection('mongodb://' + host + ':' + port + '/' + db);

var schema = mongoose.Schema({
  index : Number,
  value : Number
});

var model = conn.model('Test', schema, 'test');

var query = model.find({});

var queryStream = query.stream();

var dataCount = 0;

setTimeout(function() {
  queryStream.on('close', function() {
    console.log("Data Count: " + dataCount);
  });

  queryStream.on('error', function(err) {
    console.log("ERROR: " + err);
  });

  queryStream.on('data', function(doc) {
    dataCount += 1;

    if (Math.floor(Math.random() * 100) == 50) {
      queryStream.pause();
      process.nextTick(function() {
        queryStream.resume();
      });
    }
  });
}, timeout);
```

If you set the timeout value to 0, you will probably get a count of 30000 (the actual number of records). Set it higher and the count drops, eventually down to zero if you set it to 1000ms or more.

It looks like the QueryStream is iterating through records in the background whether or not an event has been set up.

**Comment by blyork** [comment]
I ran into this issue myself. This is a work around:
```javascript
(new stream.Readable({ objectMode: true })).wrap(Model.find({}).stream());
```

**Comment by vkarpov15** [comment]
No update yet. Don't really have a good idea where this fits on the roadmap either - open to suggestions.

**Comment by helmus** [comment]
Bump !

**Comment by kfitzgerald** [comment]
I'd consider this problem to be a much more serious issue, especially because it's a real nasty "gotcha".

I ran into this when I discovered that 260,000 docs were dropped when processing a stream batch of 4.5 million docs, using `stream.pause` and `stream.resume` as a governor to control memory while processing. There's zero indication that something went wrong.

This should not be a "find out the hard way" sort of issue. At the very least, a well documented warning that pausing the stream may result in data loss, should be immediately warranted.
