### ISSUE TITLE
Weird 'Maximum call stack size exceeded' errors @ 3.8.6

### ISSUE THREAD

**Issue by d-oliveros** [Automattic/mongoose#1920]
Hello. I'm getting a 'Maximum call stack size exceeded' error when upgrading from 3.8.5 to 3.8.6. Reverting the version back to 3.8.5 seems to fix the issue.

I tried to trace the error back with no luck. If I try to run node with --stack-size=10000, I get a "Segmentation fault" error. The only solution I could find was revert the version to 3.8.5.

Is anyone else having issues with this?

The affected query looks like this:

var query = { _id: '52f2f10153a87ced0e04f6c6', community: { '$in': [ 1 ] } }

var update = { '$push': 
   { comments: 
      { user: 52f2ee3353a87ced0e04f6c5,
        body: 'asdqw',
        comments: [],
        _id: 52f44fc8f5d436332ae8293d,
        created: Thu Feb 06 2014 22:15:20 GMT-0500 (EST),
        counts: { appreciations: 0, comments: 0 } } },
  '$inc': { 'counts.comments': 1, karma: 90 } }

var fetch = { community: true,
  user: true,
  userName: true,
  path: true,
  title: true }

Post
.findOneAndUpdate(query, update, {select: fetch})
.exec(function(err, post){  ... })

**Comment by memelet** [comment]
I am seeing this now with 4.0.2. I am updating just a part of the document. Will post more if learn anything.

**Comment by vkarpov15** [comment]
Please do @memelet. The test isn't failing so I doubt it's the exact same issue...

**Comment by memelet** [comment]
The problem was invoking findOneAndUpdate(.., {upsert: true, new: true})

where update document contained attributes with undefined values.

eg,

{
  tenant: "tenantA",
  plants: undefined
}

When took care to remove undefined keys from the document the upsert works correctly.

Specifying undefined certainly should not be valid, but error could be handled better.
