### ISSUE TITLE
near()'s maxDistance seems to be being ignored

### ISSUE THREAD

**Issue by johngeorgewright** [Automattic/mongoose#1991]
Hey there,

I'm trying to write a simple query in Mongoose that returns a number of nearby results that all have GeoJSON properties. However, I'm getting a different number of results from my Mongoose script to that of a query directly in mongo.

Here's a raw Mongo script:

```js
var conn = new Mongo(),
    db = conn.getDB("my_db"),
    collection;

collection = db.my_moodels.find({
  geo: {
    $nearSphere: {
      $geometry: {
        type: "Point",
        coordinates: [-0.02028, 51.50703]
      },
      $maxDistance: 3000 // 3k I'm assuming
    }
  }
});

print(collection.length()); // I get 6 (which is round about right)
```

Here's my Mongoose script:

```js
MyModel
  .find()
  .where('geo')
  .near({
    center: [-0.02028, 51.50703],
    maxDistance: 3000,
    spherical: yes
  })
  .exec(function (err, results) {
    if (err) {
      throw err;
    } else {
      console.log(results.length); // Here I get over 340, which I think is all of the possible results.
    }
  });
```

As you can see, the result count is entirely different. In fact, changing the maxDistance property in the Mongoose script seems to do nothing.

I've also found that putting the query directly in to the `find()` method brings back the correct amount of results:

```js
MyModel
  .find({
    geo: {
      $nearSphere: {
        $geometry: {
          type: "Point",
          coordinates: [-0.02028, 51.50703]
        },
        $maxDistance: 3000
      }
    }
  })
  .exec(function (err, results) {
    if (err) {
      throw err;
    } else {
      console.log(results.length); // Now I get 6
    }
  });
```

Is there a problem with using the `near()` method or am I using it wrong?

**Comment by jyounus** [comment]
Is there any update on this? I have the same problem with mongoose. The maxDistance in my query seems to be ignored, it seems to act as a "sort" instead (sorts by closest locations instead of limiting them to a specific distance).

Here's my specific code for the "near" query:
```
.where("profile.coordinates").near({
            center: currentUser.profile.coordinates,
            maxDistance: 5000, // in meters
            spherical: true
        });
```

My user model for profile.coordinates is defined like this:
```
coordinates: {
            type: [Number], // must be lon/lat
            index: "2dsphere"
        },
```

It doesn't matter if I set the maxDistance or not, I always get the same amount of documents returned from the database (which is wrong, because not all of those documents are 5km away from my centre point).

**Comment by vkarpov15** [comment]
@jyounus that's how [mongodb `$near` works](https://docs.mongodb.org/v3.0/reference/operator/query/near/), has nothing to do with mongoose.

**Comment by jyounus** [comment]
According to the mongodb docs, it should limit the results and not just sort them (or am I not understand it properly?):

> $maxDistance limits the results to those documents that are at most the specified distance from the center point.

**Comment by vkarpov15** [comment]
First sentence on that page: "Specifies a point for which a geospatial query returns the documents from nearest to farthest."

**Comment by jyounus** [comment]
Well clearly the documentation is contradicting itself lol. Unless I have to specify the minDistance property as well for it to actually "limit" the results and not just sort.

**Comment by dttvinh** [comment]
I concur. Sorting and limiting doesn't have to be mutually exclusive.

Yes, `$near` "returns the documents from nearest to farthest," but that doesn't mean it can't limit the results with a `$maxDistance`.

In fact, the very reason this bug was created was because it works in mongodb shell, but not in mongoose.

**Comment by vkarpov15** [comment]
@dttvinh what query are you running exactly? `$maxDistance` should in theory limit the results.

**Comment by atheroth** [comment]
`$maxDistance` does not do anything for me in the below code. The following query only sorts the results by distance from the given geoJSON point. 

```
Model.find(
    {
      loc: {
        $near: {
          $geometry: {
            type: "Point",
            coordinates: coordinatesArray
          },
          $maxDistance: 5000
        }
      }
    }, function (error, results) { console.log(results) });
```

I reiterate that `$near` seems to work but `$maxDistance` does not.

**Comment by vkarpov15** [comment]
@atheroth `$maxDistance` needs to be at the same level as `$near`, not a sub-key of `$near` https://docs.mongodb.com/manual/reference/operator/query/maxDistance/

**Comment by atheroth** [comment]
Thanks for pointing that out. I'll try that now. However, the query examples for `geoJSON` data with `2dsphere`  indexes do show `$maxDistance` as a sub-key of `$near`. 
https://docs.mongodb.com/manual/reference/operator/query/near/#query-on-geojson-data

After fooling around in the past few days, I am now almost completely sure the problem is in my code.

**Comment by atheroth** [comment]
Confirmed nothing wrong with `$near` or `$maxDistance`. The problem was elsewhere in my code. Sorry! :sheep:

**Comment by eAmin** [comment]
> @jyounus that's how [mongodb `$near` works](https://docs.mongodb.org/v3.0/reference/operator/query/near/), has nothing to do with mongoose.

Then why the first example of  @johngeorgewright  works correctly?
Could you please explain that?

The main question is "Why maxDistance is ignored in mongoose but not in mongodb?".

Thank you.
