### ISSUE TITLE
$pull not working properly for subdocuments

### ISSUE THREAD

**Issue by hybreda** [Automattic/mongoose#2028]
The project I am working on utilizes a method where I have objects in two different collections that have references to each other through keeping an array of those references. In this case:

```javascript
Person: {_id: "111", items: [{_id: objID, itemID: "123123"}]}
Items: {_id: "123123", name: "pencil", people:[{_id: objID, personID: "111"}]}
```

Here's the problem. MongoDB runs the following query without any issues (tried through Robomongo):
```javascript
db.person.update({_id: ObjectId("111")}, {$pull : {"items" : {"itemID" : "123123"}}}, false, true)
```

However mongoose currently can't run the following properly:
```javascript
Person.update({_id : ObjectId("111")}, {$pull : {"items" : {"itemID" : "123123"}}}, function(err, count){})
```

is there a problem with $pull for subdocs?

**Comment by OKNoah** [comment]
I think you may have to pul the subdoc by the `_id` field.

**Comment by vkarpov15** [comment]
Hmm I think I see what the problem is. In robomongo, when you do `{$pull : {"items" : {"itemID" : "123123"}}}`, no casting is done, so mongodb pulls from the items array where the `ItemID` is equal to the string "123123".

However, mongoose will cast arguments, so if your PersonSchema says `itemID` is an ObjectId, mongoose will cast to ObjectId first, which is **not** a string, and then execute the update. Thus no items will match.
