### ISSUE TITLE
Cannot query for $type on Date fields

### ISSUE THREAD

**Issue by kilianc** [Automattic/mongoose#2045]
```js
module.exports = Schema({
  foo: { type: String },
  updatedAt: { type: Date, default: null },
}, { minimize: false })
```

```js
q.where({ updatedAt: { $ne: { $type: 10 } } })
```

    MongooseError: Cast to date failed for value "[object Object]" at path "updatedAt"

**Comment by vkarpov15** [comment]
This is not a valid query in MongoDB, mongoose is right in this case. `$ne: { $type: 10 }` means "find me every doc where `updatedAt` is not equal to the document `{ $type: 10 }`", which is every document in MongoDB >= 2.6 because it doesn't allow keys that start with '$'. For instance, in the MongoDB shell:

```
> db.dropDatabase();
{ "dropped" : "test", "ok" : 1 }
> 
> 
> db.test.insert({ x: 'abc' });
WriteResult({ "nInserted" : 1 })
> db.test.find({ x: { $ne: { $type: 2 } } }); // 2 = BSON type "string"
{ "_id" : ObjectId("55520c90c4f9ef851f3e7993"), "x" : "abc" }
```

The query returns the doc with x = "abc", even though "abc" is a string.
