### ISSUE TITLE
Validation bug?

### ISSUE THREAD

**Issue by kanata1988** [Automattic/mongoose#2096]
Hi, I just try mongoose and right now I'm having a difficulty using validation.
I tried to input `[123, 123]` to field `name`, which should be `String`, and it passed.

Here's my schema:

```
var Schema = require('mongoose').Schema,
    ObjectId = Schema.ObjectId,
    City;

City = new Schema({
    _id: ObjectId,
    name: { type: String, required: true },
    created_by: ObjectId,
    created_date: { type: Date, required: true },
    modified_by: ObjectId,
    modified_date: Date,
    is_deleted: { type: Boolean, default: false }
}, { collection: 'city' });

module.exports = City;
```

Is that the expected behavior or is it a bug?

**Comment by mark-langer** [comment]
I assume this issue can be closed.

**Comment by lineus** [comment]
@kanata1988 Sorry this went under the radar. 
@mark-langer Thanks for pointing this out. 

For anyone finding this in the future, I'll answer this question from the perspective of the latest release of mongoose (5.2.3), though I don't suspect it would have been a much different answer in previous versions.

This is the expected behavior because the elements in the array can be cast into strings. The cast value is a comma separated string of the input array's elements. It's this cast string that gets validated and as you pointed out, passes.

## Full code sample demonstrating this.

### 2096.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: [123, 123]});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.findOne();
  console.log(doc);
  return conn.close();
}

run();
```
### Output:
```
issues: ./2096.js
{ _id: 5b4c778a069a8213e9da2a08, name: '123,123', __v: 0 }
issues:
```

## One potential way to change this behavior:

You can test for an Array as input in a setter on the path and if true add a property to the errors object for that path. When validation occurs, a validation error will be thrown.

### 2096_with_error.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: {
    type: String,
    set: function(v) {
      if (Array.isArray(v)) {
        this.errors.name = new mongoose.ValidationError('');
        return undefined;
      }
      return v;
    }
  }
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: [123, 123]});

async function run() {
  await conn.dropDatabase();
  await test.save().catch(e => console.error(e.message));
  return conn.close();
}

run();
```
### Output:
```
issues: ./2096_with_error.js
test validation failed: name: Cast to String failed for value "[ 123, 123 ]" at path "name"
issues:
```
