### ISSUE TITLE
Mongoose method - useDb ( name) not allowing more than 10 concurrent requests

### ISSUE THREAD

**Issue by Chatosh** [Automattic/mongoose#2257]
Refer to the below Link for more info 
 https://jira.mongodb.org/browse/NODE-245

**Comment by danieljoppi** [comment]
+1

**Comment by vkarpov15** [comment]
Unfortunately this memory leak warning is by design. The way `useDb()` works is that it creates a new mongoose connection on top of the same connection pool, and each connection keeps track of all of the `useDb()` calls so that, if one connection closes the connection pool, all connections close. I'd recommend not calling `useDb()` transactionally (that is, don't call it in a route handler) because it'll leak memory on every request. That's just something `useDb()` is really not designed to do. #3302 will help slightly with this.
