### ISSUE TITLE
Add .catch to mpromise

### ISSUE THREAD

**Issue by hendricha** [Automattic/mongoose#2308]
Hey, I noticed that mpromise does not have a .catch, like the promise library we use (bluebird). It's a nice and simple feature, and makes one's promise chains a quite readable.

Note, that I did check, that .catch is not part of the Promise/A+ specs, however it does seem to be part of the ECMA Script 6 proposed specs. ( https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promisecatch ) I saw the discussion here ( https://github.com/LearnBoost/mongoose/issues/1699 ), that mpromise will eventually be just a schim until node promises arrive, and I checked out unstable node, the Promise there did have a .catch.

**Comment by zekenie** [comment]
:+1:

**Comment by DFectuoso** [comment]
+1

**Comment by Jokero** [comment]
+1

**Comment by markoknez** [comment]
+1

**Comment by loxy** [comment]
+1

**Comment by xpepermint** [comment]
+1

**Comment by AHgPuK** [comment]
+1

**Comment by dozoisch** [comment]
:+1: Lack of catch in mongoose is a pain. Have to wrap every call with native Promises.

**Comment by vkarpov15** [comment]
See #2688

**Comment by akolpakov** [comment]
+1 for supporting native ES6 Promises

**Comment by mavdi** [comment]
+1

**Comment by royhowie** [comment]
Probably already mentioned elsewhere, but I just use bluebird's `.promisifyAll` feature:

```javascript
let Promise = require("bluebird")
let mongoose = Promise.promisifyAll(require('mongoose'))
```

coupled with `.execAsync`. For example, in my `queries.js` file:

```javascript
export let userQueries = {
    // lots of other queries
    findBy: {
        email: (email) => User.findOne({ email }).execAsync()
    }
}
```

Then, in `passport.js`, I can use `.catch` with the Mongoose query:
```javascript
function login (req, email, password, done) {
    userQueries.findBy.email(email)
    /* lots of `then`s */
    }).catch((err) => {
        return done(null, false, req.flash('message', err.message || err))
    })
}
```

**Comment by JeffAshtonCT** [comment]
+1

**Comment by dgaubert** [comment]
+1

**Comment by paambaati** [comment]
+1. This is a pretty important feature, and for everyone jumping on ES6, this completely breaks immersion. I have code all over the place using `then(...).catch(...)` except for Mongoose!

**Comment by vkarpov15** [comment]
See #2688, 4.1.0 supports the below

`require('mongoose').Promise = require('bluebird');`
`require('mongoose').Promise = global.Promise;`
`require('mongoose').Promise = require('q').Promise;`

or whichever ES6 promise constructor you prefer.

**Comment by paambaati** [comment]
@vkarpov15 A-ha! Thanks a bunch. This is awesome.

**Comment by zekenie** [comment]
Hi @vkarpov15 just tried it with 4.1.0 and it doesn't seem to work for me. Throws an error that says undefined is not a function when I use `catch`

**Comment by paambaati** [comment]
@zekenie Works for me, actually. Here's how I do it now on 4.1.0 -

```
const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');

const UserSchema = new mongoose.Schema({...});

function createUser(userData) {
    const newUser = new User(userData);
    return newUser.save().then(function (savedUser) {
        return savedUser;
    }).catch(function (error) {
        console.log('something terrible went wrong!');
        throw error;
    });
}
```

Can you show us some code to help debug your problem?

**Comment by vkarpov15** [comment]
@zekenie are you actually setting `require('mongoose').Promise`? To avoid backwards breaking changes, right now mongoose still uses mpromise by default, but you can set `require('mongoose').Promise` to whatever ES6 promise constructor you want to use, including ones that support `.catch()` like native ES6 promises in Node >= 0.12, bluebird, Q.Promise, etc.

**Comment by adambuczynski** [comment]
I think for the next major version, maybe switch to native promise implementation by default?

**Comment by vkarpov15** [comment]
@adambuczynski yep we won't support mpromise at all in 5.0, will use native promises by default but support switching to whichever ES2015 promise constructor lib you want: https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings

**Comment by adambuczynski** [comment]
:+1:

**Comment by Jeff-Lewis** [comment]
@vkarpov15 without any hard stats, my gut says more and more people are using Bluebird. Strongloop is converting everything to use [Bluebird in 3.0 of loopback](https://github.com/strongloop/loopback/blob/master/3.0-RELEASE-NOTES.md#always-use-bluebird-as-promise-library). Do you think we can emphasize tests cases and code coverage for promises with bluebird in v5 even though v5 will technically be only supporting ES2015 promises?

**Comment by vkarpov15** [comment]
@Jeff-Lewis yeah I see a lot of people going to bluebird as well. On the other hand, with ideas like co and async/await, I haven't cared which promise library I'm using since mid-2015, and minimal promise libs like https://www.npmjs.com/package/es6-promise are seeing good adoption too.

v5 will support bluebird in the same way that >= 4.1 supports bluebird. There's really not much more we can do short of switching over to bluebird by default, and bluebird's too quirky and bloated for my tastes.

**Comment by adambuczynski** [comment]
@vkarpov15 what quirks do you think it has? I was under the impression that it was quite a decent promise library, after having a look at it last week (I was using native promises and Angular's $q before that).

But one big thing missing from native promises for example, is that there is no `.finally` in the spec yet. I think that's a big miss.

Also, Bluebird didn't seem too bloated, and even if it were, the performance gains over other libraries were quite impressive.

**Comment by vkarpov15** [comment]
Honestly I've never been a big fan of `.catch()` and `.finally()`. It is true that syntactic sugar is more important than most devs care to admit, but IMO those two functions are too trivial to lose sleep over.

My beef with bluebird is:

1) If I had a case where I really cared about getting every last drop of CPU performance, I wouldn't use promises. Frankly, I wouldn't even use node. I've yet to see a case where one promise lib has enough of a performance win over another promise lib to register on my care-o-meter.
2) [API is far too big](http://bluebirdjs.com/docs/api-reference.html). Smaller API is better, especially since 99% of what I want to do with promises is easily achieved with `.then()` and `.all()`. 
3) Weird bugs: https://github.com/aheckmann/mquery/pull/66

Contrast this with http://npmjs.org/package/es6-promise - nice neat minimal implementation that you can grok in 15 minutes https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/promise.js .

**Comment by adambuczynski** [comment]
Fair points, thanks for your feedback.

While you can pass in a second function to `.then()` and use that as an error handler, I do find that code is easier to read with a dedicated `.catch()` block. As for `.finally()`, that just helps with maintaining DRY principles. Often (particularily in front-end applications) after promises are returned there needs to be some clean up happening, like a button being re-enabled or a spinner turning off, and that needs to happen regardless of whether the promise has resolved or rejected. So in order to not repeat code, the `.finally()` block is ideal.

But I agree, in Node apps, there is much less need for `.finally()`

**Comment by Jeff-Lewis** [comment]
@vkarpov15 Regarding 3) Weird bugs: aheckmann/mquery#66, I added a [comment](https://github.com/aheckmann/mquery/pull/66#issuecomment-182499401) to it.
