### ISSUE TITLE
Add support for bulk API

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2366]

**Comment by jtmarmon** [comment]
Is there a workaround for this for now?

**Comment by vkarpov15** [comment]
Use underlying mongodb driver is the only workaround right now unfortunately

**Comment by jtmarmon** [comment]
It would look like `Model.collection.initializeOrderedBulkOp();` right? Having some trouble getting it to cooperate...

**Comment by vkarpov15** [comment]
Yeah, there's a somewhat nasty corner case there - `initializeOrderedBulkOp()` is a sync operation, but mongoose queues operations while its connecting so you can do operations without waiting for it to connect. The queueing assumes async though, so you don't get the return value of `initializeOrderedBulkOp()`, hence why [this commit](https://github.com/LearnBoost/mongoose/commit/eba1ec39bc6f56b0b9950560f42abaddb97b61a1) has a `db.on('connected')` in the test. Other than that, I think it should work - what specific problems are you having?

**Comment by jtmarmon** [comment]
ahh I see, that should fix it, thanks :+1:

**Comment by noducks** [comment]
+1 for this feature

**Comment by efkan** [comment]
+1

**Comment by nottinhill** [comment]
+1 for this feature

**Comment by nottinhill** [comment]
Bulk insert on native mongo driver seems to be buggy, confirmed getting the `RangeError: Maximum Call Stack Size Exceeded`, see: http://stackoverflow.com/questions/24466366/mongoose-rangeerror-maximum-call-stack-size-exceeded

**Comment by sguillen** [comment]
+1 for this feature

**Comment by rfink** [comment]
+1

**Comment by webryan** [comment]
+1

**Comment by vkarpov15** [comment]
Since [`initializeUnorderedBulkOp` and its ilk (the fluent bulk API) are deprecated](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#id27), this isn't going to happen. More likely we're just going to implement the new CRUD API, which has more sane support for bulk inserts.

**Comment by joeytwiddle** [comment]
I am curious what is the status of this.

I was going to use `initializeUnorderedBulkOp` but if Mongo might remove it later, I would prefer to use a future-proof method.

**Comment by vkarpov15** [comment]
https://github.com/Automattic/mongoose/issues/3997 for updateOne and updateMany. We added `insertMany()` in 4.4.0. No real ETA yet for 4.6, right now focusing on 4.5. What's your use case for updateOne/updateMany?

**Comment by joeytwiddle** [comment]
Thanks. Our use case is that we are calculating regular statistics for a large number of users, so we are doing it in batches. Each user gets a slightly different result. So I was thinking of moving to:

    // Calculate statistics for 1000 users
    for (stat of stats) {
        bulk.findOne({_id: stat.userId}).upsert().updateOne(stat);
    }
    bulk.execute(...);

In theory the calculation should be the heavy bit, but in practice it seems the writes dominate!

If there is a danger that Mongo might remove `initializeUnorderedBulkOp` then I'll probably just stick with a slower method (1000 individual upserts) for now. But I could also pull this stuff into a reusable function, with a fallback if `initializeUnorderedBulkOp` is unavailable, and an upgrade to `upsertMany()` when it becomes available.

We could also consider keeping stats up-to-date in realtime, rather than performing scheduled calculations. Whether that is more or less efficient really depends on how many minor updates it would generate.

**Comment by vkarpov15** [comment]
Yeah that's a pretty reasonable use case. Will implement.

**Comment by ManeeshCh** [comment]
It worked when i did this

`Model.update({ query }, { update object }, { multi: true });`

**Comment by vkarpov15** [comment]
@ManeeshCh yeah multi update works well, the bulk API is more about sending multiple distinct query, update pairs in a single command to save network bandwidth.

**Comment by fyockm** [comment]
@vkarpov15 I have a use case that's very similar to the one described by @joeytwiddle. I am calculating stats on a large number of records and updating them in place one at a time (see code below). I've found that the network traffic between my server and the database is the biggest bottleneck in this operation, and therefore want to try running these updates in bulk with a single request.

slow code:
```js
// doc.stats object calculated elsewhere
async.each(docs, (doc, cb) => {
  const updateStats = { stats: doc.stats };
  Model.findByIdAndUpdate(doc._id, updateStats, cb);
}, done);
```

I see that `updateMany` was just added as part of #3997. But I don't understand how to perform a similar operation with it? It seems like it can apply the same update to multiple docs? Is there a way update different different documents with different values?

What am I missing?

**Comment by vkarpov15** [comment]
Yeah `updateMany` only applies the same update to multiple docs. Mongoose doesn't have a good approach to do what you're trying to do right now, but you can use the mongodb driver's `bulkWrite` function: http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#bulkWrite

```javascript
Model.collection.bulkWrite([{ updateOne: { filter: { _id: doc._id }, update: { $set: { stats: doc.stats } } }]);
```

**Comment by adamreisnz** [comment]
@vkarpov15 since last year, has there been any news on how the best perform bulk upserts?

My use case is that I need to processes potentially large numbers of logs at once, while checking if a similar log doesn't already exist according to certain criteria, and then update instead. I don't want to upsert them one by one, so I've been using bulk operations on the collection. 

The drawback of this however is that it bypasses Mongoose's schema validation/defaults, causing Date fields and ObjectID's for example to be stored as plain strings, so it'd require a lot of manual pre-processing and massaging of the data which Mongoose normally takes care of.

Second drawback is that the API doesn't return promises, so you have to wrap it in your own promises. And lastly, in this thread I am reading about the bulk API possibly being deprecated, so that does not bode well when you're trying to write future proof implementations.

So from what I understand, `insertMany` uses bulk operations for inserting many docs, yet judging by this discussion and the docs, `updateMany` does not, and merely sets the `{multi: true}` option for you.

Is there some kind of `upsertMany` implementation, or could it be developed in Mongoose, to support bulk upserts _with_ schema validation?

My current implementation looks as follows and could possible be used to create an `upsertMany` method:

```js
/**
 * Bulk upsert operation
 */
LogSchema.statics.upsertMany = async function(logs) {

  //Create bulk operation
  const bulk = this.collection.initializeUnorderedBulkOp();
  logs
    .forEach(log => {

      //Extract match criteria
      const {foo, bar} = log;

      //Create upsert
      bulk
        .find({foo, bar})
        .upsert()
        .replaceOne(log);
    });

  //Execute bulk operation
  await new Promise((resolve, reject) => {
    bulk.execute((error, result) => {
      if (error) {
        return reject(error);
      }
      resolve(result;
    });
  });
};
```

**Comment by adamreisnz** [comment]
I've poured this into a generic [plugin](https://github.com/meanie/mongoose-upsert-many) for now, but hope it can make it's way into an official Mongoose implementation.

**Comment by vkarpov15** [comment]
@adamreisnz this issue was specifically related to the `initializeUnorderedBulkOp()` and `initializeOrderedBulkOp()` API, which is "soft deprecated" by mongodb. It has been replaced by the [`bulkWrite()` API](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#bulk-write-models), which is part of MongoDB's core CRUD spec and thus is much more widely implemented.  In particular, [mongoose has a `Model.bulkWrite()` function](http://mongoosejs.com/docs/api.html#bulkwrite_bulkWrite) as of [4.9.0](https://github.com/Automattic/mongoose/blob/master/History.md#490--2017-03-13) that has validation, casting, promises, and ref depopulating. Let me know if that works for you.

**Comment by adamreisnz** [comment]
Thanks I will look into it. I must have missed it. Does it support upserts?

**Comment by vkarpov15** [comment]
@adamreisnz yes, see [mongodb driver docs](http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#bulkWrite) for an example

**Comment by adamreisnz** [comment]
Correct link to Mongoose docs has been changed to https://mongoosejs.com/docs/api.html#model_Model.bulkWrite
