### ISSUE TITLE
ObjectId Cast Error on New Ref

### ISSUE THREAD

**Issue by iq-dot** [Automattic/mongoose#2535]
Hi Guys,

I have an issue where if I try save a new ref property to an existing document I get an castId error, however this same update works fine IF I had originally created that document with that document property set.

Let me try to explain a bit more:

I have a schema like so:

```
name: String,
desc: String,
user: {
  type: ObjectId,
 ref: 'User'
}
```

Now if I create a new document with the 'user' value set, I can freely update that. However if I create the document without a 'user' value and then later try to update it with user value I get a 

'Cast to ObjectId failed for value "[object Object]"'

The data I send back to my function is same in both cases, which is a JSON object that has an '_id' field.
Doing a console.log I verified that the difference is when the value is set, the value is populated with the FULL document of the 'User'. Where as when I send it for update, I pass in user object with partially selected fields.

Is this why? When I first create it, all I do is set 'user' to a objectID value. I tried to the same for the update as well but still I get the complaint.

Is this a bug or am I doing something wrong? My update code is quite simple:

```
myModel = _.extend(myModel, req.body);
myModel.save()
```

My create code when I first make the document is also simple:

```
var model = new Model(req.body);
model.save()
```

**UPDATE:**

I managed to fix this by setting the req.body.user to an '_id' before running the _.extend operation only when it does not already exist. It is not ideal and feels a bit hacky but I guess it works.

**Comment by Phenome** [comment]
Trying to work around the same issue here.

Basically, if you have a schema like
```
Post = new Schema({
  body: String,
  comments: [{type:ObjectId, ref:'Comment'}]
})
```
You don't even have to use an array of actual Mongoose documents. It's enough for them to be regular JS objects, but with real ObjectId for `_id`. The `_id`s can't be strings.
`post.comments = [jsComment1, jsComment2, jsComment3]`
However, you can set it to an array of 'stringified' ObjectIds like
 `post.comments = [ '54ef1a709b88d1c48be1b13c', '54ef1a709b88d1c48be1b13c' ]` 

In both those cases, `post.comments` becomes an array of real ObjectIds.

Sadly, when you try to assign an array of JS Objects with ObjectIds as Strings, you get the aforementioned Cast Error.

Since Mongoose converts both an array of Strings, and an array of JS Objects (with real ObjectIds) to an array of ObjectIds (as per schema), I'd expect it to also convert an array os JS Objects with `_id` as Strings to be converted to an array of ObjectIds as well.

As of now, I'm parsing the JS Objects to convert the `_id`s to ObjectIds before trying to assign them.

**Comment by vkarpov15** [comment]
you can just convert `jsComment1`, etc. to mongoose documents:

```javascript
post.comments = [new Comment(jsComment1), new Comment(jsComment2), new Comment(jsComment3)]
```

Can always flatten using _.pluck too `post.comments = _.pluck([jsComment1, jsComment2, jsComment3], '_id');`

Should work. Plenty of ways to do what you're trying to do, I'm just hesitant about adding extra complexity to mongoose in order to make a one-liner slightly shorter.

**Comment by Phenome** [comment]
Both great ways to solve it, thanks. Very straightforward.

I'll try not to get too much into my particular problem:
It's just that I'm using Angoose (a framework between Angular and Mongoose) and it`s all very "hidden away". I basically have no access (or shouldn't need to) on the backend side. I just define the schemas and use them on the frontend. Upon trying to saving them, I got to this problem.

Since the frameworks automatically receives the JSON object and  'forward' it to Mongoose, I had to 'hack' into the framework to make it work. It does work now. It just got me thinking on where it should be implemented. On the framework or on Mongoose itself.

Just an open discussion. It is indeed a one-liner. It was just a matter of expectation.

**Comment by vkarpov15** [comment]
Angoose does look like a pretty cool framework, I look forward to playing around with it. However, I would imagine it would be easy to tell it to just insert `_id` fields into `post.comments`, no?

Also worth mentioning, if you're looking for the ability to reuse schemas on the client with AngularJS, [mongoose supports that as a core feature in 4.x](http://thecodebarbarian.com/2015/02/20/better-angularjs-form-validation-with-mongoose). There's no equivalent to angoose's remote invocation though, so you have direct control over your HTTP requests.
