### ISSUE TITLE
MongoError: Cannot update '__v' and '__v' at the same time 

### ISSUE THREAD

**Issue by jonathanong** [Automattic/mongoose#2593]
seeing this in my logs. has anyone else seen this?

**Comment by vkarpov15** [comment]
I've seen it in a few places, mostly #1933. What version of mongoose are you using? [This commit](https://github.com/LearnBoost/mongoose/commit/c2c4d98856763417d3096d4207997375ef8733ab) went into 3.8.15 and should fix the issue specified in #1933.

**Comment by jeremyml** [comment]
I am using 4.4.3 and I get `Cannot update '__v' and '__v' at the same time` when I run this code:

userModel.findOneAndUpdate({siteId: req.user.siteId, _id: req.body.user.userId}, req.body.user,
	{runValidators: true, upsert: true, setDefaultsOnInsert: true, new: true })

I find when I remove the `upsert:true` option, then the error message goes away.

userModel.findOneAndUpdate({siteId: req.user.siteId, _id: req.body.user.userId}, req.body.user,
	{runValidators: true, setDefaultsOnInsert: true, new: true })

I don't need the upsert: true, so I can live without it in this case.  But it seems that something may be wrong here.

**Comment by vkarpov15** [comment]
@jeremyml what does your schema and the `req.body.update` contents look like? I suspect this is because of `setDefaultsOnInsert`

**Comment by vkarpov15** [comment]
Issue's stale, closing

**Comment by alobaidizt** [comment]
@vkarpov15 I'm having the same issue. Like you've suspected the issue is probably due to `setDefaultOnInsert`. To reproduce it, you need to update a document that doesn't currently exist with these options `{upsert: true, setDefaultOnInsert: true}`. Example ``` xModel.update(query, {$inc: incrementField, $push: pushObj}, { upsert: true, setDefaultsOnInsert: true}, function(err)....
```

**Comment by vkarpov15** [comment]
@alobaidizt added a test case for what you suggested, works just fine. What else do I need to do to repro this?

**Comment by alobaidizt** [comment]
@vkarpov15 Thank you for adding the test! I still get the same error. Here's the error: ```{"name":"MongoError","message":"Cannot update 'field' and 'field.count' at the same time","driver":true,"index":0,"code":16836,"errmsg":"Cannot update 'steal' and 'steal.count' at the same time"}```

This issue is slightly better explained in the is [StackOverflow](http://stackoverflow.com/questions/23992723/findandmodify-fails-with-error-cannot-update-field1-and-field1-at-the-same)  thread. I was able to get my code working around it without using the `setDefaultsOnInsert` which is leading to this conflict with `upsert` flag.

**Comment by vkarpov15** [comment]
The SO thread doesn't look like it has anything to do with mongoose... Can you show your schema please?

**Comment by aryeharmon** [comment]
This is happening to me as well, any new info?

**Comment by vkarpov15** [comment]
@aryeharmon please provide code samples, there's a "can't reproduce" label for a reason.

**Comment by yoadsn** [comment]
Encountered the same error - although it seems clear to me what is the cause. Here is a simple repro:
```
 var EmbeddedSchema = mongoose.Schema({
      embeddedField: String
  }, { _id : true})

  var ParentSchema = mongoose.Schema({
      embedded: EmbeddedSchema
  })
  
  var Parent = mongoose.model('User', ParentSchema);

  var newDoc = {
      _id: new mongoose.Types.ObjectId(),
      embedded: null
  }

  Parent.findOneAndUpdate({ _id: newDoc._id }, newDoc, { upsert: true, setDefaultsOnInsert: true })
  .then(() => console.log('done'))
  .catch(err => console.error(err));
```

So the cause seems to be that mongoose puts in some cases the same fields (or derivatives therof) in both the `$setOnInsert` and the `$set` fields. In the case above, the _id of an null embedded document is generated.
Expected behavior in this case would be to ignore the embedded field for the `$setOnInsert` due to the fact it would be inserted as null.

I have not found a workaround for this yet.

**Comment by vkarpov15** [comment]
@yoadsn this is a different issue so I opened up #4911 to track
