### ISSUE TITLE
.explain() helper for aggregate

### ISSUE THREAD

**Issue by unusualbob** [Automattic/mongoose#2714]
The current aggregate method exposed by Mongoose does not support passing an options object such as `{explain: true}` to mongodb as the second parameter.

See: http://docs.mongodb.org/manual/reference/method/db.collection.aggregate/

**Comment by vkarpov15** [comment]
That's by design - `MyModel.aggregate()` is currently designed to take a spread of pipeline stages. `aggregate()` returns an Aggregate object that you can manipulate options on, but currently there's no particularly elegant way to set `explain: true` on that object. That's something I should add. As a workaround:

```javascript
var aggregate = MyModel.aggregate();
aggregate.options.explain = true;
aggregate.append(stage1, stage2 /* ... */).exec(callback);
```

**Comment by unusualbob** [comment]
If you're looking for suggestions, it should probably behave like the other mongoose functions, where options is passed as an additional parameter. ie:
```
MyModel.aggregate([stage1, stage2], options).exec(callback);
```
It would be icing on the cake if it supported `.explain()` like the others as well.

Thanks for the workaround.

**Comment by vkarpov15** [comment]
Yeah I would think that would be the more ideal solution going forward, see #2716. For now we'll have to add an `explain()` helper to the Aggregate object in 4.1.
