### ISSUE TITLE
Mongoose doesn't always update version

### ISSUE THREAD

**Issue by jamespharaoh** [Automattic/mongoose#2762]
I'm having a problem with mongoose not always updating the version number. This is causing conflicts in my data. Specifically, I am checking if a subdocument with a specific id exists and creating it if it does not, but I often end up with two subdocuments with the same id.

Examining the code, it looks like mongoose does not always update the version number, depending on the type of update. I don't understand how this can possibly be correct, since it essentially means that the protection offered by the version numbering doesn't always apply, making it very diffcult to reason about the code.

Without this version check, any conditional logic which looks at other parts of the document may not apply once the update takes place, due to changes. Can someone please confirm if this is considered correct behaviour, and why?

I am working on a pull request which will make the version number always be checked and updated, if there are any changes to the document, which as far as I can see is the only behaviour which can be correct-by-default if versioning is enabled.

If there is a valid use case for this, then I would suggest it should be an option which can be enabled if needed, so that the default behaviour provides the more conservative guarantees which I imagine most people would expect.

**Comment by vkarpov15** [comment]
Mongoose only updates version number for certain array operations that may cause inconsistent state - for instance, updating an array element when the array has been overwritten on the backend. See [Aaron's overview on the subject](http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html). Things like "append to an array" don't cause version increment by design. If you're trying to add a subdocument to an array and ensure it has a unique id, you would probably want to use `findOneAndUpdate()` and/or `$addToset` instead of the "load then save" design pattern, its cleaner.

**Comment by jamespharaoh** [comment]
Yeah, I can understand that point, but in our case we have big complex documents and lots of logic. It would be extremely difficult to create an optimized atomic update to represent every possible transaction which can take place. That's why we rely on the database to perform serialization, and the version numbers are what is supposed to provide that.

Now, I realize that not everyone's use case is the same, but I am pretty sure that there are plenty of other people out there who have similar requirements to us, and that it would be useful to have the option to support that behaviour.

I'd go further than that, and say that I was extremely surprised by this behaviour, and I exepect that a lot of other people would be as well, which is why I think the default should be to always update the version number, which is the only way to provide any kind of "serialization" of transactions in a way that is easy to understand.

Obviously this is my opinion, and I'm interested to hear what other people think. I still propose to create a pull request for this, one that would set this behaviour by default, and provide an option for the current behaviour. Obviously the other option would be a similar option, but with the default as it is now, and this might be preferred for legacy compatibility.

**Comment by vkarpov15** [comment]
The concern is that this option is overly aggressive for most use cases. Updating "title: String" shouldn't fail because somebody else updated "author: String", at least in just about every use case I've seen. Frankly, I don't really find versioning that useful in any application that I've built. It's a nice feature to prevent me from shooting myself in the foot, but it's not a core consideration when I'm designing schemas.

You should hold off on that pull request, I will not accept it because it's a major backwards breaking change and one that I'm not entirely willing to support at this time. However, "increment version number on each and every save, and make sure you query on it" is something that could in theory be implemented with a plugin. There may be one limitation that may prevent making that a reality, but it's a limitation I could remove in a future version. Perhaps that could be a good solution?
