### ISSUE TITLE
Mongoose fails on undefined callback when trying to call it with cast error

### ISSUE THREAD

**Issue by apierzch** [Automattic/mongoose#2786]
Hi, I was trying to execute: `Model.distinct('field', query)` but got error:
`TypeError: undefined is not a function` from:
`Query.distinct ()` at `node_modules/mongoose/lib/query.js:1275:5`

After some debugging I found out that callback at line 1275 was not defined (because I wanted to use `.exec(callback)` version).

The real error was `CastError: Cast to ObjectId failed for value "" at path "_id"` which was perfectly correct, but all I could see was `TypeError: undefined is not a function`.

Missing callback should be somehow handled in such situation. Maybe rethrow instead of calling callback? I'm not sure.

mongoose version : `3.8.25`

**Comment by demetriusnunes** [comment]
Same thing happening for Query#count

**Comment by MorrisDa** [comment]
I had the issue described above with version 3.8.25. 
I have downloaded version 3.8.26 but it just partially solved the problem.

in version 3.8.26 (differentely from 3.8.25) the error that is thrown is right about what originated the problem, so 'CastError: Cast to ObjectId failed for value..', but i think the fact it is thrown is not consistent with mongoose api.
Errors are usually handled internally by mongoose and passed in the error object, so that developers can properly handle the problems and behave consequently. 
This error is not handled by mongoose and wrapped as data in the error object, it's simply thrown and it makes my application crashing. 
I don't want to catch this error manually (using try/catch), because it's not compliant to my application structure, which usually handle the mongoose error object passed in callbacks and perform logic. 

A workaround i've used is to previously check if the object id is valide, but i would like to delete this and make consistent my interface with mongoose. 

Thank you for any help.

**Comment by vkarpov15** [comment]
The "throw if no callback" behavior is consistent with how things like `update()` work, that's how mongoose 3.8 does things. I think we could improve this in the future though, but discuss this in #2935 going forward.
