### ISSUE TITLE
Model.findByIdAndUpdate() default option new false?

### ISSUE THREAD

**Issue by topaxi** [Automattic/mongoose#2793]
It seems that the Model.findByIdAndUpdate() options "new" defaults to false in mongoose 4.0.0.
According to the documentation, it should be true.

Did the default value change or is this a bug?

http://mongoosejs.com/docs/api.html#model_Model.findByIdAndUpdate

**Comment by vkarpov15** [comment]
Intentional change, see the [4.0 release notes' Backwards Breaking Changes section](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes) and discussion in #2756, #2262, etc. The reason for this change was that the mongodb server and node mongodb driver use false by default, so this would be an extra point of friction for someone trying to convert mongodb server docs examples into mongoose code. You can specify the `new: true` option to findOneAndUpdate() to get the old behavior, or just write a plugin to make that the default for your application.

**Comment by vkarpov15** [comment]
The fact that the docs are wrong, though, is unfortunate. I will fix that.

**Comment by topaxi** [comment]
Thanks for clarifying and fast answer :)

**Comment by morkai** [comment]
Shouldn't it say:

> `new`: bool - **true** to return the modified document rather than the original. defaults to false (changed in 4.0)

instead of

> `new`: bool - **false** to return the modified document rather than the original. defaults to false (changed in 4.0)

?

**Comment by vkarpov15** [comment]
Good catch, I didn't read carefully and assumed that the first "false" meant the default

**Comment by cachrisman** [comment]
does anyone know why mongodb defaults to returning the unmodified document?  just curious about the logic/reasoning behind this.

**Comment by vkarpov15** [comment]
Not entirely sure, but it's been this way as long as I've been using MongoDB. Plenty of valid use cases for both scenarios, so I guess somebody at some point decided that false was a better better default.
