### ISSUE TITLE
mongoose 4.0.1: pre "update" middleware this object does not return model object

### ISSUE THREAD

**Issue by ruverav** [Automattic/mongoose#2812]
Hi, I've a problem with the newest version of Mongoose. I'm creating an API with Express and Mongoose 4.0.1, and I'm not sure if I'm doing anything wrong, but the fact is whenever I try to use the new `pre` update middleware the same way I use `pre` save middleware, `this` object does not return the object being updated, instead it returns the `Query` object.

Example of what I'm trying to explain:
```javascript
ExerciseSchema.pre('save', function (next, done) {
        var self = this;
        console.log('exercise:', self); // returns exercise object
        // some validations here
       next();
});
```
```javascript
ExerciseSchema.pre('update', function (next, done) {
        var self = this;
        console.log('exercise:', self); // returns Query object instead of exercise object
        // some validations here
       next();
});
```
This is what I get in `this` reference object within the middleware, and I don't know how it's useful to me. 
``` javascript
{ _mongooseOptions: {},
  mongooseCollection: 
   { collection: { s: [Object] },
     opts: { bufferCommands: true, capped: false },
     name: 'exercises',
     conn: 
     ... },
   ...
}
```
Looking at the source code, some of its properties are defined inside `Query` function defined in `./node_modules/mongoose/lib/query.js`:

Is this something unexpected or I am doing anything wrong? It would be interesting to have a solution because I don't like the idea of validating within a middleware on object saving and being forced to run validations directly on controller when updating.

The same thing happens with findOneAndUpdate `pre` middleware, but I don't expect it to return the exercise before finding it.  In fact and in my honest opinion, I think it would be interesting that findAndUpdate and findOneAndUpdate pre middlewares triggered find(One) and update middlewares, in this order, instead of having its own middleware.

Thanks in advance for your help.

**Comment by vkarpov15** [comment]
By design - the document being updated might not even be in the server's memory. In order to do that, mongoose would have to do a findOne() to load the document before doing the update(), which is not acceptable.

The design is to enable you to manipulate the query object by adding or removing filters, update params, options, etc. For instance, [automatically calling .populate() with find() and findOne()](https://github.com/vkarpov15/mongoose-autopopulate), setting the `multi: true` option by default on certain models, access control, [and other possibilities](https://github.com/Automattic/mongoose/labels/plugin).

`findOneAndUpdate()` is a bit of a misnomer, it uses the underlying mongodb `findAndModify` command, it's not the same as `findOne()` + `update()`. As a separate operation, it should have its own middleware.

**Comment by ryudice** [comment]
How would you suggest updating a document field during 'pre' update middleware then?

**Comment by vkarpov15** [comment]
`this.update({ field: val });` will add `{ $set: { field: val } }` to the update operation before it happens.

**Comment by ryudice** [comment]
Thanks for replying, on which version is that supposed to work? because I'm using 4.0.2 and it doesn't. Do I have to call "exec" on the query?

**Comment by ryudice** [comment]
if I run this.update wouldn't I be calling this method http://mongoosejs.com/docs/api.html#query_Query-update?

**Comment by ryudice** [comment]
I ended up doing  this.findOneAndUpdate({matcher: "myvalye"}); hope that's the right approach.

**Comment by vkarpov15** [comment]
Hmm 4.0.2 should work. What does your code look like?

**Comment by ryudice** [comment]
I just did something like this:

```javascript
var schema = mongoose.Schema({
    name: String,
    description: String,
    matcher: String,

});

var generateMatcherUpdate= function(next) {
	 var matcher = "generate matcher function"
        this.update({matcher: matcher});

    next();
};

 schema.pre('update', generateMatcherUpdate);

```

**Comment by vkarpov15** [comment]
Ah ok I see you're using `findOneAndUpdate()` rather than `update()`. These are two distinct functions with distinct hooks, so if you want to add update ops to `findOneAndUpdate` in a pre hook, you should do

```javascript
schema.pre('findOneAndUpdate', function() {
  this.findOneAndUpdate({}, { $set: { key: 'value' } });
});
```

**Comment by askdesigners** [comment]
man mongoose documentation is hatefully bad.

**Comment by vkarpov15** [comment]
@askdesigners put what exactly in there?

**Comment by askdesigners** [comment]
Sorry I wrote that in a moment of stress :) 

Just the brittleness of version compatibility really. It's not an obvious issue, and leaves a lot of people scratching their heads.

**Comment by vkarpov15** [comment]
No worries. What sort of version compatibility issues are you having?

**Comment by chewax** [comment]
And what if i want to sanitize a value on pre.update...I cant seem to find a way to do it.
Thanks!

**Comment by vkarpov15** [comment]
```javascript
schema.pre('update', function() {
  var v = this.getUpdate().valueToSanitize;
  this.update({}, { $set: { valueToSanitize: sanitize(v) } });
});
```

**Comment by chewax** [comment]
Nice, I will try that out! 
Thanks!!

**Comment by CMatias** [comment]
Hey @vkarpov15, I've come across something I would say is kind of unexpected behaviour, or at least it should be documented.

If I do something like 

```
MyModel.findOneAndUpdate({a: 1}, {v: '__3'}, function (err, model) {
    console.log(model);
});
```

And on my model I implement your suggestion

```
mySchema.pre('findOneAndUpdate', function() {
  var v = this.getUpdate().v;
  this.findOneAndUpdate({}, { $set: { v: sanitize(v) } });
});
```

The log will output '__3' since the original update query will be executed after the hook. I'm able to change other schema properties but all the fields which are updated on the original query will remain the same even if they're changed in the pre hook.

**Comment by vkarpov15** [comment]
@CMatias this is a case where you need to be careful about using `$set` or not consistently. Mongoose doesn't necessarily know whether or not to wrap in `$set`, so in your case you should do `this.findOneAndUpdate({}, { v: sanitize(v) });`

**Comment by CMatias** [comment]
@vkarpov15 thanks, that worked. Could you briefly explain what's the difference between using `$set` and not using it? Can't find much information about it.

**Comment by vkarpov15** [comment]
So if you use the native mongodb driver directly and do `coll.findOneAndUpdate({ a: 1 }, { __v: 3 })`, mongodb will take the first document with a = 1 and replace it with the document `{ __v: 3 }` modulo `_id`. In other words, it will overwrite the existing document. In order to just set the key '__v', you need to do `coll.findOneAndUpdate({ a: 1 }, { $set: { __v: 3 } })`.

This behavior has always been controversial and error-prone, so by default mongoose prevents you from overwriting the document. In other words, `MyModel.findOneAndUpdate({ a: 1 }, { __v: 3 })` becomes `MyModel.collection.findOneAndUpdate({ a: 1 }, { $set: { __v: 3 } })` _unless_ you set the `overwrite: true` option. However, you can do strange things like `MyModel.update({}, { $set: { b: 2 } }).findOneAndUpdate({ a: 1 }, { __v: 3 }, { overwrite: true })` that make it quite confusing as to what the current state of `getUpdate()` is, so we just leave the status of `update` as-is for middleware.

**Comment by namlet** [comment]
I'm trying to grok all of this but am having a hard time determining if I can modify the doc that will be returned from a find using these middleware methods. Specifically, I'd like to "decorate" the response by adding additional fields.

For instance, if I have a Schema:
```
const Thing = new mongoose.Schema({
  name: {type: String}
});

Thing.post('find', function(doc, next){
  doc.newfield = "example text";
  next();
}
```

Is this possible? 

The reason `newfield` isn't defined in the schema is that depending on the values of `Thing`, different field names are needed.

Thanks!

**Comment by jrogatis** [comment]
i need any specific plugin to use schema.pre('update') ?

**Comment by vkarpov15** [comment]
Nope @jrogatis

**Comment by qqilihq** [comment]
@vkarpov15 

Looking at the example you gave above ...:

```
schema.pre('update', function() {
  var v = this.getUpdate().valueToSanitize;
  this.update({}, { $set: { valueToSanitize: sanitize(v) } });
});
```

This does **not** work for me. The `this.getUpdate().value` does not contain my property `value` as the example suggests. Instead it's available under `this.getUpdate().$set.property`.

Is it supposed to be like that? Am I understanding something wrong? Did the API change?

**Comment by varunjayaraman** [comment]
@qqilihq can you open a separate issue with a repro script?

**Comment by varunjayaraman** [comment]
@qqilihq nvm, just saw that you did :P

**Comment by qqilihq** [comment]
@varunjayaraman Actually the separate issue is a different one :) But I'll gladly open a new one for the comment above, once I have some spare minutes to compile an example.

**Comment by varunjayaraman** [comment]
@qqilihq ah ok, thanks !

**Comment by Alendorff** [comment]
Exactly the same for me as mentioned by @qqilihq 

![image](https://user-images.githubusercontent.com/4989157/29567202-b9d1e5a4-874c-11e7-88a6-895640ad49d2.png)

**Comment by ababba15** [comment]
`pre` method should not work with `this.update`, because it is "pre"-save and there is nothing to update. While `this.newProp = "value"` works perfectly, thanks guys.

**Comment by rluncasu** [comment]
I understand the reasoning behind having the query as "this" on the "pre" update hook but why is the "post" update hook behaving in a similar manner ? Shouldn't post update have the actual model as "this" ?

**Comment by vkarpov15** [comment]
So then post find would execute multiple times or have `this` as an array of there are multiple results? And what if there are no results, should post find not run?

**Comment by munroe7** [comment]
I see that this issue is pretty old now and was wondering if there was any way to achieve this now? When data is updated, I want to be able to manipulate other fields based on the new data. I am inputting DNA into a database so if someone makes a change to their DNA value, it should re calculate some schema values based on this new input. 

```
DnaSchema.pre('update', function(next) {
    dna = this;
    calculateMass(dna){
          //math is done here
          dna.mass = newCalculationFromNewDNAInput;
   }

})
```

**Comment by ajbraus** [comment]
This is all very strange. IMHO The pre hooks should all just behave the same, with a `this` that is the object being modified and nice methods like isModified to check things.

**Comment by ajbraus** [comment]
Actually I think I understand now. I should just be using the pre 'save' method and then the this.isNew method. Thanks!

**Comment by vkarpov15** [comment]
@ajbraus it is a little strange, but the alternative is massive performance overhead. Suppose you have an updateMany that updates millions of docs - mongoose would have to load those all into memory.

**Comment by PDS42** [comment]
How is one supposed to check for document fields before updates ? Say I need to check whether certain fields are filled to set document as "valid", how can I access the whole document, and not just fields being updated ? `this` is referring to the query here

**Comment by vkarpov15** [comment]
@PDS42 you'll have to run a separate query to load the document from mongodb

**Comment by ronakvora** [comment]
Is there a particular link in the mongoose documentation where all of this is explained in more depth? I'd love to read up on it and understand this more fully :).

**Comment by vkarpov15** [comment]
@ronakvora there's a [`Query#getConditions()` function](https://mongoosejs.com/docs/api.html#query_Query-getQuery). 

```javascript
schema.pre('update', function() {
  console.log(this.getConditions()); // Will include `{ field: 'value' }`
});
```

**Comment by whoisronak** [comment]
Gotcha, that will help me play with things :). Thanks!
