### ISSUE TITLE
Mongoose 4.0.1 - dropDatabase callback not executed

### ISSUE THREAD

**Issue by SamVerschueren** [Automattic/mongoose#2831]
When I use Mongoose 3.8.25, the ```mongoose.connection.db.dropDatabase()``` method works fine. When I update to the latest (4.0.1), the callback is not executed.

**Comment by vkarpov15** [comment]
Hmm I think this might be a more subtle issue. The following code works in both 3.8.25 and 4.0.1:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/gh2831');

var schema = new mongoose.Schema({ test: String });
var m = mongoose.model('gh2831', schema);

mongoose.connection.on('connected', function() {
  mongoose.connection.db.dropDatabase(function(err) {
    console.log('Err: ' + err);
    process.exit(0);
  });
});
```

But if you remove the `.on('connected')`, that is, don't wait for connection to succeed, then the above code will fail with both 3.8.25 and 4.0.1 - callback will never get called because mongoose doesn't buffer `dropDatabase()` calls. Can you confirm that this is consistent with what you're seeing?

**Comment by vkarpov15** [comment]
Can't repro, re-open if this is still an issue.
