### ISSUE TITLE
Mongoose 4.0.1 - Exception inside of a setter function causes ValidationError with undefined path

### ISSUE THREAD

**Issue by lbeschastny** [Automattic/mongoose#2832]
Hi.

Consider the following code sample:

```js
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/test');

var FooSchema = new mongoose.Schema({
  data: {
    type: String,
    set: function (arr) {
      throw new Error('Ooops!');
    }
  }
});

var Foo = mongoose.model('Foo', FooSchema);

Foo.create({
  data: undefined
}, function (err, doc) {
  console.error(err);
})
```

This code throws the following `ValidationError` exception:

```
{ [ValidationError: Foo validation failed]
  message: 'Foo validation failed',
  name: 'ValidationError',
  errors: 
   { undefined: 
      { [CastError: Cast to String failed for value "undefined" at path "undefined"]
        message: 'Cast to String failed for value "undefined" at path "undefined"',
        name: 'CastError',
        kind: 'String',
        value: undefined,
        path: undefined } } }
```

As you can see, it indicates `CastError` at `undefined` patch, instead of pointing me to the troublesome `data` path.

This thing made it really hard to find out that my code broke because of #1892 breaking change.

**Comment by vkarpov15** [comment]
PR #2862 should fix this as far as I can tell. FWIW I wouldn't blame this on #1892, the issue is more closely related to 4.x's new way of handling CastErrors - mongoose 3.x has a significant limitation where there's only one CastError per document that never goes away, so if you get one cast error that document can never be saved without tweaking with internal state. Related work was in #2766, #2775, and a couple other issues that I forget. As always, when there's a complete overhaul of a large piece of the software, there's gonna be some bugs that slip through the cracks :)

**Comment by vkarpov15** [comment]
I'm gonna review #2862 again tomorrow - if you can double check that branch and see if it works for your use case that would be very helpful :)

**Comment by lbeschastny** [comment]
@vkarpov15 tested #2862 with my minimal code example and it worked fine:

```
{ [ValidationError: Foo validation failed]
  message: 'Foo validation failed',
  name: 'ValidationError',
  errors: 
   { data: 
      { [CastError: Cast to String failed for value "undefined" at path "data"]
        message: 'Cast to String failed for value "undefined" at path "data"',
        name: 'CastError',
        kind: 'String',
        value: undefined,
        path: 'data' } } }
```
