### ISSUE TITLE
Incorrect semantic versioning for unstable packages

### ISSUE THREAD

**Issue by LegitTalon** [Automattic/mongoose#2852]
Mongoose isn't properly using semver and I think it's an accident but the current recommended stable version is 3.8.23 which if you have in your `package.json` as `"mongoose": "^3.8.23"` it will download 3.8.26 which is an unstable release as indicated by the console warning when executed.

Even using `"mongoose": "~3.8.23"` which would lock updates to just patches will download the unstable 3.8.26 version. The only way to ensure a download of a stable mongoose version right now is to explicitly lock down your package.json version to `"mongoose": "3.8.23"` which is undesirable as it will not download future stable releases with potentially important updates.

The solution is to release unstable versions with a suffix of `-rc.x`, `-alpha`or `-beta`.

**Comment by vkarpov15** [comment]
Mongoose 3 didn't [properly use semver by design](https://github.com/Automattic/mongoose/wiki/Development-%28unstable%29-branch-details). Mongoose 4 [uses proper semver](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) because we decided that the stable/unstable branch approach was a poor fit for node and not the right way to get the stability we wanted.

Also, where are you getting an unstable warning from 3.8.26? Are you sure you're not just downloading 3.9.7 (last unstable development release in the 3.9.x series) because you're using "^3.8.23", which will pull down 3.9.7 unless I unpublish it?

**Comment by LegitTalon** [comment]
I didn't know the 3.9 series existed as I was looking in the tagged releases in this repo. I will update my package.json to use a tilda. Thank you for your assistance! Also glad to here 4.x is switching to semver :wink:

**Comment by vkarpov15** [comment]
Glad it worked out for you. Please use the ~ until you're ready to upgrade to 4.0 :)
