### ISSUE TITLE
Potentially bug in mongoose.Types.ObjectId.isValid

### ISSUE THREAD

**Issue by sielay** [Automattic/mongoose#2853]
Following IMHO should both be false, but:
```
mongoose.Types.ObjectId.isValid('wok express') 
false
mongoose.Types.ObjectId.isValid('#wok express') 
true
```

**Comment by vkarpov15** [comment]
This is by design - any string of length 12 is a valid ObjectId because an ObjectId can be anything with 12 bytes. See mongodb/js-bson#112. If you need to check if something is 24 hex characters (the common string representation of an objectid) you can just use the `/^[0-9a-fA-F]{24}$/` regexp. We may export that regexp in a future version of js-bson but it's not a very complex regexp :)
