### ISSUE TITLE
Post Hooks Called *BEFORE* Their Function

### ISSUE THREAD

**Issue by jthomerson** [Automattic/mongoose#2949]
This has been happening in post-***save*** hooks for a while, but I have not had the time to track down enough details to report it or submit a pull request. However, between 4.0.1 and 4.0.2 the post hooks for post-***init*** have broken. This is easy to track down. It broke in commit 6e276a8b.

By using 'post' instead of 'on', your hook actually gets called **before** the init happens. This totally broke both the `this` context *and* `doc` object that are passed into post-init. The `doc` object worked properly in 4.0.1. In 4.0.2 if you `console.log(this.toObject())` or `console.log(doc.toObject())` in a post-init hook, you will see that the values are in fact *not* initialized. The object simply has the defaults from the schema. In 4.0.1 you could log `doc.toObject()` and get the initialized values from the DB. Obviously you could not use `this` in 4.0.1 as discussed in #2816 - which is the cause of the regression in post-init.

My understanding was that those who upgraded to 4.0.x were supposed to change from using `this` to `doc`. If that's correct, the fix for the post-init hook is to revert 6e276a8b. Does Mongoose really need to continue supporting `this` in a post-init hook if the doc is passed in?

***However, the larger problem is that all post hooks that use `queue('post'` are broken.*** That is what breaks post-***save*** hooks. To replicate that problem you can add a post save hook and enable Mongoose logging. In your post-save hook, output something to the console. Then watch and see that the `update` query actually runs *after* your post save hook. It's important to note that this happens only with asynchronous hooks.

This happens for the same reason as the post-init problem discussed above. In [lib/schema.js#L671-L683](https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L671-L683) it is using `queue('post'` instead of `queue('on'`. If you step through [this code in Document.$__registerHooksFromSchema](https://github.com/Automattic/mongoose/blob/master/lib/document.js#L1500) the root of the problem appears to be in this function. When we debugged this last time it appeared that `pre` and `post` hooks were getting lumped together and pointcuts were created for them.

**Comment by lbeschastny** [comment]
I'm experiencing the same issue.

All my `post('save', ...)` hooks are being called before an actual save. It totally broke all post-save logic in our project.

**Comment by vkarpov15** [comment]
Re: the discussion from #2816, we decided to make the context of post hooks supported behavior. It was unsupported and undocumented behavior that worked by accident before, but people started using it and we'd rather avoid breaking people's code unless there's a good reason to. Regardless, I think I successfully put a band-aid on this issue in 2d2c43f and now there's test coverage so it won't break again.

Re: $__registerHooksFromSchema, that's going to go in #2754. Hooks and that function are both a mess. The whole "point cut" notion was introduced as a way to make promises and hooks play nice, but caused a whole lot of other problems.

Also, @jthomerson, in the future, could you provide code samples? Typically providing code that reproduces the issue is more concise than using prose to describe code that reproduces the issue. :palm_tree: :beers:
