### ISSUE TITLE
How to efficiently convert nested JSON to separate schemas

### ISSUE THREAD

**Issue by mcky** [Automattic/mongoose#2972]
I've got nested object where a project has many stakeholders, who each have many outcomes, which have many indicators but the back end is like
```
  , indicators : [{
    type: Schema.ObjectId
    , ref: 'Indicator'
  }]
  , parent: {
    type: mongoose.Schema.Types.ObjectId
    , ref: 'Stakeholder'
  }
```

At the moment I'm having to loop through each array saving them and then updating the parents, but it's a lot of code and not very dry and I know there's probably a much better way to handle it.

Gist with some sloppy sample code below:
https://gist.github.com/mcky/c7ecf71f86210d3bf0f2

**Comment by vkarpov15** [comment]
You might want to try the `Model.create()` function (see [docs](http://mongoosejs.com/docs/api.html#model_Model.create) ) - that provides a nice wrapper around using async.parallel() for creating multiple docs. Beyond that, there's no really good way because by design .save() in mongoose only saves one document

**Comment by vkarpov15** [comment]
You can also take a look at [insertMany in 4.4.x](http://mongoosejs.com/docs/api.html#model_Model.insertMany)
