### ISSUE TITLE
custom validation middleware and error messages

### ISSUE THREAD

**Issue by mrphelz** [Automattic/mongoose#3004]
I have some schema where i mix direct type validation (like required) and custom middleware (pre validate).

In my custom middleware i'm acqually managing errors this way:
```
schema.pre('validate', function (next) {
  var err = new Error('value x in field y is wrong for this reason');
  next(err);
});
```
which works, but this way i end up with a single error (i.e. when using document.save in my node route accessing the model).
```
{ error: value x in field y is wrong for this reason }
```
For what i can understand custom validation in some way block entire model validation when it gets an error, whereas other validation method are executed altogether resulting in an error object contaning all fields with problems.

Is there some way to add custom errors to the "standard" error object?

**Comment by vkarpov15** [comment]
See "Validation errors" section in the [validation docs](http://mongoosejs.com/docs/validation.html) for an example. Pre validate hooks are executed in order **before** validation happens, which is why you're only getting a single error. You can tie in to the actual validation function with custom error messages though like shown in the above link.

**Comment by mrphelz** [comment]
So, if i understand correctly, i can replicate the structure of the error object within my custom validation middleware function, but i cannot have a single cumulative validation object with all errors (both schema validation, like required or unique, and my custom validation) (unless i include all validation inside my custom function), am i right?

**Comment by JohnnyEstilles** [comment]
@mrphelz, what I believe @vkarpov15 is  trying to explain is that instead of using a `.pre('validate', ...)` hook (which executes before ANY other validation, whether built-in or custom, you should use Mongoose' custom validation feature. Pre validate hooks and custom validation are two different concepts. If an error is returned (i.e. passed using `next()`) on a pre validation hook the entire validate process is short circuited and only that error is shown as a validation error. Custom validation, on the other hand, are executed as part of the schema validation workflow.  Errors from any failed custom validation will be returned cumulatively, along with with any other validation errors (for both built-in and custom validation), just as you would expect. 

Let's say you have an `xyz` path to which you want to add custom validation. You can do the following:

```js
YourModel.schema.path('xyz').validate(function (value) {
  return value === 'OK'; // <-- return true if validation is successful
}, 'Invalid xyz value'); // <--- specify your custom validation failure message
```

I think the above code is pretty self explanatory, but if you have any other questions don't hessitate to ask.

**Comment by mrphelz** [comment]
@JohnnyEstilles thank you for your explanation; i think i understood the fact that custom validation and validation hooks are different concepts and that validation hooks "blocks" normal validation process; i also understand i should use custom validation, but there are validations i need to perform that are unsupported by custom validation.

Something like
* check if an array field has at least one element
* check if at least one of n fields has a specific value
* check if field A is greater than field B
* and other more or less complex validations which require checking more than one field

All of this i can do (i'm currently already doing) with validation hooks, but i cannot return an error object with all validations errors: if a document is submitted, the flow is currently something like
* user submit document
* nope, field A is not valid for this and that reason
* user modifiy field A, submit again
* nope, field A is now ok but field C is not valid
* user modify field C, submit again
* and so on

whether an optimal workflow should be
* user submit document
* nope: field A is not valid for this and that reason, field C is not valid for some other reason, field E must be greater than field F (etc.)
* user modifiy all invalid fields, submit again
* ok, everything is fine

**Comment by mrphelz** [comment]
as an answer to myself, i'm testing what i can actually validate with custom validation; it appears i can check if an array field has at least one item

```
someSchema.path('somePath').validate(function (value) {
  return value.length > 0;
}, 'somePath must contain at least one item');
```

**Comment by vkarpov15** [comment]
Also, with document validation, `this` refers to the document in the validation function. So you can do stuff like:

```javascript
someSchema.path('somePath').validate(function (value) {
  // `this` is the document
  return value.length > 0 && this.someOtherField.length > 0;
}, 'somePath must contain at least one item');
```

Just be careful - you can't use `this` if you're using update validators: http://mongoosejs.com/docs/validation.html

**Comment by mrphelz** [comment]
yep, i'm currently testing a similar approach and found you can use `this` to access other document fields; i'm now going to rewrite my validation hooks into custom validation.

Thanky you for the assistance
