### ISSUE TITLE
Ability to get current conditions and update params from query

### ISSUE THREAD

**Issue by andrenarchy** [Automattic/mongoose#3013]
I'm trying to increase a version number every time a document is updated with `findOneAndUpdate`. Analogous to [the docs](http://mongoosejs.com/docs/middleware.html), I tried:
```
schema.pre('findOneAndUpdate', function() {
  this.findOneAndUpdate({$inc: {revision: 1}});
});
```
However, when I use `findOneAndUpdate` with `overwrite: true` like
```
mongoose.model('User').findOneAndUpdate(
  {_id: id, revision: revision},
  {name: 'Darth'},
  {overwrite: true},
  function(err, darth) {
    console.log(err);
  }
);
```
I end up with the following error:
```
MongoError: exception: The dollar ($) prefixed field '$inc' in '$inc' is not valid for storage.
```

It seems to mix the `$inc` operator into the new document. Is there a way to detect in a middleware if the `overwrite` option is set to `true`? Furthermore, I'd need access to the document that should replace the stored one... Any ieas?

**Comment by vkarpov15** [comment]
If you're using overwrite, it doesn't really make sense to use `$inc`, because the existing document will be overwritten entirely.

```javascript
schema.pre('findOneAndUpdate', function() {
  if (!this.options.overwrite) {
    this.findOneAndUpdate({$inc: {revision: 1}});
  }
});
```

Should let you bypass running the middleware if overwrite is specified.

Accessing the document that will be stored, `{ name: 'Darth' }`, is actually pretty difficult right now, I don't really think we have a good way to do that. The dirty way would be something like:

```javascript
mongoose.model('User').findOneAndUpdate(
  {_id: id, revision: revision},
  {name: 'Darth'},
  {overwrite: true})
  .exec(function(err, darth) {
    console.log(err);
  }); // important to use .exec()

// ...

schema.pre('findOneAndUpdate', function() {
  // `this._update is the update operation that will be sent, in this case `{ name: 'Darth' }`
});
```

This is currently unsupported though.
