### ISSUE TITLE
mongoError: getaddrinfo ENOENT

### ISSUE THREAD

**Issue by Kaminto** [Automattic/mongoose#3049]
Just got started with mongoose and am using the latest mongoose 4.0
3 but when i try running my code as well as the example code provided I get this error, MongoError getaddrinfo ENOENT"

**Comment by vkarpov15** [comment]
Which example code?

**Comment by Kaminto** [comment]
meant the example code given about connecting to mongodb with mongoose. gotten from internet resources like here on github.

**Comment by Kaminto** [comment]
I have actually figured it out, i had to change the connection url from "localhost to 127.0.0.1"  forexample..
var mongodbUri = 'mongodb://localhost/bg';  to var mongodbUri = 'mongodb://127.0.0.1/bg';

**Comment by vkarpov15** [comment]
Yeah it really depends on your networking configuration whether localhost works. #2999 mentioned this too.

Just out of curiosity, what OS are you using such that 'localhost' isn't mapped to the loopback address?

**Comment by Kaminto** [comment]
Windows 8

**Comment by vkarpov15** [comment]
Ah that might explain it. I don't really use windows much anymore so I always forget :)

**Comment by eshwaryaddanapudi** [comment]
This has started to happen in Windows 7 Ultimate - 64bit machine as well. It was working fine the other night.

**Comment by vkarpov15** [comment]
If localhost doesn't resolve to 127.0.0.1, not much mongoose can do about that.

**Comment by felixivance** [comment]
was getting Error: getaddrinfo ENOENT localhost:27017
"I have actually figured it out, i had to change the connection url from "localhost to 127.0.0.1" forexample..
var mongodbUri = 'mongodb://localhost/bg'; to var mongodbUri = 'mongodb://127.0.0.1/bg';"
Solution above worked Thanks :+1:

**Comment by magesa** [comment]
I was having the same problem running the example code from, "The Introduction to MEAN Stack course on Edx", developed by the able [vkarpov15](https://github.com/vkarpov15) himself. The environment is Windows 10 and I received the same Error: "MongoError getaddrinfo ENOENT" 

Apparently you need to declare localhost explicitly by pointing it to the specific Mongodb URI: 127.0.0.1, i.e localhost doesn't resolve to 127.0.0.1. Since I am in the learning curve of the MEAN Stack, I decided to create this table as mnemonic for people attempting the course( designed for MacOS users) on the Win8-10 environment. As per the MongoDBx course cited above, the piece of code;

 `Var URI = "Mongodb://localhost:27017/example"` is to be broken to the following by substitution

Connect to the  | Mongodb Instance
Running on       | localhost (substitute) to 127.0.0.1
Port                   | 27017
On database     | example (substitute) to  test( my test database or your-project-name-database)

This reduces the learning curve quite a bit for anyone running the MEAN Stack on Windows 8-9. Happy coding ;-)

**Comment by vkarpov15** [comment]
Thanks @magesa . Windows is pretty quirky when it comes to localhost. Also please don't accuse me of designing a course for OSX users, I wrote it on linux, just the video people insisted that I record screencasts on mac :)

**Comment by magesa** [comment]
You are most welcome @vkarpov15 . 

Windows adds an undue level of complexity, which I don't really mind as I am always up for a good challenge. I take back all and any accusations that I might have leveled against your person with respect to designing a course for OSX users ;-). 

Thanks a ton for the good work. The course is really, all that I needed to upgrade to this JavaScript Stack and boy am I enjoying it! It makes everything simpler and more intuitive.

**Comment by vkarpov15** [comment]
Thanks for your kind words, best of luck. Check out the gitter and slack channels for mongoose if you have small questions :)

**Comment by Shankar016** [comment]
Thank you

**Comment by Ljsam6** [comment]
It localhost was working fine till today suddenly it started showing error for me , solved it within no time ,thanks to github community <3

**Comment by erdalstk** [comment]
Same here, it started after i update mongo db version. Wish i see this solution 3 days ago.  thanks a lot.
