### ISSUE TITLE
Error codes for Mongoose validation?

### ISSUE THREAD

**Issue by manikandants** [Automattic/mongoose#3059]
For unique field validation we get error message as follows

<code>{ [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: test.users.$phone_1  dup key: { : 9876543210.0 }]
  name: 'MongoError',
  message: 'insertDocument :: caused by :: 11000 E11000 duplicate key error index: test.users.$phone_1  dup key: { : 9876543210.0 }',
  index: 0,
  **code: 11000,**
  errmsg: 'insertDocument :: caused by :: 11000 E11000 duplicate key error index: test.users.$phone_1  dup key: { : 9876543210.0 }' }</code>

For required field validation the error is as follows.

<code>{ [ValidationError: User validation failed]
  message: 'User validation failed',
  name: 'ValidationError',
  errors: 
   { email: 
      { [ValidatorError: Path `email` is required.]
        properties: [Object],
        message: 'Path `email` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'email',
        value: undefined } } }</code>

The interesting part in first error is the error.code as 11000 which can be directly compared to identify the error.
Wouldn't it be nice to have either predefined or customized error code for each of these error kind?
for example 91000 for 'required', 91001 for 'length' etc

**Comment by vkarpov15** [comment]
Unique is not a mongoose validator, it creates [mongodb unique index](http://docs.mongodb.org/manual/tutorial/create-a-unique-index/) on the mongodb server, because mongoose can't effectively verify unique constraints in the general case. Validation errors have a 'kind' that you can use to check the error type for a given field, which seems to be the answer to your question.

If you're looking to get more friendly MongoErrors, @MattouFP wrote a plugin https://www.npmjs.com/package/mongoose-beautiful-unique-validation (see https://github.com/Automattic/mongoose/issues/2284#issuecomment-102785674)

**Comment by manikandants** [comment]
Thanks @vkarpov15 :) That answers my question. I was looking for a common error kind/code for all errors. Using @MattouFP plugin will give errors with 'kind' and solve my issue.
