### ISSUE TITLE
bug ?  Model.findOneAndUpdate()

### ISSUE THREAD

**Issue by zhaolihang** [Automattic/mongoose#3076]
var kittySchema = new Schema(
		{
			name:{type:String,default:"dog"},
			age:{type:Number,default:10},
		}
	);//new Model, the first step 
	kittySchema.methods.speak=function () {
		console.log('my name is '+this.name);
	};
	var Kitty = mongo.model("kitty",kittySchema);//build Model, must be the last step 

	var condition = {name:"smalldog"}; 
	var update = {$inc:{age:1}};  //age add 1
	var options = {new:true,upsert:true}; 
 	Kitty.findOneAndUpdate(condition,update,options,function (error,kitty) {
 		if (!!!kitty) {return false};
 		console.log(kitty); //kitty.age should be 11   but I got 1 ,it look like incorrect .
 	});

please see  the second line from the bottom .

**Comment by vkarpov15** [comment]
By default, mongoose doesn't set defaults when you do `findOneAndUpdate()`. You can set the `setDefaultsOnInsert` option, but in this case that won't work because you're using `$inc` on age, and mongoose uses the [mongodb server's $setOnInsert operator](http://docs.mongodb.org/manual/reference/operator/update/setOnInsert/) and mongodb server doesn't allow you to use `$setOnInsert` and `$inc` on the same field in the same `findAndModify`:

```javascript
> db.x.findAndModify({ query: { test: 1 }, update: { $inc: { age: 1 }, $setOnInsert: { age: 10 } }, upsert: true });
2015-06-16T13:49:33.648-0400 E QUERY    Error: findAndModifyFailed failed: {
	"errmsg" : "exception: Cannot update 'age' and 'age' at the same time",
	"code" : 16836,
	"ok" : 0
}
    at Error (<anonymous>)
    at DBCollection.findAndModify (src/mongo/shell/collection.js:636:15)
    at (shell):1:6 at src/mongo/shell/collection.js:636
```

**Comment by zhaolihang** [comment]
ok  I got it
