### ISSUE TITLE
update should not strip out fields not defined in the schema

### ISSUE THREAD

**Issue by vincentcr** [Automattic/mongoose#3119]
i am writing code migrating an old schema field to a new one. it looks like this: 

``` 
MyModel.update(query, {  $set: newField, $unset: { 'oldField' : '' } }, callback)
``` 

However because I have removed `oldField` from this model's schema definition, mongoose is stripping out `'oldField'` from the `$unset`, and thus the resulting query is:
```
{  $set: newField, $unset: {  } }
```

which is (a) not what I wanted; and (b) an invalid mongodb query, resulting in this error: 
```
MongoError: '$unset' is empty. You must specify a field like so: {$mod: {<field>: ...}}
```

If I put back `oldField` in the schema, the error goes away, but this is not what I want, as I don't want to leave obsolete fields in the schema.

**Comment by vkarpov15** [comment]
Why not just migrate the data and then remove the field from the schema? If you want, you can also bypass mongoose's casting entirely and use `MyModel.collection.update()`

**Comment by vincentcr** [comment]
This is the way I wanted to migrate. In any case, if you want to forbid updates that don't fit the schema, you should return an error, not silently strip the data. If this hadn't happened to trigger the empty unset error in mongo, it would have been very frurstrating to debug.

**Comment by vkarpov15** [comment]
You can then just turn [strict mode off in your schema for the duration of your migration](http://mongoosejs.com/docs/guide.html#strict). I wouldn't recommend that, but it will work. If you want to not silently strip the data, you can set the [schema's strict option to 'throw'](http://mongoosejs.com/docs/guide.html#strict) and then mongoose will throw an exception rather than strip it out. However, silently stripping the data is typically the right choice for REST API's - you don't want to try/catch around every update call in your REST API in case a malicious user sends over corrupted data, you typically just want to ignore it.
