### ISSUE TITLE
plugins.mongoosejs.com

### ISSUE THREAD

**Issue by tjsail33** [Automattic/mongoose#3127]
is currently throwing an application error.

**Comment by kevinsimper** [comment]
It seems to work now?

**Comment by tjsail33** [comment]
This is down, once again. 

I"m receiving a standard Heroku application error. 

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.


Are you perhaps running this on a free dyno that caps usage at 18h per day?

**Comment by vkarpov15** [comment]
Looks back now. I'm actually not sure about the heroku details, I've never touched that myself. If you're interested in putting in a PR, the code is at https://github.com/aheckmann/mongooseplugins

**Comment by tjsail33** [comment]
It wouldn't be solvable via PR, you would need the person who set it up to change the type of dyno (server) it is running on to hobby, which is $7/m instead of free.

**Comment by mchapman** [comment]
Has been down the last few times I have checked (and is down now)

**Comment by vkarpov15** [comment]
Yeah it's down now. I'm not terribly familiar with how heroku works so it'll take some time for me to get up to speed and figure out how it works.

**Comment by mchapman** [comment]
I have a few things running on Heroku and would be happy to provide any help you thought suitable (but not $7 per month!)

**Comment by vkarpov15** [comment]
Yeah that's kinda annoying. I may decide to just switch over to a free-tier machine on EC2 because heroku is too much of a hassle

**Comment by leobudima** [comment]
Again :)

**Comment by maysale01** [comment]
Still down

**Comment by jonascript** [comment]
bump.

**Comment by vkarpov15** [comment]
Changing over to http://plugins.mongoosejs.io/ because I don't have access to mongoosejs.com DNS. Heroku bugs out because the plugins site tries to load all npm packages with "mongoose" in the name and so devours all memory, so we're now running on an EC2 t2.medium as a stopgap until somebody has a good idea as to how to make the plugins site performant without caching everything in memory. Contribs welcome here: https://github.com/aheckmann/mongooseplugins
