### ISSUE TITLE
Log error when saving props not in schema

### ISSUE THREAD

**Issue by ca** [Automattic/mongoose#3152]
This is pretty minor but I've spent a couple hours hunting down errors when I .save() an object and the properties I set don't save, only to realize that it's not part of the schema. So if you guys could work in console.logging a warning when saving props not part of the schema I'm sure that would save some people some time! Thanks to @sfarthin for hunting this down with me

**Comment by vkarpov15** [comment]
See docs on [strict mode](http://mongoosejs.com/docs/guide.html#strict) in schemas. There's 3 options

* `strict: false`: when you set a key that isn't in the schema, mongoose will save it without any validation
* `strict: true`: This is the default. When you try to set a key that isn't in the schema, mongoose will remove it.
* `strict: 'throw'`: throw an error when you try to set a key that isn't in the schema

`strict: true` is the default because in many cases you overwrite nested objects with user-provided data, like from a REST API, and you just want mongoose to filter out extraneous data. Given that use case, printing a warning would be silly. You're welcome to put in a PR for a separate `strict: 'warn'` mode that logs an error, but I'm hesitant to do that because in production you typically don't want code logging to the console.

**Comment by ca** [comment]
Okay very cool didn't realize you had that feature already; should've looked harder. Yep you're exactly right, the warning would be strictly for development. I guess I'll just open the PR and you can decide what you want to do with it!
