### ISSUE TITLE
Schema level indexes not created automatically

### ISSUE THREAD

**Issue by tylkomat** [Automattic/mongoose#3184]
When I start my app with `mongoose.set('debug', true)` I can see `ensureIndex()` calls for all field indexes, but the schema level indexes don't show up there and are also not added in mongodb.

I use mongoose 3.8.34.

**Comment by vkarpov15** [comment]
Can you show me what the syntax you're using to declare indexes looks like?

**Comment by tylkomat** [comment]
Some Examples:
```
schema.index({_id: 1}, {unique: true, name: '_id_1'};
schema.index({_id: 1, isPublic: 1, isCompleted: 1, completedAt: 1}, {name: 'project'});
schema.index({
	name: 'text',
	description: 'text',
	isPublic: 1,
	isCompleted: 1,
}, {name: 'textIndex'});
```
None of them Shows up in mongodb while they are all returned when I call `schema.indexes()`.

**Comment by vkarpov15** [comment]
Try listening to `MyModel.on('index', function(err) { console.log('error building indexes: ' + err); });`. This sounds like a classic case of an index build failing because of a bad index. In particular, I suspect that your index on `_id` is breaking, because mongodb creates an index on `_id` by default and `ensureIndex()` will fail if there's a conflicting index.

**Comment by tylkomat** [comment]
You were right. These two were the culprits:
```
schema.index({_id: 1}, {unique: true, name: '_id_1'});
schema.index({_id: -1}, {unique: true, name: '_id_-1'});
```
I would have expected that it would continue if one fails, but everything that came after was just omitted.

Thanks a lot for the fast help.
