### ISSUE TITLE
question: does the versionkey __v mess with my indexes?

### ISSUE THREAD

**Issue by japrescott** [Automattic/mongoose#3235]
I have recently noticed that saves on a document (`document.save`) of a collection with 8mio rows can get very slow vs `model.update` or `model.findOneAndUpdate`. I get the document by querying the _id directly. As I read in the docs, using document.save adds a `__v` key to the query to ensure version safety. Now, there is obviously an index on _id. Could it be, that by adding __v to the query, mongodb ditches the index its got?
I assume that by adding the __v to the END of the query, this would be solved as indexes would be used to find _id and then filtered/sorted in-memory by __v?

**Comment by vkarpov15** [comment]
Worth double-checking. I doubt this is the case, but mongoose often does a bad job of retaining key order (re: #2749). This is because the question of "do BSON key orders matter?" is a big grey area in  MongoDB - the answer is "sometimes yes, sometimes no" and hitting indexes is one case where the answer is yes.
