### ISSUE TITLE
Automatic casting from string to number differs in find() vs aggregate()

### ISSUE THREAD

**Issue by johntmyers** [Automattic/mongoose#3251]
When building a query, I had an expressiont I used in find() and aggregate() methods, which is:

```stop_time_epoch:{'$gte': req.query.start, '$lte': req.query.stop}```

stop_time_epoch is a Number type in my model, when I include this expression on a .find() the req.query strings are automatically cast to a Number and the query works fine

When I include this expression in the $match clause of .aggregate() the strings are NOT automatically cast to a Number, so the $match stage fails.

Is this by design? If so, why?

**Comment by johntmyers** [comment]
I was able to explicitly use Number() to make them both work, but still seems like it should have the same behavior, considering $match query format matches find() exactly, per the MongoDB docs.

**Comment by vkarpov15** [comment]
This is by design. Mongoose doesn't do any casting on aggregation framework queries because it's really tricky to get that right in the general case; the whole point of the aggregation framework is to transform documents into different forms with each pipeline stage. Mongoose could in theory cast the first stage of the pipeline for you and continue to cast so long as they're '$match' pipelines, but that wouldn't make for a very clean API... I'm open to alternative suggestions though.

**Comment by johntmyers** [comment]
Ok that makes more sense, it's easy enough to know to explicitly cast for
aggregation, I just wasn't sure if that was the norm.

**Comment by efkan** [comment]
Hi @vkarpov15 ,
I've almost opened a new issue like this :)
I couldn't find any explanation on documentation about it. If so, it would be great if it was as a alert like the following sentence;
"Mongoose doesn't do any casting on aggregation framework queries."

Thank you for your developing and supporting on this 'huge!' project.
