### ISSUE TITLE
Minimize handles undefined values in arrays

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3269]
Re: #2930

**Comment by dbellavista** [comment]
Hi! I'm bumping this ancient issue since I'm dealing with it now :)

Mongoose transforms empty object inside mixed array in `undefined` if `toObject` is used or `null` using `toJSON`. This can break the application, but more importantly this behavior applies onyl when dealing with mixed array. array of schemas (event with `_id: false`) are not minimized.

Here a gist to reproduce: https://gist.github.com/dbellavista/12e885e9d152d55af8d641c641f347ef

**Comment by vkarpov15** [comment]
Thanks @dbellavista , will investigate asap, opened up a new issue :point_up:

**Comment by vkarpov15** [comment]
This was fixed in 5.4.6 with #7422.
