### ISSUE TITLE
Should findById(undefined) return null?

### ISSUE THREAD

**Issue by wlingke** [Automattic/mongoose#3270]
Currently, findById(undefined) retrieves the first document. Intuitively I'd expect this to return null.

**Comment by vkarpov15** [comment]
IMO this is a case where intuitiveness is relative, because `findOne({ _id: undefined });` will also return the first document if your _id is an ObjectId, because query casting will cast out the invalid objectid. Worth discussing whether or not if your query gets casted to empty should qualify as an error, return null, or just do what it does now...

**Comment by callmevlad** [comment]
Related to https://github.com/Automattic/mongoose/issues/3255

Also it looks like `findById` has inconsistent behavior across MongoDB versions, with `MongoDB 2.6.5` returning the first document and `MongoDB 3.0.5` returning `null`.

**Comment by wlingke** [comment]
That's fair. It is definitely dependent on the person.. My vote would go to returning null though.

**Comment by jaredpetersen** [comment]
I discoverd this problem recently with ``findOne({keyhere: undefined}, callback);``. I agree with @wlingke, it should return null.

**Comment by dlear** [comment]
I like deterministic software so returning `null` for `undefined` gets my vote too - *sometimes* returnng the first document in this situation is dangerous - it certainly broke our application.  (Fortunately caught during testing, but now we're pegged back to the 4.0.2 release.)

**Comment by crispen-smith** [comment]
as this seems to be something that is project specific, is this something that can be configured on instantiation of a new mongoose object?   ie:

      var mongoose =  new mongoose.config("returnUndefinedDoc", true);

**Comment by jaredpetersen** [comment]
@crispen-smith I don't particularly like being forced to set that as an option, but at least it would solve the problem of breaking backwards compatibility.

**Comment by dlear** [comment]
This behaviour has changed since 4.0.2 which returned null for undefined.  So instead of saying that you are breaking backwards compatibility, you might consider that you are restoring it...

**Comment by crispen-smith** [comment]
@jaredpetersen, I don't have an opinion as to the default, I think this is probably really outside of the scope of mongoose and the best practice is to guard the code that could call findByID(undefined) to prevent it from happening at all.  But; as this is not always possible, it's probably best to have a mechanism to manage it.

**Comment by vkarpov15** [comment]
You could also probably implement this as a plugin.

```javascript
schema.pre('findOne', function(next) {
  if (isEmptyObject(this.getQuery())) {
    return next(new Error('findOne with empty query!'));
  }
  next();
});
```

Do you think that's a reasonable alternative?

**Comment by callmevlad** [comment]
@vkarpov15 It seems very dangerous to leave the default as-is, particularly because very recently (4.0.2) Mongoose behaved very differently.

Here's some example pseudo code of something that happened recently to us:

```javascript
function deleteUserForever(req, res, cb) {
  var user = models.Users.findById(req._id);
  var usersWebsite = models.Websites.findById(user.siteId);

  // nuke website forever
  // nuke user forever
}
```

In the above case, there are two huge potential issues that no one would reasonably assume could happen:

- The `req` object could have a missing `_id` by mistake (e.g. frontend code sends `id` instead after refactoring), in which case **the first user in the Users collection will be removed**
- The user could have previously deleted their site, so `siteId` could be undefined, in which case **the first website, which in all likelyhood is completely unrelated to the context user, will be blown away**

Implementing this as an opt-in plugin, in my opinion, is not a good solution. The only way people will discover that workaround is if they get bitten by this behavior in the first place.

**Comment by jaredpetersen** [comment]
@callmevlad Agreed. Your situation is similar to what I ran into accidentally and new people __will__ fall into this trap. Besides, the more data validation responsibility that I can pass onto Mongoose, the better.

**Comment by yaring** [comment]
+1

**Comment by vkarpov15** [comment]
Turns out this behavior was in earlier versions. I suspect this had to do with the recent change to bson that no longer converted undefined -> null re: https://github.com/mongodb/js-bson/commit/c9b500140db03962523267b5a5237ba541c7ce71

**Comment by callmevlad** [comment]
Thank you Valeri!

**Comment by yaring** [comment]
Thanks @vkarpov15, when the new version suppose to be?

**Comment by vkarpov15** [comment]
@yaring Earlier today :)
