### ISSUE TITLE
`Model.update` does not return the same type of promise as specified in `mongoose.Promise`

### ISSUE THREAD

**Issue by suprememoocow** [Automattic/mongoose#3307]
I've just discovered that you can now set `mongoose.Promise = X` to use your Promise library of choice. This is great. I'm investigating how much work it would be for us to drop our `mongoose-q` and just use the promise returned from `.exec()` etc. 

One thing I've noticed is that some operations that use `mquery` internally don't adhere to this behaviour, for example:

```js
var Q = require('q');
mongoose.Promise = Q;

...
// Q Promises!
Q.isPromise(Model.findOne().exec()) // --> true

// But,unfortunately
Q.isPromise(Model.update(/* .. */)) // --> false
// Also tried
Q.isPromise(Model.update(/* .. */).then()) // --> false
```

I presume that this is an oversight and not intentional? 

mquery allows you to configure the promise library being used:
> NOTE: The returned promise is a bluebird promise but this is customizable. If you want to use your favorite promise library, simply set mquery.Promise = YourPromiseConstructor. Your Promise must be promises A+ compliant. [Source](https://github.com/aheckmann/mquery#then)

Is `mquery` being configured when `mongoose.Promise` is set? I can't find any reference to this in the code, so I'm guessing not? 

As a side note, `Model.update` returns an mquery instance, which is `then`able but not actually a promise. This means that in order to get at the promise, I'd need to use `Model.update(/* .. */).then()` which feels quite clunky, but obviously I understand that this would be a breaking API change.

**Comment by vkarpov15** [comment]
[We do set mquery.Promise when mongoose.Promise is set](https://github.com/Automattic/mongoose/blob/03e874eb4ad336590a366f2fb01f80cd28bbef68/lib/promise_provider.js#L38). If you dig into how mquery is implemented, you'll see that `Model.update(/* .. */)` is actually an instance of mquery - it has a `.then()` but Q won't pick it up.

Furthermore, we don't support `mongoose.Promise = require('q');`. [You need to use `mongoose.Promise = require('q').Promise;`](https://github.com/Automattic/mongoose/blob/cbc59d94f9bd197c6e0d3b879a4c370f28e310a6/test/promise_provider.test.js#L315-L316) AFAIK, because what Q exports is not an ES6-compatible promise constructor. Does that help?

**Comment by suprememoocow** [comment]
Thanks @vkarpov15, I've realised the error in my ways. For some reason I thought `Model.update` returned a promise instead of a query.

I am, in fact, using `mongoose.Promise = require('q').Promise;`, that was a typo on my behalf. 

I've tested and it is in fact working correctly.
```js
var promise = Model.update({ fred: 'bob' }, { $set: { bob: '1' } })
  .exec();

console.log(Q.isPromise(promise)); // --> true
```

Sorry about the confusion and thanks for pointing me in the right direction...

Finally, I also noticed that:
http://mongoosejs.com/docs/api.html#model_Model.aggregate

says it returns `<Aggregate, Promise>` when in fact, it returns an `Aggregate` and you need to do an `exec()` to get the promise. Should I create a PR to change this documentation or is there a reason for this?

Thanks for brilliant library and the quick response.

**Comment by vkarpov15** [comment]
Re: PR, please do, that would be very helpful. Thanks for your kind words :beers:
