### ISSUE TITLE
No backward incompatible changes in patch version updates please

### ISSUE THREAD

**Issue by adamhadani** [Automattic/mongoose#3324]
Hey guys,
Recently there was a couple of backward incompatible changes introduced as patch version updates:

- Change of signature of findOneAndUpdate to return a tuple in 4.1.3
- reversal of said change in 4.1.4 (with addition of optional flag)

It would be great to have any API breaking changes applied as a minor version rather than  patch version, as many package maintainers use the convention of 'squigly' line semver specification for such dependencies as mongoose, e.g 'mongoose: ~4.1.3', which would automatically update to 4.1.4 and break the code.

**Comment by srt32** [comment]
:+1:

**Comment by vkarpov15** [comment]
The 4.1.3 change to the `findOneAndUpdate()` callback signature was an oversight, which is why 4.1.4 changed it back for backwards compatibility. I'm not entirely sure what semver's policy is on what to do when a point release unintentionally turned out to be backwards breaking, so I'm treating it as a bug fix. We'll mark 4.1.3 as deprecated in npm and make sure to make these changes more transparent in the future. My sincerest apologies for the inconvenience.

**Comment by adamhadani** [comment]
thanks @vkarpov15 !
