### ISSUE TITLE
document.remove() removes whole collection

### ISSUE THREAD

**Issue by RBLU** [Automattic/mongoose#3326]
I think this commit (https://github.com/Automattic/mongoose/commit/caf7181ee088ae649aeccdcbc3f61ca0951228eb)  for a fix of model.remove() has triggered that now when we call: 
    
    document.remove(cb) 

everything in the collection is removed, previously only the one document was removed. 
This can be pretty bad (my users collection was emtpy after deleting one user)... I hope my analysis is not correct.

Also the documentation here states clearly that the current behaviour is not intended: http://mongoosejs.com/docs/api.html#model_Model-remove
model.remove(fn) removes this document from the db.

**Comment by vkarpov15** [comment]
Whoa yeah that's not terribly good. On it.

**Comment by fyockm** [comment]
duplicate of #3325

**Comment by farhanpatel** [comment]
This fix should be out now. This is pretty huge

**Comment by vkarpov15** [comment]
Done. Thanks.

**Comment by Martii** [comment]
@vkarpov15 
Perhaps a silly question... but is there an "unremove" *(undelete)* method?

**Comment by shauntrennery** [comment]
This got me this morning. Thank goodness for database backups. All our platform's apps were deleted. I even started to suspect we had been hacked.

**Comment by vkarpov15** [comment]
Sorry about that @shauntrennery - unfortunately we did not have test coverage for this situation and the fix for #3235 went awry. 4.1.4 has been unpublished so hopefully that'll limit the possibility of anybody running into this again...

@Martii not that I know of unfortunately. Typically it's a better choice to not explicitly delete individual docs and instead hide them behind an `isDeleted` flag for this sort of situation.
