### ISSUE TITLE
Model.update({ _id: undefined }, ...) updating all documents in collection

### ISSUE THREAD

**Issue by gonzalezjordi** [Automattic/mongoose#3336]
Hi guys,

When using the **Model.update** method with a wrong query - saying *{_id: undefined}* - all documents in my collection are being updated, is that the expected behavior? We already got one of our collections removed due to the doc.remove() issue (#3325) and don't want to experience any similar problem. What a nightmare.

Thanks

**Comment by vkarpov15** [comment]
Due to https://github.com/mongodb/js-bson/commit/c9b500140db03962523267b5a5237ba541c7ce71, fields with value `undefined` are no longer serialized to mongodb, so sending `{ _id: undefined }` query to the driver gets treated as `{}`, which would update all docs if you set `multi: true`. However, I'm pretty sure mongoose converts undefined -> null for queries, so you shouldn't get that behavior using mongoose... Can you show me what your code and schemas look like?

**Comment by gonzalezjordi** [comment]
You're right, I updated to last version and it works fine now - we were using v4.1.0. Any other potentially dangerous behavior that we should be aware of? Just want to make sure we are using Mongoose in the safest possible way and avoid undesired massive updates/removes.

I appreciate the prompt response.

**Comment by vkarpov15** [comment]
There were a couple snafus with 4.1.3 (https://github.com/Automattic/mongoose/issues/3173#issuecomment-134690708) and 4.1.4 (#3325), but no major issues with 4.1.5 thus far. I apologize for the inconvenience - that js-bson change caused a great deal of headache.
