### ISSUE TITLE
Lazy Migration of Documents after schema changes

### ISSUE THREAD

**Issue by akreienbring** [Automattic/mongoose#3340]
Hello, I implemented some code that handles the migration of documents that were created with an outdated schema version.

Let's say I've got an outdated schema version like 'User' and created some docs in that collection.
Further on I defined a new schema version "User1" and want to migrate the 'old' docs to the 'new' collection. Currently I'm using code like this to achive this:

```
		//user is one doc within the 'old' collection
		var newUser = new User1(user);
		
		newUser.save(function(err, newUser) {
			if(!newUser || err) {
				//error
				callback(err, user);
			}else{
				//success
				user.remove();
				callback(err, newUser);
			};
		});
```
My questions are: 
Will newUser._id be the same as user._id after the migration? In other words: Will the ObjectID (that was automatically created by mongo) be preserved when I call  var newUser = new User1(user)?
Also, Will there be an issue with duplicate id's? Provided that in collection of Model User1 there's an existing user that has the same id as the user that is getting migrated.
Do I have to use this plugin https://github.com/yamadapc/mongoose-uniqueid/blob/master/lib/index.js to be sure that this is not going to happen?

Thanks in Advance.

**Comment by vkarpov15** [comment]
1) Yes, the `_id` should be the same.
2) No, as long as you're inserting the doc into a different collection. MongoDB has a unique index on `_id` in every collection, so if you try to insert a new document with an `_id` that already exists in that collection, your insert will fail. However, since you're moving docs to a new collection, this shouldn't be an issue.
3) No, that plugin gives you a hacky way to make an _id unique across multiple collections, which is typically not very useful since it's very hard to make MongoDB object ids collide, especially in NodeJS.
