### ISSUE TITLE
Manipulating result object (callback)

### ISSUE THREAD

**Issue by efkan** [Automattic/mongoose#3349]
I think this is a known case and I don't know this is a real issue or not. For this reason I am asking a question.

Sometime we need to play with result object.

```
User.find({name: 'Jupiter'},function(err, Jupiters){
     var i = 1;
     Jupiters.forEach(function(item){
        item.number = i;
        i++;
    })
    console.log(Jupiters[0]); // there is no 'number' property and its value
})
```

I use `aggregation` to overcome this issue;

```
var match = { $match: { name: 'Jupiter' } }
var group = { $group: { _id: '$_id', name: { $first: '$name' } } }

User.aggregate(match, group, function(err, Jupiters){
     var i = 1;
     Jupiters.forEach(function(item){
        item.number = i;
        i++;
    })
    console.log(Jupiters[0]); // number prop can appear now
})
```

Question;
Is there any chance to modify result object of 'Model.find()' function?

**Comment by vkarpov15** [comment]
In the first example, each item in `Jupiters` is a mongoose document. If `number` is not in the schema, then it won't show up when you do `JSON.stringify()` like in that `console.log` statement. However, if you check `Jupiters[0].number` you'll see it's still there. There are a couple workarounds to get the behavior you want:

1. `User.find({name: 'Jupiter'}).lean().exec(callback);` - this will make it so that the results are plain-old JavaScript objects
2. Call `.toObject()` before modifying each Jupiter.

The reason why aggregation works for you is that the output of aggregate is not a mongoose document.

**Comment by efkan** [comment]
Thanks! :)
