### ISSUE TITLE
.catch() for Promise is not on Query object

### ISSUE THREAD

**Issue by aliatsis** [Automattic/mongoose#3377]
while using `require('mongoose').Promise = global.Promise;`

`doc.find().then(...).catch(...)` works fine
`doc.find().catch` is `undefined`.
the caller might want to add a .catch() immediately and delegate any success handlers to later promise chains.

**Comment by vkarpov15** [comment]
`doc.find()` is not a promise (otherwise you couldn't use chaining syntax), it's an [mquery](https://github.com/aheckmann/mquery) instance. The mquery instance has a `.then()` as syntactic sugar for `yield`, but we don't plan on making it support every method that the ES6 promise does. If you want to `.catch()` just do `doc.find().exec().catch();`. `.exec()` executes the query and gives you a real promise.
