### ISSUE TITLE
Capped arrays

### ISSUE THREAD

**Issue by fcristel** [Automattic/mongoose#3395]
I don't know if I'm missing something here, but I'm not able to use capped arrays. I have an array field, defined like this:
<pre>var UserSchema = new Schema({
feed: { type : Array , "default" : [], _id: false }
});</pre> 
and then in code I have a addToSet, like this:
<pre>User.findById(myId)
.exec(function(err, user){
user.feeds.addToSet(newFeed);
})</pre>
Then I try to check if the array "feeds" has more than 10 elements, and then slice somehow.
I've tried using with lodash library:
<pre>user.feeds = _.drop(user.feeds, user.feeds.length-10);</pre> 
 or just like this:
<pre>user.feeds.slice(-10);</pre>
Also tryed this after the addToSet:
<pre>User.findById(myId).slice('feeds', -10);</pre>

And at last, save the object:
<pre>user.save(function(err){
});</pre>

Nothing seems to get the array to update. This must be a simple operation, but I'm a bit stuck here. Any help would be much appreciated.

Thanks!

**Comment by vkarpov15** [comment]
Doing `$addToSet` with an array size limit is [not possible with MongoDB](http://docs.mongodb.org/manual/reference/operator/update/addToSet/). Just a case where you get very counter-intuitive behavior, especially since `$addToSet` does not guarantee the order of the elements after adding, and mongoose's `addToSet()` internally translates to a `$addToSet` operator to MongoDB. I'd recommend just doing this in NodeJS directly rather than relying on mongodb updates:

```javascript
var arr = user.feeds.toObject();
var el = _.find(arr, function(v) { return v._id.toString() === newFeed._id.toString(); });
if (el) {
  return;
}
arr.push(newFeed);
while (arr.length > 10) {
  arr.unshift();
}
user.feeds = arr;
```
