### ISSUE TITLE
Compatibility issue with Morphia relations

### ISSUE THREAD

**Issue by frapontillo** [Automattic/mongoose#3411]
I am sharing the same data layer for both Morphia (JVM) and Mongoose, but there is an inconsistency on how relations are saved.

Mongoose uses a regular field whose value is an `ObjectId("somethingsomething")`.

Morphia, instead, uses an object such as:

```javascript
"theReference" : {
    "$ref" : "Project",
    "$id" : ObjectId("5605ba5c4524667591b23649")
}
```

It looks like Mongoose can populate such references built by Morphia, but it can't save them this way.
My sample model is as simple as:

```javascript
{
  id: mongoose.Schema.ObjectId,
  date_start: Date,
  project: { type: mongoose.Schema.ObjectId, ref: 'Project' }
}
```

Is there a way to provide compatibility of behaviour? Why does Mongoose can read and populate Morphia fields but throws a `ValidationError` when saving such relations?

See https://github.com/mongodb/morphia/issues/852

**Comment by vkarpov15** [comment]
Typically, [MongoDB recommends using manual references (mongoose style) over dbrefs (morphia style)](http://docs.mongodb.org/manual/reference/database-references/). Mongoose does not really support dbrefs, as you've noticed. We could in the future if there's a lot of demand. Otherwise, looks like your issue was solved on the morphia thread.
