### ISSUE TITLE
findOne (and its derivatives) must return 'undefined' instead of 'null' (for ES6)

### ISSUE THREAD

**Issue by klimashkin** [Automattic/mongoose#3457]
It is needed for destructing with default values
```javascript
const [count, { _id: userId } = {}] = await* [
     SomeModel.count({}).exec(),
     SomeModel.findOne({ someField: 1 }).exec()
]
```
Now, if findOne finds nothing, it throws error ```Can not read property _id of null```, because default parameters sensitive only to 'undefined', and in this case engine trying doing this: ```const userId = null._id```

**Comment by vkarpov15** [comment]
That's a big backwards breaking change. AFAIK the whole point [of null is to represent intentional absence of a value](http://www.ecma-international.org/ecma-262/6.0/#sec-null-value), which seems pretty correct to do when a query returns no results. You should be able to do this with a post `findOne` hook though, no?

**Comment by klimashkin** [comment]
It's interesting question.
On the one hand we may have default parameters incoming to functions, the can be undefined.
On the other hand we have return values from function, which often are 'null' to show that function can return real value with another parameters.

But functions in JS are first-class objects, so we can transfer functions as parameters and result and function result as parameter to another function.
So how to handle in this case 'value absence' to substitute it with default parameter?

I think we need help. Maybe @jakearchibald could clarify the situation

**Comment by bricss** [comment]
I'm fully agree with @vkarpov15

**Comment by vkarpov15** [comment]
I'm not familiar enough with destructuring assignments atm to make a definitive suggestion. I looked into using post hooks for this, but that's not feasible because query post hooks don't allow you to arbitrarily transform the result data - best you can do is return an error if `findOne` returned no results.

Here's a quick hack that may help:

```javascript
const [count, { _id: userId } = {}] = await* [
     SomeModel.count({}).exec(),
     SomeModel.findOne({ someField: 1 }).exec().then((v) => v === null ? undefined: v) 
]
```

**Comment by klimashkin** [comment]
More compact:
```
const [count, { _id: userId } = {}] = await* [
     SomeModel.count({}).exec(),
     await SomeModel.findOne({ someField: 1 }).exec() || undefined
]
```
But anyway it's one more microtask, pity

**Comment by vkarpov15** [comment]
Well this is the sort of thing that [monogram](https://github.com/vkarpov15/monogram) and any changes to mongoose that come out of it should be able to help with. Making `findOne()` return undefined when empty is actually super easy there, quick little middleware.

In general this is the sort of thing that hooks should really be for, unfortunately the current iteration of query middleware can't do it though...
