### ISSUE TITLE
Virtuals not able to be "populated" (Possible enhancement?)

### ISSUE THREAD

**Issue by mcpDESIGNS** [Automattic/mongoose#3465]
(This might be more of a potential enhancement, and maybe I'm unaware of the consequences of adding this capability) 
Populating "virtuals" doesn't seem to be an option, and typically must be done by either entering in the fields you need, or maybe having them as a variable as part of your Model.

As an example:

    User.find({ name: req.params.name })
        .populate({ path : 'likesvirtual' }) // imagine "likesvirtual" is a virtual with lots of fields
        .execAsync(function (err, user) {
            // likes will just be an ObjectId
        });

But of course manually populating all of those fields in likes works:

      .populate({ path: 'likes', select : 'name type image status active' })

Am I missing something obvious perhaps?

**Comment by vkarpov15** [comment]
Umm the whole point of a virtual is that it's not stored in the database, pulling a virtual from the database defeats that purpose.

**Comment by mcpDESIGNS** [comment]
That's what I figured, oh ok so it's all working as it's supposed to then. 
My apologies.

I just thought it was possible to use a virtual to fill in the "select" portion of the `.populate` command. I'll stick with variables containing all the fields. Thanks Val

**Comment by vkarpov15** [comment]
Right now we don't really support `.select()` on virtuals, because it's not really obvious how to make that work - virtuals aren't stored in the database, so we can't really send them to MongoDB. We could use `.select()` to disable certain virtuals, but that has a lot of nasty edge cases like "what happens when you just select a virtual and nothing else?"
