### ISSUE TITLE
Stack traces on errors (Error.stack) should not be captured by default.

### ISSUE THREAD

**Issue by fklingler** [Automattic/mongoose#3571]
Since version 4.0, errors stacktraces seems to be captured by default:
https://github.com/Automattic/mongoose/blob/c76effbf2c9a6f7f1e6e7cc359a1b7d04a526e14/lib/error/validation.js#L22

I don't think it should be the case, there should be an option to activate this or not. It can be helpful in development, but it can be dangerous in production where the errors can be sent to client on API responses.

**Comment by fklingler** [comment]
If someone else has a problem with this, it can simply circumvented with this:

```
  Error.stackTraceLimit = null;
```

See https://nodejs.org/api/errors.html#errors_error_stacktracelimit.

**Comment by fiznool** [comment]
@fklingler I agree this should be an option of some sort.

The workaround posted is far from ideal, as it causes all error stack traces in the app to be removed. This isn;t ideal if you are relying on traces to diagnose other errors that may be occurring.

**Comment by vkarpov15** [comment]
A better workaround would be to just use something like lodash's `omit()`. I usually just have some error handler middleware that pulls out `error.errors` if the error is a mongoose `ValidationError`, and otherwise just sends the `toString()`.

Would it help if we used `Error.captureStackTrace()` instead of just using `new Error().stack`?

**Comment by fiznool** [comment]
How about providing a flag, eg mongoose.noValidationErrorStacks that could
be set on app startup?

You could then do things like mongoose.noValidationErrorStacks =
(process.env.NODE_ENV === 'production')

Since disabling stacks is opt in, this wouldn't be a breaking change. Or
you could take the approach of express, which automatically disables stack
traces in the default error handler if the NODE_ENV is production.

**Comment by vkarpov15** [comment]
I'm very much committed to never adding environment variable configs to mongoose, IMO modules that touch env variables are an appalling anti-pattern that needs to die.

I also don't like adding unnecessary knobs - is there a case where you would want stacks for errors in general but not for mongoose errors?

**Comment by fklingler** [comment]
I don't personnally see a case where  you would want stacks for errors in general but not for mongoose errors.

But I don't get why it should be on by default in Mongoose. I think it should be the responsability of the user of mongoose (the dev using mongoose) to add these stacks to the errors returned, if he wants. (with `Error.captureStackTrace(err)`).

And there could definitely be some config options for mongoose, I don't quite see why not.

**Comment by vkarpov15** [comment]
The argument is that [v8 error objects have a `.stack` property that contains the stack trace](https://chromium.googlesource.com/v8/v8/+/master/docs/javascript_stack_trace_api.md), the fact that mongoose does this is nothing unusual. I don't really know of any other node module that lets you bypass the 'stack trace by default'...

**Comment by fiznool** [comment]
I think the point of the original issue was that the stack trace is
included in the object when it is returned by a library such as express.
This is because currently the `stack` property is enumerable in a
ValidationError.

AFAICT using `Error.captureStackTrace` would be a better solution as this
will still create a correct `stack` property, but it will be non
enumerable, and so won't be returned by express.

The argument is that v8 error objects have a .stack property that contains
the stack trace
<https://chromium.googlesource.com/v8/v8/+/master/docs/javascript_stack_trace_api.md>,
the fact that mongoose does this is nothing unusual. I don't really know of
any other node module that lets you bypass the 'stack trace by default'...

—
Reply to this email directly or view it on GitHub
<https://github.com/Automattic/mongoose/issues/3571#issuecomment-156553337>.

**Comment by vkarpov15** [comment]
That makes sense, will do that instead.
