### ISSUE TITLE
findOneAndUpdate doesn't work with QueryStream

### ISSUE THREAD

**Issue by gunar** [Automattic/mongoose#3584]
`findOneAndUpdate` doesn't update the doc when called with `.stream()`  -- although it does return a doc.

e.g.

```js
var now = new Date();
var interval = now.setMinutes(now.getMinutes() - MINIMUM_INTERVAL_MINS);
var query = { $or: [
  { 'lastCrawl.date': { $lt: interval } },
  { 'lastCrawl.date': { $eq: null } }
] };

var update = { $set : { 'lastCrawl.date' : new Date() } };
var options = {
  sort: { 'lastCrawl.date' : 1 },
  new: true
};

var stream = User.findOneAndUpdate(query, update, options).stream();
stream.on('data', function (doc) {
  // here, doc wasn't updated, and neither the one in the database
  console.log('This doc has not been updated:', doc.lastCrawl.date);
});
```
This works though:
```js
User.findOneAndUpdate(query, update, options).exec().then(function (doc) { console.log('Updated doc:', doc.lastCrawl.date); });
```

I'm running Mongoose 4.2.3 and Node v5.0.0.

Thank you all for your time and for the awesome piece of software that Mongoose is ;-)

**Comment by vkarpov15** [comment]
`.stream()` converts the operation to a `.find()`. `User.findOneAndUpdate(query, update, options).stream();` is the same as `User.find(query).stream();`. There isn't much point to streaming for `findOneAndUpdate()`, because, like the name implies, it only finds one document, and the mongodb server doesn't support streaming at a finer granularity than a single document.

**Comment by gunar** [comment]
@vkarpov15 thank you!
