### ISSUE TITLE
why connect() does not return a promise ?

### ISSUE THREAD

**Issue by davibe** [Automattic/mongoose#3622]
Since most of the api is promised, i was wondering why connect() function is not.

It looks bad (example: https://gist.github.com/davibe/8986a865a96005fa2467)

**Comment by vkarpov15** [comment]
You're right, worth adding this.

**Comment by davibe** [comment]
probably same as disconnect()

**Comment by Jokero** [comment]
+1

**Comment by xpepermint** [comment]
+1

**Comment by bsonntag** [comment]
+1

**Comment by Jokero** [comment]
@vkarpov15 How to handle `mongoose.connect()` error in catch handler? I want to use application initialization chain but can't do that because `mongoose.connect()` does not return rejected promise.
It returns rejected promise only if I specify callback, but it's not a good solution.

Example:
```js
mongoose.connect('mongodb://127.0.0.2/test')
    .then(() => {
        return server.start();
    })
    .catch(err => { // <---- we will not be here...
        console.error('App starting error:', err.stack);
        process.exit(1);
    });
```

Workaround:
```js
mongoose.connect('mongodb://127.0.0.2/test', function() { /* dummy function */ })
    .then(() => {
        return server.start();
    })
    .catch(err => { // mongoose connection error will be handled here
        console.error('App starting error:', err.stack);
        process.exit(1);
    });
```

**Comment by vkarpov15** [comment]
@Jokero that's odd. Can you open up a separate issue for this?
