### ISSUE TITLE
Remove timestamp from mongoose options

### ISSUE THREAD

**Issue by yordis** [Automattic/mongoose#3649]
Use the approach of plugins and create a repository for this functionality.

**Comment by vkarpov15** [comment]
Thanks for the suggestion, I've been thinking about this myself. Should probably be a plugin.

**Comment by yordis** [comment]
@vkarpov15 I think is a good idea even create two plugins for this. One for createdAt and the other for the updatedAt. This way we plug in just the necessary plugin.

**Comment by vkarpov15** [comment]
You're right. In hindsight, adding this into core mongoose was a little shortsighted since it's really easy to add as a plugin. The reason why we added it was that this was a commonly requested feature and putting it as a plugin is a bit of a barrier to entry since many users don't really understand how to use plugins, but we should just work on making plugins more accessible.

**Comment by yordis** [comment]
@vkarpov15 yeah, at this point I support the idea of them having question and helping the community to understand the tech instead of create shortcuts for them :smile:

**Comment by simnare** [comment]
@yordis i think single plugins is enough, simple config option to disable updated timestamp is a better approach imho

**Comment by yordis** [comment]
@simnare which ever is the case it's fine as long as we created a package for those things

**Comment by vkarpov15** [comment]
I'm going to close this. Timestamps is sufficiently useful to keep in Mongoose core for the foreseeable future.
