### ISSUE TITLE
get installed mongodb version from mongoose

### ISSUE THREAD

**Issue by aakrem** [Automattic/mongoose#3654]
After taking a look on the links below it seems that the solution is outdated. 
`node-mongodb-native` is not available even in `package.json`
So anyone has a solution to get the installed mongodb version from mongoose ? 
http://stackoverflow.com/questions/15311305/how-to-get-mongodb-version-from-mongoose
http://mongoosejs.com/docs/api.html#index_Mongoose-mongo
https://github.com/Automattic/mongoose/blob/master/package.json

**Comment by vkarpov15** [comment]
The solutions aren't outdated. `node-mongodb-native` isn't in the `package.json` because `node-mongodb-native` is the github repo name, the npm package is [mongodb](http://npmjs.org/package/mongodb).

Here's what mongoose uses internally to determine the version of the mongodb instance its talking to.

```javascript
  mongoose.connection.on('open', function() {
    var admin = mongoose.connection.db.admin();
    admin.serverStatus(function(err, info) {
      if (err) return cb(err);
      var version = info.version.split('.').map(function(n) { return parseInt(n, 10); });
      cb(null, version);
    });
  });
```

**Comment by ulrichb** [comment]
@aakrem You can also use `serverInfo()` which has a `version` string property.

```JS
console.log((await mongoose.connection.db.admin().serverInfo()).version);
```
