### ISSUE TITLE
Casting objectId on match aggregation

### ISSUE THREAD

**Issue by santimacia** [Automattic/mongoose#3742]
I don't know if is a bug or just normal behavior but I just want to let it know. If I do a .match with a objectId of type string for example '565ddabc2e1b9f7b23059a52' the return is empty array. 

Should it cast to a objectId automatically or not?

what I do tho solve the "problem" is:

```
ExampleModel.aggregate().match({
        _id: mongoose.Types.ObjectId('someId')
    })
```

**Comment by vkarpov15** [comment]
No this is expected behavior. Mongoose doesn't do any casting on aggregation pipelines because the aggregation framework can change the schema of the documents. We could do things like cast `match` stages if they're the first stage in the pipeline, but that's bound to be more confusing than helpful.
