### ISSUE TITLE
new populate needs explicit specification of the model

### ISSUE THREAD

**Issue by nschloe** [Automattic/mongoose#3748]
In the most recent version 4.3.5, a fix for the population has been added (cf. issue #3734). The removes the need for us to call `execPopulate()`. Yeay!

However, the syntax has now changed. It used to be
```js
discussion.populate('author');
discussion.execPopulate();
```
and now is
```js
yield mongoose.model('Discussion').populate(discussion, 'author');
```
when it could be
```js
yield discussion.populate('author');
```
Check out [the corresponding test](https://github.com/Automattic/mongoose/blob/bc8bdfce42de1e46953ba07c08a24f97f8edd014/test/promise_provider.test.js#L329). Not sure why one now needs to explicitly specify the model. Might this be an oversight?

**Comment by vkarpov15** [comment]
It doesn't necessarily remove the need to call `execPopulate()`. The syntax hasn't changed at all, the first way you specified works just fine in 4.3.5. Mongoose supports numerous different ways to `populate()`, one of which is calling `MyModel.populate()`. This approach isn't commonly used, which is why it silently returned the wrong promise type and nobody noticed for a while :)
