### ISSUE TITLE
rewire()-ing static model methods

### ISSUE THREAD

**Issue by JaycobA** [Automattic/mongoose#3769]
Hi,

I'm trying to use rewire to mock a service used in an appended static model-method, but it seems not to be working. 

I'm basically doing this:

``` javascript
// ... model init stuff
var fooService = require('fooService');

fooModel.statics.foo = function() {
  fooService.doSomeFoo();
}
```

and then in the test

``` javascript
var fooModel = rewire('fooModel');
var fooServiceMock;

beforeEach(function() {
  fooServiceMock = jasmine.createSpyObj('fooService', ['doSomeFoo']);
  fooService.__set__('fooService', fooServiceMock);
});

it('works', function() {
  fooModel.foo();
  expect(fooServiceMock.doSomeFoo).toHaveBeenCalled();
});
```

I would expect this to work. However, the original Service is still called, when debugging I can see that fooService is still the original in the static foo()-method. Is there some kind of context switch happening with appended model methods that I am not aware of? If so, is there a way to circumvent it? Not being able to mock the content of these model-methods would be quite a blow to their usefulness.

Any help very much appreciated.

**Comment by vkarpov15** [comment]
A few questions:

1) What is fooService?
2) What does your schema look like?
3) Are you defining the `foo` function directly on the model or on the schema? The former is not supported.

Also, minor pedantic point: using rewire for testing is a really dirty hack. If you're going to stub things out for unit tests, I would recommend using proper dependency injection rather than monkey-patching.
