### ISSUE TITLE
No matching document found. Mongoose

### ISSUE THREAD

**Issue by nairicode** [Automattic/mongoose#3772]
process.nextTick(function() { throw err; });
                                                        ^
VersionError: No matching document found.

------------------------------------------------------------------------
When you are doing a lot of queries
and when you need to do a lot of changes in the DB
bring such

It did not seem to have time

how can I fix INTO could do a lot of requests for DB

**Comment by vkarpov15** [comment]
Please provide code example that reproduces this issue.

**Comment by nairicode** [comment]
var n= req.body.n;
		var my= req.body.my._id;

		User.findOne({ _id: my}, function (err, doc){
			doc.ar.splice(n, 1);
			doc.save(function(err, doc){
				if(err)
					throw err;
				res.json(doc);
			});
		});

**Comment by vkarpov15** [comment]
If you have multiple requests in parallel, `.splice()` isn't safe because the doc in the database might not have the same doc in the same position: http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html . The above issue is most likely triggered because you're splicing the same user doc multiple times at the same time (duplicate request?).

The best workaround is to explicitly `$pull` yourself, but specify the `_id` of the subdoc you want to remove rather than the index, because removing elements by array index in a distributed system can have unintended consequences. Here's how you might `$pull`:

```javascript
User.update({ _id: my }, { $pull: { ar: { _id: req.body.subdocId } } }, function(error, doc) {
  // ...
});
```
