### ISSUE TITLE
[question] prevent duplicates with unique index or check before save to db?

### ISSUE THREAD

**Issue by creeperyang** [Automattic/mongoose#3778]
I have a schema as below:

```js
// ...
    mobile: {
        type: String,
        required: true,
        unique: true
    }
// ...
```

I want to know does `mongoose` will always **search db** to ensure `mobile` field unique before save or make a **unique index**? And do I need any validate/check code to ensure unique myself ( *I think it's waste* )?

I'm not sure it's appropriate to ask question here, but any help will be appreciated :smile:

**Comment by vkarpov15** [comment]
`unique: true` does nothing other than create a unique index. Mongoose will **not** search the db itself. The only thing I would recommend doing is setting [the `emitIndexErrors` schema property to true](http://mongoosejs.com/docs/guide.html#emitIndexErrors) to make sure you get a loud error if the mongoose index build fails, because you might still get duplicates if the unique index isn't created on the mongodb side. The `emitIndexErrors` behavior will probably be the default in 5.0, but for backwards compat it's off by default.

**Comment by filipecatraia** [comment]
Hi @vkarpov15, I know this is old news, but as a newcomer from PG, the property being called `unique` is really confusing. I get it, the first time you bump into the issue you learn it and it will never happen again. But given the recent breaking changes when moving to `5.x`, why not rename it to, e.g., `createUniqueIndex`? It's explicit and doesn't make people think it applies a uniqueness validation :)

**Comment by vkarpov15** [comment]
We've thought about renaming it. But it would break too many people's code and break the convention that index options are schema type options.
