### ISSUE TITLE
Validator swallows bad data for field of type array with default

### ISSUE THREAD

**Issue by sedge** [Automattic/mongoose#3785]
**Mongoose**: v3.8
**Node**: v4.2 LTS
**MongoDB**: v2.6.5

This is an approximation of my use case, boiled down into a working example of the bug:

``` js
var mongoose = require('mongoose');

var internalSchema = new mongoose.Schema({
  innerString: { type: String, required: true },
  innerNumber: { type: Number, required: true }
}, { id: false, _id: false });
var internalModel = mongoose.model('InternalModel', internalSchema);

var testSchema = new mongoose.Schema({
  outerString: { type: String, required: true },
  outerNumber: { type: Number, required: true },
  outerArray: { type: [internalModel], model: internalModel, default: [] }
});
var testModel = mongoose.model('TestModel', testSchema);

var instance = new testModel({ 
  outerString: 'foo',
  outerNumber: 1,
  outerArray: { // Note that this isn't an array
    whiz: 'bang'
  }
});

instance.validate(function(error) {
  console.log(error); // Undefined, should complain about the object
  console.log(instance.outerArray); // [ ]
});
```

**Comment by vkarpov15** [comment]
So this was fixed for 4.0.0, see #2592 . It's a fix that I'm hesitant to backport to 3.8.x because not validating if you're setting an object field to a string or an array field is a quirk that's been part of mongoose since the beginning. Is there something blocking you from upgrading that I can help with?

**Comment by sedge** [comment]
@vkarpov15 Thanks for the offer. I'm investigating the complexity of upgrading my project to use v4 as we speak, so I'll follow up. I filed the issue mainly to get it some visibility. If it's a `wontfix` I'll understand :smile:

**Comment by vkarpov15** [comment]
The [migration guide](http://mongoosejs.com/docs/migration.html) and [4.0 release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) should be helpful. The fix is fairly straightforward to backport but I'm hesitant to do so unless there's a good reason, because inevitably this behavior change will break somebody's code.
