### ISSUE TITLE
Use Number.isNaN() instead of global isNaN

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3868]
Re: #3832

**Comment by alexkavon** [comment]
I don't think this is backwards breaking. It just needs some love and improvement inside the if (util.isNaN(val)) statement for how the replacement isNaN works.

**Comment by vkarpov15** [comment]
If we don't change the behavior, there's little point to preferring `Number.isNaN` over `isNaN`, no?

**Comment by alexkavon** [comment]
I guess. You could argue that with any improvement to software though. The point of a discussion about improving code isn't to argue for why we shouldn't improve something, but instead argue for it and discuss how to make it work. Since there doesn't seem to be any interest in making this work, but rather push back. I've no interest in continuing to contribute.

**Comment by vkarpov15** [comment]
That's a shame, sorry you feel that way.

**Comment by alexkavon** [comment]
It has nothing to do with the way I feel, and everything to do with trying to move this forward with nothing but push back due to lack of understanding and concern.

**Comment by vkarpov15** [comment]
Upon further inspection the way mongoose uses `isNaN()` is correct and using `Number.isNaN()` would just add more boilerplate for us. `isNaN()` coerces the value to a number before checking for NaN, which is right for us.
