### ISSUE TITLE
Document how to pass a user selected promise lib to the underlying native mongo client

### ISSUE THREAD

**Issue by toddbluhm** [Automattic/mongoose#3869]
When using the native mongo client you can pass in the option `promiseLibrary` as a connection option. 

Because mongoose does not use the `MongoClient.connect` method, the location in the native mongo docs is not accurate for mongoose. The `promiseLibrary` option within the native driver eventually ends up as a db option. So in mongoose in order to pass in the `promiseLibrary` option you want to pass it in the `db` option.

```js
mongoose.connect('...', {
  db: {
    promiseLibrary: require('bluebird')
  }
});
```

It would be great if this was documented in the mongoose docs more clearly or better yet, whatever the mongoose promise lib was set too, just automatically passed that to the native client.

**Comment by vkarpov15** [comment]
It's really tricky to pass the promise library along to the mongodb driver, because the driver keeps track of promise libraries at the db level as opposed to globally. However, in the next release, you'll be able to pass `promiseLibrary` to `mongoose.connect()` and `mongoose.createConnection()` as [you do for the mongodb driver](http://mongodb.github.io/node-mongodb-native/2.1/api/MongoClient.html)

**Comment by andrewaustin** [comment]
Should http://mongoosejs.com/docs/connections.html also list ```promiseLibrary``` as an accepted parameter?
