### ISSUE TITLE
document.set() resets single subdocument fields

### ISSUE THREAD

**Issue by andrenarchy** [Automattic/mongoose#3875]
The problem can be reproduced with the following code:

```javascript
var accountSchema = new mongoose.Schema({
  email: String,
  active: {type: Boolean, default: false}
});
var personSchema = new mongoose.Schema({
  name: String,
  age: Number,
  account: accountSchema
});
mongoose.model('Person', personSchema);
mongoose.model('Person').create({
  name: 'leia',
  age: 55,
  account: {
    email: 'leia@theforce.org',
    active: true
  }
}, function (err, person) {
  console.log(person);
  person.set({
    name: 'luke', 
    account: {
      email: 'luke@theforce.org'
    }
  });
  console.log(person);
});
```
The output is
```javascript
{ _id: 56bcb24fb9a1062d27f0265d,
  account: { active: true, email: 'leia@theforce.org' },
  age: 55,
  name: 'leia',
  __v: 0 }
{ _id: 56bcb24fb9a1062d27f0265d,
  account: { active: false, email: 'luke@theforce.org' },
  age: 55,
  name: 'luke',
  __v: 0 }
```

Note that `active` is surprisingly set to false although we didn't touch it.

**Comment by vkarpov15** [comment]
Expected behavior, because the above `set()` says to set the `account` field to `{ email: 'luke@theforce.org' }`, so you are implicitly touching the `account.active` field because you're overwriting `account` as a whole. IMO this is the right design choice, because that's similar to how the MongoDB $set operation works. If you just want to change `account.email` without changing `account` as a whole, just do this:

```javascript
  person.set({
    name: 'luke', 
    'account.email': 'luke@theforce.org'
  });
```

Then `active` won't be affected.
