### ISSUE TITLE
Update/$set filters out non-strict, deeply nested content

### ISSUE THREAD

**Issue by spamguy** [Automattic/mongoose#3883]
[Assume a schema called 'Season' with an array 'regions'. 'regions' is made up of the subschema 'Order', which is not strictly structured.](https://github.com/spamguy/diplomacy/blob/master/server/models/season.js) My goal is to select and revise an Order item with arbitrary, deeply nested content.

Let's assume there is a document that looks like `{ regions: [{ r: 'CON' }] }`. Using MongoDB directly, this query results in `{ r: 'CON', unit: { order: { action: 'hold' } } }` as expected:
```
db.seasons.findAndModify({ 'regions.r': 'CON', _id: ObjectId("55e9f39e631812241bb7f579") },
{ '$set': { 'regions.$.unit': { order: { action: 'hold' } } } }, { new: true, upsert: false, remove: false }
```

Dropping the query into a Mongoose command and running it filters the deeply nested stuff out. That is, running
```
mongoose.model('Season').findOneAndUpdate({
        _id: ObjectId("55e9f39e631812241bb7f579"),
        'regions.r': 'CON'
    }, {
        $set: {
            'regions.$.unit': {
                order: {
                    action: 'hold'
                }
            }
        }
    }, { new: true }, cb);
```
results in this query printed in debug:
```
seasons.findAndModify({ 'regions.r': 'CON', _id: ObjectId("55e9f39e631812241bb7f579") }) [] { '$setOnInsert': { createdAt: new Date("Mon, 15 Feb 2016 20:52:40 GMT") }, '$set': { updatedAt: new Date("Mon, 15 Feb 2016 20:52:40 GMT") } } { new: true, upsert: false, remove: false }
```

Notice the total absence of regions.$.unit and everything therein.

Was running 4.3.6, upgraded to 4.4.3 just now, no difference.

**Comment by vkarpov15** [comment]
As a workaround, you can just set `strict: false` as an option to `findOneAndUpdate()`. Will work on a better fix.

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior atm, we actually have tests in place for this somewhat indirectly: https://github.com/Automattic/mongoose/blob/24e79898fdab69206ffe0a15b0d95ae94cfd4d78/test/model.update.test.js#L348-L370. The assumption right now is that, as far as `update()` and `findOneAndUpdate()` are concerned, the top-level schema's strict mode determines how casting works. This behavior is pretty counterintuitive, however, changing it would be backwards breaking. In the next release there will be a `useNestedStrict` option that you can set on schemas to overwrite this behavior. I suspect in 5.0 we'll remove `useNestedStrict` and just always set it to true.
