### ISSUE TITLE
alias Query#eq to Query#equals

### ISSUE THREAD

**Issue by Fonger** [Automattic/mongoose#3953]
```js
// find users of which number is not 5
let users = yield User.find().where('number').ne(5).exec();

// find users of which number is 5
let users = yield User.find().where('number').equals(5).exec();
```

I have a question that why `Query#eq` is not implemented?
`ne` stands for `not equals to`, so I think `eq` should be `equals to` by intuition.

```js
// doesn't work
let users = yield User.find().where('number').eq(5).exec();
```

I get the following error
` "User.find(...).where(...).eq is not a function"`

I suggest make `eq` alias of `equals`.

**Comment by sarslanhan** [comment]
hey @vkarpov15 and other contributors, i want to start contributing to the project. i picked this issue to address first since it is relatively small. however while analyzing the codebase, i noticed that this issue might be more related to mquery repo. so, should i move this issue to mquery repository or is there any other way you could think of to do this in mongoose? if can you point me to the right direction here, it would be great. thanks

**Comment by vkarpov15** [comment]
@sarslanhan sorry for the delay. You're right, the correct place to fix this issue would be in the mquery repo and then bump the mquery version in mongoose
