### ISSUE TITLE
`bulkWrite()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3998]
https://docs.mongodb.org/manual/core/bulk-write-operations/

**Comment by iliakan** [comment]
Right now I tried to do like this:
```js
User.collection.bulkWrite(commands, function() {
    console.log(arguments);
 });
```
The function is never called, looks like the operation does not execute either. 
Is that ok for the current state of mongoose development?

P.S. mongoose 4.5.0

**Comment by vkarpov15** [comment]
Nope, that's not expected. Can you show me a more complete code sample?

**Comment by iliakan** [comment]
@vkarpov15 I'm sorry I deleted that comment, was totally my fault.

**Comment by kpman** [comment]
Can I use `bulkWrite` in mongoose now?
The following is my code:
```
User.collection.bulkWrite(bulkWriteOperation, (err, result) => {
  if (err) throw err;
  console.log(result);
});
```

The operation executed successfully and the data are updated, but I can get any result from the callback function.

Do you have any idea? Thanks.

**Comment by JJPandari** [comment]
@kpman I used Model.collection.bulkWrite as described [here](http://stackoverflow.com/a/35210361/4788022) and I got result.matchedCount and result.modifiedCount as expected(and also other properties as I debugged). You may wanna check the *native node-mongo driver docs* since Model.collection gets the native driver model object according to the SO answer above.

**Comment by kpman** [comment]
@JJPandari Thank you for the reply so much, it is really helpful for me.
Besides, after Mongoose upgrade to v4.0, the `insertMany` API is useful. And I just want to know can I use `bulkWrite ` in the future?
Because I need to get the insert, update or even upsert result after the bulkWrite exec rather than just got the number count.
Most important of all, mongoose return `Promise` after call `insertMany` API.

**Comment by JJPandari** [comment]
@kpman First question is up to mongoose's maintainers. And `bulkWrite` with node-mongo native driver works so you can use it if missing the model validations mongoose provides is tolerable for you.  
I assume by "result" you mean the document(s) after the update? I don't think it's really required since you can make sure the update succeeds with `modifiedCount` and assemble the new document(s) by combining the old-version document with the updated fields/values(and not `find`ing from the db again).
