### ISSUE TITLE
Dates in embedded schemas not converted to strings in toJSON

### ISSUE THREAD

**Issue by boucher** [Automattic/mongoose#4016]
I have a schema that contains an array of objects (with their own schema). Calling toJSON on a document from the collection converts top level dates to strings (as desired), but dates inside the array are left as ISODate objects.

**Comment by vkarpov15** [comment]
Hmm calling `toJSON()` looks like it **never** convert dates to strings as far as I know, see the below script.

```javascript
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4016');
mongoose.set('debug', true);

var childSchema = new Schema({
  born: Date
});   

var parentSchema = new Schema({
  children: [childSchema],
  born: Date
});   

var Parent = mongoose.model('gh4016', parentSchema);

var doc = { born: '1954-12-20', children: [{ born: '1988-10-31' }] }; 
Parent.create(doc, function(error, doc) {
  console.log(doc.toJSON().born instanceof Date);
  console.log(doc.toJSON().children[0].born instanceof Date);
});
```

Logs out true for both cases for me. Doesn't make much difference, since `JSON.stringify()` will properly convert dates to strings for you anyway. Can you modify the above script to reproduce the behavior you're seeing?

**Comment by vkarpov15** [comment]
Issue's gone stale, closing.
