### ISSUE TITLE
Returning mongoose Query object from within a promise

### ISSUE THREAD

**Issue by azhang** [Automattic/mongoose#4033]
I'd like to return a query object from a promise (so I can reuse it with different chained methods), but since the query object is a thenable, it'll always resolve before I get there. Any way to work around this?

**Comment by vkarpov15** [comment]
You can always just wrap the query in an object, like `return { q: query }`

**Comment by azhang** [comment]
What was the reasoning for putting .exec() thenable functionality into the Query itself? It seems redundant and confusing to make Query a thenable and have .exec(), when both behave the same when used with promises.

**Comment by vkarpov15** [comment]
The reason was so you could do `yield MyModel.findOne()` when using co, without needing the extra `.exec()`, because that's a much more common use case than returning a query from a promise AFAIK.

Also, [they don't behave _exactly_ the same](http://mongoosejs.com/docs/promises.html). You can't `.catch()` on a query, for instance.
