### ISSUE TITLE
plugins.mongoosejs.io header redirects to mongoose.com

### ISSUE THREAD

**Issue by znja** [Automattic/mongoose#4088]
I don't know where to put this so i'm creating an issue here. If it belongs somewhere else please point me to the right place.
The Header at http://plugins.mongoosejs.io/ redirects to `mongoose.com` instead to `mongoosejs.com`

**Comment by vkarpov15** [comment]
Fixed in https://github.com/vkarpov15/mongooseplugins/commit/a4528410448a202a2d066e8ccc69d6d60bf5d426. For future reference you can open issues with that site in https://github.com/vkarpov15/mongooseplugins .

I opened up https://github.com/vkarpov15/mongooseplugins/issues/16 so that link will be easier to find.
