### ISSUE TITLE
Merge options rather than replacing for toObject

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#4131]
#4097

**Comment by wlingke** [comment]
@vkarpov15 - need some help with this one.

Please see my repo: https://github.com/wlingke/mongoose/tree/5.0-merge-%24toObject

This problem happens when we think about how Child Schemas play into this. My implementation fails a number of tests (`npm test -- -g 'toObject'`) because it merges the Parent Schema's options and overrides the Child's options.

Here's what happens:
- Suppose Parent and Child each have their own `schema.options.toObject`
- A Parent document calls `toObject({...something})`
- the `{...something}` is merged with the Parent's `schema.options.toObject`.
- in Document.js `$toObject` method, we ultimately call `utils.clone(this, options)` which then through some helpers, recursively calls `toObject(options)` for the Child sub-document.
- Now the child schema has an input `options` that includes the merged properties from Parent.

One solution here would be to modify `utils.clone`, `cloneArray` and `cloneObject` methods, allowing us to pass in `utils.clone(this, options, originalOptions)`

Another solution could be to pass in the original input options via a property `_original` on the `options` object so we can avoid changing the utils.

Let me know your thoughts on this.

**Comment by vkarpov15** [comment]
Thanks for the detailed analysis @wlingke . I ended up taking a midway approach between your two approaches and passing down a slightly modified options object to `clone()`, taking into account the quirks of `minimize`. Now that `retainKeyOrder` is gone in 5.0, `utils.clone()` options get passed transparently to `toObject()`.
