### ISSUE TITLE
speed up tests and make test output more clear 

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#4153]
I have an idea to speed up the test suite ("npm test"). One way to speed it up would be to allow each separate file to run concurrently by having each separate file work with a different mongo db.

is there any interest in speeding up the tests and getting the test output to more clear? Right now it just prints out a bunch of dots and I don't know what that means.

Let me know thanks!

**Comment by vkarpov15** [comment]
We use mochas dot reporter because there's a lot of tests and that makes it easier to see all the results. If you want to use a different reporter, just run `npm test -- -R spec` to use mochas spec reporter. Re: speed, the entire test site runs in about 10 seconds on my machine, so long as i don't use wiredtiger, plenty fast, especially since I usually only run a small subset of the tests while developing anyway. Are you trying to run the tests with WT?

**Comment by Jeff-Lewis** [comment]
@vkarpov15 WT is slower when running the mongoose tests? Interesting... do know what that is?

**Comment by vkarpov15** [comment]
Thread contention because mongoose tests open a lot of connections. WT generally struggles when you have thousands of connections open, which is why we're working on reducing the number of connections the tests use

**Comment by ORESoftware** [comment]
What is WT?

**Comment by vkarpov15** [comment]
WiredTiger, the default storage engine for the mongodb server in 3.2
