### ISSUE TITLE
How to populate an array of ObjectIds and return null if the object is deleted?

### ISSUE THREAD

**Issue by timeswind** [Automattic/mongoose#4161]
for example, I have an array of objectids which contains 5 objectids linking to another collection,
and one of the object is deleted, so the populate method only return an array only contains 4 object, for some reason I need to make the populated results remains the same length as the objectids array, just thinking is there any way to make populate method return null for deleted object?

**Comment by vkarpov15** [comment]
Nope there isn't atm

**Comment by agnjunio** [comment]
Damn I need this feature too. 
I have this:
```json
"teams" : [ 
        ObjectId("57582db89979b7cd6b1d17d8"), 
        ObjectId("5758607f4e7e20d07f7025bc"), 
        ObjectId("5758655d177fde1e03661cd3"), 
        ObjectId("57587fae217df32008e783d8"), 
        ObjectId("5759c043675a7844288ff8dd"), 
        ObjectId("5759c0fc675a7844288ff8e3"), 
        ObjectId("5759c40a99ba26a729c32b34"), 
        ObjectId("5759c52a99ba26a729c32b3a"), 
        null, 
        null, 
        ObjectId("5759be8c9d0446d5274cf1ba"), 
        null, 
        null, 
        ObjectId("5759c653e738e76c2beb3a78"), 
        null, 
        null
    ],
```
And I need to bring the nulls to the populated version.

**Comment by vkarpov15** [comment]
@agnjunio can you please clarify what you're trying to do?

**Comment by agnjunio** [comment]
So, basically this is a tournament bracket. Each team is registered on position, which is relative to the position in the array. If there are no teams registered in given position, then the most logic return should be null.
However, since the returned array ignores those null slots, I can`t organize my championship bracket using array index, but instead by creating a mixed type with the seed and the document reference.

**Comment by vkarpov15** [comment]
Yeah that's something that I never tried modeling in mongoose. The way I'd do it is I'd instead store an array like this:

```javascript
var tournamentSchema = new Schema({
  teams: [{ team: { type: Object, ref: 'Team' }, seed: Number }]
});
```

That way populate can do its magic.

**Comment by agnjunio** [comment]
Still is a pain to have all my arrays like this. Cause I'll have to create an index field everytime I use an array reference where the position matters.
Ex.: My Match model was like this 

```javascript
var GameSchema = new Schema({
	number: Number,
	teams: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Team' }],
	matchCode: String,
	points: [Number]
});
```

Instead of just using team[0] and team[1] I'll have to use team1 and team2 field which is ugly, or the solution you mentioned.
Since Mongo itself supports nulls in array, I can't see why mongoose shouldn't support them as well (or have an option to make it available)

**Comment by vkarpov15** [comment]
We support it, just populate specifically ignores null refs, and that's a pretty fundamental consideration of how populate works that's really difficult to dig out
