### ISSUE TITLE
schema.pre('save') not triggered by MyModel.update()

### ISSUE THREAD

**Issue by Hamms** [Automattic/mongoose#419]
example.js:

``` javascript
var mongoose = require('mongoose')
  , Schema = mongoose.Schema

mongoose.connect('mongodb://localhost/test')

var Thing = new Schema({
  title : String,
  content : String
})

Thing.pre('save', function(next){
  console.log("saving: %s (%s)", this.title, this.content)
  next()
})

var MyThing = mongoose.model('Thing', Thing)

var example = new MyThing({
  title : 'foo',
  content : 'bar'
})

example.save(function(err){
  MyThing.update({title:'foo'},{content:'baz'}, function(err, rs){
    console.log(rs)
  })  
})
```

Output:

```
$ node example.js 
saving: foo (bar)
1
```

The pre is triggered by the initial save, but not the update.

**Comment by changfuguo** [comment]
> i ama aa

**Comment by changfuguo** [comment]
* aa
* aa

**Comment by changfuguo** [comment]
#3144 
#我们今天去干嘛呢

**Comment by r3wt** [comment]
This is fucking bullshit. we can't do anything async in setters. idiots.

**Comment by trentmillar** [comment]
this is a really old thread but ok. There are pre's that actually inturup this or it has been figured out since the post.

**Comment by r3wt** [comment]
It's all good trent, i went ahead and reorganized my code to make a findById and then a subsequent save, so the pre save hook to salt a password still works. I guess it is what it is, though it would be nice to have a pre update hook as well, it still will take two queries to service the operation since you must read data and check if it has changed any way with isModifed

**Comment by martindale** [comment]
Tagging #964 and bumping for interest.
