### ISSUE TITLE
InsertMany not returning a promise anymore

### ISSUE THREAD

**Issue by jakesjews** [Automattic/mongoose#4237]
InsertMany isn't returning a promise anymore after upgrading from version 4.4.20 to 4.5.0. It looks like it may have been caused by [wrapping the method with kareem](https://github.com/Automattic/mongoose/commit/6ddccacf794e7b766d0091ff92a9e6a85d1f4be3). 

Heres an example of failing test. I'm not quite sure how to go about fixing the issue while preserving the new hooks.
```
    it('insertMany() returns a promise', function(done) {
      var schema = new Schema({
        name: String
      }, { timestamps: true });
      var Movie = db.model('promiseModel', schema);

      var arr = [{ name: 'Star Wars' }, { name: 'The Empire Strikes Back' }];
      Movie.insertMany(arr).then(function(docs) {
        assert.equal(docs.length, 2);
        return Movie.find({})
      }).then(function(docs) {
          assert.equal(docs.length, 2);
          done();
      }).catch(done);
    });
```

**Comment by vkarpov15** [comment]
Well that's embarrassing. Good catch 👍

**Comment by cikpis** [comment]
Confirm what @jakesjews said. Seems we are getting an undefined object.

**Comment by sjorssnoeren** [comment]
While this solves the problem of not being able to use promises. It became required to use promises. I like to use promises and would always try to do so, however when using a promise, you cannot throw multiple errors. It became therefore unavailable to insertMany while stacking up the errors but continue trying for other models.

I'd like to be able to continue inserting after finding a invalid model. Much like how the option: `ordered: false` is described over at MongoDB for node.js. This would be possible by using the callback functionality and wrapping it in a promise after completing either with error or docs. However when using callback, it throws an unhandled rejection error (caused by not using the returned promise).

For me it's not a problem if it rejects after all inserts have been done with the first error if one has occurred. This seems to be expected behavior or using insertMany promised.

If there's anything I can help with to make it to work like that, please let me know.
