### ISSUE TITLE
Why do array sub documents get `_id` by default and object sub documents don't?

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4308]
Say I have a product schema with a nested color sub document which references a color and implements denormalization for the name:

```js
let ProductSchema = new Schema({
  name: String,
  color: {
    id: {
      type: Schema.Types.ObjectId,
      ref: 'Color',
    },
    name: String,
  },
};
```

This does not automatically get an `_id` field and works as expected.

However, when I create an array of sub documents, e.g.:

```js
let SuggestionSchema = new Schema({
  name: String,
  products: [{
    id: {
      type: Schema.Types.ObjectId,
      ref: 'Product',
    },
    name: String,
    color: {
      id: {
        type: Schema.Types.ObjectId,
        ref: 'Color',
      },
      name: String,
    },
  }],
});
```

These *do* get `_id`'s automatically appended. Why this discrepancy, is there a reason behind it?

I know I can disable it by defining a sub schema and specifying `_id: false`, but I don't understand why it's false by default when nesting just a single document, but not when nesting an array of sub documents. Isn't the most common use case to *not* need the `_id`'s?

**Comment by vkarpov15** [comment]
Because `new Schema({ products: [{ name: String }] });` is the same thing as `new Schema({ products: [new Schema({ name: String })] });`: both generate a 'products' property that's a mongoose [document array](http://mongoosejs.com/docs/subdocs.html), which have several helper functions that rely heavily on the subdocs having an `_id` field. A nested subdoc doesn't have these helpers.

**Comment by adambuczynski** [comment]
Ok thanks
