### ISSUE TITLE
How do i $set and $push in one update Mongoose?

### ISSUE THREAD

**Issue by kacak9229** [Automattic/mongoose#4338]
Im trying to $push and $set at the same time, $push is working just fine, when it comes to $set, it spits some error

> MongoError: The positional operator did not find the match needed from the query. Unexpanded update: files.$.name

Here's the code

```
 Course.update(
                  {
                    _id: req.body.courseId,
                    'files.fileUrl': { $ne: url }
                  },
                  {
                    $push: { files: { fileUrl: url } },
                    $set: {'files.$.name': file.name},
                  }, function(err, count) {
                    if (err) return next(err);
                    console.log("Successfully saved")
                });
```
and the ORM model, Im using mongoose

```
var CourseSchema = new Schema({

  files: [{
    fileUrl: String,
    name: { type: String, default: 'File name'}
  }],

});
```
Any help would be appreciated Thanks

**Comment by vkarpov15** [comment]
You're getting this error because you can't [use negations with the positional operator unless you use `$elemMatch`](https://docs.mongodb.com/manual/reference/operator/update/positional/#negations). In other words, you need:

```javascript
Course.update(
                {
                  _id: c._id,
                  'files': { $elemMatch: { url: { $ne: url } } }
                },
                {
                  $push: { files: { fileUrl: url } },
                  $set: {'files.$.name': 'test2' },
                }, function(err, count) {
                });
```

However, this still won't work because you'll get a "Cannot update 'files' and 'files.0.name' at the same time" error. MongoDB won't let you use different operators on the same field in the same update.

**Comment by Arun101031** [comment]
f
