### ISSUE TITLE
virtual property on document condition

### ISSUE THREAD

**Issue by thatisuday** [Automattic/mongoose#4367]
Hi, I am using mongoose 4.5.3.

I am trying to get a virtual property based on a condition that if a nested property exists in the document. Like..

```
// virtual : profile pic url
userSchema.virtual('avatar').get(function(){
	if(this.hasOwnProperty('accountPics')){
		return this.accountPics.profile.dir + '/' + this.accountPics.profile.photoId+ '.sm.jpg';
	}

	return '/img/avatars/user-sm.png';
});
```

But this is not working out for me.

**Comment by vkarpov15** [comment]
Can you show me your schema and define what "not working out" means?

**Comment by thatisuday** [comment]
@vkarpov15 This is my schema

```
{
	...,
	accountPics : {
		profile : {
			photoId : String,
			dir : String,
			path : String
		},
		cover : {
			photoId : String,
			dir : String,
			path : String
		}
	},
}
```

**Comment by thatisuday** [comment]
now, inside a virtual get, if I check if nested property exists, using lodash

_.has(this, 'accountPics.profile.photoId') returns true even in document, `accountPics` or `accountPics.profile` is empty. I am sure I am missing something and there isn't something wrong with mongoose...

**Comment by vkarpov15** [comment]
`_.has()` checks if the property exists, which will always return true in mongoose because mongoose does `Object.defineProperty()` for every path in your schema on every doc. Basically, you should use `_.get(this, 'account.profile.photoId') != null` rather than `_.has(this, 'account.profile.photoId')`, because `_.has()` is a very specialized function that doesn't do what you're trying to do (check if there is a photo id). For example,

```javascript
var test = {};
Object.defineProperty(test, 'a', {});
// Prints 'undefined true'
console.log(test.a, _.has(test, 'a'));
```
