### ISSUE TITLE
`.stream()` and `.cursor()` return inconsistent stream implementations?

### ISSUE THREAD

**Issue by mreinstein** [Automattic/mongoose#4650]
In the docs http://mongoosejs.com/docs/api.html#query_Query-cursor

indicates `.cursor()` returns a nodejs streams3 compatible stream object, but

http://mongoosejs.com/docs/api.html#querystream_QueryStream
`.stream()` returns a nodejs "streams1" compatible stream object.

I'm just curious why they return such drastically different interfaces. Is this just a matter of one interface being a lot newer, and therefore using a more up to date streams version, or is there something at play under the hood?

**Comment by mreinstein** [comment]
maybe orthogonal to this, maybe not. I'm not sure what the differences are (if any) between `.stream()` and `.cursor()`. Apart from the exposed stream api differences are they doing the same thing under the hood? Are the more appropriate for different use cases? 

I'd be happy to send a PR to whatever mongoose doc repo is appropriate to clear up this info, just want to be sure I'm understanding things correctly.

**Comment by vkarpov15** [comment]
`.stream()` is deprecated and only there for backwards compatibility, you should use `.cursor()` unless you have old code that uses `.stream()` that isn't worth upgrading. It will no longer be there in 5.0.

Beside being compatible with the newer node streams, `.cursor()` also lets you use iterator-like semantics (calling `.next()` to get the next doc rather than listening for the next doc in `on('data')`) if the stream approach isn't right for you. Nowadays, with co/yield and async/await, the stream approach is of limited use

**Comment by vkarpov15** [comment]
See http://thecodebarbarian.com/cursors-in-mongoose-45.html for some more info on cursors

**Comment by sibelius** [comment]
Can I consome .cursor() using async iterators?

**Comment by vkarpov15** [comment]
@sibelius  I haven't tried using them with async iterators yet, but I think [the async iterator example I described here](http://thecodebarbarian.com/common-async-await-design-patterns-in-node.js.html#processing-a-mongodb-cursor) should work
