### ISSUE TITLE
mongoose.connect(uri, opts) does not return a promise

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#4659]
when passing two arguments to `mongoose.connect` and expecting a promise to be returned, there is simply no promise returned and an error is thrown

for example:

``` js
await mongoose.connect(config.mongodb, config.mongodbOptions);
```

will throw the error

```
TypeError: this.$opPromise.then is not a function
    at MongooseThenable.then (/Users/nexus/Public/crocodile/node_modules/mongoose/lib/index.js:785:26)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

but without the second argument, it does not throw the error

```
await mongoose.connect(config.mongodb);
```

works fine

cc @vkarpov15

**Comment by niftylettuce** [comment]
it looks like the alternate solution until this is fixed is to append the options to your URI such as

`mongodb://db1.example.net,db2.example.net:2500/?replicaSet=test&connectTimeoutMS=300000`

https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options

**Comment by niftylettuce** [comment]
Not sure how to pass `{ server: ... }` server options in a URI - I don't think this is possible?  Anyways another workaround is `await mongoose.connect(config.mongodb, config.mongodbOptions).then;` which seems to work OK.

**Comment by dmansfield** [comment]
This happened to me when two test cases each tried to `mongoose.connect(...)`.  The second time it failed with the same error as in the first comment.  The first connect was successful.  Just FYI, I am using bluebird's Promise by setting mongoose.Promise.

I've worked around by preventing "double connect" in this particular case, but in general I'm not sure what the solution is or why it's failing like this.

**Comment by dmansfield** [comment]
Actually, I think it's one tiny bit more complicated.  If you have:
```
mongoose.connection.on('error', err => { something(err); });
```
Then the failure to re-connect ("Trying to open unclosed connection.") does not throw, and in this scenario, `mongoose.connect` fails to return a valid promise or promise-like object.

Without the error handler installed, the second connect will throw, and so there is no return value.

**Comment by vkarpov15** [comment]
@niftylettuce can you provide a more thorough code sample and clarify which version of mongoose? I don't see any errors when I run:

```javascript

**Comment by niftylettuce** [comment]
@vkarpov15 you can see my issue here - https://github.com/crocodilejs/crocodile-node-mvc-framework/blob/development/src/helpers/mongoose.js - I have to add the `.then` otherwise it does not work and gives this error

**Comment by dmansfield** [comment]
The issue is that mongoose.connect() does not return a promise when there's an error. If there's no 'on error' handler, then the method will throw, which hides the bug.  If there's an error handler installed, it breaks. 

See this line as an example of incorrect return value:

https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L239

Here's a test case.

```
var mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
var url = 'mongodb://localhost/gh4659';

mongoose.connect(url)
    .then(() => {
        mongoose.connection.on('error', err => {
            console.log('mongoose connection error: '+err);
        });
        
        console.log('connected - attempting reconnect');
        return mongoose.connect(url);
    })
    .catch(err => {
        console.log('rejected promise: '+err);
        mongoose.disconnect();
    });
;
```

**Comment by dmansfield** [comment]
Actually that example also covers it a bit because bluebird translates the exception thrown: `this.$opPromise.then is not a function` into a rejection automatically - but you can see how it demonstrates the issue I hope.  If you need further clarification I can rework this a bit more.

**Comment by niftylettuce** [comment]
Thanks @vkarpov15

**Comment by avasuro** [comment]
That is so not obvious that mongoose.connect() will reject promise only on certain conditions... I really dislike this approach, because for example I have the following code:
```javascript
mongoose.connect().then(
    () => {
        // Do something, that can be done only when there is active connection with DB
    },
    (e) => {
        // Do something, that can be done only when failed to connect to DB
    }
)
```

I can't be sure that this code will work properly all the time. Perhaps somebody in other place of code did ```mongoose.connection.on('error', () => {...}) ```, in that case both handlers (success and error) will work improperly: error handler will never been called because promise never rejects, and success handler will always been called because of the same reason.

My opinion: or library should provide stable and predictable promises or eliminate promise response at all to prevent developers from writing potentially unstable and buggy code.
