### ISSUE TITLE
When set()-ing an object, set paths in the order they're defined in the schema, not in the object

### ISSUE THREAD

**Issue by jrthib** [Automattic/mongoose#4665]
When creating a document with setters that access other properties on the document, setters are unexpectedly ran before any values on the document are set. It seems to be running on doc init when all the default values are set. It seems like reversing the properties passed into the doc constructor makes it work though. Not sure why...

Any help would be appreciated! Thanks!

**Symptom Example**

``` javascript
var TestModel = mongoose.model('TestModel', new mongoose.Schema({
    field1: {
        type: String,
    },
    field2: {
        type: String,
        set: function(v) {
            return v + this.field1;
        }
    },
}));

var test = new TestModel({
    field1: 'test',
    field2: 'this is a ',
});

console.log(test);
```

This yields:

``` javascript
{ field1: 'test',
  field2: 'this is a undefined',
  _id: '5813a2a97ad1ad407aedf806' }
```

Expected outcome:

``` javascript
{ field1: 'test',
  field2: 'this is a test',
  _id: '5813a2a97ad1ad407aedf806' }
```

When adding a default value to the model for `field1` => `field1: { type: String, default: 'problem' }`, everything seems to work, however the setter never gets ran again when the document values are set, only runs when the defaults are set.

**Example with default set**

``` javascript
var TestModel = mongoose.model('TestModel', new mongoose.Schema({
    field1: {
        type: String,
        default: 'problem'
    },
    field2: {
        type: String,
        set: function(v) {
            return v + this.field1;
        }
    },
}));

var test = new TestModel({
    field1: 'test',
    field2: 'this is a ',
});

console.log(test);
```

This yields:

``` javascript
{ field2: 'this is a problem',
  field1: 'test',
  _id: '5813a31ede9c0340ba5995af', }
```

Expected outcome:

``` javascript
{ field1: 'test',
  field2: 'this is a test',
  _id: '5813a2a97ad1ad407aedf806' }
```

**Example with correct outcome**
Reversing the order of the properties on object seem to achieve the expected outcome.

``` javascript
var test = new TestModel({
    field2: 'this is a ',
    field1: 'test',
});

console.log(test);
```

This yields:

``` javascript
{ field2: 'this is a test',
  field1: 'test',
  _id: '5813a31ede9c0340ba5995af', }
```

**Comment by vkarpov15** [comment]
So with a couple caveats, this is expected behavior. When you do `new TestModel()`, setters will get called, it's just a matter of what order they get called in. For backwards compat (see #2749 to track removing this, this was a well-intentioned minor performance optimization that's proven to be a bad idea) mongoose will execute them in _reverse_ order.

If you want them to execute in order based on how you defined fields in your schema, do:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4664');
mongoose.set('debug', true);

var TestModel = mongoose.model('TestModel', new mongoose.Schema({
    field1: {
        type: String,
    },
    field2: {
        type: String,
        set: function(v) {
            return v + this.field1;
        }
    },
}, { retainKeyOrder: true }));

var test = new TestModel({
    field1: 'test',
    field2: 'this is a ',
});

console.log(test);
```

**Comment by vkarpov15** [comment]
See `retainKeyOrder` option here: http://mongoosejs.com/docs/guide.html#retainKeyOrder

**Comment by AdamGerthel** [comment]
Since `retainKeyOrder` is [now deprecated](https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings), how would I solve this in 5.x.x? See https://stackoverflow.com/questions/56644961/using-another-field-value-in-set-function for full example.

**Comment by AdamGerthel** [comment]
@vkarpov15 I see.. Does it behave differently on `document.set()`? Or if the fields are reversed in the input data? i.e. per your sample:

```
var test = new TestModel();

test.set({
    field2: 'this is a ',
    field1: 'test'
}).save()
```

**Comment by vkarpov15** [comment]
@AdamGerthel it behaves differently if the fields are reversed. In your example where `field2` comes before `field1`, a setter on `field1` would see the value for `field2`, but the `field2` setter would not see a value for `field1`. That's because Mongoose sets each field one at a time, and runs each field's setters when it sets the field.

**Comment by AdamGerthel** [comment]
@vkarpov15 Alright, so that means that it doesn't really matter what order you put them fields in on the model if the incoming data doesn't have the order you want it to have? If so, isn't that a little weird or at least prone to cause unexpected issue (since the order of the fields in the incoming object might naturally differ from time to time)? Objects don't have a fixed order, and it a lot of situations this means that in order for a setter to be able to read the value of another field, the incoming data (which Mongoose has no control over) has to match a specific order.

I guess I would've expected Mongoose to call the setters in the same order as they are in the model rather than the order they have in the incoming object.

**Comment by vkarpov15** [comment]
The idea of calling setters in the order they're defined in the schema is an interesting one. I'll re-open this issue and consider it for a future release. It's a little too close to backwards breaking to release without a major bump.

**Comment by vkarpov15** [comment]
Also, @AdamGerthel can you please describe your use case for this behavior? Why does your setter depend on another field being set?

**Comment by AdamGerthel** [comment]
@vkarpov15 Sure! I have a field called `govIdentifier` and a field called `type`. `govIdentifier` is a type of number that we use in Sweden to identify an individual or a company/municipality. The numbers look the same, and it makes sense to use a single field for both types because a single entity can not be both company/person/municipality etc at the same time. The `type` field is the field I use to identify the type of number.

The formatting of the `govIdentifier` is the same no matter the type, but they contain hidden information. I'm using a third party library to identify validate and _format_ the numbers before I set them. The reason why I format the number is because they are sometimes written NNNNNN-NNNN and sometimes without the dash, i.e. NNNNNNNNNN.

So, before _setting_ the value, I want to normalize them. For this I'm using [a library](https://github.com/kelszo/personnummer.js), but In order to be able to format them correctly, I need to know what the `type` is. I.e. I need to access the value of the field `type` in the setter of the field `govIdentifier`. I can access the value in the field validator, but not in the setter.

As a workaround I did this in a pre-save hook instead, but I think it's cleaner to keep this sort if thing close to the fields in the schema.

**Comment by vkarpov15** [comment]
I like the suggestion of running setters in the order the fields are defined in the schema, but in the meantime you're better off using a pre save hook or a [method](https://mongoosejs.com/docs/guide.html#methods). If you use setters, you'll also run into the issue that setters on on `update()`, so if you try to use [`updateOne()`](https://mongoosejs.com/docs/api/query.html#query_Query-updateOne) to update the `govIdentifier`, you won't be able to without the `type`.

How do you get the `type` property? Are they both part of the same form input?

**Comment by AdamGerthel** [comment]
@vkarpov15 Yes, they're both part of the same form:

![Screenshot 2019-07-03 at 16 12 47](https://user-images.githubusercontent.com/1490370/60598686-6b808a80-9dad-11e9-9e8f-a3c4cc962720.png)

As you also suggest, I've solved it using a pre save hook. But I'm looking forward to seeing this being added to a future version :)

> If you use setters, you'll also run into the issue that setters on on update(), so if you try to use updateOne() to update the govIdentifier, you won't be able to without the type.

I rarely use queries in Mongoose for that specific reason. I'd only use it if it was very important for other reasons (performance), because IMO it's confusing that a lot of hooks aren't run on queries (although I totally understand why).

**Comment by Joeb3219** [comment]
@vkarpov15 I am also interested in the ability to do things like this, albeit for a very narrow use-case:

If I have model that contains a subdocument with its own Schema, I can use setters or validators on the fields in that subdocument's schema just fine. However, if I call `findOneandUpdate(...)` on the parent document, none of the middlewares actually get called for the subdocument -- not save, fineOneAndUpdate, etc.

To do this sort of "formatting" that was described by others, I put the logic into a setter for the fields in question, but it strongly depends on the order that the fields were set. JSON.parse isn't deterministic in object key order, so this can lead to some unintentional misorderings.

**Comment by vkarpov15** [comment]
@Joeb3219 can you please go into more detail about what sort of "formatting" you're looking to do? In general, if you find yourself modifying multiple other paths in a setter, that logic is better off in a pre('save') hook.

**Comment by Joeb3219** [comment]
@vkarpov15 Sure, I agree that a `pre(save)` hook is better, but in my case it's not firing:

```
const LocationSchema = new mongoose.Schema({
    country: String,
    state: String,
    address: String,
});
const Location = mongoose.model('Location', LocationSchema);
LocationSchema.pre('save', locationFormatter);

const User = mongoose.model('User', new mongoose.Schema({
    location: LocationSchema,
    name: String,
}));
```

If I now do:
```
const newLocation = foo() // get the modified location for this user
User.findOneAndUpdate(
   { name: 'George' },
   { location: newLocation },
   { runValidators: true, upsert: true, new: true }
```

The `formatLocation` call here is meant to do things like convert the country name to a valid country code, convert the state to a valid state/province code (which depends on the country field), and verify that the address is valid for the state/country. There are other fields that go into this, but I kept my example short.

The `findOneAndUpdate` hook fires in `User`, but not in `Location`. I tried every pre and post hook, and none fire in the Location subdocument on initial create, update, etc. But the setters and validators _do_ fire for the subdocument, which seems fairly strange. I could elevate the locationFormatter function to be called from `User`, but this seems fairly messy, as now `User` is interfering with `Location`s data, and any other model which uses `Location` now needs a similar call as well, when the behavior really should be within `Location`.

does my issue make sense?

**Comment by AdamGerthel** [comment]
@Joeb3219 See https://mongoosejs.com/docs/middleware.html#notes

**Comment by Joeb3219** [comment]
@AdamGerthel So I've read through that documentation, but it still doesn't really address this issue. I understand why middlewares aren't being called, but have a hook anyway for `findOneAndUpdate` in `User` (using the above described scenario) to do other updates, in which I perform the query, get the real document, etc. But that still doesn't fill the gap that would be solved by being able to do set in a specified order, as the setters are still called on the underlying subdocument.

**Comment by AdamGerthel** [comment]
@Joeb3219 I see. Is it called if you get the parent document and save it?

I.e. 

```
const newLocation = foo();
const user = await User.findById(x);

await user.set({
  location: newLocation
}).save();
```

**Comment by Joeb3219** [comment]
@AdamGerthel Yep, things do fire just fine that way in a `pre('save')` hook. 

I debated going through and converting `findOneAndUpdate(...)` throughout our codebase to do this, but our application is fairly large, and this happens in more than one model.

**Comment by AdamGerthel** [comment]
Ok so, if I understand correctly, you're basically expecting an update on a document using `findOneAndUpdate()` to trigger a `pre('save')` on a sub-document? If so - then I don't think it will be supported or possible. You will have to use document middleware rather than query middleware.

Personally, I don't use queries for these types of operations at all, for this reason. In either case, this is really OT and not related to the issue.

**Comment by vkarpov15** [comment]
@Joeb3219 your example is a valid concern. I'd recommend using `save()` instead of `findOneAndUpdate()` for your case. But you're right that this seems like an example where running `pre('findOneAndUpdate')` on child schemas would be handy.

**Comment by Joeb3219** [comment]
@vkarpov15 I definitely would use `save()` for future instances, but it definitely will be difficult to backport the large amount of code at my org.

I mentioned previously, but I'd be willing to spend some time trying to implement either the setters being run in definition order (this does seem like a hack, though), or having `findOneAndUpdate()` fire for children documents. I'll submit a PR if I make any headway with it, pending how busy of a week I have upcoming.

Thank you again for the discussion back and forth!

**Comment by vkarpov15** [comment]
Both seem like pretty involved projects, but you're welcome to try it out.

I do like the idea of ensuring that document key order matches schema key order, and setters are called in the order that paths are defined in the schema. Doesn't feel like much of a hack, feels more like a good guarantee given that there are cases where object key order matters, like `.find({ nested: { key1: 1, key2: 2 } })` will not match `{ nested: { key2: 2, key1: 1 })`
