### ISSUE TITLE
transform option for cursor()

### ISSUE THREAD

**Issue by cblanc** [Automattic/mongoose#4705]
I understand mongoose is on course to deprecate `.stream()` in favour of `.cursor()`

Is there a option of transforming documents returned by `cursor()` which is analogous to the way  we could transform documents returned by `stream()` with something like `Thing.find().stream({ transform: JSON.stringify });`

I'm just wondering if this omission was a deliberate design decision because this should be approached some other way (presumably transform streams?). If not, would you accept a PR which implements a `transform` option for `cursor()`?

**Comment by vkarpov15** [comment]
Yeah it was an omission because it didn't seem too important at the time, especially since, as you mentioned, transform streams make this doable. Unfortunately, transform streams are confusing because the node stream API is not very clean or well documented. What I'd love to see would be a `.map()` function for cursors, which would go nicely with a transform option. Looking forward to the PR :)
