### ISSUE TITLE
Is manually execute "db.collection.createIndexes" better than state index in mongoose Schema?

### ISSUE THREAD

**Issue by timeswind** [Automattic/mongoose#4723]

**Comment by vkarpov15** [comment]
Depends on your use case and how big your code is. Declaring the index in the mongoose schema is good for development and small data sets, particularly in cases like nearSphere where you need an index to access certain functionality. But as your data gets bigger index builds will start to take longer, so you will probably want to decouple your application deployments from new index builds. Also, if you remove an index from a mongoose schema it'll still be in mongodb, so that's another case where you'd have to manage the indexes manually.

**Comment by timeswind** [comment]
thank you
