### ISSUE TITLE
Select: false doesn't work on timestamp fields

### ISSUE THREAD

**Issue by jensengar** [Automattic/mongoose#4868]
Bug unless there's another way to do this. Long story short, I want mongoose to record timestamps for me but I don't want them selected unless specified.

I have verified that adding a `select: false` to the schema elsewhere works, but not on the timestamp fields. For example if I have something like

```
var UserSchema = new Schema({
	email: {type: String, index: {unique: true, trim: true, index: true, sparse: true}},
	firstName: {type: String, required: true},
	lastName: {type: String, required: true},
	createdAt: {type: Date, select: false},
	updatedAt: {type: Date, select: false}
}, {timestamps: true});
```

my queries are still returning the `createdAt` and `updatedAt` fields. Is there a way only fetch these fields if requested?

node 6.9.1
mongoose 4.7.5
mongo 3.2.8

**Comment by varunjayaraman** [comment]
That won't work because passing in `{ timestamps: true }` as an option causes the schema to rewrite the `createdAt` and `updatedAt` fields as `Date` fields with no other parameters.

This is the relevant code from `Schema.prototype.setupTimestamps`:

```
var createdAt = timestamps.createdAt || 'createdAt';
    var updatedAt = timestamps.updatedAt || 'updatedAt';
    var schemaAdditions = {};

    schemaAdditions[updatedAt] = Date;

    if (!this.paths[createdAt]) {
      schemaAdditions[createdAt] = Date;
    }

    this.add(schemaAdditions);
```

Allowing you to pass in an option of `select: false` would be a backwards breaking change because  the `timestamps` object only takes a nested object to rewrite the field name:

```
{ timestamps: { createdAt: 'myNewFieldName' } }
```

My guess is that this change would require the option to instead be something like this, which would be backwards-breaking

```
{ timestamps: { createdAt: { fieldName: 'myNewFieldName', select: false } } }
```

Looping in @vkarpov15 here, since this seems like a feature request more than a bug.

**Comment by jensengar** [comment]
Awesome. Happy to help with anything.

**Comment by TrejGun** [comment]
meanwhile you can use global plugin

```js
import {omit} from "lodash";

mongoose.plugin(schema => {
	schema.set("timestamps", true); // for all models

	const transform = (schema.get("toJSON") || {transform: (doc, ret) => ret}).transform;
	schema.set("toJSON", {
		virtuals: true,
		transform(doc, ret) {
			return omit(transform(doc, ret), ["__v", "createdAt", "updatedAt", "id"]); // remove whatever you don't like on global level
		}
	});
})

mongoose.model("SomeName", new Schema({
   // some fields
}, {
	toJSON: {
		transform(doc, ret) {
			ret.created = ret.createdAt; // if you still need this info
			delete ret.someOtherField; // remove whatever you don't like on model level
			return ret;
		}
	}
}))
```

**Comment by jensengar** [comment]
I'll do that. thanks.

**Comment by jensengar** [comment]
So I see this as a partial work around. Using the plugin method works, but not when the query is done with the `lean` option which unfortunately is the majority of my queries probably. Is there anything else you can recommend?

**Comment by TrejGun** [comment]
express middleware 
https://www.npmjs.com/package/express-json-transform

**Comment by vkarpov15** [comment]
You can just use a pre find hook to deselect those fields unless they're explicitly selected. Or you can use a post find hook to remove them after the query. Is there some reason why you can't do this?

**Comment by Fred2MTL** [comment]
@vkarpov15 
I don't see how to implement your proposals. 
However, isn't it a workaround compared to add a select 'attribute' to the timestamps field ? As for the other fields of the corresponding schema.

**Comment by vkarpov15** [comment]
The problem is that timestamps adds its own `createdAt` and `updatedAt` fields to the schema, [with no properties, just `createdAt: Date`](https://github.com/Automattic/mongoose/blob/b66be34d54a6a3cf538b90bf1b5296f123c688a8/lib/schema.js#L822-L841), so adding your own `select: false` won't work. I suppose the better fix is to make it so that timestamps use the existing `createdAt` and `updatedAt` if they exist, rather than overwriting. Will add for next minor release.

**Comment by Fred2MTL** [comment]
@vkarpov15 
It could be better to consider the timestamp management as a facility, allowing the developper to link it to fields in the effective schema declaration and valued by default with createdAt/updatedAt declaration.
The basic (based on default declaration) would be 
var UserSchema = new Schema({
	...
}, {timestamps: true});
The proposal of @jensengar runs correctly, according to the default mapping.
var UserSchema = new Schema({
	createdAt: {type: Date, select: false},
	updatedAt: {type: Date, select: false}
}, {timestamps: true});
It could be extended with a help of mapping capability 
var UserSchema = new Schema({
	_createdAt: {type: Date, select: false},
	updatedAt: {type: Date, select: false}
}, { timestamps: { createdAt: '_createdAt'}};
