### ISSUE TITLE
New client-side model auto assigns _id as string and states that it is not 'New'!

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#4876]
I am initializing a document model using this code:

```
var doc = new mongoose.Document({}, MyDocSchema);
console.log(doc.isNew);
```

The console prints out `false` - why, it is a new document!?

I also noticed that `doc._id` has been generated automatically, but I do not want this to happen. I have defined the `_id` as `{type: String}` in the schema, so would expect it to require me to generate my own (?)

Note: I am using Mongoose v4.7.6

**Comment by varunjayaraman** [comment]
This isn't really the point of `isNew`. When mongoose runs in the browser, it uses a `browserDocument` (see https://github.com/Automattic/mongoose/blob/master/lib/browserDocument.js) rather than a regular mongoose `Document` (see https://github.com/Automattic/mongoose/blob/master/lib/document.js). The consequence of that is that it initializes slightly differently. 

The mongoose document `isNew` property is meant to indicate that a document hasn't been saved yet. This doesn't really mean anything in the context of the browser because you can't save to the DB from the browser. 

If you initialize a document on the server, you will notice that `isNew` is set to true:

*test-is-new-on-server.js*
```
const mongoose = require('mongoose');
const bluebird = require('bluebird');
mongoose.Promise = bluebird;

const MyDocSchema = new mongoose.Schema({
  name: String
});

const Model = mongoose.model('docs', MyDocSchema);


var doc = new Model({ name: 'bob' });
console.log(doc.isNew); // true

```

If you run this file with `node test-is-new-on-server.js` it will `console.log` true to the console.

In the browser, however, mongoose explicitly sets `isNew` to false in the initialization function unless you pass `false` to the 5th parameter that the constructor takes, which explicitly tells it to skip that initialization function. But there's no need to do that in the browser I think because, like I mentioned, the browser has no access to the database. 

I'm going to close this for now, but let me know if you still have any questions about the `isNew` property, I'm happy to explain more.

**Comment by joetidee** [comment]
Thanks for the explanation Varun. Correct me if I am trying to use this in the wrong way, but what I am trying to achieve is to use one schema for both client-side and server-side validation (at least for data type checking). I have seen other schema packages that allow client-side validation to be addressed using a schema pattern, but this would mean having to maintain two schema's for each document type. It would certainly be very efficient to be able to utilize the Mongoose schema definitions for both server-side and client-side validation. Perhaps each field in the schema could have a 'client' definition that allows conditions and messages to be added, so that if a certain condition was met it would show a specific message. For example, if the 'name' field was empty, it would throw a validation error of 'Please ensure that you have entered a name'. This would close the circle on isomorphic use of the Mongoose package.

Regarding the isNEW variable, I wonder if it would also be useful for this to be set to true on the client-side when the model is empty and false when the model has been populated using a document (retrieved using Ajax, for example). This way you can use it as a model, populate it with data from a form and send it to the server intact, where it can be properly validated.

**Comment by varunjayaraman** [comment]
You can use mongoose for both client-side and server-side validation, I do it all the time. Not sure what you're asking with the first part?

As for the isNew property, that really isn't the point of `isNew`. @vkarpov15 can chime in here but I think it's dangerous to assign one meaning to `isNew` on the client and another to it on the server.

Also,  `isNew` has nothing to do with the object being a mongoose document. You can still validate the document without `isNew` being set to true on the client.
