### ISSUE TITLE
How to use async/await with statics method?

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#4884]
Please see:

http://stackoverflow.com/questions/41559541/mongoose-await-is-a-reserved-word

**Comment by varunjayaraman** [comment]
You're using async/await incorrectly. The callback function has to be an async function as well, i.e.:

```
this.model('Template').findById(id, async function (err, doc) {
        let ref = await getNextSequence();
        ...
    });
```
 
To be honest, if you're going to use async/await, you should just use promises (findById returns a `Promise` if you don't pass it a callback)

```
try {
  const doc = await this.model('Template').findById(id);
  let ref = await getNextSequence();
  ...
} catch (error) {
  handleError(error);
}
```

**Comment by varunjayaraman** [comment]
@inanmadak i can't repro without a full repro script. I've done something similar to that many times with async/await and it has worked for me

**Comment by vkarpov15** [comment]
The unexpected identifier error is a syntax error that usually means that `await` is used in a function that isn't marked `async`. For example, the below function will error:

```javascript
async function test() {
  [1, 2].forEach(function() {
    await new Promise(resolve => setTimeout(() => resolve(), 50);
  });
}
```

Because `await` is inside the closure passed to `forEach()`, which is **not** async. I wrote a couple articles on async/await to help people grok the fundamentals:

* http://thecodebarbarian.com/80-20-guide-to-async-await-in-node.js
* http://thecodebarbarian.com/common-async-await-design-patterns-in-node.js
* http://thecodebarbarian.com/common-async-await-design-patterns-in-node.js

Make sure you check them out if you're new with async/await

**Comment by TheSuperFly** [comment]
The OP's snippet has an `async` / `await` errors but even with right `async` / `await`, it seems they doesn't work.

In the code below, `await` gets ignored and `res` equals to an empty array.

```
mySchema.statics.getPostIDs = async function (categoryId = false) {
  return this.distinct('postId', {
    categoryId: categoryId,
  });
};

// implementation

const res = await MySchema.getPostIDs(5);

console.log(res) // -> []
```

I'm using v4.13.4.
