### ISSUE TITLE
Deprecation warning - guidance requested

### ISSUE THREAD

**Issue by bazineta** [Automattic/mongoose#4886]
As has been mentioned in other closed issues, installation of mongoose 4.7.6 yields a big, scary deprecation warning with respect to the embedded driver version. While the driver has been updated in the master branch, no new version has been issued.

It would be nice to have some guidance as to the nature of the issue; i.e., should users immediately back off to a previous release, wait for a new release, or is the issue of no real consequence?

**Comment by YasharF** [comment]
Are you referring to the following when running npm install?

npm WARN deprecated mongodb@2.2.16: Please upgrade to 2.2.19 or higher

**Comment by varunjayaraman** [comment]
@bazineta there is a known bug relating to https://github.com/Automattic/mongoose/issues/4867, which derives from https://github.com/mongodb/js-bson/issues/204.

If this is an issue for you, you might want to use mongoose 4.7.2. Otherwise, unless other errors have been reported, as long as your tests pass, you can feel free to use 4.7.6. When 4.7.7 is released, the `mongodb` dependency will be upgraded to 2.2.19 and the warning will go away.
