### ISSUE TITLE
Node server not response to any database request after 2-3 days running.

### ISSUE THREAD

**Issue by rahulkulmi** [Automattic/mongoose#4901]
"mongoose": "^4.6.1",
"express-session": "^1.14.1",
"express": "^4.14.0",
node = v6.9.2

Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

Is there any mongoose connection issue or some thing else.

My database connection is 

```
var session = require('express-session')
var mongoose = require('mongoose')
mongoose.Promise = global.Promise
var autoIncrement = require('mongoose-auto-increment')
var connection = mongoose.connect(config.mongodb.uri + config.mongodb.database)
autoIncrement.initialize(connection)

app.use(session({
	secret: 'some-key',
	saveUninitialized: false,
	resave: false,
}))

```

**Comment by varunjayaraman** [comment]
Hmm I'm not sure if this is enough context to address this issue. What do you mean by the server isn't responding to a database request. Is it your server itself that doesn't receive an HTTP request, or are you saying that the response from MongDB isn't caught by your server?

**Comment by rahulkulmi** [comment]
My node server is receive HTTP request and also log inside the file. But MongoDB isn't response the request.

This is the request which get the output from MongoDB:
GET /api/v1/user/location?version=1484585221354 200 117.744 ms - 157 HTTP/1.1"

Now this is the request which didn't get response from MongoDB:
GET /api/v1/user/location?version=1484585221354 - - ms - - HTTP/1.1"

That is why i know that my node server is running but didn't get response from MongoDB database.

Here i am using MongoDB Atlas cloud service.

Some more information are required for you or now you know the problem.

**Comment by varunjayaraman** [comment]
Can i see the code in the endpoint that handles the 2nd GET request?

**Comment by rahulkulmi** [comment]
No it is single GET request. 
I have added both the logs when server gives response and when server not give the response.

**Comment by varunjayaraman** [comment]
I'm confused, you said there are 2 requests in your response:

```
This is the request which get the output from MongoDB:
GET /api/v1/user/location?version=1484585221354 200 117.744 ms - 157 HTTP/1.1"

Now this is the request which didn't get response from MongoDB:
GET /api/v1/user/location?version=1484585221354 - - ms - - HTTP/1.1"
```

Also, what I meant was I wanted to see the code from that endpoint that handles the GET request and makes a db call.

**Comment by rahulkulmi** [comment]
OK, I have put code below here. Here UserDevice is mongoose model object.

```
UserDevice.findOne({ _id: device_id }, 'settings.location', function(err, userDeviceRes) {
	if (err) {
		return callback(err)
	} else {
		return callback(null, userDeviceRes)
	}
})
```

When I start/restart my node server then I have got response
GET /api/v1/user/location?version=1484585221354 200 117.744 ms - 157 HTTP/1.1"

But after 2-3 days latter I have got response for same api
GET /api/v1/user/location?version=1484585221354 - - ms - - HTTP/1.1"

Here i am using winston logger to log every request on server. Know i thing you have clear all.

May be I got this problem due to memory leaks, that is why i have to conform from your side is it memory leaks or  mongoose connection issue.

**Comment by djanowski** [comment]
@rahulkulmi Can you please try downgrading to Mongoose 4.5.10?

**Comment by varunjayaraman** [comment]
Sorry I'm not sure I understand yet. That 2nd GET request is something you intentionally sent off yes? Why is the timestamp on that request undefined while the first one is? And is this a log of the incoming request or does it happen after the db call?

**Comment by djanowski** [comment]
@varunjayaraman Wouldn't that mean there was a timeout generating a response?

**Comment by varunjayaraman** [comment]
ah i see. @djanowski i thought these were logs for incoming requests, not for the response (like if you put a morgan middleware right after you define an express server for instance). I think i understand now, the 2nd log is for the response 2-3 days later.

@rahulkulmi this looks like a recurring problem relating to #4513. Thanks for keeping a record of related PRs @djanowski hopefully this problem can be debugged soon.

**Comment by rahulkulmi** [comment]
Right now i don't have mongoose log but i will add mongoose debug mode and give you logs when same problem comes again.

@djanowski Can i downgrading to Mongoose 4.5.10, because right now i am using Mongoose 4.6.1.

And thanks for @djanowski to explain this problem to @varunjayaraman

**Comment by rahulkulmi** [comment]
@varunjayaraman 

Is it required to add options in mongoose.connect() function like:

```
var session = require('express-session')
var mongoose = require('mongoose')
mongoose.Promise = global.Promise
var autoIncrement = require('mongoose-auto-increment')
var options = { server: { socketOptions: { keepAlive: 60000, connectTimeoutMS: 30000 } },
                replset: { socketOptions: { keepAlive: 60000, connectTimeoutMS : 30000 } } }
var connection = mongoose.connect(config.mongodb.uri + config.mongodb.database, options)
autoIncrement.initialize(connection)


app.use(session({
	secret: 'some-key',
	saveUninitialized: false,
	resave: false,
        cookie: { maxAge: 60000 }
}))
```

Right now i am not using options inside the mongoose.connect() function.

**Comment by varunjayaraman** [comment]
Nope, you shouldnt need any options, unless you want to set `keepAlive` and `connectTimeoutMS` and such.

**Comment by varunjayaraman** [comment]
@rahulkulmi can you try this again with the latest mongoose?

**Comment by rahulkulmi** [comment]
@varunjayaraman No i am using "mongoose": "4.5.10". But i am steel facing memory leak problem.
So i am setting cron to restart my node server in every 6 hours. But memory leak is very big problem. 
Is that problem is fix in new version "mongoose": "4.8.1" ?

**Comment by rahulkulmi** [comment]
I am also update the session code which is given below

```
app.use(session({
	secret: config.secretKey,
	saveUninitialized: false,
	resave: false,
	cookie: { maxAge: 1200000 },
	store: new MongoStore({
		mongooseConnection: mongoose.connection,
		autoRemove: 'interval',
                autoRemoveInterval: 10 // Time period in minutes.
	})
}))
```

Can i update mongoose version also.?

**Comment by tjaneczko** [comment]
We're also seeing a similar issue when connecting with a replica set in Atlas.  It seems the trigger is when the replica set elects a new primary.  We have two database connections open through mongoose (using `mongoose.createConnection()`) to the same replica set, one of the connections was able to reconnect automatically to the new primary just fine, the other connection was not and would hang whenever a query was executed.  We're not passing any additional options to the connection creation currently.  Restarting the server fixes the issue.

I tried to reproduce the issue using a local replica set (3 mongodb instances running on localhost), but could not reproduce the hanging connection as long as one primary was in the set (killing two instances would cause the queries to hang).  My guess is this has more to do with the underlying driver rather than mongoose, not entirely sure though.  Also not sure how to solve the issue besides monitoring both connections and killing / restarting the server or the connection if one starts to hang.

node: 6.9.1
mongoose: 4.7.3
mongodb server: 3.2

**Comment by rahulkulmi** [comment]
@tjaneczko Yes, I am facing same issue as you explain and also I am also using replica set in Atlas service. One quick fix is that you have to set cron to restart your server some interval. But it is not the actual fix for this problem. Please let me know if you are getting some other better option.

**Comment by vkarpov15** [comment]
Have you tried https://www.npmjs.com/package/connect-mongodb-session instead of writing your own session store?

**Comment by tjaneczko** [comment]
Just wanted to give an update on this, we kept seeing the issue come up any time a primary switchover happened in our Atlas replica sets.  After digging some more into it it seems like the added latency of connecting to Atlas (along with some latency within the Atlas VPC) was causing the issue to surface.  I found this mongodb ticket which helped me reproduce the issue locally using a TCP proxy: https://jira.mongodb.org/browse/NODE-893 .  Upgrading mongoose to version 4.9.3 and increasing the server pool size from 5 to 10 helped immensely and we haven't seen the issue pop up again in any of our environments since deploying that change (we've seen around 5 primary switchovers since then).  Hope this info helps!
