### ISSUE TITLE
how to validate an attribute before setter?

### ISSUE THREAD

**Issue by vicapow** [Automattic/mongoose#492]
I have a password field that I have a validator on as well as a setter. The validator checks to see if the password is longer than 6 characters and the setter applies an md5 hash. right now, the setter is applied before the validator causing validation to always pass because the md5 hash of the password is always more than 2 characters. How can I have the validator go before the setter to avoid this before? 

I also tried adding the md5 hash during the pre.("save") event but that causes the md5 hash to be applied each time the any user model is edited causing it to be applied multiple times.

**Comment by C-Collamar** [comment]
I know this thread is old, but apparently the issue is still there, and what @aheckmann provided in the link didn't really solve it. So I came up with this workaround.

### The workaround

In the setter, if the argument passes your criteria, simply follow through the setter as usual. If not, what you want to do is to simply **return that invalid value**. This assigns that invalid value to the document so that, just before the document gets saved, the validator(s) can catch that invalid value and spit out the appropriate error message.

### The code

Here's the solution to this specific issue.

```typescript

set: (pass: string): string => {
    return (pass.length <= 6)
        ? pass
        : encrypt(pass)
}

```

Hope this helps.

**Comment by C-Collamar** [comment]
I know this thread is old, but apparently the issue is still there, and what @aheckmann provided in the link didn't really solve it. So I came up with this workaround.

### The workaround

In the setter, if the argument passes your criteria, simply follow through the setter as usual. If not, what you want to do is to simply **return that invalid value**. This assigns that invalid value to the document so that, just before the document gets saved, the validator(s) can catch that invalid value and spit out the appropriate error message.

### The code

Here's the solution to this specific issue.

```typescript

set: (pass.length <= 6) ? pass : encrypt(pass)

```

Hope this helps.
