### ISSUE TITLE
timestamps returning as string

### ISSUE THREAD

**Issue by bonesoul** [Automattic/mongoose#4921]
using mongoose 4.7.7

have a schema like this;

```
let CommentSchema = new mongoose.Schema({
...
}, {
	timestamps: true,
	toObject: { virtuals: true },
	toJSON: { virtuals: true }
});
```

so in my nunjucks view when i render createdAt;

```
	{{ comment.createdAt | dump}}
	{{ comment.createdAt}}
```

prints:

```
"2017-01-20T14:32:13.297Z"
Fri Jan 20 2017 17:32:13 GMT+0300 (Turkey Standard Time)
```

why it runs a toString()?

**Comment by varunjayaraman** [comment]
This probably isn't a good way of seeing if mongoose runs a `.toString()` on a Date object. Can you console log the `createdAt` property?

**Comment by vkarpov15** [comment]
Does mongoose run the `.toString()` or does nunjucks? I'd imagine the latter, no good way to render a date in a templating framework without .toString()

**Comment by bonesoul** [comment]
i have also created an ticket for nunjucks repo, will let you know about the results.

**Comment by varunjayaraman** [comment]
@bonesoul I think the issue here is that youre expecting a NON version of a string in a template. Mongoose definitely is not running a .toString() on the date object unless you are trying to display this in a template, which is the only real way you could display something in a template, so I'm going to close this out.
