### ISSUE TITLE
Issue with pre save hook : the object to be saved is modified

### ISSUE THREAD

**Issue by clement-escolano** [Automattic/mongoose#4967]
Hello everyone !
Thank you for creating and supporting mongoose which is an awesome package. I encountered an issue however (maybe my mistake, maybe a bug, I am a bit pretentious so I say it's a bug 😄 ).

**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I have an article model. An article is a title and a boolean property to see if the article is active or not. I would like to have only one active article in my database. To do so, when I save an active article, I set other articles to be inactive.
This works well except for one case : the article is initially active, I modify its title (only) and save it. When I do this, the article is no more active, and I don't understand why.

**If the current behavior is a bug, please provide the steps to reproduce.**

Below is a sample code to test the behaviour. 

```js
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;

const articleSchema = new mongoose.Schema({
    title: { type: String, required: true },
    active: { type: Boolean, default: false }
});

articleSchema.pre("save", function(next) {
    const article = this;
    if (article.active) {
        return article.constructor.findOneAndUpdate({ active: true }, { active: false }, next);
    }
    return next();
});

const Article = mongoose.model("Article", articleSchema);

mongoose.connect("localhost/test");
mongoose.connection.once("open", () => {

    let article = new Article({
        title: "Test",
        active: true
    });

    article.save((error, savedArticle) => {
        savedArticle.title = "nextitle";
        savedArticle.save(() => {
            Article.find((err, res) => {
                console.log(res); // log the article which should be active but actually is not
            });
        });
    });
});

```

**What is the expected behavior?**

I should log the article that should be active.

**Please mention your node.js, mongoose and MongoDB version.**

node version : 7.5.0
mongo version : 3.4.1
mongoose version : 7.8.1

Thank you very much for your help, and if you see another way to handle my problem which doesn't involve a pre save hook, I would be happy to do so 😃

**Comment by varunjayaraman** [comment]
@clement-escolano bit of a gotcha here: You're calling save twice, so the 2nd time you call save, it finds the document in the database with `active: true` (the doc you just saved for the 2nd time) and sets `active` to false.

This seems like a pretty messy way to track active documents though. I'm usually weary of solutions that have to retroactively update the database, but maybe you could try using another collection to track active documents so that you don't have to edit other documents before flipping the `active` flag on another document to true?

**Comment by clement-escolano** [comment]
@varunjayaraman I agree that the second time, `active` is set to false. However, it is the article in the database that is set to inactive. As it is a pre save hook, I would expect that the actually saved article override the stored values and will set again the `active` field to true. Am I right ?

I agree this is kind of messy. I will certainly switch to your solution if I don't find anything to fix this problem.

**Comment by varunjayaraman** [comment]
ah you're right actually, my bad. But I think i figured it out:

On the second save, since the only modified path on the article is `title`, the `save()` operation doesn't record it as a path to update. So a little known fact is that `.save()` doesn't actually just take the document and save the entire thing to the db. Instead, it looks at modified paths and only updates those. If you want to wholescale update the entire document (which I'm usually not a fan of doing), you can use `.findByIdAndUpdate` and pass in the entire document as the 2nd parameter. Otherwise, in this specific case, you could do this:

```javascript
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-4967`;

const articleSchema = new mongoose.Schema({
  title: { type: String, required: true },
  active: { type: Boolean, default: false }
});

articleSchema.pre("save", function(next) {
  const article = this;
  if (article.active) {
    return article.constructor.findOneAndUpdate({ active: true }, { active: false }, next);
  }
  return next();
});


mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);
const Article = mongoose.model("Article", articleSchema);
mongoose.connection.once("open", () => {
  let article = new Article({
    title: "Test",
    active: true
  });

  article.save((error, savedArticle) => {
    if (error) {
      console.error(`Error: ${ error }\n${ error.stack }`);
      return;
    }
    savedArticle.title = "nextitle";
    savedArticle.markModified('active'); // this will tell `.save()` to also modify this path
    savedArticle.save(() => {
      Article.find((err, res) => {
        console.log(res);
      });
    });
  });
});
```

Either way, it's a tad messy. I'd recommend going with an alternate approach to tracking active articles tbh

**Comment by clement-escolano** [comment]
@varunjayaraman Thank you for finding out why this behaviour is happening and for offering this solution ! I will switch to a proper solution now, but I am glad to know why what I wanted didn't work as I expected.
Thank you again and have a good day.
