### ISSUE TITLE
return as Bson

### ISSUE THREAD

**Issue by antonioaltamura** [Automattic/mongoose#4985]
I would like to bring a little attention to this question
http://stackoverflow.com/questions/41656179/bson-restful-service

Maybe this way could be a valid option in some cases. Some of you already tried to accomplish that?

**Comment by vkarpov15** [comment]
An interesting idea. Never tried that, but it would be extremely difficult for mongoose to do that since the mongodb driver is what handles BSON serialization/deserialization, so the mongodb driver would need to support this. Please open an issue on the [mongodb driver jira](https://jira.mongodb.org/browse/NODE) if you're interested in pursuing this further.

**Comment by antonioaltamura** [comment]
The jira issue has been solved, I guess moongoose should expose some methods to support this :)
https://jira.mongodb.org/browse/NODE-938

**Comment by vkarpov15** [comment]
@antonioaltamura this lib is for extended json, not bson. These are two different serialization formats that mongodb supports.

**Comment by vkarpov15** [comment]
By "this lib" I mean https://github.com/christkv/mongodb-extjson
