### ISSUE TITLE
Bug in default object values for indexes

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5014]
`acquisitionSchema.index({ _id: 1 }, {});  // notice second object is empty object
`
```
/Users/alexamil/WebstormProjects/cdt-now/node_modules/mongoose/lib/utils.js:517
        throw err;
        ^
MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "dimalpha-dev.acquisitions", key: { _id: 1 }, name: "_id_1", background: true, unique: false }
    at Function.MongoError.create (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongodb/lib/db.js:1083:80
    at /Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

bug should be self-evident but if not lmk thanks

**Comment by varunjayaraman** [comment]
Sorry, I'm not really quite sure what bug you're trying to illustrate here. Are you passing an empty object as a second parameter to the `index` function? And can I see the entire schema?

**Comment by ORESoftware** [comment]
Mongoose seems to be setting "background" for me - I passed an empty object, but Mongoose is then setting it for me, and then complaining about background being present.

**Comment by varunjayaraman** [comment]
I don't think that's a bug. Mongo ALWAYS indexes `_id`.

**Comment by vkarpov15** [comment]
Yeah mongoose does set the `background` option for indexes to true by default. Just a general best practice because not running indexes in the background can have a massive performance impact.

There's also the problem that you're building an index on `_id`. Don't do that! MongoDB automatically has an index on `_id` for every collection, and you can't remove or reconfigure this index (at least as of 3.4), so there's no reason to ever create an `_id` index in mongoose.

**Comment by ORESoftware** [comment]
ah thx ok!
