### ISSUE TITLE
Report error if populating on non-existent path

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5124]
https://github.com/Automattic/mongoose/issues/5036#issuecomment-286952828

**Comment by TrejGun** [comment]
in strict mode?

**Comment by vkarpov15** [comment]
@TrejGun yeah I presume turning off this behavior if strict is off would be prudent

**Comment by neubee** [comment]
Are there any plans to add a global option for strictPopulate? I would much prefer such an option instead of setting strict to false for my models.
I'm dealing with a older codebase that has many populates and it's very difficult to track down which ones are using paths that don't exist. Also, there is extensive use of the following pattern

```
.populate({
  path: 'users',
  populate: {
    path: 'x y z',
    populate: {
      path: 'subPath1 subPath2',
    },
  },
})
```

Where subPath1 and subPath2 are only defined for a subset of x, y, and z.

**Comment by taxilian** [comment]
Before I create a new issue, I want to verify if this is "as designed" -- I get this error if I do a nested populate -- is that expected?

e.g:

    ApplicantModel.findOne({_id: applicantId, deleted: {$in: [false, null]}})
            .populate({
                path: 'assignedVeDocs',
                populate: {path: 'ulsRecord'},
            });

This is a 100% valid populate, but it throws the "strictPopulate" error, presumably because it doesn't follow through the refs to see that it does actually know about ulsRecord on the ref that assignedVeDocs populates to.

Bug or design feature?

**Comment by vkarpov15** [comment]
@taxilian I believe this is the issue we discussed in Slack on Friday. Without looking at the schema, I can't tell. I'll paste the script I posted in Slack for posterity that demonstrates this works.

```javascript
const mongoose = require('mongoose');
const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  console.log(mongoose.version);
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const VELinkSchema = new Schema({ ve: 'ObjectId' });
  VELinkSchema.virtual('veDoc', {
    ref: 'VE',
    localField: 've',
    foreignField: '_id',
    justOne: true
  });
  const parentSchema = new Schema({ assignedVes: [VELinkSchema] });

  const veSchema = new Schema({ call: String });
  veSchema.virtual('ulsRecord', {
    ref: 'UlsActiveCallsigns',
    localField: 'call',
    foreignField: 'callsign',
    justOne: true,
  });

  const ulsSchema = new Schema({ callsign: String });

  const Parent = mongoose.model('Test', parentSchema);
  const VE = mongoose.model('VE', veSchema);
  const ULS = mongoose.model('UlsActiveCallsigns', ulsSchema);

  await ULS.create({ callsign: 'Maverick' });
  const ve = await VE.create({ call: 'Maverick' });
  let p = await Parent.create({ assignedVes: [{ ve: ve._id }] });

  p = await Parent.findOne().populate({
    path: 'assignedVes.veDoc',
    populate: {path: 'ulsRecord'},
  }).exec();

  console.log(p.assignedVes[0].veDoc.ulsRecord.callsign);
}
```

**Comment by efcjunior** [comment]
I think there is bug about it https://github.com/Automattic/mongoose/issues/10976
