### ISSUE TITLE
Array required should not require length > 0

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5139]
Re: https://github.com/Automattic/mongoose/issues/5059

**Comment by joeytwiddle** [comment]
I'm in favour of this because I found the current behaviour to be rather unintuitive.

I set `required: true` because I wanted to guarantee that the client could do `document.arrayProp.length` after a `.find()`. I was surprised when my creates were rejected as invalid, despite having passed a valid empty array.

It seems there was no way to achieve my initial goal, because if I set `required: false` then even when I passed a valid empty array (`[]`) it didn't get stored in Mongo, or returned to me on the next `.find()`.

**Comment by joniba** [comment]
so what is the workaround now to get the previous behavior that validates that there is at least one member? 

Also, shouldn't this be mentioned in the[ mongoose-4-to-5 migration doc](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md)?

**Comment by vkarpov15** [comment]
@joniba it is there, just towards the bottom: https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#required-validator-for-arrays

Workaround is:

```javascript
const schema = new Schema({
  arr: {
    type: ['number'],
    validate: v => v == null || v.length > 0
  }
});
```
