### ISSUE TITLE
dataType to use need help

### ISSUE THREAD

**Issue by ezekel** [Automattic/mongoose#5150]
I have problem to migrate my table to mongodb I don't know what datatype is equivalent to mongodb, ex: decimal, time, char ? 
also if I am using mongoose do I need to specify the datatype if we create model ?

here is my structure.

```
CREATE TABLE `locators` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`mch_id` VARCHAR(15) NOT NULL ,
	`lat` DOUBLE(10,6) NULL DEFAULT NULL,
	`lng` DOUBLE(10,6) NULL DEFAULT NULL,
	`latcot` CHAR(1) NULL DEFAULT NULL,
	`ttime` TIME NULL DEFAULT NULL,
	`tdate` DATE NULL DEFAULT NULL,
	`tdatetime` DATETIME NULL DEFAULT NULL,
	`velo` DECIMAL(5,2) NULL DEFAULT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT NULL,

	PRIMARY KEY (`id`),
	INDEX `locators_mch_id_tdatetime_index` (`mch_id`, `tdatetime`),
	INDEX `locators_created_at_index` (`created_at`)
)
```

Thank you in advance.

**Comment by varunjayaraman** [comment]
@ezekel do you have any experience with `mongodb`? I would read up on it first. MongoDB uses `collections` in lieu of `tables`, but you define the data type at the `schema` level (if you choose to use something like `mongoose`). Otherwise, mongo will let you put any datatype in any field.

In mongoose's case, when you define a schema, you can do this:

```javascript
const schema = new mongoose.Schema({
  mch_id: { type: String, required: true },
  lat: Number,
  lng: Number,
  latcot: String,
  ttime: Number,
  tdate: Date,
  tdatetime: Date,
  velo: Number,
  
}, { timestamps: true });

```

You can read more about creating indexes with mongoose here: http://mongoosejs.com/docs/guide.html#indexes
