### ISSUE TITLE
count + distinct

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5174]
I think this might be a bug -

```js
router.get('/count', function (req, res, next) {

  const query = req.parsedQueryParams;
  const info = req.parsedQueryOpts;

  let q = Response.count(query);

   if(info.distinct){
     q = q.distinct('userId')
   }

  q.exec()
  .then(
    stdPromiseResp(res),
    next
  );

});
```

bug: the count works fine, but if distinct is used, it looks like I don't get a number returned, instead I get an ObjectId, kinda weird!

**Comment by ORESoftware** [comment]
Also, what would be really useful, is if we could do this:

```
  if(info.distinct){
     q = q.distinct('userId').distinct('promptId')
   }
```

or
```

  if(info.distinct){
     q = q.distinct(['userId','promptId']);
   }

```
that would be very useful, not sure if it's possible given MongoDB.

**Comment by varunjayaraman** [comment]
yeah so `count` and `distinct` are different ops. A `count()` is not a `find()` operation but a `distinct()` is. You have to just call `.length` off the results of the `distinct()`.

As for multiple `distinct()` calls, i'm pretty sure mongodb doesnt allow that because it has to be a string. @vkarpov15 probably knows better than me but my hunch says thats not possible

**Comment by vkarpov15** [comment]
The original post is not a bug, really just expected behavior. `.count({ field: 'value' }).distinct('userId')` is equivalent to `.distinct('userId', { field: 'value' })`, chaining the two together doesn't give you anything beyond adding query conditions.

Re: distinct on multiple fields with one command, not really possible with mongodb, [you can only do distinct on one field](https://docs.mongodb.com/manual/reference/method/db.collection.distinct/). A potential alternative though would be that [distinct works with array fields](https://docs.mongodb.com/manual/reference/method/db.collection.distinct/#return-distinct-values-for-an-array-field).
