### ISSUE TITLE
autoIndex doesn't work for `mongoose.connect()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5176]
See https://github.com/Automattic/mongoose/issues/1875#issuecomment-292855301

**Comment by vkarpov15** [comment]
Upon closer inspection it looks like autoIndex is working as expected, the below script prints nothing, but if you change `autoIndex` to true it prints that it called `ensureIndex`. @yasharma can you please modify the below script to reproduce your issue? Couple questions:

1) Are you sure you don't have a plugin that's setting `autoIndex` on your schema?
2) Are you expecting that mongoose would remove the index for you if `autoIndex` is false? If `autoIndex` is false, mongoose will not remove existing indexes, so any indexes in the db will stay there.

**Comment by mhueter** [comment]
Hi @vkarpov15 , I think I'm experiencing this issue. I was experiencing large spikes in my response time in production code for some queries, and through the debug setting, I think I have tracked it down to `ensureIndex` being called on the slow queries, which brought me to this issue.

Here is my `server.js` snippet:

`mongoose.connect(uri, { user: '', pass: '', replset: '', config: { autoIndex: false } })`

Then, with debugging enabled, it prints immediately after that:

`Mongoose: sites.ensureIndex({ subdomain: 1 }, { background: true })`

This happens when index is set on the prop (i.e. `subdomain: { type: string, index: true }` or when `sites.index({ subdomain: 1})` is set in the schema definition file.

**Comment by vkarpov15** [comment]
Below script reproduces the issue. As a workaround, make sure you call `mongoose.connect()` **before** `mongoose.model()`
