### ISSUE TITLE
findByIdAndUpdate documentation unclear

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#5194]
The documentation doesn't state whether the `findByIdAndUpdate `method can update only the fields provided by the `update` object. For example, I want to update only the `name `field in the following document:

```
{
    name: "Joe",
    age: 30
}
```

If `age `is a required field in my schema definition and I include the `runValidators: true` option, does this mean that the `update `object must always have the age value defined each time I want to update the document?

**Comment by varunjayaraman** [comment]
i think it's fairly obvious that it only updates the arguments passed to the `update` object, especially given the example explaining how it translates the update:

```
Model.findByIdAndUpdate(id, { name: 'jason borne' }, options, callback)

// is sent as
Model.findByIdAndUpdate(id, { $set: { name: 'jason borne' }}, options, callback)
```

**Comment by houssem-yahiaoui** [comment]
Actually, it doesn't, when dealing with update you need to be extremely cautious,  because i run into some situation where i had to make a custom middleware before updating my schema, because it will simply wipe down everything.
So you will need to think of a way to only process the field that aren't null or undefined or simply blank, it's applying if you're sending a general update request from express or something like it.

**Comment by varunjayaraman** [comment]
taking a request body and blindly passing it as an update doc to `findByIdAndUpdate` is not a good idea in the first place. It's not `mongoose`'s job to also perform data validation on your incoming requests. You should properly sanitize and construct your update ops before sending them to the db as an update

**Comment by joetidee** [comment]
What do you use to cleanse data?

**Comment by vkarpov15** [comment]
Re: "Actually, it doesn't, when dealing with update you need to be extremely cautious, because i run into some situation where i had to make a custom middleware before updating my schema, because it will simply wipe down everything.", can you please clarify?

And I'd argue that using mongoose to validate a request body is the right way to go. Mongoose is designed specifically to ensure that potentially unsafe end-user data fits a specified format.

Re: OP, unless you explicitly set `overwrite: true`, if `age` is not specified in the update, then `runValidators` will not error even if `age` is required, see: http://mongoosejs.com/docs/validation.html#update-validator-paths . 4.10 will have handle the `overwrite: true` case.

**Comment by houssem-yahiaoui** [comment]
@vkarpov15 Typically in a normal application , the flow will be sending an update to an api, in such not all field are set, that's why i mentioned the middleware thing, the final one will simply strip all null, unset or blunk fields, it's an application hing not mongoose since the findByIdAndUpdate won't care about the value, it will replace everything with the given value of a specific field at a specific time, it won't filter it don't you think such simple filtering of value should be present over the build in mongoose function ?
