### ISSUE TITLE
Can't delete a entity's field when using .save()

### ISSUE THREAD

**Issue by Prumeth-shen** [Automattic/mongoose#5239]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by Prumeth-shen** [comment]
Here is my example
let fruitSchema = new mongoose.Schema({
	kind: {type: String,}
        need: {type : String}
})
let Fruit = mongoose.model('Fruit', fruitSchema)
let apple = new Fruit({kind: "apple", need: "yes"})

apple.save()
	.then((apple) => {
		delete apple.kind
		return apple.save() // here I find that the field of kind hasn't been deleted
	})
	.catch((error) => {
		console.error(error)
	})

// how can I delete a entity's field when using .save() ?

**Comment by varunjayaraman** [comment]
Please wrap your code in 3 backticks next time, I did it for you this time. If you don't it makes it really hard to read your code.

the problem is that you're using `delete`. mongoose documents aren't POJOs (plain old javascript objects), they have some weird getters and setters. so you should do `apple.kind = undefined` before you save it
