### ISSUE TITLE
Never store createdAt in db, but always show (even if document is just created) createdAt upon toJSON.

### ISSUE THREAD

**Issue by codeofnode** [Automattic/mongoose#5246]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It is not getting createdAt when i do toJSON on newly created document. It gets createdAt only when i update it. So probably createdAt is saved to db and no virtual are added for createdAt.
Why do we need to save createdAt in db at all?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Never store createdAt in db, but always show (even if document is just created) createdAt upon toJSON.
Also updatedAt should not be stored in db, until the document is actually updated (after creation).
while doing toJSON, if there is no updatedAt then it should be equal to virtual createdAt.

Say document is { name : "John" }
with Schema { name : String }

* When document is just created
** In db : { _id : someObjectId, name : "John"  }
** when toJSON  { _id : someObjectId, name : "John", createdAt : someTimeStampFrom_id, updatedAt : someTimeStampFrom_id  }

* When document is updated after creation
** In db : { _id : someObjectId, name : "John", updatedAt : updatedAtTimeStampFromDB  }
** when toJSON  { _id : someObjectId, name : "John", createdAt : someTimeStampFrom_id, updatedAt : updatedAtTimeStampFromDB  }

the option "timestamps" : true, should handle all above situations automatically, with whatever virtual property is applied internally.

**Please mention your node.js, mongoose and MongoDB version.**
node : v7.10.0
├─┬ mongoose@4.7.9
│ ├─┬ mongodb@2.2.22
│ │ ├── mongodb-core@2.1.7

**Comment by varunjayaraman** [comment]
The whole point of `createdAt` is that we can know when the document was created. If we didn't store it in the database, how would we access that value in the future?

**Comment by codeofnode** [comment]
_id of monodb does contain the timestamp information of when the document was created.

So createdAt can be generated on the fly while doing toJSON.. by setting that into virtual

I hope everyone can understand i am talking in context of option "timestamps".

**Comment by vkarpov15** [comment]
If you want `createdAt` to be a virtual based on the timestamp value encoded in `_id` then go ahead, implementing that is a 3-liner. Storing timestamps in the database, though, lets you more easily query by timestamps and makes timestamps easier to read in the db, so we'll continue to do that in the future. Plus, relying on ObjectId for timestamps can be brittle because there's no guarantee that the ObjectId isn't manually specified. For example, below is perfectly valid:

```javascript
var doc = new MyModel({ _id: '000000000000000000000000' }); // _id must be 24 hex chars, only real restriction
```

Mongoose does not prevent you from manually setting an `_id` on a new doc, so no guarantee that the ObjectId contains the correct timestamp.
