### ISSUE TITLE
Mongoose Repo Doc :  Plugin section

### ISSUE THREAD

**Issue by houssem-yahiaoui** [Automattic/mongoose#5247]
Hello all,

I was wondering, since the generator repo of the mongoose plugins is dead, does the API, way of creating a plugin still the same ?

**Comment by vkarpov15** [comment]
Which generator repo

**Comment by vkarpov15** [comment]
Added more detail to the docs now that the generator repo is gone. Yeah the plugin API has been stable since 2012. Here's [docs](http://mongoosejs.com/docs/plugins.html) and a [blog post](http://thecodebarbarian.com/2015/03/06/guide-to-mongoose-plugins) on how to write a plugin. You don't really need a yeoman generator for mongoose plugins, there isn't much boilerplate, a plugin is just a function that takes 2 params, a schema and optional options.

**Comment by houssem-yahiaoui** [comment]
Wonderful, i just wanted to point that fact only, but yeah creating a mongoose plugging is straightforward process.
