### ISSUE TITLE
Code pattern query regarding multiple Mongoose version dependencies

### ISSUE THREAD

**Issue by steve-p-com** [Automattic/mongoose#5256]
This is (probably) not a bug, more a request for information on how a developer should handle a particular scenario.

I have a product which is split into multiple separate modules (all published to a private internal npm server). One of the modules ('shared') contains and exports some (but not all) Mongoose models. This particular module was set to use Mongoose 4.9.9. Another module ('server') was what made the actual db connection, but that was set to depend on Mongoose 4.9.7. It has some models defined as well.

What happens in this scenario is that every query for a model that is defined in 'shared' gets queued, and never executes. The server 4.9.7 instance successfully makes the database connection, but the 'shared' queue (which was associated with 4.9.9) never gets processed. So the application hangs forever. Changing the server to also use 4.9.9 did fix the problem, but I don't think that's the best solution.

What I'm asking I suppose is whether this is the expected behaviour, and how could you mitigate against it? I thought that when using require there would only be a single instance of mongoose, and therefore the queue and connection status would be shared. However, this is not the case, so it's not as simple as I thought it might be. It seems there are actually multiple Mongoose versions loaded at once, and they each have their own queue, and connection status, and cannot really co-exist. (I should add this is a yarn install).

While I have the ability in this case to control both version levels, what if you were using models exported by a third party module with a dependence on a different Mongoose version, where you can't rely on them to keep the Mongoose level the same as your own? It seems like that can't work. How do other developers handle this? Is it a bug, an oversight, or expected behaviour? I could export connection code from the 'shared' module, which would probably work, but that still won't work if you have multiple models from multiple modules with unknown Mongoose versions. It's only reliable if everything is using the same version, which is not always possible to control. 

Guidance needed  :smiley:

**Comment by vkarpov15** [comment]
`require('mongoose')` does return a singleton, but the question is, which version of mongoose? If 'shared' has a separate mongoose version, it'll get a different `require('mongoose')`.

There's a few simple patterns to improve your setup:

1) `shared` should export **schemas**, not models. In general, any project that doesn't instantiate its own database handle shouldn't initialize models. Conceptually, model = schema + connection, so if the 'shared' lib doesn't connect to a database on its own then exporting models doesn't make sense.
2) List mongoose in `peerDependencies` for 'shared' rather than as a hard `dependency`. That way the app that uses 'shared' determines which version of mongoose to use and you get the version consistency you're looking for.

**Comment by steve-p-com** [comment]
Thanks very much for taking the time to write a detailed explanation. I will take a long look at the architecture of this particular product, and make the necessary changes which should guarantee better reliability. And of course, I will design future product to take this into account from day one.
