### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) of ms package < 2.0.0

### ISSUE THREAD

**Issue by JasonBoy** [Automattic/mongoose#5275]
Due to an incomplete fix for previously reported vulnerability  [npm:ms:20151024](https://snyk.io/vuln/npm:ms:20151024), the new [npm:ms:20170412](https://snyk.io.cnpmjs.org/vuln/npm:ms:20170412) was reported.
Any chance to update? or update the ms package is a major change?

**Comment by clozanosanchez** [comment]
Mongoose should update ms to v2.0.0, but mquery (another mongoose dependency) is also affected by this problem (I think they are working on to release a new version soon).

**Comment by vkarpov15** [comment]
I pushed a fix which upgrades to the latest version of mquery, which in turn bumps its dependency on debug. Mongoose's exposure to this issue is minimal:

* Mongoose doesn't use `debug` directly, but mquery uses it to [print some query debug info](https://github.com/aheckmann/mquery/blob/master/lib/mquery.js#L1724)
* Mongoose uses `ms` directly for parsing arguments to [schema-declared TTL indexes](http://mongoosejs.com/docs/api.html#schema_date_SchemaDate-expires), and the overhead of building an index on production data is likely more than 0.3 seconds

Still, better safe than sorry. Gonna push a new release :+1:
