### ISSUE TITLE
TTL index fails to create with particular call

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5276]
This works:

```js
lockSchema.index({expiresAt: 1}, { expireAfterSeconds: 36000, background: false});
```

however this fails:

```js
lockSchema.index({expiresAt: 1}, {expires: 'true', expireAfterSeconds: 36000, background: false});
```

the failing one will create an expireAfterSeconds value of null in the database.

Any idea why that would happen?

**Comment by ORESoftware** [comment]
I had to drop the index created by the second call above, then recreate with the first call above

**Comment by vkarpov15** [comment]
Because `expires` is [syntactic sugar for setting `expireAfterSeconds`](http://mongoosejs.com/docs/api.html#schema_Schema-index). There's no need to set both, the big difference is that `expires` gets passed through [ms](https://www.npmjs.com/package/ms) so you can do things like `expires: '10h'` rather than `expireAfterSeconds: 36000`
