### ISSUE TITLE
BrowserDocument won't create nested object on access

### ISSUE THREAD

**Issue by speterli** [Automattic/mongoose#5440]
If you reuse a schema definition, Mongoose on Browser doesn't create a default object while you want to access the nested variable.

**Example (Browser)**

```javascript

var nestedSchema = new mongoose.Schema({
  name: { type: String }
});

var schema = new mongoose.Schema({
  nested: nestedSchema,
  inlineNested: {
    name: String
  }
});

var doc = new mongoose.Document({}, schema);

doc.inlineNested.name = "OK";
console.log("inlineNested created!");

doc.nested.name = "OK";
console.log("nested created!");
```

**Output**
```
inlineNested created!
TypeError: Cannot set property 'name' of undefined
```

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix. Will take a couple weeks though, we're currently backed up with issues, sorry

**Comment by varunjayaraman** [comment]
yep this looks like a confirmed bug:

**index.html**

```html
<html>
  <head>

  </head>

  <body>
    
    <script src="app.js"></script>
  </body>
</html>
```

**index.js**
```javascript
const mongoose = require('mongoose');


var nestedSchema = new mongoose.Schema({
  name: { type: String }
});

var schema = new mongoose.Schema({
  nested: nestedSchema,
  inlineNested: {
    name: String
  }
});

var doc = new mongoose.Document({}, schema);

doc.inlineNested.name = "OK";
console.log("inlineNested created!");

doc.nested.name = "OK";
console.log("nested created!");
```

to run:

`npm install mongoose browserify && $(npm bin)/browserify index.js -o app.js && open index.html`

**Comment by vkarpov15** [comment]
Looking more closely, this behavior isn't unique to the browser, the below script fails on node as well:

```javascript
const mongoose = require('mongoose');

var nestedSchema = new mongoose.Schema({
  name: { type: String }
});

var schema = new mongoose.Schema({
  nested: nestedSchema,
  inlineNested: {
    name: String
  }
});

var TestDoc = mongoose.model('Test', schema);

var doc = new TestDoc({});

doc.inlineNested.name = "OK";
console.log("inlineNested created!");

doc.nested.name = "OK";
console.log("nested created!");
```

Single nested schemas are different from inline nested in several ways. They can be null/undefined, their `required` paths are not `required` in the parent doc, they have their own hooks like `init` that don't fire if the doc is null, etc. These features are all due to the fact that mongoose treats `nested` as a value that contains a separate document with its own getters/setters, whereas `inlineNested` gets getters/setters for `inlineNested` and `inlineNested.name`. As a consequence of this, `doc.nested.name = 'ok';` won't work, you need to do `doc.set('nested.name', 'ok')` or `doc.nested = { name: 'ok' };` or `doc.nested = {}; doc.nested.name = 'ok';`. Unfortunate but we can't change this without throwing out the nice behaviors of nested schemas listed above.

If you want code sharing without having to rely on nested schemas, you can do something like:

```javascript
var inline = { name: String };

var schema1 = new mongoose.Schema({ nested: inline });
var schema2 = new mongoose.Schema({ nested2: inline });
````
