### ISSUE TITLE
Fat arrow for pre, post, statics, methods etc.

### ISSUE THREAD

**Issue by a-koka** [Automattic/mongoose#5458]
**Feature Request**
Support fat arrow syntax for schema methods.

**Current behavior**

    MySchema.methods.myMethod = (cb) => {
      console.log(this.mySchemaField) // Does NOT Work
    }

    MySchema.methods.myMethod = function(cb) {
      console.log(this.mySchemaField) // Works
    }

**Versions**
Node: 6.8.1
Mongoose: 4.8.1
MongoDB: 3.4.0

**Comment by varunjayaraman** [comment]
this is really difficult, fat arrows lose `this` and schemas rely on that.

**Comment by a-koka** [comment]
I understand. Perhaps we can include in the documentation to not use fat arrows? I spent quite a few hours figuring this out the hard way.

**Comment by vkarpov15** [comment]
Will add to the docs

**Comment by reklamehusetwera** [comment]
@varunjayaraman @vkarpov15 

I believe it should be possible to implement something like this?

```js
MySchema.methods.myMethod = (model, cb) => {
   console.log(model.mySchemaField)
}
```

**Comment by vkarpov15** [comment]
@reklamehusetwera that wouldn't be backwards compatible - methods can have any number of params. We can't assume that every method takes exactly 1 argument.

**Comment by reklamehusetwera** [comment]
@vkarpov15 Your right that it would not be backwards compatible with custom made functions, but I thought it would be internally in the library.

Anyways, that could simply be solved by increasing the version number of mongoose with a migration guide. Both with warnings in console & in documentation.

At our company we are all always using arrow functions these days & have no plans for going back to a more complicated way of writing functions. So because of this we decided not to use mongoose, but we just stay with the mongodb lib for now.

Else, it looks like mongoose does simplify allot of things, so nice job anyways. ;)

**Comment by vkarpov15** [comment]
You can use Mongoose without writing custom methods you know :) You can use arrow functions for just about everything else in Mongoose.
