### ISSUE TITLE
Playground environment

### ISSUE THREAD

**Issue by smooJitter** [Automattic/mongoose#5484]
I'm new.  Is anyone aware of a playground environment where I play with mongoose commands and observe the impact?  I'm using vscode.  For now, each time I want to exam mongoose calls, i have to save a file and wait for app to reload.  I would prefer to build up my commands trying them out in the context of the rest of my code. I'm using MongoClient but that only works for mongoDb

**Comment by varunjayaraman** [comment]
you could just write a script and keep testing it on a db, or use the mongo shell. Not sure what else youre looking for?

**Comment by smooJitter** [comment]
Thanks for the reply.  I was not aware I could reference mongoose models via mongo shell.  I will give it a try. I'm using MongoClient to interact with my mongo database.  Tools such as these are great but they interact via mongo native drivers. I was wondering if there exist tools such as these where instead of writing mongo native queries and mutations I could reference the database via mongoose models instead.

**Comment by varunjayaraman** [comment]
i dont think so since mongoose is just an abstraction over the driver itself, and to my knowledge no cli client exists for what you're looking for. 

mongoose models are just references to mongoose collections (with js abstraction on top), so it's not that you can reference mongoose models from the mongo shell, but you can reference the underlying collection

**Comment by varunjayaraman** [comment]
im going to close this for now since what you're looking for is well outside the purview of mongoose, and would be well-suited for a different lib as an abstraction over mongoose itself to create a playground environment
