### ISSUE TITLE
unexpected warning : To create a new ObjectId please try `Mongoose.Types.ObjectId` instead of using `Mongoose.Schema.ObjectId`.

### ISSUE THREAD

**Issue by DariosDjimado** [Automattic/mongoose#5587]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The warning is shown even if we're not creating a new ObjectId

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
var mongoose = require('mongoose');

var zoneSchema = new mongoose.Schema({
    employees: {
        certifications: {type: mongoose.Schema.Types.ObjectId, ref: 'Certifications'}
    }
});

var certificationsSchema = new mongoose.Schema({
    type: String,
    list: [{type: mongoose.Schema.Types.ObjectId, ref: 'Certification'}]
});

var certificationSchema = new mongoose.Schema({
    name: String
});

var Zone = mongoose.model('Zone', zoneSchema);
var Certifications = mongoose.model('Certifications', certificationsSchema);
var Certification = mongoose.model('Certification', certificationSchema);

var newZone = new Zone();
```
**What is the expected behavior?**
Do not show the warning when it is not an explicit instance of new ObjectId

**Please mention your node.js, mongoose and MongoDB version.**
Node v8.2.1
Mongoose v4.11.8
MongoDB v3.2.7

**Comment by vkarpov15** [comment]
Sorry about the snafu, we'll release a fix later this week. This was an unintentional side effect of #5571 because 'employees.certifications' happens to be exactly 24 characters long. This issue should go away unless you happen to have a top-level property that's a 24 character hex string, and we now have an option to suppress the warning for that (hopefully) unusual edge case.
