### ISSUE TITLE
Set checkKeys option for .save() function not working

### ISSUE THREAD

**Issue by daumann** [Automattic/mongoose#5667]
I encountered the `Error: key must not contain '.'` issue. 

On Stackoverflow it was adviced to set the checkKeys to false in order to solve the issue.

I also found on the official repo a test which does exactly that (adding {checkKeys: false} to the insert options) :
https://github.com/mongodb/node-mongodb-native/blob/3bd25ebfcc515b362f57f959467cc588296dfdf6/lib/db.js#L1087

I assume the .save() options will be passed down to the insert function?
Unfortunately the official mongoose docs are not helpful and I already tried:
`.save({checkKeys: false})`

which did not work.

**Comment by vkarpov15** [comment]
`checkKeys` is there for a reason, because [MongoDB property names cannot contain '.'](https://docs.mongodb.com/manual/core/document/#field-names) and that's enforced in the MongoDB server, nothing mongoose can do about it. `checkKeys` is still there because some older MongoDB versions that allowed this.

**Comment by daumann** [comment]
@vkarpov15 
The reason why I want to use `checkKeys: false` is that I don't want to access those keys but rather tread it as a atomic payload.

Example:

keyuser1: {huge_user_defined_JSON}
keyuser2: {huge_user_defined_JSON}
keyuser3: {huge_user_defined_JSON}

I will only access those entries by the root key, never dig into the payload JSON. That is a valid case for `checkKeys: false`, no?

I know the other workaroudn would be to stringify the whole JSON payload and save it as a string - but I would like to avoid that unnecessary performance hit.

**Comment by vkarpov15** [comment]
Unless you save it as a string, mongodb will have to dig into the keys and hit the keys that have dots in them. MongoDB does this to ensure that dotted queries work correctly, because if you have an object like this:

```javascript
{ a: { 'b.c': 1, b: { c: 2 } } };
```

What happens when you query for documents with `{ 'a.b.c': 1 }` ? If you want to save an arbitrary JSON payload with dollar signs and dots in property names you'll have to save it as a string, no way around that currently.
