### ISSUE TITLE
call .toObject for documents returned via Aggregate function

### ISSUE THREAD

**Issue by mayeaux** [Automattic/mongoose#5672]
I'm trying to pagination which requires me to sort by custom fields using MongoDB's aggregate function.

However, I'd like to access Mongoose virtuals after that, but I can't call .toObject() for the documents returned by MongoDB. What can I do in this case? Thanks

**Comment by varunjayaraman** [comment]
mongoose aggregates return lean docs because of the nature of aggregation, which manipulates docs such that they may or may not fit the schema once they exit the pipeline. If you want, you can reconstruct the doc once it exits the pipeline by iterating through the results and calling `Model.new(result)` on each one, and then each item in the array will be a mongoose object instead of a POJO.

Does that solve your use case?

**Comment by mayeaux** [comment]
You know I've had such an issue with the Aggregate function call and bending it to my will (esp. with needing to make 2 joins), that I think I'm going to go a different route and just deal with a lot of stuff in memory and cache it. I'm reading a textbook on MongoDB hopefully that will increase my skills then I'll come back to this.
