### ISSUE TITLE
Update array column is failed by mongoose update function

### ISSUE THREAD

**Issue by spursy** [Automattic/mongoose#5673]
In my mongodb document , I have set one column as **Arrary** type.

- case1, if this array column store **string array** like: ['one', 'two', 'three'], then I use mongoose update this column as ['five', 'six', 'seven']. This operation is ok.
- case2, if this array column store **object array** like: [{name: "Tom", age: 2}, {name: "Kake", age: 3}], then I use mongoose update this column as  [{name: "JJ", age: 20}, {name: "KK", age: 30}], This operateion is not success, the result is **{ n: 0, nModified: 0, ok: 1 }**
## The followed is my nodejs code.
the **content** is array type

```
    var updateddata = _.cloneDeepWith(existeddata);
    updateddata.content =  [{name: "JJ", age: 20}, {name: "KK", age: 30}];
    updateddata.update_dt = new Date();
    try {
        var result = await WXAutoReply.update(existeddata, updateddata);
        console.log(result)
        return result;
    }catch(e) {
        return e;
    }
```

**Comment by varunjayaraman** [comment]
I would not recommend using `_.cloneDeepWith` with a mongoose object.

That being said, can you please post an actual reproducible script, I still dont really understand what youre doing in the update operation, especially since i dont know what `existeddata` is. That is the query condition, so maybe its not finding the proper document?

**Comment by vkarpov15** [comment]
@varunjayaraman is correct. If you want to clone a mongoose object, use `doc.toObject()` instead
