### ISSUE TITLE
Unhandled error in findByIdAndUpdate

### ISSUE THREAD

**Issue by sshyvr** [Automattic/mongoose#5710]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Calling `findOneAndUpdate` or `findByIdAndUpdate` with a `$addToSet` field set to `undefined` or `null` throws a synchronous unhandled error.
```
/repro-mongoose-err/node_modules/mongoose/lib/services/updateValidators.js:39
          if (castedDoc[keys[i]][_keys[ii]].$each) {
                                           ^

TypeError: Cannot read property '$each' of undefined
    at module.exports (/repro-mongoose-err/node_modules/mongoose/lib/services/updateValidators.js:39:44)
    at Query._findAndModify (/repro-mongoose-err/node_modules/mongoose/lib/query.js:2251:20)
    at Query._findOneAndUpdate (/repro-mongoose-err/node_modules/mongoose/lib/query.js:2064:8)
    at /repro-mongoose-err/node_modules/kareem/index.js:250:8
    at /repro-mongoose-err/node_modules/kareem/index.js:23:7
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is a minimal single file example to help reproduce the issue.
```
'use strict';

const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
mongoose.connect('mongodb://localhost:27017/repro-test');

const db = mongoose.connection;
db.on('error', (err) => console.log('caught error on db.on') );

const someSchema = mongoose.Schema({
    strField: String,
    arrField: [String],
});

const SomeModel = mongoose.model('SomeModel', someSchema);
const someInstance = new SomeModel({ strField: 'foobar' });

someInstance.save((err, savedDoc) => {

    if (err) return console.error(err);
    console.log(`saved doc: `, savedDoc._id, savedDoc.strField);

    // So far so good...

    SomeModel.findOneAndUpdate(
        { _id: savedDoc._id },
        {
            $addToSet: {
                arrField: undefined         // Causes unhandled error
            }
        }
    )
    .exec()                  // Fails on both promise and callback versions
    .catch(err => {
        console.log(`caught error`, err);         // Never gets caught!!
    });

});
```

**What is the expected behavior?**
- An `undefined` or `null` field in `$addToSet` should not throw an error
- All unhandled exceptions should either be a Promise rejection, or an error on the callback

**Please mention your node.js, mongoose and MongoDB version.**
```
$ node --version
v6.11.4

$ yarn list mongoose bluebird
yarn list v1.1.0
├─ bluebird@3.5.1
└─ mongoose@4.12.1

$ mongod --version
db version v3.4.2
```

Please let me know if you need any other details to reproduce this issue. Thanks!

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate and fix ASAP

**Comment by sshyvr** [comment]
@vkarpov15 Thank you for fixing this issue really fast! It is still a mystery as to why the error was neither caught synchronously (try-catch) or asynchronous (promise.catch or callback).

**Comment by vkarpov15** [comment]
Because mongoose was throwing the error in a separate tick, so `try/catch` wouldn't work. Definitely an internal bug on mongoose's part and nothing you could do to catch the error outside of `process.on('uncaughtException')`

**Comment by as1414** [comment]
I am still having the same issue, but it is 2+ years later, so I'm sure I'm doing something wrong.  I've got a findByIdAndUpdate method inside of a try/catch block.  I've tried a dozen different setups, but I can't seem to push the error out to my catch block.  Should I be able to?  I see that this is resolved above and I've been searching for answers for most of the day, but I can't find any actual samples or resolutions.

**Comment by AbdelrahmanHafez** [comment]
@as1414 
The script below doesn't throw any errors, could you modify the script below to demonstrate the issue you're facing, and open a new issue with it?
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false });

const userSchema = new Schema({ arrField: [String] });

const User = mongoose.model('User', userSchema);

async function run () {
  const user = await User.create({});

  await User.findOneAndUpdate({ _id: user._id }, { $addToSet: { arrField: undefined } });

  console.log('All done.');
}

run().catch(console.error);
```

**Comment by as1414** [comment]
Thanks for the quick reply.  It may be because I'm newer to all of this (mongoose, node and async/await) that I'm not understanding.  I may have the syntax/order wrong or being trying to do something that is just not a good practice (I'm open to suggestions).

In the code above, I want to do my try/catch blocks in the "run" function and catch the error there before it returns anything.  My "run" function is a longer function that handles some validations, formatting, etc. and then updates the record if needed using the findByIdAndUpdate function (which I understand is similar to findOneAndUpdate).  

The bulk of the method lives inside of a try block, but the error that is being produced by the findByIdAndUpdate is not being caught in the catch block of that function.  The findByIdAndUpdate function has the error inside of the callback so I can see it there and I can deal with it, but I can't find a way to throw it out to the parent function ("run" in this case).

Here's something similar to what I have using your code from above:

`const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false });

const userSchema = new Schema({ arrField: [String] });

const User = mongoose.model('User', userSchema);

async function run () {
  try {
    const user = await User.create({});

    // do formatting, validation, etc.

    await User.findOneAndUpdate({ _id: user._id }, { $addToSet: { arrField: undefined } });

    console.log('All done.');
  catch (err) {
    // I am expecting to see my invalid casting error here, but it is just crashing
    console.log(err);
  }
}

run()

**Comment by AbdelrahmanHafez** [comment]
Don't worry, we've all been there.

Mongoose, like many other libraries out there, support both callback, and promises.

You can call most of the mongoose API with one of both options.

So you can either use it with a callback, like so:
```js
User.findOneAndUpdate({ _id: user._id }, { $addToSet: { arrField: undefined } }, {}, (err, res) => {
  console.log(res);
  console.log(err);
});
```

or using a promise:

```js
User.findOneAndUpdate({ _id: user._id }, { $addToSet: { arrField: undefined } })
.then((res) => {
  console.log(res);
})
.catch((err) => {
  console.log(err);
});
```

and the best solution with the best readability, is using async/await (which is syntactic sugar built on promises)

```js
try {
  const res = await User.findOneAndUpdate({ _id: user._id }, { $addToSet: { arrField: undefined } });
  console.log(res);
}
catch (err) {
  console.log(err);
}
```

You can learn more about callbacks/promises/async & await [here](https://scotch.io/courses/10-need-to-know-javascript-concepts/callbacks-promises-and-async).

**Comment by as1414** [comment]
Thank you again for your continued help!

My understanding of the callback in this case is that I can use it to make an evaluation to see if the update should proceed, something like a "pre-hook" where the find portion is done but the update is not committed.  So, if I do a custom evaluation in this function and return "false", then the update will not proceed.

So, if that is true, is there no way to use this functionality as well as handling any errors (i.e. type casting errors) in the parent/calling function using the try/catch blocks as outlined in your async/await example?

**Comment by vkarpov15** [comment]
`findOneAndUpdate()` is an atomic operation on the MongoDB server side, there isn't really a way to execute arbitrary logic between the find and the update. Usually, the trick is to structure your `filter` so that your `findOneAndUpdate()` is a no-op if your conditions aren't met. For example, suppose you only want to `$addToSet` if `User.role === 'ADMIN'`. You can do this:

```javascript
await User.findOneAndUpdate({ _id, role: 'ADMIN' }, { $addToSet: { arrField: val } });
```

Read more about [async/await here](https://masteringjs.io/tutorials/fundamentals/async-await).

**Comment by Rishi-121** [comment]
I am unable to handle the error in findByIdAndUpdate, can someone help me?

code:
try{
     const user = await User.findById(req.params.id);
     User.findByIdAndUpdate({_id:user._id }, {4set: req.body}, {new: true}, (err, doc)=> {
                         return res.json(doc);
            });
            
  }
  catch(err){
           next(err);
           }
           
           How can I throw an error on mismatched datatype like contact: "qwerty"?
