### ISSUE TITLE
getIndexes command not buffered or invoked in a wrong order 

### ISSUE THREAD

**Issue by anatoly314** [Automattic/mongoose#5756]
Can somebody explain me where I wrong?

As said in manual: 
> Mongoose buffers all the commands until it's connected to the database. This means that you don't have to wait until it connects to MongoDB in order to define models, run queries, etc.

But when I need to perform `getIndexes` command against not existing database I get an error: `no database`.

As I understand Mongoose connect to server on a startup and creates database if it doesn't exist. Also it creates collection according to model if it doesn't exists. So if it will perform all sequence above in order I invoked it: connect to database -> create if no database exists -> define model -> create collection -> get indexes of this collection, no error should be thrown.

Thank you in advance.

P.S. I need to invoke `getIndexes` command as part of my installation procedure.

**Comment by vkarpov15** [comment]
Mongoose does not explicitly [create collections or databases](https://docs.mongodb.com/manual/reference/command/create/) when it starts, because mongodb creates them on its own when you write to the database.

If you need to call `getIndexes()` when bootstrapping your application, you should handle the 'no database' error in a way that makes sense for your application. For example, if you're looking to make sure there's no out-of-date indexes then the 'no database' error means you're good to go, because there's no indexes at all. The error should have [`.code` = 26](https://github.com/mongodb/mongo/blob/09388643a69af34af0d123c7ccb814548454f35e/src/mongo/base/error_codes.err#L29)
