### ISSUE TITLE
how to change collection name with model 

### ISSUE THREAD

**Issue by AaronChen2012** [Automattic/mongoose#5767]
i have app log collection ,this is a dynamic  name by year and month, like log_201710 .
so insert data in current year month log collection,how do?

**Comment by vkarpov15** [comment]
Create a new model, `mongoose.model('Log201710', schema, 'log_201710')`.

**Comment by Jokero** [comment]
@vkarpov15 Is model creation a cheap and fast operation?
Is it ok to just create a model every time or it's better to cache it?
```js
// --- model.js
// without caching
exports.getCurrentModel = function() {
    const currentDate = now();
    return mongoose.model(`Log${currentDate}`, schema, `log_${currentDate}`);
};

// with caching
let currentDate;
let currentModel;
exports.getCurrentModelCached = function() {
    const newCurrentDate = now();
    if (!currentDate || currentDate.isBefore(newCurrentDate)) {
        currentDate = newCurrentDate;
        currentModel = mongoose.model(`Log${currentDate}`, schema, `log_${currentDate}`);
    }
    return currentModel;
};

// --- service.js
const { getCurrentModel } = require('model.js');
exports.getLogs = function() {
    return getCurrentModel.find().limit(50).exec();
};
```

**Comment by Jokero** [comment]
I've checked the `Mongoose.prototype.model` code and it looks like the model creation will be very trivial only in case when collection name is not passed.
For example:
```js
const model = mongoose.model('Log201710', schema);
const sameModelInstance = mongoose.model('Log201710', schema);
console.log(model === sameModelInstance); // true
```
But if you pass the collection param, every time you will get a different model:
```js
const model = mongoose.model('Log201710', schema, 'log201710');
const differentModelInstance = mongoose.model('Log201710', schema, 'log201710');
console.log(model === differentModelInstance); // false
```
In first example collection names are the same and models are equal, but in the second one we also have identical collection names, but models are already different. Inconsistency.

Snippet of `Mongoose.prototype.model` with `collection` param check:
```js
if (this.models[name] && options.cache !== false) {
    if (originalSchema && originalSchema.instanceOfSchema && originalSchema !== this.models[name].schema) {
        throw new mongoose.Error.OverwriteModelError(name);
    }

    if (collection) { // <--- here there is no check, that this collection is already used
        model = this.models[name];
        schema = model.prototype.schema;
        sub = model.__subclass(this.connection, schema, collection);
        return sub;
    }

    return this.models[name];
}
```

**Comment by vkarpov15** [comment]
You should create models once when your server starts, you should **not** create a new model for every request.

**Comment by Jokero** [comment]
@vkarpov15 I agree but if I need to change model at some period of time I have to create a new one.
And now I see inconsistent behavior in `mongoose.model`. When you specify only model name and schema you always will get the same model. New model will not be created. However if you add a collection name, every time new model will be created even if a collection name is always the same

**Comment by vkarpov15** [comment]
@Jokero I'm not a big fan of that behavior either, but it has been in Mongoose for many years and we haven't seen the need to change it. In what way do you need to change your model?

You can also explicitly call [`deleteModel()`](https://mongoosejs.com/docs/api.html#connection_Connection-deleteModel) to remove the model and then create a new one.

**Comment by Jokero** [comment]
@vkarpov15 I’m implementing daily rating in my application. And I’ve decided to use separate collections for storing data for every day. In order to do this I need to create a new model every day so that model will be connected with new collection. And this is simple because I can define a special function like `getDailyRatingModel` which will return me a mongoose model depending on current day:
```
function getDailyRatingModel() {
    const currentDay = getCurrentDay();
    return mongoose.model(`DailyRating${currentDay}`, schema);
```
And then I can call this function to get the actual model.
This works fine, new model is not created when you call `mongoose.model` with the same model name and schema. However, the problem happens when you additionally set collection name in `mongoose.model` as third param. And I actually always specified this param before, but now I’ve figured out that `mongoose.model` works differently depending on it. Even if you always set the same collection name, new model will be always created (and this can slowdown code execution), it will not be chosen from existent models dictionary. It’s not a big problem as I can skip this param and it will work as expected.
But in order to learn it I had to read source code and debug mongoose library :)

**Comment by vkarpov15** [comment]
@Jokero that's an interesting use case, hadn't thought of that. You're right that if you pass in the same schema, Mongoose won't recreate the model, but that behavior isn't [currently documented anywhere](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-model). We'll make this behavior more robust for a future release

**Comment by harshilishere** [comment]
I too have similar kind of a task like @Jokero . I need to save about 1500 transactions daily and then generate reports of them. The most efficient way to do it was to save the data under the name of the collection with the current date. But unable to find a way which can make this happen. So that when i fetch all the 1500 transactions of the day i can do it from one collection. 

Anybody found a possible way out!?

**Comment by vkarpov15** [comment]
@harshilishere what's preventing you from creating a new model with the same schema?

**Comment by harshilishere** [comment]
Hey @vkarpov15  yeah finally I was able to do that. Thanks for responding. You may close it again. Sorry I forgot to come back here and mention that I was able to resolve the problem.
