### ISSUE TITLE
There is a bug when I using aggregate 's  match()

### ISSUE THREAD

**Issue by grapewheel** [Automattic/mongoose#5806]
Like  this:
`let result = await this.aggregate()
        .match({seller: _id})
        .exec()`
Return **no records**, then I found mongoose didn't change the _id string to ObjectId type

Must be like this:
`let result = await this.aggregate()
        .match({seller: Mongoose.Types.ObjectId( _id)})
        .exec()`

Why the other find, findOne... functions change it for me, but not this??

mongoose version: 4.12.3

**Comment by wlingke** [comment]
@grapewheel there's easy no way for mongoose to always know what fields are defined as object ids in an aggregation pipeline because the schema in each stage of the pipeline is not static. In your example, `match` happens to be first  - so it feels analogous to a `find`. However, `match` can really be anywhere in the pipeline. 

It's plausible to do this if `match` is exactly the first stage in the pipe, but it feels like a bit of a feature bloat. Instead, it might be better to add a user-beware note in the docs for this. 

Would you want to make a PR for the docs @grapewheel ?

@vkarpov15 thoughts?

**Comment by grapewheel** [comment]
@wlingke Thx! I got it! Actually I used the aggregate to group the data after the match, But If I used the **find** first, and then use the **aggregate** , it would slow down the query. So adding a user-beware note is the only option.

**Comment by varunjayaraman** [comment]
yeah @wlingke is right, although I'm wondering if mongoose could help users out if it sees an `_id` field, to cast to a mongo id for you if it detects that you havent overriden `_id` in the schema.

Would that be a useful feature?

**Comment by vkarpov15** [comment]
@varunjayaraman @wlingke thanks for the suggestion. Its feasible but has a bit too many caveats. We can cast `$match` if its the first stage but that's it, seems like a very rough surface for the API.
