### ISSUE TITLE
Error when used with Nuxt: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by zikeji** [Automattic/mongoose#5903]
Apologies in advance if this is the wrong place to report this issue. The issue is with the Mongoose package, but Nuxt is causing it. So I've reported it on both repos.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Throws a TypeError when using populate / virtual populate.

**If the current behavior is a bug, please provide the steps to reproduce.**
[https://github.com/zikeji/nuxt-mongoose-interaction-bug](https://github.com/zikeji/nuxt-mongoose-interaction-bug)

**What is the expected behavior?**
Not to throw a TypeError and ignore that ref field altogether. It should return the references.

**Please mention your node.js, mongoose and MongoDB version.**
v.8.9.3, 4.13.7, 3.0.0-rc0

**Comment by zikeji** [comment]
See report on alternate repo: https://github.com/nuxt/nuxt.js/issues/2381

**Comment by simllll** [comment]
Just ran into the same issue, must be somehow related to a dependency upgrade. I had used shrinkwrap before, all was working fine even with nuxt@next, since I removed my shrinkwrap file and upgraded all (inclduign dependency) packages I have the same issue. Unfortuantely I couldn't track it down further yet...

**Comment by vkarpov15** [comment]
Will investigate but this will likely take a while, I have zero experiencw with nuxt...

**Comment by zikeji** [comment]
@vkarpov15 I'm not sure what your "need repro script" label means, I provided a repo that reproduces the issue

**Comment by vkarpov15** [comment]
The label means we generally prefer to have a standalone script that isolates a bug in mongoose, rather than a heavy repro project that takes me 30 seconds to recompile. I don't mean to be snarky, just having a standalone script versus an [enterprise-quality file structure and build system](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition) typically shaves days or weeks off of debugging :palm_tree: .

I can confirm that mongoose for some reason `populate()` is making `parent` null here: https://github.com/zikeji/nuxt-mongoose-interaction-bug/blob/65e660c84b9274dee04fe9df85c892a46e5d1ac1/src/server/api/children/controllers.js#L10 . But on the other hand, the below script works fine in vanilla node:

```javascript
const mongoose = require('mongoose');

const ObjectId = mongoose.Schema.Types.ObjectId;
const Schema = mongoose.Schema;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect('mongodb://localhost/bug', { useMongoClient: true });

  const childSchema = new mongoose.Schema({
    name: {
      type: String,
      required: true
    },
    parent: {
      type: mongoose.Schema.ObjectId,
      ref: 'Parent'
    }
  },
  {
    timestamps: true,
    toObject: {
      virtuals: true
    },
    toJSON: {
      virtuals: true
    }
  });

  childSchema.set('toJSON', {
    transform(doc, ret, options) {
      ret.id = ret._id
      delete ret._id
      delete ret.__v
      return ret
    }
  });

  const Child = mongoose.model('Child', childSchema);

  const parentSchema = new mongoose.Schema({
    name: {
      type: String,
      required: true
    }
  },
  {
    timestamps: true,
    toObject: {
      virtuals: true
    },
    toJSON: {
      virtuals: true
    }
  });

  parentSchema.virtual('children', {
    ref: 'Child',
    localField: '_id',
    foreignField: 'parent'
  });

  parentSchema.set('toJSON', {
    transform(doc, ret, options) {
      ret.id = ret._id
      delete ret._id
      delete ret.__v
      return ret
    }
  });

  const Parent = mongoose.model('Parent', parentSchema);

  const children = await Child.find({}).populate('parent');

  console.log(children);
}
```

`populate()` correctly populates `parent` with the same underlying data. This makes me think there's something wonky with Nuxt's build system. @simllll seems to have come to a similar conclusion: https://github.com/nuxt/nuxt.js/pull/2443 . @simllll do you know what about backpack makes mongoose bug out?

In general, I'd challenge you to think critically about why you're using a transpiler for server-side node code. With node 8, the only thing using a transpiler gives you is `import` statements and grey hairs. Async/await, `const x = { hello: 'world', ...y };`, etc. are all natively supported in node 8.

**Comment by vkarpov15** [comment]
Also can confirm that the above script :point_up: works fine with `backpack dev`. Haven't tried running it directly with nuxt but haven't been able to figure out how to do that :(

```javascript
 DONE  Compiled successfully in 996ms                                                                                                                                10:18:54

(node:11431) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[ { _id: 5a4135c71e900622198855e2,
    updatedAt: 2017-12-25T17:30:47.696Z,
    createdAt: 2017-12-25T17:30:47.696Z,
    name: 'Test',
    parent: 
     { _id: 5a4135c11e900622198855e1,
       updatedAt: 2017-12-25T17:30:41.805Z,
       createdAt: 2017-12-25T17:30:41.805Z,
       name: 'Test',
       __v: 0,
       children: null,
       id: '5a4135c11e900622198855e1' },
    __v: 0,
    id: '5a4135c71e900622198855e2' },
  { _id: 5a4135d61e900622198855e4,
    updatedAt: 2017-12-25T17:31:02.407Z,
    createdAt: 2017-12-25T17:31:02.407Z,
    name: 'Test2',
    parent: 
     { _id: 5a4135d11e900622198855e3,
       updatedAt: 2017-12-25T17:30:57.111Z,
       createdAt: 2017-12-25T17:30:57.111Z,
       name: 'Test2',
       __v: 0,
       children: null,
       id: '5a4135d11e900622198855e3' },
    __v: 0,
    id: '5a4135d61e900622198855e4' } ]
^C
$ ./node_modules/.bin/backpack dev
```

**Comment by zikeji** [comment]
https://github.com/nuxt/nuxt.js/issues/2381
https://github.com/nuxt/nuxt.js/pull/2443
https://github.com/zikeji/nuxt-mongoose-interaction-bug/issues

They appear to have identified the issue and a few potential solutions, so I'm going to go ahead and close this.
