### ISSUE TITLE
Can not connect mongo alias

### ISSUE THREAD

**Issue by hoangnguyenba** [Automattic/mongoose#5923]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Can not connect to mongo alias server via mongoose

**If the current behavior is a bug, please provide the steps to reproduce.**

I got uri from Mongo Alias:
`mongodb+srv://my_user_db:my_password_db@example-staging.com/test`
If I connect via mongodb, it's working:
`MongoClient.connect(config.db.MONGODB_CONNECTION, (err, data) => {
			console.log(err);
		})`
I get this error:
`Error: Invalid mongodb uri "mongodb+srv://my_user_db:my_password_db@example-staging.com/test". Must begin with "mongodb://"
`
**Please mention your node.js, mongoose and MongoDB version.**
Nodejs: 8.9.1
Mongoose: 4.12.5
MongoDB: 3.6

**Comment by BalasubramaniM** [comment]
Why this issue has been closed without any response? I too getting the same error and need a solution to overcome this.

**Comment by lineus** [comment]
@BalasubramaniM This issue was closed by the person who opened it. Presumably they sorted out their own problem.

The 'mongodb+srv' style of url isn't supported by mongoose until version 5.0.15 and beyond. If you're using an older version it won't work. If you're using a compatible version and still can't connect, please open a new issue or seek help in one of these communities:

[StackOverflow](https://stackoverflow.com/questions/tagged/mongoose)
[Gitter.im](https://gitter.im/Automattic/mongoose)
[Slack](https://mongoosejsteam.slack.com/)

**Comment by BalasubramaniM** [comment]
Thanks for a response. It worked after the update (5.0.15).

**Comment by aks30498** [comment]
Not working for me even after updating to 5.0.15
