### ISSUE TITLE
[Mongoose v5] Allow us to disable the pluralize part of models

### ISSUE THREAD

**Issue by KingDGrizzle** [Automattic/mongoose#5947]
**Do you want to request a *feature* or report a *bug*?**
I'd like to request a feature.

**What is the current behavior?**
Making a model of a word that isn't pluralized will make the model pluralized

**What is the expected behavior?**
By default the model would respect the entered string, not pluralize it. This can break backward-compatibility TOO much, to the point of data being missing due to certain words being non-plural.

I'd love for this to be a toggleable option in the connect options.

**Please mention your node.js, mongoose and MongoDB version.**
Node.JS v8.9.1
Mongoose v5.0.0-rc
MongoDB v3.6.0

**Comment by vkarpov15** [comment]
You can do this in 5.0.0-rc0:

```javascript
mongoose.pluralize(null);
```

This will make mongoose not pluralize collection names at all, so `mongoose.model('User', schema)` will store documents in the 'User' collection.

We considered making this the default for 5.0.0-rc0 (see discussion on #5878) but decided against it because we didn't think we'd given enough notice.

**Comment by Kezzsim** [comment]
The above solution doesn't appear to be working when using Typescript in mongoose version 5.12.3.
When doing `import mongoose from "mongoose";` and then trying `mongoose.pluralize(null);` the compiler says:
<img width="1075" alt="Screen Shot 2021-04-26 at 1 39 51 PM" src="https://user-images.githubusercontent.com/15878154/116127512-f115ae80-a695-11eb-904e-f0651c957045.png">
Which makes sense when I look at the type definition, which seems to be just for a standard getter/setter incapable of intaking a null argument:
<img width="660" alt="Screen Shot 2021-04-26 at 1 40 07 PM" src="https://user-images.githubusercontent.com/15878154/116127621-0f7baa00-a696-11eb-8335-b76771d7ce46.png">

This issue's solution might need to be updated for clarity since multiple other threads on the subject link to it.
