### ISSUE TITLE
Promises: .catch() not working on Model.create/save

### ISSUE THREAD

**Issue by Sparki2002** [Automattic/mongoose#5987]
Hi,

im using `mongoose 4.13.9` on `node 8.9.4` with native promises
```js
mongoose.Promise = global.Promise
```

**Problem:**
The `.catch()` part on create/save is never executed (it's working on `.find()`)

**Example:**
This is working
```js
User.create({ email, password }, err => reject(err));
```

This is not
```js
User.create({ email, password })
    .then(resolve())
    .catch(err => reject(err));
```

**Comment by vkarpov15** [comment]
Because you're always resolving your promise immediately without actually waiting for `User.create()` to finish. Do this instead:

```javascript
User.create({ email, password })
    .then(() => resolve())
    .catch(err => reject(err));
```

Based on your code, it looks like you have something like this:

```javascript
new Promise((resolve, reject) => {
  User.create({ email, password })
    .then(() => resolve())
    .catch(err => reject(err));
});
```

This is cumbersome, you're creating an extra promise for no reason, `User.create()` already returns a promise so no need to wrap it in another promise.
