### ISSUE TITLE
schema.indexes() does not include default _id_ index

### ISSUE THREAD

**Issue by viveleroi** [Automattic/mongoose#5998]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** `schema.indexes()` does not include an entry for the default MongoDB index `_id_`.

**What is the expected behavior?** `schema.indexes()` should return all indices.

Node v9.2.1, MongoDB v3.4.10, Mongoose 4.9.x and 5.0.0rc2

I tried asking in gitter for support, in case I'm missing something, but got no reply. I've written a plugin that needs to know about a collection's indices and `schema.indexes()` is not giving me the full list.

**Comment by vkarpov15** [comment]
Upon more careful thought, this is not something we're going to fix. The idea of `schema.indexes()` is it returns the indexes that are declared on the schema, which may or may not line up with the indexes in the actual database. For example, you may turn `autoIndex` off in production, or you may have an extra index in the db that isn't in your schema that you created using `createIndex()` from the shell. Changing `schema.indexes()` from a function that just pulls the indexes from the schema into a function that pulls the existing databases from the db is a major backwards breaking change.

Since you need the `_id` index for your plugin, you can hard code it because you can safely assume that it is always there. [The MongoDB server automatically creates that index and does not allow removing or modifying it in any way](https://docs.mongodb.com/manual/indexes/#default-id-index).
