### ISSUE TITLE
Custom validators are not called on specific update operations

### ISSUE THREAD

**Issue by Saravanan90** [Automattic/mongoose#6009]
During findOneAndUpdate(), custom validators are not getting run on when `$addToSet`, `$push` is used.

**Sample Code Snippet:**

```
var schema = mongoose.Schema({
    emails: {
        type: [
            {
                type: String,
                validate: [validator.isEmail, 'Invalid email']
            }
        ],
        validate: {
            validator: function(v) {
                return (v.length <= 10);
            }
        }
    }
});
var Blob = mongoose.model("Blob", schema);

Blob.findOneAndUpdate(
    { name: "blob1" },
    { $addToSet: { emails: "abc@xyz.com" } },
    { runValidators: true, new: true }
).then(...)

```
The validator, whether an element in set is an email field, is getting called, but the validator for the set, to check whether the number of values in set hasn't reached the upper limit, is not getting called. When `$set` operator is used, the validator is getting called, not for operators like `$addToSet` `$push`

node version: 4.4.7
mongodb version: 3.4.10
mongoose version: 4.11.3

**Comment by Saravanan90** [comment]
@vkarpov15 As commented in other related issues which are closed, I have opened a new issue.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP :+1:

**Comment by vkarpov15** [comment]
Upon closer inspection I think I understand your issue: you're confused about why you're not getting an error when `$addToSet` brings the number of emails above 10. That's an unfortunate limitation of update validators, when [using operators like `$addToSet` mongoose does **not** run validation on the array](http://mongoosejs.com/docs/validation.html#update-validators-only-run-on-specified-paths). That's because the whole array isn't in memory, so mongoose would have to execute a separate query.

Your best bet would be to do this instead, this will only add 'abc@xyz.com' to `emails` if it isn't already there and limit emails to 10. See [MongoDB docs](https://docs.mongodb.com/manual/reference/operator/update/push/#append-multiple-values-to-an-array)

```javascript
Blob.findOneAndUpdate(
    { name: "blob1", emails: { $ne: 'abc@xyz.com' } },
    { $push: { emails: { $each: ["abc@xyz.com"], $slice: 10 } },
    { runValidators: true, new: true }
)
```
