### ISSUE TITLE
schema.pre('init', function (next) -> next is doc not a function

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#6037]
I just upgraded to mongoose 5.0.1 and most of the tests started failing and the reason seems to be that when running this code:

```
schema.pre('init', function ensureSummaryIsFetched (next) {
  console.log('pre init', 'next', next, 'this', this)
  const group = this;
  ...
  next()
});
```

`next` is not a function but the document itself

**Comment by paglias** [comment]
Reproduction script https://gist.github.com/paglias/ad7dd5f0b5dff22c9dc2cb8b5f801253, using mongoose 5.0.1 on node 6.12.3

**Comment by vkarpov15** [comment]
This is a change we made in 5.0.0 https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#init-hook-signatures because init hooks have always been synchronous, so giving them a `next()` parameter was a loaded footgun. Is this something you can refactor on your end or do you need some help?

**Comment by paglias** [comment]
@vkarpov15 sorry, I went through the migration doc but completely missed that part, closing the issue
