### ISSUE TITLE
Using sinon.useFakeTimers prevents doc from saving (in 5.0)

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#6074]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Noticed some tests failing, turns out that after upgrading to 5.0.x using sinon.useFakeTimers (http://sinonjs.org/releases/v4.2.2/fake-timers/) is the cause.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/paglias/943c6f3c3efbce095c0e6257eac9b4ae -> Using mongoose 4 it works correctly, with version 5 it doesn't unless you comment out line 12. I've tried with past and future dates and even enabling mongoose debugging but there's no info at all. 

From testing I noticed that it arrives up to the pre validate hooks but not further

**What is the expected behavior?**
It should save docs with sinon.js and useFakeTimers

**Please mention your node.js, mongoose and MongoDB version.**
node 6 or 8
mongo 3.4
mongoose

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP :+1:

**Comment by vkarpov15** [comment]
Yeah this is a feature of sinon, `useFakeTimers()` [stubs out `setImmediate()`](https://github.com/sinonjs/lolex#automatically-incrementing-mocked-time), so when mongoose uses `setImmediate()` internally everything goes straight to hell. In my experience, the practice of stubbing out language-specific global state like `useFakeTimers()` is one to avoid because you never know how a library will react to things like `setImmediate()` never calling its callback, and it isn't something libraries test for.

Since sinon is so popular, we'll switch back to using `process.nextTick()` everywhere because sinon doesn't stub that out by default.

**Comment by paglias** [comment]
Thanks! Unfortunately we have some stuff that relies a lot on dates and sinon is quite easy to simulate them. We could probably switch to passing a date parameter to functions but when you have a lot of nested functions it becomes messy

**Comment by vkarpov15** [comment]
@paglias granted. What I usually do is just have a `time.js` file that exports a `now()` function that sinon can stub, and place `new Date()` usage with `time.now()`. Makes things a little cleaner because tweaking global behavior that other libs might rely on is dangerous.
