### ISSUE TITLE
docs: details of "useMongoClient" "new connection logic are not documented

### ISSUE THREAD

**Issue by markstos** [Automattic/mongoose#6118]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Docs for `useMongoClient` refer opt'ing into "new connection logic", but what the logic is not documented. This matters because apparently the new logic is not always desirable, as seen in #6117.

Better docs could help users evaluate whether or not to enable the option.

**What is the expected behavior?**

Clearer docs.

**Please mention your node.js, mongoose and MongoDB version.**

Mongoose 4.13.8

**Comment by vkarpov15** [comment]
The particular quirks are really difficult to enumerate because we ripped out a lot of legacy baggage in favor of something that defers to the [mongodb driver's `MongoClient.connect()` function](http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html#connect). There aren't any intended breaking changes as long as you're connecting using a connection string.
