### ISSUE TITLE
While querying an array of dates with $elemMatch, mongoose compares dates as string and not as Date

### ISSUE THREAD

**Issue by sidgujrathi** [Automattic/mongoose#6143]
I have array of dates store in collection and wants to query document using $elemMatch on dates, but whenever I am firing query, mongoose compares dates as String and not as Date()

Example:

I have following collection:

`"_id" : ObjectId("5a8442137c51100001b83757")
"financial_years" : {
        "from" : ISODate("2017-04-01T00:00:00.000Z"),
        "to" : ISODate("2018-03-31T00:00:00.000Z")
    }
"__v" : 0`

If I `find()` document with condition `{ financial_years: { $elemMatch: { from: "04/01/2017", to: "21/03/2018" } } }`

Mongoose doesn't convert `from: "04/01/2017"` this to Date object instead it fires same as above.

Expected query should be `{ financial_years: { $elemMatch: { from: new Date("Sat, 01 Apr 2017 18:30:00 GMT"), to: new Date("Fri, 31 Mar 2018 18:30:00 GMT") } } }`

I am using -- mongoose@4.13.11 with Node 6.11.1

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap. If you can create a standalone script that reproduces your issue that will save us some time :+1:

**Comment by varunjayaraman** [comment]
It looks like mongoose doesn't auto convert that date-string format `MM/DD/YYYY` correctly:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6143`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({
    dates: [{ from: Date, to: Date }]
  });

  const Model = mongoose.model('Model', schema);

  await Model.remove({});
  await Model.create({
    dates: [
      { from: new Date('2017-05-01'), to: new Date('2018-01-01') }
    ]
  });

  console.log(
    await Model.findOne({
      dates: {
        $elemMatch: {
          from: '05/01/2017',
          to: '01/01/2018'
        }
      }
    })
  );


}

```

this logs `null` when it should log the record correctly (as it does if you do it as `YYYY-MM-DD`

**Comment by vkarpov15** [comment]
Mongoose is comparing these strings as dates, it is just a question of how mongoose converts these strings to dates. Mongoose uses the [built-in JavaScript `Date` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), which has [nuances about what time zone it assumes for certain strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Differences_in_assumed_time_zone). Specifically, it assumes 'YYYY-MM-DD' dates are in UTC, but 'MM/DD/YYYY' dates are in your local timezone. For example, note the difference below is 7 hours, which lines up with the fact that my computer is configured for the America/Los_Angeles time zone:

```
$ node 
> new Date('2017-05-01')
2017-05-01T00:00:00.000Z
> new Date('05/01/2017')
2017-05-01T07:00:00.000Z
> 
```

@varunjayaraman 's script above with debug mode shows that mongoose is querying by date, just off by a few hours because of the implied time zone in the string:

```
$ node gh-6143.js 
Mongoose: models.remove({}, {})
Mongoose: models.insert({ dates: [ { from: new Date("Mon, 01 May 2017 00:00:00 GMT"), to: new Date("Mon, 01 Jan 2018 00:00:00 GMT"), _id: ObjectId("5a973363d63a0b33571a160d") } ], _id: ObjectId("5a973363d63a0b33571a160e"), __v: 0 })
Mongoose: models.findOne({ dates: { '$elemMatch': { from: new Date("Mon, 01 May 2017 07:00:00 GMT"), to: new Date("Mon, 01 Jan 2018 08:00:00 GMT") } } }, { fields: {} })
null
^C
$ 
```
