### ISSUE TITLE
Set function is bound to different objects depending on how it's triggered

### ISSUE THREAD

**Issue by diegohaz** [Automattic/mongoose#6155]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`this` inside the function passed to set in `schema.path().set(function() {})` is inconsistent. Sometimes it's the document, sometimes, the model. When it's triggered by `new Model({ foo: 'bar' })` or `Model.create({ foo: 'bar' })`, `this` is the model.

**If the current behavior is a bug, please provide the steps to reproduce.**
```sh
git clone https://github.com/diegohaz/mongoose-keywords
cd mongoose-keywords
yarn
yarn test # make sure mongod is running
... # everything will pass because it's still using Mongoose v4
yarn upgrade mongoose --latest
yarn test
... # it will throw an error in one test using `Model.create` because `this` became the model, instead of document
```

**What is the expected behavior?**
`this` to always be the document.

**Please mention your node.js, mongoose and MongoDB version.**

Node: v9.4.0
Mongoose: v5.0.6
MongoDB: v3.6.2

**Comment by varunjayaraman** [comment]
I'm not able to reproduce this. The console.log I've placed inside the setter shows an empty object `{}`, which means its the instance and not the `Model` or else it would be a huge object:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6155`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({ name: String, test: Number });

  schema.path('name').set(function(v) {
    console.log(this); // {}
    return v;
  });
  
  const Model = mongoose.model('Model', schema);

  const doc = new Model({ name: 'test', test: 5 });

  console.log('doc', doc);

  await Model.create({ name: 'test' }); // again logs {}
}
```

**Comment by diegohaz** [comment]
Hi, @varunjayaraman. That's the same that happened to me (it logs empty object).

However, if `this` was the doc, shouldn't it log `{ _id: ..., name: 'test', test: 5 }` and `{ _id: ..., name: 'test'  }`.

I only figured out that it was the model by logging `Object.keys(this)`. Could you try that? Or is that repro hosted somewhere?

**Comment by diegohaz** [comment]
So, is that part intended to not be backward compatible with v4? Shouldn't it be added to the migration guide at least? That broke one of my mongoose plugins (https://github.com/diegohaz/mongoose-keywords/issues/12) and it wasn't easy to find the source the problem.

**Comment by vkarpov15** [comment]
@diegohaz it's not intended to break compatibility with v4. @varunjayaraman 's script above has the below output with 4.13.11

```
$ node gh-6155.js 
(node:12320) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
{ test: 5, _id: 5aa064a51f0bba3020bb15e1 }
doc { name: 'test', test: 5, _id: 5aa064a51f0bba3020bb15e1 }
{ _id: 5aa064a51f0bba3020bb15e2 }
^C
$ 
```

The `_id` is because we switched defaults to apply after the initial setting of the doc. The reason why 'test' shows up in the first `console.log()` is because mongoose 4 iterated through keys in reverse, so it would set 'name' before setting 'test', whereas [mongoose 5 always uses forward order for iterating through keys](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#always-use-forward-key-order).

I'll take a look at mongoose-keywords and see what the issue is. Thanks for your patience

**Comment by vkarpov15** [comment]
I tracked this down to the fix for #3781, looks like that fix had some unforeseen consequences that caused your plugin to break. This issue doesn't affect all 5.x versions, just 5.0.5-5.0.9. We'll have a fix in 5.0.10, I can confirm your basic example works with 95c6685 above:

```javascript
var mongoose = require('mongoose');
 
var ArtistSchema = new mongoose.Schema({
  name: String
});
 
ArtistSchema.plugin(require('mongoose-keywords'), {paths: ['name']});
 
var Artist = mongoose.model('Artist', ArtistSchema);
 
var artist = new Artist({name: "L'arc~en~Ciel"});
console.log(artist.keywords); // ['larc en ciel']
```

Don't hesitate to reach out if you run into any other issues, we're always happy to help plugin authors. Particularly ones that have excellent J-Rock tastes, I love L'arc~en~Ciel, Daybreak's Bell is easily a top 10 all-time anime song :+1:

**Comment by diegohaz** [comment]
Hey, @vkarpov15. Thank you so much. 

I'm always meeting J-Rock fans out there through that project hahaha

**Comment by diegohaz** [comment]
Accordingly to https://github.com/diegohaz/mongoose-keywords/issues/12#issuecomment-376360406, it seems that the issue wasn't completely solved. 

It can still be something with my plugin though. I'll try to look at that next weekend.

Just posting here so you guys may find something in the meanwhile.

**Comment by vkarpov15** [comment]
@diegohaz thanks for the heads up. If you can provide a script that reproduces the issue, we'd be happy to take a look.
