### ISSUE TITLE
Schema methods aren't propagated again

### ISSUE THREAD

**Issue by mirkods** [Automattic/mongoose#6237]
**Do you want to request a *feature* or report a *bug*?** 
Report a bug

**What is the current behavior?**
5.0.10

**If the current behavior is a bug, please provide the steps to reproduce.**
I notice a breaking change not reported in list between mongoose 4 and 5. Seems that schema methods in mongoose 5 aren't propagated to nested properties as in mongoose 4. 

Mongoose 4.9.8:
```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const mySchema = new Schema({
  myObj: {
    test: {
      type: String
    }
  }
});

mySchema.methods.myFn = () => {};
const MySchema = mongoose.model('MySchema', mySchema);

const instance = new MySchema();

console.log(typeof instance.myFn) // function
console.log(typeof instance.myObj.myFn) // function
```

Mongoose 5.0.10:
```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const mySchema = new Schema({
  myObj: {
    test: {
      type: String
    }
  }
});

mySchema.methods.myFn = () => {};
const MySchema = mongoose.model('MySchema', mySchema);

const instance = new MySchema();

console.log(typeof instance.myFn) // function
console.log(typeof instance.myObj.myFn) // undefined
```

**What is the expected behavior?**
The same of the example with mongoose 4.9.8

**Please mention your node.js, mongoose and MongoDB version.**
- node 8.9.3
- mongodb 3.6.3
- mongoose 5.0.10

Mirko

**Comment by lineus** [comment]
Hi @mirkods. I had never seen the expectation of being able to call instance methods directly on a model instance property documented anywhere before, so I dug into it a bit, and it seems that this behavior changed in version 4.12. 

I verified that it behaves as you expected all the way up to and including 4.11.14. After a bit of digging I discovered that this was indeed intentional per #5470. The change was documented in the History.md file that gets shipped in the root of the mongoose npm package and is also available [here](https://github.com/Automattic/mongoose/blob/master/History.md).

I was curious how this might be useful, and came up with the following example:
```
'use strict'
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const mySchema = new Schema({
  myObj: {
    test: {
      type: String
    }
  }
})

mySchema.methods.myFn = function () {
  return Object.keys(this.toObject())
}

const MySchema = mongoose.model('MySchema', mySchema)

const instance = new MySchema({
  myObj: {
    test: 'testing123'
  }
})

console.log(instance.myFn())
console.log(instance.myObj.myFn())
```
### output on 4.11.14:
```
mongoose4: node ./6237.js
[ '_id', 'myObj' ]
[ 'test' ]
mongoose4: 
```
I'm curious how you were taking advantage of this. If you'd care to elaborate on how you were using it, I'd be interested in knowing. Is it something that you can replace with getters/setters set on a particular path?

**Comment by mirkods** [comment]
Hi @lineus thanks for your response. I was having advantage from this behaviour because I was able to call the methods function on subset of the model instead of the whole model. I understand that probably this behavior has happened from a side affect and not properly implemented but this can be considered as breaking change.

**Comment by lineus** [comment]
@mirkods you're welcome!

> I understand that probably this behavior has happened from a side affect and not properly implemented but this can be considered as breaking change.

The fact that this wasn't a documented feature (or public API) is the reason why it's not a backwards-breaking change. Normally I avoid being pedantic, but in this case, it's part of what defines a backwards-breaking change. You can check out the spec for semver [here](https://semver.org/). Let me know if you have any questions.

**Comment by mirkods** [comment]
It makes sense. Thanks for the clarification.

**Comment by vkarpov15** [comment]
@mirkods @lineus is right, we made this change in 4.12.0 (specifically #5546) because this was an unintentional quirk of how nested docs were implemented that caused a lot of problems, and was not a supported feature.

Can you elaborate a bit on some use cases where you used this pattern? We'd love to help and see if we can make your task of migrating to mongoose 5 easier.

**Comment by mirkods** [comment]
Hi @vkarpov15 and thanks for your explanation. I have already migrated my code to mongoose 5.

**Comment by vkarpov15** [comment]
Great! Thanks for upgrading and for reporting this issue, feel free to reach out if you run into any more difficulties.
