### ISSUE TITLE
Mongoose populate query on populate field and filter the result that have null

### ISSUE THREAD

**Issue by pratraj** [Automattic/mongoose#6293]
I have users collection that has data and their post referenced id.

```javascript
users:[
    {
        _id:"bxhhsjjsj09923445325",
        name:"My Name",
        myPosts:["ppan232342423","iweiej004994"]

    }
]
and the posts collection data is below.

posts:[
    {
        _id:"ppan232342423",
        data:"Hello Hi",
        isDeleted:false
    }
    {
        _id:"iweiej004994",
        data:"Bye Bye",
        isDeleted:true
    }
]
```
I am writing a query on Users Scheme and filter the post that is Deleted. I want to filter the User data that post returns null.

```javascript
users.find().populate({
        path: 'myPosts',
        model: 'posts',
        match: {isDeleted:true},
    })
```

**Comment by varunjayaraman** [comment]
thanks @lineus . Yeah i think what he is asking for is to modify the initial query based on fields within the "join"ed or populated collection. That's not really possible @pratraj  without, as you suggested, using aggregation or making separate queries and combining them. This is just an inherent difference between MongoDB and other SQL solutions because mongoose populates are illusory joins and are actually separate queries (unless you use the aggregation framework's $lookup)

**Comment by RodrigoOkuta** [comment]
@varunjayaraman Did you find a solution? I am also trying to filter the null result from my populate. I couldn't make it work with $lookup as well.

**Comment by vkarpov15** [comment]
@RodrigoOkuta please open a new issue with code samples.
