### ISSUE TITLE
Support for selected fields in Model.hydrate()

### ISSUE THREAD

**Issue by gonenduk** [Automattic/mongoose#6300]
I'm using node 9.10.1 and mongoose 5.0.12.
When I declare a schema, I don't want to expose the __v field in my API but I do want it to be in the DB.
What I do is add this line to the schema to remove the field from queries:
schema.add({__v: {type: Number, select: false}});
When doing find operations it is indeed not shown in the results.
When doing create it is included in the returned document. I believe the correct behavior is not to include it also when creating a new document.

**Comment by vkarpov15** [comment]
Unfortunately that isn't something we can support, that would be a huge breaking change because then creating a new document with `new MyModel()` would also exclude de-selected fields. However, I think we should add this feature to [`Model.hydrate()`](http://mongoosejs.com/docs/api.html#hydrate_hydrate)

**Comment by vkarpov15** [comment]
Fixed by #9209 in v5.9.24
