### ISSUE TITLE
Enhance ObjectId#equals()

### ISSUE THREAD

**Issue by kitce** [Automattic/mongoose#6301]
I know that the type `ObjectId` comes from the native MongoDB driver, I wonder if it could be enhanced.

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

```
const Schema = new mongoose.Schema();
const Model = mongoose.model('Schema', Schema);
const id = mongoose.Types.ObjectId();
const doc = new Model({_id : id});
doc.equals(doc); // true
doc.equals(id); // true
id.equals(id); // true
id.equals(doc); // false
```

**What is the expected behavior?**

Since I am comparing two parameters, they could be either a `Document` or an `ObjectId`, I assume they are same when their `_id` match.
It could be quite annoying that I have to check their types every time.
I think it will be nice that if both `Document#equals()` and `ObjectId#equals()` could support comparing with `Document` and `ObjectId`.
```
id.equals(doc); // true
```

**Please mention your node.js, mongoose and MongoDB version.**

node v8.10.0
mongoose 5.0.12
MongoDB 3.6.2

**Comment by vkarpov15** [comment]
This is a good idea, we will add this feature in a future release :+1:

**Comment by vkarpov15** [comment]
I'm going to close this one for now because this will be trickier than I anticipated. There's 2 ways to do this: make mongoose objectids a separate class that inherits from a mongodb objectid, or overwrite the mongodb ObjectId#equals() function. The latter is dangerous, and the former is much trickier than I had imagined.
