### ISSUE TITLE
Mongoose Save API fail with Document Not Found Error

### ISSUE THREAD

**Issue by sarmask33** [Automattic/mongoose#6327]
Mongoose version: 5.0.0

**Do you want to request a *feature* or report a *bug*?**
I'm new to mongoose and I'm not sure its a bug or i'm missing something.

**What is the current behavior?**
I'm getting "Document Not found Error" when updating a model and saving them using mongoose save method.

**If the current behavior is a bug, please provide the steps to reproduce.**

Attached the zip file which contains the source code. The error occurs in seed.js line 73. 

[models.zip](https://github.com/Automattic/mongoose/files/1887197/models.zip)
![cmd-error](https://user-images.githubusercontent.com/38178609/38465634-c3dab69a-3b3b-11e8-96ae-15078c6e0c3e.png)

**What is the expected behavior?**
I'm expecting that save method works fine without any issue. If i use mongo db shell i can see that the document exist in database.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 8.9.3, Mongoose: 5.0.0, Mongo: 3.6.0

**Comment by lineus** [comment]
Hi @sarmask33 Welcome to mongoose and node! 

I took a look at the code in seed.js and found the problem.

In order to run the seed file with minimal changes I created a file called index.js:
```
models>: cat index.js
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const seedDB = require('./seed')

seedDB()
```

here are the changes that I made to seed.js
   1. Use the builtin addToSet method of the mongoose array. It casts the value to the definition in the schema and won't duplicate existing entreis, so you wind up with only unique _id(s) in the array. 

```
-                foundCg.comments = foundCg.comments.concat(foundC);
+                foundCg.comments.addToSet(foundC);
```

   2. The second thing I changed was the use of .then() on the call to save() with the incorrect parameter signature.
```
-                foundCg.save().then(function(err, savedCg){
+                foundCg.save(function(err, savedCg){

```

### here is the output from index.js:
```
models>: ./index.js
foundCg: CG1
        To be foundComments: Nice Place !
        To be foundComments: Ok OK
        To be foundComments: Beautiful
foundCg: CG2
        To be foundComments: Nice Place !
        To be foundComments: Ok OK
        To be foundComments: Beautiful
found comments: Nice Place !
found comments: Beautiful
found comments: Ok OK
Title: CG1, Image: image1
Title: CG1, Image: image1
Title: CG2, Image: image2
^C
models>:
```
### here is what got stored in mongodb:
```
models>: mongo --quiet test
> db.campgrounds.find().pretty()
{
        "_id" : ObjectId("5aca133a03433f6bece12180"),
        "comments" : [
                ObjectId("5aca133a03433f6bece12182"),
                ObjectId("5aca133a03433f6bece12184")
        ],
        "title" : "CG1",
        "image" : "image1",
        "__v" : 2
}
{
        "_id" : ObjectId("5aca133a03433f6bece12181"),
        "comments" : [
                ObjectId("5aca133a03433f6bece12183")
        ],
        "title" : "CG2",
        "image" : "image2",
        "__v" : 1
}
>
```
If you have any questions or just want to chat about mongoose, feel free to join us on the [slack channel for mongoose](https://mongoosejsteam.slack.com/) or the [gitter community for mongoose](https://gitter.im/Automattic/mongoose)

**Comment by sarmask33** [comment]
HI @lineus Thanks for your clarification. It solved the issue. But I have two questions,

1) The error was misleading, it was prompting for "Document Not found" and not Duplicate Unique Id. How do you explain that.
2) By retaining the line "foundCg.comments = foundCg.comments.concat(foundC);"  and by using findByIdAndUpdate instead of save also works fine. 

/*Campground.findByIdAndUpdate(foundCg._id, foundCg, function(err, updatedCg){
     if(err){
	console.log("Error in saving cg: " + err);
     }else{
	updatedCg.print();
     });	*/	

so not sure if save is running into "Document Not Found Error" because of multiple calls in a loop which is avoided either by using "addToSet" or "findByIdAndUpdate".

Thanks for your time.

**Comment by sarmask33** [comment]
HI @lineus Thanks for your detailed explanation and clarification. The gist helped me.
I understood the difference between "save" and "findByIdAndUpdate" and "Document not found error due to version". But still one thing is bothering me in this,
* How $addToSet solves the issue?
It just removes the duplicates in comment array of campground, but how adding it solves "async save issue and document not found error". Looks like i'm still missing something.

Thanks for your time.

**Comment by lineus** [comment]
You're welcome @sarmask33! 

>How $addToSet solves the issue?
It just removes the duplicates in comment array of campground, but how adding it solves "async save issue and document not found error". Looks like i'm still missing something.

mongoose can detect when your array path has been changed with addToSet vs. other methods 
( such as concat in this case ). If the array has been changed with addToSet it does not require the version (`__v`) property to be included in the query condition in the call to save. This is a protection against two disparate processes potentially mutating an array within a document of the same version. 

For example, say two people (A & B) both load the same route from your http server at roughly the same time. They both retrieve the same version of the document. Person A adds to the contents of what will eventually get stored back into the array, while person B adds to the contents of the same array but with different values. 

With addToSet, we can safely allow both people to add values to the array because we can trust that addToSet will only add unique values. Other methods, concat in this case, could cause the second user's update call to the db to wipe out the first user's save.

**Comment by sarmask33** [comment]
Thank you for the clarifications.
