### ISSUE TITLE
Pre hook for custom method

### ISSUE THREAD

**Issue by iofjuupasli** [Automattic/mongoose#6385]
This code works in v4, but doesn't in v5:

```js
const mongoose = require(`mongoose`);

const mySchema = new mongoose.Schema({
    host: {type: String}
});

mySchema.method(`foo`, function () {
    console.log(`method called`);
});
mySchema.pre(`foo`, function (next) {
    console.log(`hook`);
    next();
});
const MyModel = mongoose.model('User', mySchema);

// should fail
const model = new MyModel({host: `foo`});
model.foo();
```

It seems that it was undocumented, but maybe it would be nice to restore that feature?

**Comment by vkarpov15** [comment]
Definitely an unintentional change. Will look into fixing :+1:

**Comment by iofjuupasli** [comment]
@vkarpov15 
Now I have issues with args in hook and with return type:

```js
const mongoose = require(`mongoose`);

const mySchema = new mongoose.Schema({
    host: {type: String}
});

mySchema.method(`foo`, async function () {
    console.log(`method called`);
    return Promise.resolve({resolved: true});
});
mySchema.pre(`foo`, async function (a) {
    console.log(`args: ${a}`); // BUG: a is callback, should be argument == `test arg`
    console.log(`hook`);
    return Promise.resolve();
});
const MyModel = mongoose.model('User', mySchema);

const model = new MyModel({host: `foo`});
model.foo(`test arg`).then((res) => { // BUG: method returns undefined
    console.log(res);
});
```

**Comment by vkarpov15** [comment]
5.1.2 will allow returning a promise from a custom method with middleware. So the below will be fine:

```javascript
mySchema.method(`foo`, function () {
    console.log(`method called`);
    return Promise.resolve({resolved: true});
});
```

 However, the first argument to the function will still be a callback `next()`. To support existing middleware, we currently enforce that the first arg to a middleware function is always `next()`, and then the other arguments come afterward. To access `a` in your method, do this:

```javascript
mySchema.pre(`foo`, function (next, a) {
    console.log(a); // `test arg`
    console.log(`hook`);
    return Promise.resolve();
});
```

Also, sidebar: there is no need to `return Promise.resolve()` from an async function, it's unnecessary and adds wasteful performance overhead. Node.js always creates a new promise whenever you call an async function, so you should just do `return undefined;` instead of `return Promise.resolve();` and `return { resolved: true }` instead of `return Promise.resolve({ resolved: true })` to avoid creating unnecessary promises. Check out [my blog post on async/await return values](https://thecodebarbarian.com/80-20-guide-to-async-await-in-node.js#return-values-and-exceptions) for more info.

**Comment by corbfon** [comment]
@vkarpov15 I've got a similar use case, except with using instance methods. I am returning promises, and therefore have no use case for the callback functions. When I define an instance method so:

```javascript
const mongoose = require(`mongoose`);

const mySchema = new mongoose.Schema({
    host: {type: String}
});

mySchema.method(`foo`, async function (options, cb) {
    return options
});

const MyModel = mongoose.model('User', mySchema);

const model = new MyModel({host: `foo`});
model.foo({ bar: 'baz' }).then((res) => {
    console.log(res); // this logs a callback function
});
```

The only way I can get this to work is by actually sending the instance method another parameter when calling it (it doesn't seem to matter what I pass, mongoose seems to assume it's a callback). For example, this works:

```javascript
// all the model declarations as above
model.foo({ bar: 'baz' }, false).then((res) => { // see how I'm passing 
    console.log(res); // this logs the options correctly
});
```

**Comment by corbfon** [comment]
@vkarpov15 I know you've seen this already. For others who come here, there is an [issue with script to reproduce](/Automattic/mongoose/issues/7456)
