### ISSUE TITLE
Default Schema Collation Options Not Being Added to MongoDB

### ISSUE THREAD

**Issue by lmshaffe** [Automattic/mongoose#6489]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When creating a Mongoose schema with collation options, the collection that is created does not have those collation options as a default. This is verified with `db.getCollectionInfos({name: <collection_name>})` Found from this link [here](https://stackoverflow.com/questions/42986977/what-is-the-command-to-know-the-collation-of-some-collection)

I have validated that the information is there when I create the collection through the shell with something like `db.createCollection("names", { collation: { locale: 'en_US', strength: 2 } } )`, but it is not there when Mongoose is creating the collection. I used the example from the Schema [docs](http://mongoosejs.com/docs/guide.html#collation)

**If the current behavior is a bug, please provide the steps to reproduce.**

* Create new model using the schema with the default collation `{ collation: { locale: 'en_US', strength: 2 } }`.
* if autoIndex is true, collection is created on startup and you can check the collation on the collection with `db.getCollectionInfos({name: <collection_name>})` which is not there under "options"
* if autoIndex is false, create a doc and save it and validate now that the collection is there
* No collation is found when using Mongoose so you can create your own collection with default collation(example above) from the Mongo shell and it will show up in the collection info now under "options"

**What is the expected behavior?**
Create a collection with the correct specified collation

**Please mention your node.js, mongoose and MongoDB version.**
node v10.1.0, mongoose v5.1.1, mongo v3.6.4

**Comment by lmshaffe** [comment]
I think I see what you guys are doing now. You're not applying collation on collection creation, but are applying it on the queries for us. So, that means case-insensitive searches would work when strictly using Mongoose, but if I'm doing mongo queries through the shell, I have to apply that collation to my find queries manually since Mongoose is not applying it at the collection level

**Comment by vkarpov15** [comment]
@lmshaffe as you noticed, mongoose doesn't explicitly create a collection for you. How are you specifying the default collation for the collection in mongoose?

As a workaround, you can use the [`mongoose.connection.createCollection()` method](http://mongoosejs.com/docs/api.html#connection_Connection-createCollection) to manually create a collection in mongoose.

**Comment by lmshaffe** [comment]
I was defining it in the schema with the expectation that it would apply it at the collection level.

Example:
```javascript
var schema = new Schema({
  name: String
}, { collation: { locale: 'en_US', strength: 2 } });
```

I have enough information now to continue moving forward. Thank you for the `mongoose.connection.createCollection()` tip

**Comment by kenkopelson** [comment]
MongoDB supports the concept of having a default collation for the collection, so that all queries for that collection will automatically use that collation.  It's like mongoose has made it 20 miles to the finish line, but then just stopped 2 feet away from the goal.  If you mongoose passes the specified collation information through when automatically creating collections, all will be good in the world, and mongoose will do the expected thing.

Can mongoose please pass the options through to MongoDB for setting the default collation when the collection is created?

**Comment by kenkopelson** [comment]
@vkarpov15 you said that mongoose does not "explicitly" create a collection, and while that is true, it does "implicitly" do so, and there are many options that one can set in the Schema definition that deal with the created collection, including the collation information.  Notice at this link, the mongoose documentation says it creates the "default" collation for the collection, which is exactly the feature that MongoDB supports.

https://mongoosejs.com/docs/guide.html#collation

Everything in the mongoose documentation leads one to believe that this will pass through the collation specification to MongoDB so that the behaviour is consistent between mongoose and MongoDB.

**Comment by vkarpov15** [comment]
@kenkopelson you're right, thanks for your perspective. We will fix this by making `Model.init()` explicitly create the collection in 5.3.
