### ISSUE TITLE
Mongoose 4 -> 5 breaks deep equality tests and slows down queries

### ISSUE THREAD

**Issue by deklanw** [Automattic/mongoose#6548]
Upgrading Mongoose from 4.13.7 to 5.1.3 seems to change the way ObjectIds work (with deep equality tests) and slows down some of my queries significantly. I created a repo to exhibit my problem,
https://github.com/deklanw/pensieve-mongoose-4-to-5-test

I included the .env file for testing. If need be just change this line 
`MONGODB_URI=mongodb://localhost:27017/pensieve-test`
to reflect your testing environment.

Just,
`yarn install`
`yarn test`

There are three branches. The "mongoose4" branch shows all tests passing, quickly. The "mongoose5-failing-tests" branch shows how the tests fail because of deep equality testing. Lines like these,
` expect(card._id).to.deep.equal(cards[0]._id);`
stopped working. I can't seem to tell where the deep equality checks are failing. The fixtures are created using this library https://github.com/powmedia/pow-mongodb-fixtures so that's where the ObjectIds are being generated.

The "mongoose5-fixed" branch changes all tests with lines like the above to,
` expect(card._id.equals(cards[0]._id)).to.be.true;`
using the .equals method on the ObjectIds (another fix, which I haven't tried, is to just use .toString on both). On this branch all the tests pass but some of them are significantly slower. Some of the tests go from 15ms~ to 2s~. The whole suite goes from 600ms~ to 5s.

**Comment by lineus** [comment]
I ran the tests in all 3 environment on node 8.11.1 and 10.0.0, the results are the same on both ( give or take a few milliseconds ):

```sh
6548>: for branch in mongoose4 mongoose5-failing-tests mongoose5-fixed;do git checkout ${branch} && rm -rf node_modules && npm install >/dev/null 2>&1 && echo "Mongose: $(gv mongoose)" && npm test 2>&1 | tail -3;done
Switched to branch 'mongoose4'
Your branch is up to date with 'origin/mongoose4'.
Mongose:   "version": "4.13.14"

  49 passing (820ms)

Switched to branch 'mongoose5-failing-tests'
Your branch is up to date with 'origin/mongoose5-failing-tests'.
Mongose:   "version": "5.1.3"

  49 passing (901ms)

Switched to branch 'mongoose5-fixed'
Your branch is up to date with 'origin/mongoose5-fixed'.
Mongose:   "version": "5.1.3"

  49 passing (879ms)

6548>:
```

The branch that's supposed to fail doesn't for me and all 3 branches' tests run in roughly the same amount of time.

**Comment by deklanw** [comment]
Ah. It just occurred to me that it might be an OS thing.

I switched to my laptop with Ubuntu and Node v10.1 and mongoose5-failing-tests still fails, but mongoose5-fixed is now fast (only 20-50ms~ slower than mongoose-4).

Both problems occur for me on Windows 10 and Node v10.0

**Comment by lineus** [comment]
I re-ran the tests on both debian and osx and discovered that I was using npm in my example whereas you were using yarn. I switched to yarn, and lo and behold I got the failure:
```sh
6548>: for branch in mongoose4 mongoose5-failing-tests mongoose5-fixed;do git checkout ${branch} && rm -rf node_modules && yarn install >/dev/null 2>&1 && echo "Mongoose: $(gv mongoose)" && yarn test 2>&1 | tail -3;done
Switched to branch 'mongoose4'
Your branch is up to date with 'origin/mongoose4'.
Mongoose:   "version": "4.13.7",
  49 passing (743ms)

Done in 2.79s.
Switched to branch 'mongoose5-failing-tests'
Your branch is up to date with 'origin/mongoose5-failing-tests'.
Mongoose:   "version": "5.1.3",

error Command failed with exit code 16.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Switched to branch 'mongoose5-fixed'
Your branch is up to date with 'origin/mongoose5-fixed'.
Mongoose:   "version": "5.1.3",
  49 passing (783ms)

Done in 2.92s.
6548>:
```

Trying to dig into why yarn vs. npm is causing this.

**Comment by deklanw** [comment]
Just upgraded Node v10.0 -> v10.3 and Yarn v1.51 -> v1.7 and now I get no failing tests and no slowness with Yarn or NPM, on my Windows computer.

**Comment by lineus** [comment]
sweet 👍 

I was starting to lose my mind sorting through the differences between yarn and npm and the resulting node_modules dir. **Thanks again for the awesome repro code!**

**Comment by deklanw** [comment]
Thanks for your help.

On the other hand, with the same setup (Yarn v1.7 and Node v10.3) on my Ubuntu laptop, the failing tests branch still fails, but the mongoose5-fixed branch is fast. 

There is still something weird going on.

**Comment by lineus** [comment]
This was a **fun** problem to diagnose. It boils down to a dependency in the yarn.lock file.

# The why:
Two dependencies `agenda@^1.0.3:` and `pow-mongodb-fixtures@^0.14.0` require older versions of the mongodb driver 
```
mongodb@~2.2.33, mongodb@~2.2.x:
  version "2.2.34"
  resolved "https://registry.yarnpkg.com/mongodb/-/mongodb-2.2.34.tgz#a34f59bbeb61754aec432de72c3fe21526a44c1a"
  dependencies:
    es6-promise "3.2.1"
    mongodb-core "2.1.18"
    readable-stream "2.2.7"
```

which yarn installs in the root of node_modules:
```sh
6548>: grep version\": node_modules/mongodb/package.json
  "version": "2.2.34",
6548>:
```

**All fixtures created with pow-mongodb-fixtures will get ObjectIds from 2.2.34.**

**mongoose requires v3.0.8 so all of it's ObjectIds are created from version 3.0.8**:
```sh
6548>: grep version\": node_modules/mongoose/node_modules/mongodb/package.json
  "version": "3.0.8",
6548>:
```

# An example failure: 

The deep equal **eventually** compares the prototypes of the `deck._id` ( from mongoose ) and the `deck1._id` ( from pow-mongodb-fixtures ). 

This comparison fails between ObjectIds created with native 2.2.34 vs native 3.0.8 but succeeds with native version 2.2.35 vs native 3.0.8:

### 6548.js ( run from your failing repo branch )
```js
#!/usr/bin/env node

const { expect } = require('chai');
const mongoose = require('mongoose');
const mongodb = require('mongodb');

const str = '5b12987bdb935522753afce9';
const goose = mongoose.Types.ObjectId(str);
const native = mongodb.ObjectId(str);

try {
  expect(goose).to.deep.equal(native);
} catch (e) {
  console.error(e.message);
}
```
### Output:

```sh
6548>: gv mongodb
2.2.34
6548>: ./6548.js
expected 5b12987bdb935522753afce9 to deeply equal 5b12987bdb935522753afce9
6548>: npm install mongodb@2.2.35 >/dev/null 2>&1
6548>: gv mongodb
2.2.35
6548>: ./6548.js
6548>:
```
# The fix:

There's been a pull request opened since January against pow-mongodb-fixtures to support version 3.x of the native driver [here](https://github.com/powmedia/pow-mongodb-fixtures/pull/44) but the repo looks to be pretty much abandoned. 

The fix for this is to ensure that your dependencies don't clash. I don't know if I would expect this to be the only issue going forward when using two competing versions of the native driver. Unfortunately this might mean abandoning pow-mongodb-fixtures, or forking it, or offering to get involved in the project so that you can help maintain it.
