### ISSUE TITLE
[bug] findByIdAndUpdate (or similar) not validating id 

### ISSUE THREAD

**Issue by LiorGonda** [Automattic/mongoose#6551]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
when using findByIdAndUpdate (or similar functions) with a custom id and validating said id, it does not validate with inserting a new instance. I.E.: Meaning, the record did not exist before the call, the function is actually creating the record for the first time.

**If the current behavior is a bug, please provide the steps to reproduce.**

Schema:

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = new Schema({
  _id: {
    type: String,
    required: [true, 'id is required'],
    validate: {
      validator: (id) => 2 === id.length,
      message: 'id must be 2 characters'
    }
  },
  name: { type: Object, default: {} }
}, { _id: false });

module.exports = mongoose.model('Ship', schema);
```

Job:

```
Ship.findByIdAndUpdate(
    'foo',
    {},
    {
      setDefaultsOnInsert: true,
      upsert: true
    },
    function (err, response) {
      ...
    }
  );
```

**What is the expected behavior?**
The job should run and on the callback it should return an error, as well as NOT insert the instance into the dB

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.10.0
mongoose: 5.1.1
Mongo (Atlas): 3.6.4

**Comment by lineus** [comment]
@LiorGonda
check out the docs on update validation [here](http://mongoosejs.com/docs/validation.html#update-validators).

and update validator paths [here](http://mongoosejs.com/docs/validation.html#update-validator-paths)

1.) In order to get validation to run on update, you must pass `runValidators` in the update options.
1.) In order for validation of a path to fail on update, that path must be in the update doc.

## working example:
