### ISSUE TITLE
Parameter "obj" to Document() must be an object (crash not present on 5.0.6)

### ISSUE THREAD

**Issue by ronaldho** [Automattic/mongoose#6558]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Crashes on document save

**If the current behavior is a bug, please provide the steps to reproduce.**

If I downgrade to Mongoose 5.0.6; the crash does not occur, but once I upgrade to 5.1.3 or newer, it occurs. (I haven't had a chance to test versions between 5.0.6 and 5.1.3 to see if there is a particular version that starts the issue)

https://gist.github.com/ronaldho/6d3ee2092e58325033cd258113820a22
If you need to see the js file where it does the mongoose calls to save, feel free to let me know.

**What is the expected behavior?**
Document gets created and saved into mongo db

**Please mention your node.js, mongoose and MongoDB version.**
mongoose@5.1.4
node@v8.11.2
mongodb v3.4.7

**Comment by ronaldho** [comment]
Sorry I'm still waiting on clearance so nothing sensitive gets released on our end. I'll post the relevant files ASAP

**Comment by vkarpov15** [comment]
@ronaldho looks like you have a schema path with an object that gets stringified as `date=Mon Jun 04 2018 11:25:05 GMT-0700 (PDT), pid=7527, uid=502, gid=20, cwd=/Users/Ron/Work/cyberpatient/backend/app, execPath=/Users/Ron/.nvm/versions/node/v8.11.2/bin/node, version=v8.11.2, argv=[/Users/Ron/.nvm/versions/node/v8.11.2/bin/node, /Users/Ron/Work/cyberpatient/backend/app/server.js], rss=90021888, heapTotal=64884736, heapUsed=30545392, external=17903482, loadavg=[2.21142578125, 2.689453125, 2.85791015625], uptime=230606`. Does this object look familiar to you? The error occurs because mongoose doesn't think this is an object for some reason.

**Comment by Maja0426** [comment]
<input name="title"> 
route.js :
Blog.create(req.body.title,........ ==> wrong, generate error


<input name="something[title]"> 
route.js :
Blog.create(req.body.something... or Blog.create(req.body.something.title... ==> good, work correctly

**Comment by vkarpov15** [comment]
@Maja0426 I don't understand your comment, can you please clarify?
