### ISSUE TITLE
Error upgrading to 5.1.4 from 5.1.2: TypeError: ParallelSaveError is not a constructor

### ISSUE THREAD

**Issue by marcosPerezRubio** [Automattic/mongoose#6561]
The issue refers to mongoose 5.1.4 , but I've downgraded to 5.1.2

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When upgrading to the new version, some save operations causes a ParallelSaveError. Experienced with a normal .save() call and when pushing an array of save operations for a later Promise.all([saveOps]) call.

**TypeError: ParallelSaveError is not a constructor**

When performing the operations as a sequential insert with libraries like async.js, using **eachSeries** it works okay though.

I've had to downgrade to 5.1.2 in order to be able to perform inserts without changing my codebase.

**If the current behavior is a bug, please provide the steps to reproduce.**

A generic cruder function
```
  function create (req, res) {
    let entity = new Model(req.body)
    entity.save((err, data) => {
      if (err) {
        return res.status(500).json(err)
      }
      return res.json(data)
    })
  }
```

**What is the expected behavior?**
To save the document.

**Please mention your node.js, mongoose and MongoDB version.**
MongoDB: 3.4.4
Node 7.8.0

**Comment by lineus** [comment]
@marcosPerezRubio can you create a complete repro script that demonstrates the issue or modify mine below to fail in the way you are describing?

### 6561.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const tests = [];

for (let i = 0; i < 100; i++) {
  tests.push(new Test({ name: `test${i}` }));
}

async function run() {
  await conn.dropDatabase();
  let promises = [];
  tests.forEach((test) => {
    promises.push(test.save());
  });

  let saved = await Promise.all(promises);
  saved.forEach(doc => {
    console.log(doc.name);
  });

  return conn.close();
}

run();
```

### Output:
```
issues: ./6561.js
test0
test1
test2
test3
test4
test5
test6
test7
test8
test9
test10
test11
test12
test13
test14
test15
test16
test17
test18
test19
test20
test21
test22
test23
test24
test25
test26
test27
test28
test29
test30
test31
test32
test33
test34
test35
test36
test37
test38
test39
test40
test41
test42
test43
test44
test45
test46
test47
test48
test49
test50
test51
test52
test53
test54
test55
test56
test57
test58
test59
test60
test61
test62
test63
test64
test65
test66
test67
test68
test69
test70
test71
test72
test73
test74
test75
test76
test77
test78
test79
test80
test81
test82
test83
test84
test85
test86
test87
test88
test89
test90
test91
test92
test93
test94
test95
test96
test97
test98
test99
issues:
```

**Comment by loren138** [comment]
For future people who run into this:

We realized that our deployed environment wasn't emptying node_modules, it was instead just adding all the new files to it (from a compressed file built by Jenkins) which caused the problem.  We added code to erase `node_modules` before extracting the compressed copy of the app built by our build server and mongoose went back to working properly. :)

Background: If node has a file named `errors.js` and `errors/index.js` (both match `require('./errors')`), it loads `errors.js` and ignores `errors/index.js` *silently*.  Likely, some things got moved into folders somewhere during mongoose 5 development that used to be files, but in our env the old file was still getting loaded because we hadn't erased it before the deploy which meant that node didn't have the constructor for `ParallelSaveError`
