### ISSUE TITLE
Best practice to update many?

### ISSUE THREAD

**Issue by PinkyRabbit** [Automattic/mongoose#6585]
**Do you want to request a *feature* or report a *bug*?**
I want to find best practice

**What is the current behavior?**
I try to update many documents at once. I have an array of the objects. Each Object uniq field `author`. There can be old or new authors - doesn't matter. And I try to update the collection `dashboards` with this new datas. I maked it like this:
```javascript
// resultDatasArray - authors array of objects
return async.eachSeries(resultDatasArray, function updateObject(obj, done) {
  Dashboard.update(
    { author: obj.author },
    { $set: obj },
    { upsert: true },
    done
  );
}, function allDone(err) {
  if (err) console.log(err);
  resolve();
});
```
Is it the best practice to update many, or that can be done better? Thanks!

**Please mention your node.js, mongoose and MongoDB version.**
```
node -v
8.11.2
MongoDB 3.6
"mongoose": "^5.1.5",
```

**Comment by vkarpov15** [comment]
Yeah this is correct. If all the objects in `resultDataArrays` are the same you can do `updateMany()`, and you can also use [`bulkWrite()`](http://mongoosejs.com/docs/api.html#bulkwrite_bulkWrite). However, it is generally better to update in series unless you really need the update to be as fast as possible.

The only suggestion I have is to use [`updateOne()`](http://mongoosejs.com/docs/api.html#updateone_updateOne) rather than `update()`. `updateOne()` is more explicit that you only mean to update one doc.

**Comment by PinkyRabbit** [comment]
Maybe some one will need example of `bulkWrite`. I leave it here:
```javascript
return Dashboard.bulkWrite(resultDatasArray.map((obj) => {
  // console.log(obj);
  const { author, ...update } = obj;
  return {
    updateOne: {
      filter: { author: author },
      update: {
        $setOnInsert: { author: author },
        $set: update,
      },
      upsert: true,
    },
  };
}))
  .then(result => {
    console.log(result);
    resolve();
  })
  .catch((e) => reject(e));
```
