### ISSUE TITLE
how can i return mongoose query results to a "public" variable?

### ISSUE THREAD

**Issue by iraviteja** [Automattic/mongoose#6596]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
****

**Comment by iraviteja** [comment]
My query is like this

    var result = User.findById(userId, function(err, user) {
        if (err) throw err;
        res.json(user);
    });
    res.json(result);

I want to store **user** object into **result** variable but I am getting this error (Converting circular structure to JSON).

How can I store results JSON into a variable that can I use outside of the function findById function using Callback?

**Comment by lineus** [comment]
>How can I store results JSON into a variable that can I use outside of the function findById function using Callback?

The short answer is, you can't (not from within the callback anyway). Once a particular part of your code depends on asynchronous data, the rest of that code needs to be handled asynchronously as well. 

In your example (*see note below*) the call to `res.json()` outside of the callback to `findById()` is going to run before the one in the callback and before the asynchronous query completes.

**Note**
*In your example, even if the mongoose query behaved as you expected, it would still result in an express server error because you can't call `res.json()` more than once without getting the error `Error: Can't set headers after they are sent.`*

### What you can do:

[As mentioned here in the docs](http://mongoosejs.com/docs/queries.html) the pattern for mongoose queries is to **either** use the callback **or** use the promise-like `.then` method of the Query object returned by `findById()` to act on the response. The promise-like `.then` method on the Query object also allows it to work with async/await.

You can use async function in an express route, for example:
```js
  router.post('/', async function(req, res) {
    let userId = req.body.id;
    let result = await User.findById(userId);
    doSomethingElseWith(result);
    res.json(result);
  })
```

or

You can use the callback, for example:
```js
  router.post('/', async function(req, res) {
    let userId = req.body.id;
    User.findById(userId, function(err, user) {
      if (err) { throw err; }
      doSomethingElseWith(user);
      res.json(result);
    });
});
```


### Example:

Consider the following express route:
```
function printTheDocToFile(doc) {
  fs.writeFile(`/Users/lineus/dev/Help/mongoose5/issues/6596/doc_${doc._id}.txt`, doc, 'utf8');
}

router.get('/', async function(req, res, next) {
  Test.findOne({}, function(err, doc) {
    if (err) { return res.status(509).json({ error: err }); }
    if (!doc) { return res.status(504).json({ doc: 'none' }); }
    printTheDocToFile(doc);
    return res.json(doc);
  });
});
```
### bash output:
```
6596>: pwd
/Users/lineus/dev/Help/mongoose5/issues/6596
6596>: ls doc_*
ls: doc_*: No such file or directory
6596>: curl http://localhost:3000/ && echo
{"_id":"5b252d42c96565043c2995e6","name":"billy"}
6596>: cat doc_* && echo
{ _id: 5b252d42c96565043c2995e6, name: 'billy' }
6596>:
```
