### ISSUE TITLE
.save API with callback function returns undefined [Bug?]

### ISSUE THREAD

**Issue by advename** [Automattic/mongoose#6603]
NodeJS: v8.11.2
Express: v4.16.3
Mongoose: v5.1.5
Body-parser: v1.18.3

While handling POST and DELETE requests, i stumbled upon this issue, which I talked about in detail on [reddit](https://www.reddit.com/r/javascript/comments/8rqgv4/help_trying_to_work_with_promise_in_nodejs_and/)

But i guess the short version would be that 
`let newTodo = Todo(req.body).save()`

Returns an [object Promise], but the

`let newTodo = Todo(req.body).save(function(err,data){})`

returns an undefined.

Because of this, we can only use the first code snippet in a Promise chain, whereas it fails with the second code snippet. The console throws this error: 

> TypeError: Cannot read property 'then' of undefined

I would like to use .save with a callback function and still having a promise chain.

**Comment by lineus** [comment]
@advename There is no benefit from using a callback and a promise simultaneously. Do everything you need to from within the callback **or** consume the promise. 

With regard to your implementation of `find().remove()`, your delete api route is actually calling remove twice. This can be seen by turning on mongoose debugging. Here is an example:

### 6603.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'Billy'
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  mongoose.set('debug', true);
  await Test.find().remove(()=>{}); // this results in 2 remove queries
  return conn.close();
}

run();
```
### Output:
```
issues: ./6603.js
Mongoose: tests.remove({}, {})
Mongoose: tests.remove({}, {})
issues:
```

Check out the [Query docs here](http://mongoosejs.com/docs/queries.html)

**Comment by lineus** [comment]
@advename 

# regarding this comment on your reddit post:
>This seems to work and sorry for my ignorance but I would like to go with:
>    save data and listen for errors
>    Then go a fetch the updated version of data
> and not:
> save data, then go and fetch the updated version of data and then listen for errors...

If the promise returned from `.save()` rejects due to an error, the `.then()` block will be skipped. So, depending on the success/failure of the `.save()` call, the flow would either be:
save succeeded -> `.save.then()`
or
save failed -> `save.catch()`

Consider this example:

### prom.js
```js
#!/usr/bin/env node
'use strict';

function mockCall(bool) {
  return new Promise((resolve, reject) => {
    if (bool) {
      return resolve('ok');
    } else {
      return reject(new Error('fail'));
    }
  });
}

// fulfilled promise
mockCall(true)
  .then((res) => { 
    console.log('true: .then() ' + res); 
  })
  .catch((e) => { 
    console.log('true: .catch() ' + e.message); 
  });

// rejected promise
mockCall(false)
  .then((res) => { 
    console.log('false: .then()' + res); 
  })
  .catch((e) => { 
    console.log('false: .catch() ' + e.message); 
  });
```
### Output:
```
issues: ./prom.js
true: .then() ok
false: .catch() fail
issues:
```

You can see from this simple example that when the promise is fulfilled (success) only the `.then` block is called, and when the promise is rejected (fails) only the `.catch()` is called.

You can find some great information on Promises in javascript:
   [MDN: Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) 
  [MDN: Using Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises)
