### ISSUE TITLE
findOne() not working

### ISSUE THREAD

**Issue by JohnCdf** [Automattic/mongoose#6642]
**Current behaviour**
Upon a request from a user containing an email, I call upon the current model:
```
var mongoose = require('mongoose');

var UserSchema = new mongoose.Schema({
  email: {
    type: String,
    unique: true,
    required: true,
    trim: true
  },
  username: {
    type: String,
    unique: true,
    required: true,
    trim: true
  },
  password: {
    type: String,
    required: true,
  },
  bio: {
    type: String
  },
  posts: {
    type: Array
  },
  avatar: {
    data: Buffer,
    contentType: String
  }
});

var User = mongoose.model('User', UserSchema);

module.exports = User;
```
Using this model, I call findOne using the provided email:
```
mongoose.connect('my database url');

const email = 'email_that_exists@me.com';

User.findOne({email}, (err, userData) => {
```
**Reproducing the bug**
I have no clue how to reproduce this bug, as I've done the usual setup, and have no idea what causes it

**Expected behaviour**
This function should give me the data of the user with the email provided.
When I make a request using axios from an html websites, it works. However, when making a request from postman, or when making a request from the deployed website, it will return nothing, even though they all call upon the exact same function.

**Versions**
Mongoose: latest
Node.js; latest

**Comment by lineus** [comment]
@JohnCdf There are a lot of possible scenarios based on the information you have provided. This will almost certainly get resolved faster if join us in one of these chats so that someone can help you work it out in real time:

[Gitter.im](https://gitter.im/Automattic/mongoose)
[Slack](https://mongoosejsteam.slack.com/)

We're in the same timezone according to your github profile, ping @lineus in either channel and I'll see if I can help you sort it out.

**Comment by JohnCdf** [comment]
@lineus Thank you for offering to help out, I'll go ahead and do that 👍

**Comment by JohnCdf** [comment]
Issue with not matching fields
