### ISSUE TITLE
Failed to connect to local server on first connect

### ISSUE THREAD

**Issue by Exeteres** [Automattic/mongoose#6675]
After trying to launch one of my projects, I found that the request to api drops when I try to connect to the local database that is running on the current machine and I can easily access it using mongoshell or another client.
`(node:9357) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connection 0 to localhost:27017 timed out]`
This is either an internal mongoose error, or a network error. In the case of the second one, I would check the ports, whether it is a query from outside, but mongoose can not access while on the same machine as the db, that's what's strange.
What other tests should I do in this case?

**System:** Kubuntu 18.04

**Node:** 10.5.0
**MongoDB:** v3.6.3
**Mongoose:** v5.2.1

**Comment by Exeteres** [comment]
Fixed, replacing localhost with 127.0.0.1
Here only earlier all worked and in hosts at me 127.0.0.1 for localhost are registered

**Comment by vkarpov15** [comment]
The "first connect" error means that mongoose's initial connection to MongoDB failed. This is usually due to network issues. In general, if localhost doesn't work, you should try `127.0.0.1`, so glad you figured that out :+1: Check your `/etc/hosts` file and see if `localhost` is defined in your hosts file.
