### ISSUE TITLE
findOne returns success even if _id is not present with null data in promises

### ISSUE THREAD

**Issue by bhavukjain1** [Automattic/mongoose#6716]
This is my find query looks like:

```sh
function findUser(userId) {

	return schema.user.findOne({_id:userId})
	.then(user => {
		console.log(user)
		return user
	})
	.catch(error => {
		throw new Error(404)
		return
	})
}
```

For most of the cases, it works fine but sometimes when passed a random 24 chars long `userId`(example - `000000000000000000000000`), the `.then` block is called with user value null.

Ideally, if the `userId` is not found, the `catch` block should have been called.

Is there anything I'm missing?

**Comment by lineus** [comment]
@bhavukjain1 `.catch()` is called when an error occurs. Finding 0 documents is not considered an error because the query succeeded. With [queries](http://mongoosejs.com/docs/queries.html), you need to always account for the possibility of not matching any documents. With find, this will result in an empty array, and findOne this will result in null. 

What you do with a query that has 0 matches is up to you, for instance, if you want to `.catch()` an error with no matches:

### 6716.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'Billy'});

function findUser(n) {
  return Test.findOne({ name: n })
    .then((user) => { 
      if (user) { 
        return user; 
      } else {
        throw new Error('No user found.');
      }
    })
    .catch((err) => {
      console.error(`${n}: ${err.message}`);
    });
}

async function run() {
  await conn.dropDatabase();
  await test.save();
  let { name } = await findUser('Billy');
  console.log(name + ' says hi.');
  await findUser('Sally');
  return conn.close();
}

run();
```
### Output:
```
issues: ./6716.js
Billy says hi.
Sally: No user found.
issues:
```

**Comment by vkarpov15** [comment]
You can work around this using [middleware](http://mongoosejs.com/docs/middleware.html). `schema.post('findOne', doc => assert.ok(doc, 'Not found'));`
