### ISSUE TITLE
Model.create in a transaction

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#6761]
With the recent introduction of transactions, various methods now accept an additional `session` option. Unfortunately it made things a bit tricky for `Model.create`.

<img width="839" alt="screen shot 2018-07-23 at 23 16 04" src="https://user-images.githubusercontent.com/5895458/43103465-6a8064be-8ece-11e8-935d-06a4d98ca05d.png">

`Model.create` accepts options only if given an array. This means that a simple statement like this:

```js
const instance = await SomeModel.create({
  prop1: true,
  prop2: 123
});
```

now becomes:

```js
const instance = (await SomeModel.create([{
  prop1: true,
  prop2: 123
}], {session: ...}))[0];
```

It's becoming hard to read, so it would be awesome if there would be a way to create a single document without having to pass an array.

**Comment by vkarpov15** [comment]
That's a good point, but unfortunately there's no way for us to tell whether `SomeModel.create(a, b)` intends for `b` to be a doc to save or `options`. Here's a couple workarounds:

1) `const [instance] = await SomeModel.create([obj], { session })`
2) `SomeModel(obj).save(session)`

Do either of these work for you?

**Comment by c-eliasson** [comment]
@vkarpov15 Using your examples above, it is worth noting that example 1 will throw an error if the collection doesn't already exist: 

`Cannot create namespace [database].[collection] in multi-document transaction.`

Example 2 worked fine for me though, even if the collection didn't exist already.

**Comment by c-eliasson** [comment]
@vkarpov15 Should `SomeModel(obj).save(session)` really work?

When i first tried it, with my previous comment, all I verified was that the document was actually created. However, I just noticed that if i abort the transaction with `session.abortTransaction()`, the document created with `SomeModel(obj).save(session)` is NOT rolled back. The same goes for when you provoke a database error, like trying to create a dupe key on a unique index. In that case, the transaction aborts, but the document created with `SomeModel(obj).save(session)` is NOT rolled back.

I also failed to find any support for it int [the docs](https://mongoosejs.com/docs/api.html#model_Model-save)

Using your example with `await SomeModel.create([obj], { session })` works perfectly though, both when manually aborting the transaction, and when transaction aborts due to a database error.

**Comment by vkarpov15** [comment]
@c-eliasson the 'cannot create namespace' error is a pretty common pain point when testing with transactions. You can use [`Model.createCollection()`](https://mongoosejs.com/docs/api.html#model_Model.createCollection) or the [`autoCreate` option](https://mongoosejs.com/docs/guide.html#autoCreate) to work around this.

And re: `SomeModel(obj).save(session)`, that was a typo that I fixed. It should be `SomeModel(obj).save({ session })`, see [docs](https://mongoosejs.com/docs/api.html#document_Document-save). Sorry about the confusion.

**Comment by c-eliasson** [comment]
@mushfau that's because the create method accepts either an array of docs, or 1-n docs as a spread. Mongoose can't differentiate between your options object and an intended doc. It thinks your options object is yet another document you want to insert, but since no properties match you schema, the only thing inserted is the _id.

The [docs](https://mongoosejs.com/docs/api.html#model_Model.create) actually mention this:

> To specify options, docs must be an array, not a spread.

**Comment by vkarpov15** [comment]
For posterity, [here's the relevant `create()` docs](https://mongoosejs.com/docs/api.html#model_Model.create)
