### ISSUE TITLE
Mongoose skips validation on updates when using the "dot notation"

### ISSUE THREAD

**Issue by mariusbancos** [Automattic/mongoose#6873]
From my point of view this seems a bug from Mongoose.

I'm having a schema containing also a field like
```
custom_attributes: {
      type: Object,
      validate: [
        {
          validator: function (v) {
            return _.size(v) <= 5;
          },
          message: `Attribute \'{PATH}\' has more than the maximum allowed number of properties`
        }
     ]
}
```
So, a document could look like
```
{
	"_id" : ObjectId("..."),
        "name": "John",
	"custom_attributes" : {
		"first_attribute" : "first",
		"second_attribute" : "second"
	}
}
```
When I'm saving a new document the validator is applied correctly, but when I'm trying to update a document with (let's say) only an existing custom_attribute ('first_attribute') I have to use the dot notation to do it (so that the object doesn't get overwitten). Something like this:
```
Customer.update(id, { 'custom_attribute.first_attribute': 'test' }, {runValidators: true})
```
Even though I set ```runValidators: true``` the validator is skipped. If I want to update the name and it has a validator it seems to work ok for this.
If I'm not using the dot notation it seems the validation gets executed but then my field "custom_attributes" gets overwritten with the value I send in the update.

I'm using node v10.0.0, mongoose 5.2.8, mongodb 3.1.3 and MongoDB Server 4.0.1

**Comment by vkarpov15** [comment]
I consider this expected behavior. For example, your custom validator that checks that there are no more than 5 custom attributes wouldn't work right even if Mongoose ran it, because when you update using dot notation mongoose doesn't have all the custom attributes in memory. That's the main reason why we only run update validators on paths explicitly specified in the update: https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths

An alternative approach would be to use findOneAndUpdate as opposed to update and check the number of custom attributes in a post hook. You could also try using MongoDB's built in schema validation.
