### ISSUE TITLE
The Schema Model doesn't really hide attributes that are not defined in the Schema.

### ISSUE THREAD

**Issue by alielkhateeb** [Automattic/mongoose#6875]
Node version: **9.4.0**
Mongoose version: **5.1.1**
MongoDB version: **3.6.3**

I will try to be brief and clear, my issue is simply if I have 2 projects connecting to the same DB
When you define a Schema in Project A (For example):

    let categorySchema = new mongoose.Schema({
        name: String,
    });

Let's say I want to have access to this `name` property only so that's why I have this schema.

But in my Project B I have another property which is let's say `agentId`, so the Schema is like this:

    let categorySchema = new mongoose.Schema({
        name: String,
        agentId: String
    });

So here are the steps to reproduce my issue:

- Insert a document in the database that has the values `{name: 'Test', agentId: 10}`

- Now run this line in Project A `let category = await Category.findById(this.selectedCategory).exec();`

- `console.log(category)` and you will find `{name: 'Test', agentId: 10}`

- `console.log(category.agentId)` you will get `undefined`

Even if I console log `JSON.stringify(category)` I will get both properties stringified.

I am not quite sure how this works under the hood, but this is a very weird behavior to me.

I expect to see only the `name` property when I access it from project A according do my defined schema. But that is not what is happening.

**Comment by lineus** [comment]
@alielkhateeb If I understand correctly, you have two models that point to the same collection from separate processes where one model has additional fields defined in it's schema. 

If this is the case, then the behavior you are seeing is expected:

   1) **Queries without field selections will return the whole document from mongodb, including fields not defined in your schema.** This prevents unexpected data loss when saving or updating documents that contain data beyond the schema.

   1) **You get `undefined` when you try to access the undefined property directly because no getters/setters have been defined for that path on the Model.** From your comment, I assume that you expected this behavior. 

   1) **`Document.toObject()` ( which gets called by console.log ) returns the entire document retrieved from mongodb.** `toObject()` gets used internally as well, this behavior is also designed to prevent accidental data loss by including all returned fields from the db.

You can control this behavior by using a transform function in `toObject()`. Here is an example:

### 6875.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

schema.set('toObject', { transform: cleanup });

function cleanup(doc, ret) {
  for (let path in ret) {
    if (!Object.keys(schema.paths).includes(path)) {
      delete ret[path];
    }
  }
}

const Test = mongoose.model('test', schema);

async function run() {
  await conn.dropDatabase();
  let id = mongoose.Types.ObjectId();
  await Test.collection.insertOne({ _id: id, name: 'TEST', agentId: 10});
  let doc = await Test.findOne({ _id: id });
  console.log(doc);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6875.js
{ _id: 5b76ca7a6c2c5621e9b10442, name: 'TEST' }
issues:
```

**Comment by alielkhateeb** [comment]
Now it perfectly makes sense to me. Thanks a lot for the info, that is exactly what I needed, I appreciate it!
