### ISSUE TITLE
Model update functions not being called

### ISSUE THREAD

**Issue by bscotchAdam** [Automattic/mongoose#7121]
`model.update` and `model.findOneAndUpdate` do not actually perform updates even when they match documents.

+ MongoDB v3.4.9 is running locally on my machine.
+ I am directly running `node index.js` on the same machine (Node v8.12.0).
+ Mongoose is version 5.3.2

The *entirety* of the code being run via `node index.js` is:

    const mongoose = require('mongoose');
    mongoose.set('debug',true);
    mongoose.connect('mongodb://localhost/db',{useNewUrlParser: true});
    const model = mongoose.model(
      'tests',
      new mongoose.Schema({hello:String})
    );
    const test = new model({hello:'world'});
    test.save(()=>{
      model.countDocuments({},(err,count)=>{
        console.log(count);
        model.findOneAndUpdate({},{dummy:true},{new:true},(updateErr,doc)=>{
          console.log(doc);
        });
      });
    });

Which results in the following console output:

    Mongoose: tests.insertOne({ _id: ObjectId("5bbe80580d1b6757bd1eab5b"), hello: 'world', __v: 0 })
    Mongoose: tests.countDocuments({}, {})
    3
    Mongoose: tests.findOne({}, { new: true, projection: {} })
    { _id: 5bbe7f4f9cad0e56eeccb64c, hello: 'world', __v: 0 }

Where the final log is missing the new field `dummy:true` (and this doesn't exist in the database when checking directly via the shell) -- the update *did not happen*.

*(The count echoed a `3` because I ran this a few times.)*

You can see that it is running a `findOne` and no updates are occurring. Using `update` instead of `findOneAndUpdate` has the same end result with the corresponding output `{ ok: 0, n: 0, nModified: 0 }`. Running the update directly via the shell works fine.

You can see that the connection is fine since Mongoose can insert a new document. And you can see that it can find those documents because the count is successful. It's just unable to run any updates.

I've been banging my head on this for the entire day; anyone have any idea what could be happening here?

**Comment by bscotchAdam** [comment]
Prior case was on Linux (Ubuntu 16.04). Replicated on Windows10 with fresh installs of Mongoose (v5.3.2, same result with 4.0.7) and MongoDB (v3.4.17) using Node 8.11.3.

Am I just being super dumb about something?

**Comment by lineus** [comment]
@bscotchAdam your example schema only defines one path, `hello`. In your update you are trying to set an unknown ( **to the schema**) path called `dummy`.  Check out the [docs on strict mode here.](https://mongoosejs.com/docs/guide.html#strict) By default strict mode is enabled preventing you from setting paths that don't exist in the schema.

When no valid update paths exist in the update doc, i.e. the update doc is empty, the `findOneAndUpdate` command is converted to a `findOne` command otherwise mongodb would throw an error; [I just learned this too :)](https://github.com/Automattic/mongoose/issues/7011)

You can either:
   1. define the `dummy` path in your schema
   1. set the strict option to false in the findOneAndUpdate query
   1. set the schema option to strict false.

Here's an example of the second two:

### 7121.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useFindAndModify', false);
const { Schema, connection } = mongoose;
const DB = '7121';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema1 = new Schema({
  name: String
});

const Test1 = mongoose.model('test1', schema1);

const schema2 = new Schema({
  name: String
}, { strict: false });

const Test2 = mongoose.model('test2', schema2);

const test1 = new Test1({ name: 'test1' });
const test2 = new Test2({ name: 'test2' });

async function run() {
  assert.strictEqual(mongoose.version, '5.3.2');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test1.create(test1);
  await Test2.create(test2);
  const update = { dummy: 'test' };

  const cond1 = { _id: test1._id };
  const opts1 = { new: true, strict: false };
  const one = await Test1.findOneAndUpdate(cond1, update, opts1);

  const cond2 = { _id: test2._id };
  const opts2 = { new: true };
  const two = await Test2.findOneAndUpdate(cond2, update, opts2);

  assert.ok(one.toObject().dummy);
  assert.ok(two.toObject().dummy);
  assert.strictEqual(one.toObject().dummy, 'test');
  assert.strictEqual(two.toObject().dummy, 'test');
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```
### Output:
```
issues: ./7121.js
All Assertions Pass.
issues:
```

*Note that because the `dummy` path isn't defined in the schema, I use the `toObject()` method on the returned document to access the property. **Not defining the path in your schema means you won't have a getter/setter on Documents to access the property directly.***

**Comment by bscotchAdam** [comment]
Thank you so much for clarifying this!

That totally makes sense. I was originally doing this with an `$unset`, which is why this behavior was somewhat unexpected (I had removed a field from my schema, and then wanted to update all my docs accordingly to remove that field). I can see how it makes sense to now allow modification of any field when it's not in the schema though.
