### ISSUE TITLE
Conditional required field

### ISSUE THREAD

**Issue by Ron537** [Automattic/mongoose#7136]
**Do you want to request a *feature* or report a *bug*?**
Neither a bug nor a feature request

**What is the current behavior?**
Schema with optional required field has no validation when performing an `update` operation

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create the following schema:
```
const schema = mongoose.Schema({
    a: {
        type: String,
        required: function () {
            console.log(this.b);
            return this.b === 1
        }
    },
    b: {
        type: Number,
        required: true
    }
});

const Model = mongoose.model('schema', schema);
```

2. Create a valid model
```
const model = await Model.create({ b: 2 });
```

3. Try to update the model with value that makes property `a` required

```
await Model.findByIdAndUpdate(model._id, { b: 1 }, { new: true, runValidators: true});
```

**What is the expected behavior?**
Expected to throw `ValidationError` for property `a`

**What is the actual behavior?**
The document updates without any exception.

**Please mention your node.js, mongoose and MongoDB version.**
mongoose: 5.2.7
node: 8.11.1
mongodb: 4.0.0

**Note: 
Created a question in stackoverflow but didn't get a proper answer,
https://stackoverflow.com/questions/52737661/mongoose-conditional-required-field-validation
I've added my own answer to use transactions and manual validation, but doesn't seem to be the right way.

**Comment by vkarpov15** [comment]
This is expected behavior, update validators only run on paths that are in the update: https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths . Since a is not in your update, mongoose won't validate it because mongoose doesn't know whether the document in MongoDB has `a` set. If you want to ensure `a` is always in your update, you will have to write your own middleware for that.
