### ISSUE TITLE
Error: key {key} must not contain '.' (working on 5.1.5, not on later versions)

### ISSUE THREAD

**Issue by srokatonie** [Automattic/mongoose#7144]
**BUG**

We were running Mongoose on version 5.1.5 and all was good. Then cloned repo, npm installed everything (Mongoose updated to 5.1.7, but not working on most recent release 5.3.4).

Started getting error:
````
Error: key {key} must not contain '.'
````

It happens when you try to create a key that contains "." (dot), for example:
````
{
  "settings.appName": "Funky giraffes"
}
````

I believe that `"settings.appName"` is a valid JSON string and should be supported?

Node version: v9.3.0
Mongoose: 5.1.7 - 5.3.4 (working on 5.1.5)
MongoDB shell version v3.6.2

**Comment by lineus** [comment]
@srokatonie can you please include your schema and the operation that leads to the error?

**Comment by srokatonie** [comment]
@lineus I tried to reproduce, but it worked fine for some reason! possibly creating schema/collection using one version and then updating may cause the error, but need to look deeper into that. Let's close for now and reopen if I come up with something.

**Comment by sibelius** [comment]
this is happening to me with a `Mixed` field

here is a failing model

```jsx
raw: {
          type: Mixed,
          description: 'raw data of this calendar event',
        },
```

```jsx
{
      '@odata.etag': 'blah',
}
```

**Comment by vkarpov15** [comment]
So I repro-ed this with the below script, it starts failing with Mongoose 5.2.0:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7144`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { checkKeys: false });
  await mongoose.connection.dropDatabase();

  const s = new Schema({ raw: { type: Schema.Types.Mixed } });
  const M = mongoose.model('gh7144', s);

  const raw = {
    '@odata.etag': 'blah'
  };
  
  const data = await M.create({ raw: raw });

  assert.deepEqual(data.raw, raw);
}
```

This issue goes back to this PR in the MongoDB driver: https://github.com/mongodb-js/mongodb-core/pull/339 and this JIRA issue: https://jira.mongodb.org/projects/NODE/issues/NODE-1409?filter=allissues . Dotted keys are a grey area right now because, although MongoDB 3.6 and up support nested keys with '.', [MongoDB drivers do *not* currently support that](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names), so technically the MongoDB driver's behavior is correct.

Unfortunately, this is also a pretty clear backwards breaking change in Mongoose 5.2.0 that we really can't do much about without the MongoDB driver's help. Here are some alternatives that we can do to work around this issue.

1) Create a custom type that converts `{ 'a.b': 'foo' }` into `[['a.b', 'foo']]` for serialization to the MongoDB driver and then back again on the way out of MongoDB
2) We can find a way to set `checkKeys` to false for a `create()` call

Any thoughts @sibelius  ?

**Comment by sibelius** [comment]
tks for the repro

I think `Mixed` data should not validate anything, as it is `mixed`, or should I use another type?

`checkKeys` override on create() calls sounds a good option as well

I usually use  `Mixed` to store some raw data from apis, where it could change anytime

**Comment by vkarpov15** [comment]
@sibelius unfortunately this validation doesn't happen in Mongoose, this check is deep in the [bson serializer](https://www.npmjs.com/package/bson) that every operation sent to MongoDB goes through. Using a type other than mixed won't help in this case unfortunately. For now, just use: `doc.save({ checkKeys: false })` or [`Model.create([doc], { checkKeys: false })`](https://mongoosejs.com/docs/api.html#model_Model.create)

**Comment by sibelius** [comment]
tks, I think this should be considered a bug on bson serializer, as mixed should not be validated

**Comment by vkarpov15** [comment]
bson doesn't have a notion of a mixed type unfortunately. This is a bit of a rough patch in the API, but one that we'll have to live with because at the time of this writing [MongoDB drivers don't officially support dotted keys](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names), so Mongoose doesn't have firm ground to stand on in supporting it.

**Comment by natanavra** [comment]
Sorry for reviving this old thread, recently upgraded from `5.0.16` to `5.8.9` and started experiencing this issue, unfortunately the stack traces don't give any context as to where it's happening

Can someone explain what's the reason it broke after 5.1.5? Was there a change in the mongodb driver implementation?

**Comment by brian-learningpool** [comment]
I'm still seeing this issue on v.5.8.11.  If I'm understanding correctly, since Mongo 3.6 and up has supported dotted keys though.

The odd thing is, if I use `{ checkKeys: false }` I get a model `ValidationError` about properties which are definitely set.

**Comment by vkarpov15** [comment]
@brian-learningpool can you please open up a new issue and follow the issue template?
