### ISSUE TITLE
using 'await' with 'model.update' and a callback can trigger an error (E11000 duplicate key)

### ISSUE THREAD

**Issue by nihlton** [Automattic/mongoose#7174]
This may be user error, but this seems like a stumbling block that could be looked at / removed to prevent others from running into the same problem.

`await this.model.update(query, data, { upsert: true }, (err, result) => { // do stuff })`

on upsert, tries to save a new record twice because of the callback. 

The result is a mongo error `E11000 duplicate key error collection index: _id_ dup key`

changing it to
 `await this.model.update(query, data, { upsert: true}).then(result => { // do stuff }).catch(e => { // error stuff })` 
fixes the issue

node: v8.11.4, db version v4.0.3, mongoose: version "5.3.3"

**Comment by vkarpov15** [comment]
Right now that's by design. [Queries are not promises](https://mongoosejs.com/docs/queries.html#queries-are-not-promises). Passing a callback to a query executes the query, as does `await`-ing on it, so if you pass a callback and await on a query, you'll execute it twice. We may change this in the future, but you should generally avoid mixing callbacks and promises.
