### ISSUE TITLE
What is the limit for number of docs returned in a query?

### ISSUE THREAD

**Issue by govindrai** [Automattic/mongoose#7188]
When I invoke a Model.find() query, if there are a million docs in the database, will all million be returned? What is the output if there are still more documents to query from the database than are returned? I couldn't find this in the docs (except for information on cursor, which I hope I don't need to use). Thanks!

**Comment by lineus** [comment]
> if there are a million docs in the database, will all million be returned?

Yes. The native driver will attempt to return all of the docs that match your query right up until the point where your node process runs out of memory.

>What is the output if there are still more documents to query from the database than are returned?

All matching documents will be returned or you will run out of heap space and your node process will fail. 

@vkarpov15 should we add a note to this effect in the docs somewhere?

**Comment by vkarpov15** [comment]
You can use [`limit()`](https://mongoosejs.com/docs/api.html#query_Query-limit) to limit the number of docs your query returns, or [`cursor()`](https://mongoosejs.com/docs/api.html#query_Query-cursor) to process documents [one at a time](https://thecodebarbarian.com/cursors-in-mongoose-45). Otherwise, `find()` will give you an array of all documents that match the `filter` parameter.

**Comment by vkarpov15** [comment]
@lineus done :+1:
