### ISSUE TITLE
Exposing $regex. Is it secure?

### ISSUE THREAD

**Issue by Fusseldieb** [Automattic/mongoose#7208]
In mongoose 5.3.8 (latest to date) can I expose the $regex function to the user or does this impose a mayor security risk?

```
  customerModel
    .find({ name: { $regex: req.params.name, $options: "i" } })
    .then(result => {
      res.json(result);
    })
    .catch(err => {
      console.log(err);
      res.json({success:false});
    });
```

_(req.params comes from the URL like .../something/:name)_

Like that. It's nice that the user can use regex, but at the same time it bothers me that a function is exposed to users.

If someone would shed some light on this, it would be very nice.

Thanks in advance.

**Comment by larsdecker** [comment]
For a big collection you should not do it, because it will take a lot of resources to search via regex for a simple query. For small collections it should be okay. 

I don't know exactly if it has security holes when you use regex directly. Maybe someone else have an opinion on that?

You use a path param for the filtering of the items. That is a thing that i personally do not like it. For me that part are a sub ressource of something and should not filter the results.  You can use a query param for that purpose.

**Comment by Fusseldieb** [comment]
@unusualbob Is there any measure on the MongoDB that "times out" such requests? Would be nice to see...

If regex xyz is taking longer than X ms, time out and return empty.

**Comment by unusualbob** [comment]
If you'd like you could add `.maxTime(5000)` to your query which would restrict the cursor from executing longer than 5000ms.

More docs about it here: https://docs.mongodb.com/manual/reference/method/cursor.maxTimeMS/

You'd still have to keep in mind that someone could still repeatedly make this query to carry out the same attack. Another way to avoid it would be disallowing non-alphanumeric characters in the regex string. If you're just looking for a name or something that would work pretty well.

**Comment by vkarpov15** [comment]
`maxTime` is one way to work around this, see [mongoose docs](https://mongoosejs.com/docs/api.html#query_Query-getOptions).

Another option is to [escape `req.params.name`](https://www.npmjs.com/package/escape-string-regexp) so you don't get any evil regexes :)
