### ISSUE TITLE
.find() returns blank field with default value 

### ISSUE THREAD

**Issue by lzl124631x** [Automattic/mongoose#7269]
**Do you want to request a *feature* or report a *bug*?**

Might be a bug. Not sure if it's by design. Related to https://github.com/Automattic/mongoose/issues/5410

**What is the current behavior?**

I added a new field `foo` to my schema `Job` and make the default value for it being `bar`.

I found that:
1. plain `Job.find({})` request sets the `job`s with `foo: undefined` to `foo: bar`.
2. `Job.find({}).lean()` request leaves the `job`s with `foo: undefined` unchanged. (This is what I expected, but I have to add `lean()` to achieve it)

**What is the expected behavior?**

The [doc](https://mongoosejs.com/docs/defaults.html) tells nothing about this behavior. It only says that it will set the default value on save. So it surprised me and made me felt it's a bug rather than by design.

**Please mention your node.js, mongoose and MongoDB version.**
```
$ node -v
v8.11.3
"mongoose": "^5.1.1"
mongo: 4.0.2
```

**Comment by mhombach** [comment]
I can't really follow you:
Default-values are applied when **saving** to the database, not **getting** them from the DB. So, please provide the code you are using for saving, not searching. Provide the schema with your definition and the code-snippet where you create and save a document.
If you don't fully understand `lean`: https://mongoosejs.com/docs/api.html#query_Query-lean

**Comment by lzl124631x** [comment]
@mhombach Soft ping. I think my code can repro the issue. Please have a try. Thanks!

**Comment by mhombach** [comment]
Will test tomorrow (10 hours) and report back :)

**Comment by lzl124631x** [comment]
@mhombach Soft ping.

**Comment by lzl124631x** [comment]
@mhombach Really appreciate it!

A setting makes sense to me. Or if we want to keep it this way, we defintely should add this behavior in the doc.

Here is my story:

In the first week, `Job`s were added without `category` field.

In the second week, my customer asked me to add `category` field and make the default value being `2` meaning a popular job category, say Developer.

I happily updated the `Job` schema and thought:  
"okay, according to the doc of `default` field, from now on new jobs saved into the system will have default category `2`. The jobs created in the first week won't get affected, meaning that fetching them will still return `category: undefined`."

But I was shocked seeing in my app that all the jobs created in the first week appeared to be `category: Developer`. I haven't set that field! Isn't default value supposed to take effect only on saving?

**Comment by mhombach** [comment]
@lzl124631x 
Uhm, while this isn't exactly the topic of your initial question:
- You should not use the plain value "2" for the meaning "Developer" or something like that. You should use a Model or Enum for that.
- If you change the model while in use, you should AWAYS write a function that "migrates" the existing data. In your case that means, that you run a query where you change every `category` to like `0` where `category` is currently not existing. There may come more complex issues when you are changing the model with existing data. You could also use a `discriminator` (https://mongoosejs.com/docs/discriminators.html) to create a "discriminated" `Job_v2` or so and use that in the future.
- You should think a bout using "Unit Tests" (nodeJs has "chai" and "moccha" or so, they are really easy and famous) for catching exactly those bugs/issues in the future.
- Regarding your last question `Isn't default value supposed to take effect only on saving?` it should now be clear, that "default value" for mongoose means, that this value is set/saved every time the attribute itself is not set aka `undefined`.

IMPORTANT: You do NOT have to use `lean`. Using `lean` as a workaround for this misunderstanding here is dirt and brings more problems with it than it solves. If you use `lean`, you basically loose ALL mongoose functionality on that object, which will be a hughe problem later. So... just don't use it, unless you especially need that method for some special cases (like performance-tuning in massive data beeing handled).
Mongoose is used for clean, structured and consistent operations. Trying to always use `lean` as a workaround, so that no default-data is applied, is not the way you want to go. Create a clean migration-script, use "unit test" frameworks like mentioned above and always go the extra mile for clean and consistent code. If your database get's messy once, you will have a bad time fixing it ;)

**Comment by lzl124631x** [comment]
> You should not use the plain value "2" for the meaning "Developer" or something like that. You should use a Model or Enum for that.
Yes. I'm using enum. Using 2 is an over-simplification of my case.
> If you change the model while in use, you should AWAYS write a function that "migrates" the existing data.
For my particular case, the migration script was punted due to priority (or I was lazy at that moment :P).

Seems that I should run the migration script before actually changing the scheme. Otherwise after the scheme is updated and before the migration script takes effect, users will still get wrong result.

> Unit Tests
Yeah. Really important. But my issue involves accessing data in db. I doubt if unit test can handle this case. For example, if I use Travis as a test runner, how can travis have mongodb set up?

> this value is set/saved every time the attribute itself is not set aka undefined.
It took us time to understand the real behavior. I think it is worth it to put it in the doc so as to save other people's time. Especially mentioning that `default value` not only affects `save` behavior, but also affects `find` behavior. You might get the default value when `.find()` even if the field is actually `undefined` in DB.

> You do NOT have to use lean
Yeah. Just a dirty trick I found :P. Will use migration script instead.

Thanks for your advises ;) ! @mhombach

**Comment by mhombach** [comment]
@lzl124631x glad i could help :)
i just opened a new issue with the intention of flagging this as bug or at least unexpected behaviour (https://github.com/Automattic/mongoose/issues/7287). You can subscribe to that issue and maybe this will get fixed/solved soon :) This issue here can be closed, so any further discussion on that topic will be in #7287 .

**Comment by lzl124631x** [comment]
Really appreciate your help! @mhombach Subscribed. ;)
