### ISSUE TITLE
find() issue async/await

### ISSUE THREAD

**Issue by blackkopcap** [Automattic/mongoose#7289]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
await find did'nt return any result and hang connection to db

**If the current behavior is a bug, please provide the steps to reproduce.**
if no record with request  params in find method, connection will  hang...
```
import mongoose from "mongoose";
const time_zone= require('mongoose-timezone');

const AOrderSchema = mongoose.Schema({
    order_id: { type: String, required: true, unique: true, index: true },
    ts_order_id: { type: String },
   created_date: {
        type: Date,
        default: Date.now
    },
   agent_id: { type: String, required: true },
    tickets: { type: Array }
}, { collection: 'Order' });

AOrderSchema.plugin(time_zone);

let OrderModel = mongoose.model('Order', AOrderSchema);

OrderModel.get_all = () => {
   return OrderModel.find({});
}

OrderModel.get_by_agent = (agent, date_start, date_end) => {

      return  OrderModel.find({ "agent_id":agent, "created_date": {"$gte": !moment.isMoment(date_start)?moment(date_start).toDate():date_start.toDate(), "$lt":!moment.isMoment(date_end)?moment(date_end).toDate():date_end.toDate()}});

}

```
```
var order = await OrderModel.get_by_agent("test","2018-10-24","2018-10-25");
console.log(order);
```

**What is the expected behavior?**
if there is no records in db with such params in request, just return []  (async/await);

**Please mention your node.js, mongoose and MongoDB version.**
node: v9.11.2
mongoose: 5.3.14
babek: 6.26.0

**Comment by mhombach** [comment]
a few things:
- please try to format your code-pastings with the javascript-markdown (https://guides.github.com/features/mastering-markdown/), this makes it way more easy for us to read your code.
- if you think you encountered a bug, please break down your code to a minimum exaple-code where you encounter the problem.

Regardng your code: I am thinking that you maybe do have some other issue in your code-structure:
In your `OrderModel.get_by_agen` function you do this:
```javascript
OrderModel.find({
                "agent_id": agent
            })
            .then((err, docs) => {
                console.log(docs);
            });
```
but at the bottom of the function you are returning `[]`. Since you don't return something in the then-callback of the find-call, the function INSTANTLY returns an empty array, regardless of what the find-query may have resulted in.
I also am not sure if the part after `//not works, hang the connection` is meant to replace the then-construct but i assume it should.  I cannot see any error in that await-part of your code. Can you provide more information on what exactly happens? Also, as mentioned above, try to minimze the code to the basic example of showing that the find-methode doesn't work as expected. If you minimize your code and suddenly the error is gone, then you can reconstruct in your head what code-parts you did delete/change and so figure out, where the error might be related to :)

**Comment by blackkopcap** [comment]
Ok, thx, edited. So u just call method of model, like OrderModel.get_by_agent, it's return Promise. but request still hang...

**Comment by blackkopcap** [comment]
Sorry, my bad, found why it's happen, i'm using plugin mongoose-timezone,  and somehow it's affects, find request... without it, all working as fine.

**Comment by mhombach** [comment]
I personally would be suspicious about a NPM package if it hasn't seen any commit in 2 years but issue that are open for months :/
Regarding timestamps: just replace the default-timestamps with your own timestamp-function in the mongoose-schemas. No need to use libraries for simple stuff ;)

**Comment by blackkopcap** [comment]
> I personally would be suspicious about a NPM package if it hasn't seen any commit in 2 years but issue that are open for months :/
> Regarding timestamps: just replace the default-timestamps with your own timestamp-function in the mongoose-schemas. No need to use libraries for simple stuff ;)

True that. Thank you for useful advice.

**Comment by mhombach** [comment]
@blackkopcap you're welcome :) If your question is solved, please don't forge to close this issue, so others won't think they need to read the whole conversation in order to help someone ;)

**Comment by blackkopcap** [comment]
Moral is: Always check npm packages and review code. Thx.

**Comment by vkarpov15** [comment]
@blackkopcap your original code doesn't actually call [`mongoose.connect()` to connect to MongoDB](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-connect), so that would explain why it is hanging. See [buffering docs](https://mongoosejs.com/docs/connections.html#buffering). Does that fix your issue?

**Comment by blackkopcap** [comment]
> @blackkopcap your original code doesn't actually call [`mongoose.connect()` to connect to MongoDB](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-connect), so that would explain why it is hanging. See [buffering docs](https://mongoosejs.com/docs/connections.html#buffering). Does that fix your issue?

It's quite strange to call mongoose.connect in Model class, right? :)

**Comment by vkarpov15** [comment]
@blackkopcap I'm not sure I understand, can you please elaborate?
