### ISSUE TITLE
`insertMany` ignore duplicate

### ISSUE THREAD

**Issue by atulmy** [Automattic/mongoose#7306]
I've a collection say `Tweets` and each tweet has `_id` and another unique id `id_str` (added when creating schema).

When running `insertMany`, is it possible to just ignore tweets with duplicate `id_str` without throwing error? I tried following which does not work and still throw error:

```
try {
  const tweets = fetchedFromApi()

  await Tweet.insertMany(tweets, { ordered: false })
} catch (error) {
  console.log(error) // -> MongoError: write operation failed
}
```

Node: `v10.14.0`
Mongoose: `v5.3.13`
MongoDB: `v4.0.2`

**Comment by mhombach** [comment]
This seems to be no mongoose-related issue. You can just sort do this:
- sort your tweet-array for the `id_str` field (asc/desc, doesnt matter)
- loop through it and check the actual entry with the next entry (i+1) and if their `id_str` is the same, delete one of them.
After the loop has finished you have eleminated all duplications and can push that into the insertMany function.
You can also write this as hook, where you apply that logic is up to you :)

**Comment by atulmy** [comment]
Having something like `await Tweet.insertMany(tweets, { ordered: false, *silent: true* })` would work better.

**Comment by mhombach** [comment]
You are right, that your approach would be easier.
But in my opinion (just me personal) i think that the wanted behaviour of "inserting 100 elements with only 50 really getting into the database without the programmer beeing able to see/handle that" is not wanted and is vey risky to say the least.
You should not get into a situation where you want to insert things you want to put stuff into a database and then just don't care what and how much was written to it. You want the database to exactly do what you are telling it (that's what validations are for).
If you encounter this problem, like you mentioned, then, though i don#t know your whole project, i would think that at some point in your code-structure there is an issue that causes doubled IDs to be generated or duplicated entries beeing pushed into that `tweets`-array. And i would suggest to keep the code and logic clean so that this won't happen.
So i would never suggest to create or use such an option, though it would be theoretical possible.
But maybe @vkarpov15 has knowledge about this topic from earlier issues :)

**Comment by mhombach** [comment]
Well i would say that catching the error here with try/catch is not the most bad solution.
The database telling you that one entry could not be inserted because of duplicated UID is "ok" in my personal opinion as long as you filter the try/catch for that exact error and report all other errors normally (try/catching errors and not doing anything regardless of the error type is not clean).
The more cleaner way would be to check if the new uid already exists in the db and then acting accordingly. If you create an index on the UID of the tweets, that should be really fast.

**Comment by atulmy** [comment]
@mhombach thanks for your insight.

**Comment by mhombach** [comment]
@atulmy This issue came up in my head when doing bulkInsert myself now and i think what you were doing from the beginning on was technical correct.
Setting `ordered: false` in the `insertMany` will insert ALL documents that are possible and "skip" those that throw an error. But when finished, the function itself will report/throw an error with all information on how many documents had been saved and how many not (see the docs: https://docs.mongodb.com/manual/reference/method/db.collection.insertMany ).
So... i guess you were just thinking "it throws an error, so no documents were stored" maybe? But infact setting `ordered: false` will NOT abort the insert if errors happen, it will just report them at the end. So this should be the exact thing you wanted, am i right? Can you check if this works and you maybe misread the error-message? :)

**Comment by atulmy** [comment]
>  "it throws an error, so no documents were stored"

@mhombach you are correct, it does insert the data but throws an error at the end. Hence we are able to ignore the `catch` block and run the operation successfully.

By ignoring the `catch` block, we also ignore any database connectivity issues or failure which ideally should be caught.

> delete duplicated entries before the insert

Any idea how do we do that in a concise way?

**Comment by mhombach** [comment]
Regarding the missing catch for database-problems:
1st: mongoose has a buffer method that should belp when dealing with connection issues.
2nd: You can try-catch the database.issues too. there is nothing wrong with using nested try-catches, it's even more "correct", i would say, than putting your whole code in one big try-catch and hope for the best :)

Deleting duplicated entries from an array? I don't know if there is already a library (lodash maybe) or higher order function that does this for you but if not, you can loop throgu the erray and sort all entries by the `id_str` and when that has finished, you could loop over it again and always check if `entry[i].id_str == entry[i+1].id_str` and if that's true, delete one of both. this way, after that loop, you are left with only unique values for `id_str`. Also, this way, since you are doing custom coded loops, you can also check, if entries are cuplicated, if you prefer one over the other (maybe the latest entry is better to keep than an older one for example).

**Comment by FullstackJack** [comment]
My use case for this type of "throw data over the wall" insertion is in data aggregation from disparate data feeds that may or may not be updated when I pull their data on an interval. I'm worried that finding them by ID first would be more expensive for reads (more strain on Mongo) than just transmitting the data over the wire and letting Mongo determine duplicate during write. I suppose it's a problem of time vs transfer cost since either way Mongo will have to know if the data already exists. Can you afford to wait and prune your data or would you rather incur the cost of data transfer and take less time? Which one is more cost effective?

**Comment by mhombach** [comment]
If the data could contain duplicated entries and you don't want them, there is no reason why you should send them "over the wire" and letting the DB handle such cases.
Still, if you are doing that, you can use pipelines in mongoDB that have dynamic functionalities and can reduce the array to only not-duplicated entries. But then again, the DB is doing the exact same thing you could already have done before sending it.
I don't know your details, but maybe you can switch from an array to a map? This way you could just `set` the values and if they are not existing, they would be created, otherwise existing values are overwritten. This way you are not running into the problem ever that you have duplicated entries. MongoDB can also store maps to my knowledge but even if you need the array-structure inside the db-schema, you could just convert the map to an array before passing it.
What do you think about this approach? :)

**Comment by Buddikazz** [comment]
!!Need a help.I have added 1000000 numbers and make ordered:false if it have duplicate value in every 1000 items less than 200 it work fine.But if more than 500 duplicates in 1000 it gave a error and stop the insert other values.

**Comment by mhombach** [comment]
> !!Need a help.I have added 1000000 numbers and make ordered:false if it have duplicate value in every 1000 items less than 200 it work fine.But if more than 500 duplicates in 1000 it gave a error and stop the insert other values.

Please send a working code-example of what is working and what is not. I don't fully understand your problem and the mistake might be somewhere else :)
