### ISSUE TITLE
save() function not available in schema instance methods

### ISSUE THREAD

**Issue by carterw** [Automattic/mongoose#7329]
I'm experimenting with instance methods embedded in schemas and ran into an odd defect. I'm using mongoose 5.3.15

Here's an example that works;
```
 UserSchema.methods.fetch = async function(specs){
    try {
        let m = this.model("User");
        let doc = await m.findOne(specs);   // this works
        return doc;
    }
    catch (e) {
        console.error(e);
        throw(e);
    }
}
```

This fails;
```
UserSchema.methods.doSave = async function(callback){
    try {
        let m = this.model('User');
        if ('save' in m)
            var y = 'ok';  // this statement is not reached
        let doc = await m.save();  // causes an exception
        return true;
    }
    catch (e) {
        console.error(e);  // TypeError: m.save is not a function
        return false;
    }
}
```

... but this works;
```
let UserModel = models.getModel('User');
let User = new UserModel(aUser);
var result = await User.save();  // succeeds
```

**Comment by vkarpov15** [comment]
Models don't have a static `save()` function, [`save()` is an instance method](https://mongoosejs.com/docs/api.html#model_Model-save) and in Mongoose, an instance of a [model](https://mongoosejs.com/docs/models.html) is called a [document](https://mongoosejs.com/docs/documents.html). Somewhat confusing since we also have a separate document class.
