### ISSUE TITLE
Cannot use virtuals referencing schemas in external projects

### ISSUE THREAD

**Issue by nick13jaremek** [Automattic/mongoose#7417]
Hello,

I am trying to set a virtual attribute on a Mongoose schema with a ref to another Mongoose schema **that is defined in some other project**, like this:

```
const localSchema = new mongoose.Schema({
  ...some fields
})

fooSchema.virtual('remoteVirtual', {
  ref: 'remoteModel',
  localField: '_id',
  foreignField: 'remoteId'
})

const Foo  = mongoose.model('localModel', fooSchema)
```

In this example, `localModel` is the schema of my current project, and `remoteModel` is the Mongoose schema of some external project, that is not accessible from the current project. Additionally, there exists a `remoteModel` MongoDB collection in my database, so this collection is gettable.

However, with this schema configuration, after attempting to get `localModel` documents, I get the following error:

`Schema hasn't been registered for model "remoteModel"`

In order to solve this, I guess the `remoteModel` schema should be registered in the local project, but this is not feasible in my case since the `remoteModel` schema is in an external project.

**Is there any way to reference schemas defined elsewhere (not in the same project) in virtual methods?** I could not find anything in the current docs.

Currently using:
- MongoDB: 3.6.8
- Mongoose: 5.3.13
- NodeJS: 10.13

Thanks in advance!

**Comment by mhombach** [comment]
As far as i know there is no way to "include" an external model/schema.
Also, "virtuals" are maybe not what you think they are. They basically are just setter-/getter-functions in a schema/model.
`Only non-virtual properties work as part of queries and for field selection. Since virtuals are not stored in MongoDB, you can't query with them.`(https://mongoosejs.com/docs/guide.html#virtuals).

Mongoose needs to compile, link and do some internal stuff on models while the library is loading on runtime.
For example, how is your local code supposed to access a virtual property of the "remote model"? It has just access to the entris within the database. No information are available about the schema, validations, hooks and all those kind of things.
I don't know the exact thing you want to achieve with this, but there must be another way.
You could, for example, just copy (file-copy) the model from that external server.
If you only have database-access, then you need to code some basic schema/model yourself (locally).
You can try to get as detailed in that as possible or you just create a any/mixed schema and just hope that the attributes you access are existing.

**Comment by nick13jaremek** [comment]
@mhombach Thank you for the response.

What I am trying is to define a *populate virtual field* on a Mongoose schema so that I can  access the contents associated to this virtual field with a `populate` call. From what I understand, this allows to access some other collection's data by executing the `populate` method on the mongoose query.

This use case is explained in the official docs [here](https://mongoosejs.com/docs/populate.html#populate-virtuals)

The error I am facing happens because the referenced schema in the populate virtual field does not exist locally, instead it is defined in some other repository which my local repository cannot access.

However, both repositories access the same MongoDB database collections, so ideally there should be some way to skip the validations on the remote schema. Right now, this is not possible, because the referenced schema must exist on the same repository as the schema that contains the populate virtual field.

Duplicating schemas in both repositories is not feasible, as it would become a maintenance burden.

**Comment by mhombach** [comment]
I understand your problem, but this is not going to work:
As you already said, you are trying to reference a MODEL (remoteModel).
To make it short:
- For referencing, you need a MODEL. Having access to the collection is not going to help in any way
- You do not have access to the remote-model
- Your plan is not going to work

The model is not just some definition on the data-structure. As i said, it contains hooks, getter/setter, virtuals, validations, logging, calling other functions and much more.
This will not work and it's not intented to work this way.
If you can give us more insight on your situation, maybe we can guide you to a working solution:
- Does the other DB-/collection-owner approve of your plan to access the data?
- Does an API exist to get data from the remote database/collection?

Mongoose, as every ORM/ODM, is made for making database-stuff "structured" and "safe". The other model may contain highly important validations or hooks to, for example, never be able to directly read a password-hash from the database. Or to make sure that a user-role can never be set to "admin" by a non-admin user. Or that an email-adress will ALWAYS (in 100% of the cases) be a valid email-adress.
All these (and much more) functions, which are build on top of the pure database by mongoose, will be completelely skipped if you are direct-accessing the database.

If the owner of the other db/collection is fine with you accessing all his data directly without ANY validation and stuff, then try to get to a solution with him like an API you can call.
Or give us, as already said, more insight on your situation.

Just for clarification: The documentation-reference you provided is talking about referencing within YOU mongoose setup.
