### ISSUE TITLE
Doc: Add Cast error exemple in validation.jade

### ISSUE THREAD

**Issue by JulioJu** [Automattic/mongoose#7514]
Hi,

Maybe it could be cool to add the following sample. But there isn't a `validation.jade` to submit a Pull Request.  

Please, what do you think about the following ? If you are ok, where we could add it? Before https://mongoosejs.com/docs/validation.html#built-in-validators?

<hr />

### Type Validation
Mongoose check the type of each field. If the field does not correspond, it raise a `CastError`.

See also https://mongoosejs.com/docs/schematypes.html

Note: contrary to `save`, for `update`, `updateOne`, `findOneAndUpdate` and `updateMany` by default, mongoose only returns the first error that occurred in casting the query. Turn on the option `multipleCastError` to aggregate all the cast errors.

```javascript
var personSchema = new mongoose.Schema({
  isUnderage: Boolean,
});

var Person = mongoose.model('Person', personSchema);

var person = new Person({ isUnderage: 'XXX' });

person.save(function (err) {
  // `err` is a ValidationError object
  // `err.errors.isUnderage` is a CastError object
  assert.equal(err.errors.isUnderage.message, 'Cast to Boolean failed for value "XXX" at path "isUnderage"');
  assert.equal(err.errors.isUnderage.kind, 'Boolean');
  assert.equal(err.errors.isUnderage.path, 'isUnderage');
  assert.equal(err.errors.isUnderage.value, 'XXX');
  assert.equal(err.errors.isUnderage.name, 'CastError');

  assert.equal(err.name, 'ValidationError');
});

```

**Comment by vkarpov15** [comment]
"Type validation" is an interesting alternative, but the term mongoose uses is "casting", so that should be the title.

The validation docs are generated from the `test/docs/validation.test.js` file using [acquit](http://acquit.mongoosejs.io), so make your changes in that file. Add your example as the test case, the header title as the test name, and the body as the comments.

Also, can you change the `isUnderage` example? It skirts a little too close to topics I'd rather avoid putting in our docs.

**Comment by JulioJu** [comment]
Ok cool, 

Sorry, I've taken the first example that I've found in my small project for University ;-). 

Maybe simply: 

```javascript
var bicycleSchema = new mongoose.Schema({
  isBlue: Boolean,
});
```

Or an other example, as you wish ;-) .

**Comment by vkarpov15** [comment]
That works for me

**Comment by JulioJu** [comment]
Cool :-)
