### ISSUE TITLE
regression: 5.4.11 rejects subdocument required:false if type is not explicitly Object

### ISSUE THREAD

**Issue by autopulated** [Automattic/mongoose#7516]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
in 5.4.10 and below, this is accepted:
```
var testschema = new mongoose.Schema({
    subdoc:{
        required:false
    }
});
```

**If the current behavior is a bug, please provide the steps to reproduce.**
In 5.4.11, the above schema produces the error:
```(stack:TypeError: Invalid value for schema path `subdoc.required` ...```

Unless the subdocument type is explicitly set to `Object`:
```
var testschema = new mongoose.Schema({
    subdoc:{
       type: Object,
        required:false
    }
});
```
**What is the expected behavior?**
5.4.11 should continue to accept schemas which were accepted under 5.4.10

**Please mention your node.js, mongoose and MongoDB version.**
tested with node v10.15.0 amongst other v10 versions.

**Comment by vkarpov15** [comment]
The fact that this worked in Mongoose 5.4.10 is an accident more than anything, the `testschema` you defined actually creates `subdoc.required` as a path of type [mixed](https://mongoosejs.com/docs/schematypes.html#mixed) as opposed to a property `subdoc` of type object that isn't required:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7512`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  
  var testschema = new mongoose.Schema({
    subdoc:{
        required:false
    }
  });

  console.log(testschema.path('subdoc.required')); // This is a path in the schema!

  var testschema2 = new mongoose.Schema({
    subdoc:{
        type: Object,
        required:false
    }
  });

  console.log(testschema2.path('subdoc.required')); // undefined
}
```

So your schema needs a little work.

But since this check has caused so much confusion, it was probably too big a change for a patch release. Just make sure you structure your schemas correctly going forward, because the way you wrote `testschema` will likely break in 6.0 (see #7181, etc)
