### ISSUE TITLE
Only authenticated against one instance when connecting to multiple mongos (Compose.com)

### ISSUE THREAD

**Issue by christopherhex** [Automattic/mongoose#7544]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
We're using a connection string that contains the two mongos urls:
```
mongodb://<user>:<pass>@<host1>:<port1>,<host2>:<port2>/dbname?ssl=true
```

What we're seeing is that mongoose/mongodb is sending queries to both mongos instances, but is only correctly authenthicated against one, giving a lot of `not authorized on <db> to execute command`.

**Please mention your node.js, mongoose and MongoDB version.**
* mongoose: `5.4.14`
* MongoDB: ` 3.2.10` (Hosted at Compose.com with 2 `mongos` instances)
* node.js: `8.10.0`

**Comment by vkarpov15** [comment]
I'm not going to be able to realistically repro this because compose no longer allows spinning up MongoDB instances:

![image](https://user-images.githubusercontent.com/1620265/54038370-665c5780-418e-11e9-800e-8fe29ad9da6f.png)

Here's a couple thoughts to help out though:

1) Users aren't stored on mongos instances, they're stored in the [config servers for the sharded cluster](https://docs.mongodb.com/manual/core/security-users/#centralized-user-data). If auth fails against one mongos but not the other, that probably means that you're connecting to two separate sharded clusters. Is the URI you're using the uri that compose recommends?

2) How did you set up your users? Via `createUser()` in the mongodb shell, via compose's UI, somewhere else?
