### ISSUE TITLE
Multi-document transactions retry indefinitely

### ISSUE THREAD

**Issue by chidiwilliams** [Automattic/mongoose#7571]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
- When I create multiple transactions on a single document at the same time (within ~300ms), the operations retry indefinitely.

**If the current behavior is a bug, please provide the steps to reproduce.**

- I have written a test script here: https://github.com/chidiwilliams/mongodb-transactions-test. The first test starts 10 transactions within 5s. The second one starts 10 transactions within 1s. The first test passes and the second keeps retrying indefinitely.

The tests look like below, but I'll suggest having a go at the test script:
```
  await Promise.all(
    [...new Array(10)].map((x, i) => asyncTimeout(async () => {
      const session = await conn.db.startSession({ readPreference: { mode: 'primary' } });
      await session.startTransaction({
        readConcern: { level: 'snapshot' },
        writeConcern: { w: 'majority' },
      });

      await runTransactionWithRetry(async () => {
        await User.findByIdAndUpdate(user._id, { $inc: { count: 1 } }, { session, new: true });
      }, session);
      await commitWithRetry(session);
    }, i * 500)),
  );
```

**What is the expected behavior?**
The two tests should pass.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 8.11.3, Mongoose: 5.4.14, Mongo driver: 3.1.13, MongoDB: 4.0.0

**Comment by vkarpov15** [comment]
As far as I can tell, the first test shouldn't pass because you don't actually create a new transaction if `restartTransaction` is false, see [here](https://github.com/chidiwilliams/mongodb-transactions-test/blob/master/mongo.js#L12-L21). If you get a `TransientTransactionError`, you need to start a new transaction, see the [MongoDB docs on retrying errored transactions](https://docs.mongodb.com/manual/core/transactions/#retry-transaction-and-commit-operation).
