### ISSUE TITLE
unmarkModified not working as intended

### ISSUE THREAD

**Issue by jonasschmedtmann** [Automattic/mongoose#7578]
**Do you want to request a *feature* or report a *bug*?**
A bug, I think

**What is the current behavior?**
Before saving a document, I mark a certain property with `unmarkModified`. After saving, the document I get back from mongoose _is modified anyway_ (that's the bug), **but** the modification is not persisted in the database (this part works as intended). This is confusing when I send that updated document back to the client, which is now not a correct representation of the actual document in the database.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
userSchema.pre('save', function(next) {
  if (this.originalRole !== 'admin') {
    this.unmarkModified('role');
  }
  next();
});

const updateUser = async (req, res) => {
  const user = await User.findById(req.params.id);
  user.role = req.body.role;
  const updatedUser = await user.save();

  res.status(200).json({
    status: 'sucess',
    data: updatedUser
  });
};
```

**What is the expected behavior?**
If using `unmarkModified`, both the document I get back from mongoose and the database should respect that setting, showing consistent behavior. 

**Please mention your node.js, mongoose and MongoDB version.**
Node: 10.11.0
Mongoose: 5.4.14
MongoDB: 4.0.6

**Comment by vkarpov15** [comment]
In order to support this, Mongoose would have to store the original value for every modified path, which would be a little much. You can work around this pretty easily by doing `this.role = this.originalRole`. As documented, [`unmarkModified()`](https://mongoosejs.com/docs/api.html#document_Document-unmarkModified) only prevents Mongoose from persisting changes, it doesn't actually change the document for you.
