### ISSUE TITLE
Model.validate(obj, [propsToValidate])

### ISSUE THREAD

**Issue by andresespinosapc** [Automattic/mongoose#7587]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
I run updateOne with upsert and I can add a document which doesn't have some required fields in the schema.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const Item = mongoose.model('Item', new mongoose.Schema({
   name: {
        type: String,
        required: true,
    }
}, {
    strict: false,
});

Item.updateOne({}, { $set: { category: 'test' } }, { upsert: true }).exec().then(console.log).catch(console.error);
```

**What is the expected behavior?**
It should validate the query before performing it in the database.

**Please mention your node.js, mongoose and MongoDB version.**
Node.js: 8.11.3, Mongoose: 5.4.17, MongoDB: 3.6.3

**Comment by mhombach** [comment]
I might be missing something here, but what do you expect to happen?
You are updating one Item-entry and are setting the `name`-field to `'test'` .
`name`, in your schema, is a String and is required. Both those are given (string, given).
When no document is existing in the db, a new one will be created (`upsert: true`) but again, you are setting the `name` to a valid String, so... Please try to rewrite your problem, if it still exists :)

**Comment by andresespinosapc** [comment]
I'm sorry, I've just updated it. I meant to set category instead of name.

**Comment by mhombach** [comment]
I think i found some documentation about this:
https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths

As you can see there, this basically is exactly your example here.
"Update Validators Only Run On Updated Paths". Since you are using the upsert-methode and not specifying the path `name`, the validation is not touching `name` in this scenario (as far as i understand).
Could you read that documentation and tell me, if you understand it the same way as i do?
I mean... findOne + upsert is, from my interpretation, meant to change some few fields on a document WITHOUT loading the whole document. But when the document is not loaded (only `category` is loaded in your upsert-example), then mongoose can never validate for example `name` because for validating it, it must first load the attribute.

**Comment by vkarpov15** [comment]
@mhombach is right, there isn't a way for Mongoose to reliably know beforehand whether your update will insert a new doc or update an existing one. In this case, you have a few options:

1) Remove the `upsert` and execute a separate `create()` if `updateOne()` didn't update any documents
2) Manually validate that `name` exists

There's an opportunity for an interesting feature here. How about if we support this:

```javascript
Item.updateOne({}, { $set: Model.validate({ category: 'test' }, ['category', 'name']) }, { upsert: true })
```

Just run casting and validation on the subset of paths defined in the 2nd param to `validate()`. How does that sound?

**Comment by 720degreeLotus** [comment]
@vkarpov15 As much as i love new features, in my opinion this is not a good thing to do:
Validation is more than checking _some_ of the fields. It's more about keeping the whole document consistent. So, running only few field-validations, for me is the wrong approach because either a document is completely consistent or not. And custom-validations, that are for example run in pre-update hooks, are not taken into account too...
I don't know a "best" solution myself, but, even if it first seems wrong-ish, i would more tend to create something like this:
```js
Item.updateOne({}, { $set: { category: 'test' } }, { upsert: true, validate: true }
```
which **internally** loads the whole document, changes the given fields and then `save()` the document. This way there is more data traveling between mongoose and the DB and there are 2 queries instead of one, but this would be the cleanest approach imho.
But well, you could just write
```js
const item = await Item.findOne();
if(item == null) {
    item = new Item();
}
item.category = "test";
await item.save();
```
Not sure if this is a perfect way (we would need to clarify in the documentation that `validate: true` create 2 queries) but just run part of the document-validation seems not very consistend and futureproof to me :/

**Comment by vkarpov15** [comment]
I generally agree about keeping the whole document consistent. But being able to validate a subset of fields is very useful in cases where you don't necessarily have all the data, like when running updateMany or doing a bulkWrite.

The idea of actually loading the whole doc is one that we've discussed before, but decided against because generally one Mongoose function should only fire off one mongodb operation modulo middleware, especially if that function shares a name with a MongoDB driver function
