### ISSUE TITLE
Query.prototype.near's minDistance doesn't take meter as unit...(or just doesn't work)

### ISSUE THREAD

**Issue by aeroxy** [Automattic/mongoose#7594]
```
  db.listing.where('location').near({
    near: {
      type: 'Point',
      coordinates
    },
    minDistance: 1,
    maxDistance: opts.maxDistance,
    spherical: true
  }).limit(50).cursor;
```
The expected behavior is to have result based on the minDistance from the cursor but instead nothing is found, yet if I set minDistance to 0 or remove this option, result would return...(distance in meter should be 13450+)...

**Comment by vkarpov15** [comment]
The below script works as expected for me, returns the 3 locations that are close to each other and avoids the one that's fairly far away. Perhaps it is due to the fact that you're using `near: ` instead of `center: ` to specify the center for the search? See [Mongoose docs on `Query#near()`](https://mongoosejs.com/docs/api.html#query_Query-near).

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7594`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    loc: {
      type: { type: String },
      coordinates: [Number]
    }
  });

  schema.index({ loc: '2dsphere' });

  const Model = mongoose.model('Test', schema);

  await Model.init();
  await Model.create([
    // First 3 are within 3000m of each other
    { loc: { type: 'Point', coordinates: [-122.2489462, 37.5081308] } },
    { loc: { type: 'Point', coordinates: [-122.2292109, 37.486294] } },
    { loc: { type: 'Point', coordinates: [-122.2313246, 37.4850112] } },
    // Last one is within 50000m 
    { loc: { type: 'Point', coordinates: [-122.3895896, 37.7785741] } }
  ]);

  const cursor = Model.where('loc').near({
    center: {
      type: 'Point',
      coordinates: [-122.2304234, 37.485641]
    },
    minDistance: 1,
    maxDistance: 5000,
    spherical: true
  }).cursor();

  for (let doc = await cursor.next(); doc != null; doc = await cursor.next()) {
    console.log(doc);
  }
}
```

**Comment by aeroxy** [comment]
Okay let me try "center" and report it back to you. Thanks.

**Comment by schwarmco** [comment]
I just ran into the same issue:

- It works, if you're using GeoJSON as center
- You're not getting any results, if you're using legacy coordinate pairs

I got there, because the docs are using coordinate-pairs too: https://mongoosejs.com/docs/api.html#query_Query-near (not mentioning minDistance though)

The bug is kinda strange to me, because the actual mongo-query seems correct:

`tests.find({ loc: { '$nearSphere': [ -122.2304234, 37.485641 ], '$maxDistance': 5000, '$minDistance': 1 } })`

According to https://docs.mongodb.com/manual/reference/operator/query/nearSphere/ this should work (see "To specify a point using legacy coordinates, use the following syntax:")

**Comment by vkarpov15** [comment]
@schwarmco please open a separate issue with detailed code samples. "I ran into the same issue" is not actionable.
