### ISSUE TITLE
Using upsert and $inc subdocument

### ISSUE THREAD

**Issue by teknolojia** [Automattic/mongoose#7617]
The following schema is intended to record total views and views for a very specific day only.

```
const usersSchema = new Schema({
    totalProductsViews: {type: Number, default: 0},

    productsViewsStatistics: [{
        day: {type: String, default: new Date().toISOString().slice(0, 10), unique: true},
        count: {type: Number, default: 0}
    }],
});
```

So today views will be stored in another subdocument different from yesterday. To implement this I tried to use upsert so as subdocument will be created each day when product is viewed and counts will be incremented and recorded based on a particular day. I tried to use the following function but seems not to work the way I intended.

```
usersSchema.statics.increaseProductsViews = async function (id) {
    //Based on day only.
    const todayDate = new Date().toISOString().slice(0, 10);

    const result = await this.findByIdAndUpdate(id, {
            $inc: {
                totalProductsViews: 1,
                'productsViewsStatistics.$[sub].count': 1
            },
        },
        {
            upsert: true,
            arrayFilters: [{'sub.day': todayDate}],
            new: true
        });
    console.log(result);
    return result;
};
```

What do I miss to get the functionality I want? Any help will be appreciated.

Node: v10.15.0
MongoDb: v4.0.4
Mongoose: 5.4.19

**Comment by vkarpov15** [comment]
Upsert only affects top-level documents, the only way to "upsert" a subdocument with `findOneAndUpdate()` is using [the `$addToSet` operator](https://docs.mongodb.com/manual/reference/operator/update/addToSet/).

My recommendation would be to store `productsViewsStatistics` in a separate collection. Because `productsViewsStatistics` will grow without bound, your documents will get unwieldy and you'll run into the 16MB document size limit.

However, if your schema can't change, you can do the below. This will execute two separate updates, one which ensures there's an entry in `productsViewsStatistics` for `todayDate`, and one that increments counts:

```javascript
  await User.updateOne({ _id, 'productsViewsStatistics.day': { $ne: todayDate } }, {
    $push: { productsViewsStatistics: { day: todayDate, count: 0 } }
  });

  const result = await User.findOneAndUpdate({}, {
    $inc: {
      totalProductsViews: 1,
      'productsViewsStatistics.$[sub].count': 1
    },
  },
  {
    arrayFilters: [{'sub.day': todayDate}],
    new: true
  });
```

Also, I noticed one more issue in your code. The `day` schema definition below means that `day` will always default to the day your Node.js process started running, **not** the current day.

```javascript
day: {type: String, default: new Date().toISOString().slice(0, 10), unique: true}
```

You should make the `day` default a function:

```javascript
day: {type: String, default: () => new Date().toISOString().slice(0, 10), unique: true}
```
