### ISSUE TITLE
MongoError: command find|insert|update requires authentication

### ISSUE THREAD

**Issue by sd031** [Automattic/mongoose#7618]
for version 5.4.7, getting error:

error_data: {"operationTime":"6669675531664883727","ok":0,"errmsg":"command find requires authentication","code":13,"codeName":"Unauthorized","$clusterTime":{"clusterTime":"6669675531664883727","signature":{"hash":"jqjMmazFtCflNf4HZVikFGd4xbE=","keyId":"6634412437120483330"}},"name":"MongoError"}

Do anyone have any idea why this happening, my config is:
{
keepAlive: true,
socketTimeoutMS: 540000,
autoReconnect: true,
poolSize: 20,
reconnectInterval: 500,
reconnectTries: Number.MAX_VALUE,
}

I am using mongoDb atlas.

**Comment by 720degreeLotus** [comment]
Well...
First: Please don't post your issue on multiple sections within the same github-repository (https://github.com/Automattic/mongoose/issues/6838#issuecomment-473863332).
Second: We need to know, if this errormessage is because of a bug (mongoose) or a feature (Atlas).
What happens, if you use a tool like "Compass" to connect to the atlas instance and fire off the same query with the same user?
Atlas documentation tells

> To access clusters in a project, users must belong to that project. Users can belong to multiple projects. See [Atlas Access](https://docs.atlas.mongodb.com/tutorial/manage-users/).

We need to pinpoint your issue :)

**Comment by vkarpov15** [comment]
Are you actually providing a username and password? I don't see that in your config options, see https://mongoosejs.com/docs/connections.html#options

**Comment by relicmelex** [comment]
Why is this closed with no solution? It's referenced as a solution from other closed tickets as well...

**Comment by 720degreeLotus** [comment]
I guess it was closed because
- author hasn't answered to any of the 2 responses/questions for almost a month
- the issue was a duplicate that the author created multiple times
- many times on the internet, people only write back in issues, when the problem does still exist. When the problem is solved, many people forget to close or respond in their issues/questions. Vkarpov15 gave a hint to what might be the solution 22 days ago and since then no response was given. So maybe he assumed, that the problem was solved (would be my guess too).

Also i don't understand what you mean with "it has no solution" and "it's referenced as a solution in other issues", can you explain that in more detail? If this issue was referenced with the normal reference-syntax on github, then we should see the references in this issue too... But i don't see any :/

**Comment by relicmelex** [comment]
This issue is what linked me here: https://github.com/Automattic/mongoose/issues/6838
Referenced as "resolved" But... it doesn't seem resolved, just closed. And I understand why it was closed... makes sense.

**Comment by relicmelex** [comment]
This issue is what linked me here: #6838
Referenced as "resolved" But... it doesn't seem resolved, just closed. And I understand why it was closed... makes sense.

Can you look at the SO issue, or would you like me to copy paste my post here and we can re-open the issue, and when we get a solution I'll post that for anyone whom runs across it? @720degreeLotus 

Cheers :D

**Comment by 720degreeLotus** [comment]
@relicmelex Ah, i see now, thanks for the information :)
Hmm... i guess it's still not reproducable without paying money.
Maybe @vkarpov15 can write to firebase and ask for a free higher tier plan for debugging purpose?
Mongoose is the greatest ODM and i think firebase will happily help him out with test-accounts in every setting he needs (have asked such a thing myself some time ago, just ask and you will get positive answeres most of the time :) ).

**Comment by relicmelex** [comment]
@720degreeLotus I'm not using firebase. I'm using my entire own environment I plan on launch to an AWS cluster.

**Comment by relicmelex** [comment]
@720degreeLotus  - My ENV_VARs were empty. :/

**Comment by 720degreeLotus** [comment]
@relicmelex that happens to all of us at some point in life xD Thanks for beeing honest and coming back here for clarification :)
