### ISSUE TITLE
Correct way to pass parameter to pre post hook?

### ISSUE THREAD

**Issue by flyinghawker** [Automattic/mongoose#7631]
I have read lots of issues from here and stackOverflow but still unable to find a relatively official way to pass required parameter to pre post hook.

For example,
I am supposed to set password field by using findOneAndUpdate, and required to check if the new password has been applied before, if so then refuse to do the update.

I would like to do the check in pre(findOneAndUpdate'') hook, but there seems no way to pass my parameter to pre hook except **this._update** which contains the content to update, 
Actually I can really do something like adding` customName:'I am here'` in update clause, but looks weird, because update clause is purely to put` field:value`, not proper place to put parameter.

Just try to see if anyone can help me confirm the official way to **pass parameter to pre and post hook**

**Comment by 720degreeLotus** [comment]
There was a way mentioned by one of the mongoose maintainers, that you could add Symbol-Attributes to the document-object and read them in the hooks.
More about Symbols can be find here: https://www.keithcirkel.co.uk/metaprogramming-in-es6-symbols

So basically you can don't pass parameters to the hook-function but instead you can save the parameters (or options) in the document-object itself (not database, just the js-object) and read them whereever they are needed.
I hope this works for your use-case?

**Comment by flyinghawker** [comment]
@720degreeLotus 
when do some query like **findOneAndUpdate**, it is called by model like **UserModel.findOneAndUpdate**, no object to attach the attribute.
I will keep researching though. Thanks anyway.

**Comment by vkarpov15** [comment]
Can you clarify what you mean by passing a parameter to a pre hook with some code samples? I don't see how that relates with your example of checking for a reused password

**Comment by 720degreeLotus** [comment]
@flyinghawker Is there a reason why in your case it's not ok to create a custom function like `UserModel.myCustomFindOneAndUpdate(...)` so you can code your own syntax and pass it whatever you want? In my opinion this would be the best solution. Since there is, as you already said, no official way of passing arguments to a hook function, maybe just write a separate function? ^^°

**Comment by flyinghawker** [comment]
@720degreeLotus @vkarpov15 Thanks guys.
The example itself is not important. My main purpose it purely to pass custom parameter to hook. 
Based on the issue #7636 and my own finding, hook may not be able to help me implement certain logic. (I was supposing that hook could do all work in db, and no need to return huge piece of document, but it seems wrong)

**Comment by Ncifra** [comment]
I think @flyinghawker is trying to pass external parameters, sort of like trying to pass the `req` object, for checks inside the mongoose hooks.

**Comment by flyinghawker** [comment]
@Ncifra Yeah

**Comment by vkarpov15** [comment]
Hooks run in your node process, not in the database. Either way, still unclear what you mean by "passing a parameter"

**Comment by vincentwinkel** [comment]
I have the same concern.
I want to detect when something changed and add some flag for a custom logic.
If I attach some data to my doc (some properties _not_ being in he schema), I can access to them in the `pre update` (query) hook, but no in the `post update` on, like if data are sanitised.
In my case, I just want to be able to know in a `post update` (query) hook which field are modified. I'm not talking about `this.getUpdate()`, because it returns everything we put as params, but the properties that are actually modified (with a different value).
I'm reading tons of articles and forums threads since days, I don't find any proper way to do that.

**Comment by vkarpov15** [comment]
@vincentwinkel there's no way to do that with `update()`. If you need to track exactly what changed in the database, you need to use change streams:

https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html
https://thecodebarbarian.com/stock-price-notifications-with-mongoose-and-mongodb-change-streams.html

**Comment by jberrydev** [comment]
Ok so after a lot of effort the best way I could find was like so 
`await OrderModel.find({}, {test: 'test'})`
Then in your plugin 
`
export function myPlugin(schema: Schema, options: any) { 
 schema.pre(['find', 'findOne'], function () {
    const { _fields } = this as any;
    console.log('PLUGIN', _fields, schema);
  });
}
`
The _fields object will have whatever you pass.  So you could theoretically pass your request obj or session or whatever.  The suck part is you have to pass your params every time your query.  Would be nice to figure out a more global way to handle this for all models or schemas.  This at least allows you to have a global plugin with schema and passed in data.  I assume you could wrap the Model calls with something like withData or withSession, but would be nice to have something out of the box.
