### ISSUE TITLE
Virtual limitation ??

### ISSUE THREAD

**Issue by flyinghawker** [Automattic/mongoose#7636]
When I play with virtual piece, there seems two limits that bother me.
1. you can no longer use **lean()** in query, otherwise no virtual will be returned (there is one plugin that support lean to return virtual but has **bug** with typescript)
2. This one bothers me most: when virtual try to return something related to specific field in schema,  that field has to be **selected** , e.g. if I want to count the number of comments, the getter of my virtual property is **this.comments.length**, then comments field has to be chosen in query selected cause. it may looks like

> await PostModel.findOneAndUpdate({...query}, 'comments numOfComments').exec()

What if the comments array is hugely long? As I understand, this might be nightmare!

**Comment by vkarpov15** [comment]
1. Use mongoose-lean-virtuals: http://plugins.mongoosejs.io/plugins/lean-virtuals , and file a bug report with your typescript bindings.
2. If your comments array is huge, you should consider having a separate comments collection rather than embedding it and using the count option: https://mongoosejs.com/docs/populate.html#count

**Comment by flyinghawker** [comment]
@vkarpov15 Thanks for your answer firstly.
The array I am using here is one that targets array of dbRefs to comment collections already.
The purpose I try to use hook to implement count is that **I was assuming** the hook works inside db , no need to return entire array so that saving resource. But so far it turns out my assumption not correct.
Your 2rd suggestion is good, besides, I may add one field called **numOfComments** and increment 1 when $addToSet new comment in the post document.
Thanks again.

**Comment by flyinghawker** [comment]
> await PostModel.findOne(
>       ObjectId(postId),
>       'noc txt ia lb numOfLike c numOfComment sb numOfShare nor createdAt updatedAt isEdited'
>     )
>       .populate({
>         path: 'u',
>         select: 'au g nn i fe fi numOfFollower relation',
>         **options: { userId },**
>       })
>       .exec();


Here is one example I was talking, 
I can pass userId by **options: { userId }** to hook. But I don't like this hack. LOL

**Comment by 720degreeLotus** [comment]
Hooks don't execute in the database, they execute on the nodeJS/JS-Layer. For better differentiation between what happens IN the database and what happens OUTSIDE the database, i hint you to the [MongoDB-Docs](https://docs.mongodb.com/manual/reference/method/db.collection.find/). Everything written there, is DB-internal, regardles of any programming language.
Everything NOT written there (as mongoose-schemas/models, queries, functions, hooks, etc) is "ontop" of mongodb and is not executed inside of it.
One thing, regardless of your issue here, i want to mention is:
Arrays in a MongoDB-Document that COULD grow infinitely, are a so  called "anti-pattern".
There is a limit on how big one single document can get in MongoDB (i think it's 16 MB today). For example, when you have a AUTHOR with an array of POSTS-references, then at some point you could get in trouble.
In this case you would put the AUTOR-ID into each POST and populate things on demand.

**Comment by flyinghawker** [comment]
@720degreeLotus 
So awesome answer!
I will definitely do check MongoDB-Docs.
Regarding the issue about array, your suggestion is very valuable and BTW, some people also suggest we could separate the array when reach certain limit.

**Comment by 720degreeLotus** [comment]
Yeah, it's totally possible to change the referencing later.
But to be honest, you would to implement some mechanic to keep watch over the largest document and warn when something is near from day one.
If i would think "yeah, i can change that later if i hit that barrier" then i will at some point in time hit it and then have to recode FAST which will result in many errors and maybe not 100% consistent data.
So... better plan this beforehand :)
Some months a go i roughly estimated the number of references (type: mongoose-objectId) that can be placed into a single document and if i remember this number was slightly < 1,000,000... i think it was something like 800,000 or so BUT this was without ANY other attributes and with pure references.
Also, it's not advised to go near that limit, because performance can drop with big documents (that's the only reason why a limit exists).
So yeah, for posts an author writes, this could work (if the account is not used by multiple people that are writing many posts). You have to decide yourself what things could grow too big and you don't know what's coming in the future. Just wanted to place this warning here, because this is very important in cases with many references or data-arrays :)

**Comment by flyinghawker** [comment]
As I check so far and your idea @720degreeLotus 
When I try to count length of array without returning entire array, here might be a good try:

>    const res = await PostModel.aggregate([
>       { $match: { _id: ObjectId(postId) } },
>       { $project: {numOfComment: { $size: '$comments' } } },
>     ]).exec();

Mongoose, as I understand, it simply exposes mongoDb operator `aggregate` and this operation do the work in database by pipeline.

**Comment by flyinghawker** [comment]
@720degreeLotus agreed.

**Comment by 720degreeLotus** [comment]
@flyinghawker the `numOfComment` approach is very valid, but i personally don't use it if it's not totally needed. Because even if only the best coders in the world touch your code, at some point something could be forgotten and so some codeline/query forgets to increase/decrease the number and you suddenly end up with a wrong count.
I tend to think a LOT abput performance, limitations and edge-cases myself, but i try to "calm myself down" everytime because those performance-issues realyl can be tackled when the performance is slow/bad and something needs to be done (my opinion only) :)

**Comment by flyinghawker** [comment]
@720degreeLotus You spoke very practically. I also try to "calm myself down" and tell myself, put priority on some other points and just keep code as simple as possible so that it is extensible when problem comes to me and have enough space to fix it. Nobody could solve problem at once and also not necessary, every consideration comes with price. :)

**Comment by vkarpov15** [comment]
I would err on the side of the numOfComments approach. You read these docs far more often than you write them, and even if programmer error leads to numOfComments being off by one or two it is a minor issue, easily fixed. Plus Mongoose middleware makes keeping counters in sync pretty easy
