### ISSUE TITLE
List out valid options to update(), callback params, and link to query docs

### ISSUE THREAD

**Issue by Aarbel** [Automattic/mongoose#7646]
Thanks guys for your work ! Unfortunately Mongoose doc is still very hard to read ;) Do you plan to enhance it ? 

For example in the screenshot bellow, we don't know :
1- What type has the returned Query
2- What are the parameters passed to the callback
3- What could be the options
4- We don't really understand what could be the result of the example, we don't have the dataset input and output

![image](https://user-images.githubusercontent.com/25119847/55030493-cd8e5e80-500c-11e9-8d3a-49e8bb81f965.png)

Cheers

**Comment by 720degreeLotus** [comment]
Since i recently contributed to the docs, i may have an idea why this is not very easy to manage:
The docs are directly generated from the function-declaration.
So the plain JS files from the library are parsed and the JSDoc declaration is taken and converted into the html-version.
So for example, the example-code in your screenshot, this is the real code from the js-file of that function:
```js
/**
 * Sends an updateOne command with this document `_id` as the query selector.
 *
 * ####Example:
 *
 *     weirdCar.updateOne({$inc: {wheels:1}}, { w: 1 }, callback);
 *
 * ####Valid options:
 *
 *  - same as in [Model.updateOne](#model_Model.updateOne)
 *
 * @see Model.updateOne #model_Model.updateOne
 * @param {Object} doc
 * @param {Object} options
 * @param {Function} callback
 * @return {Query}
 * @api public
 * @memberOf Document
 * @instance
 */

Document.prototype.updateOne = function updateOne(doc, options, callback) {
...
```

This is, to be honest, a very clever way, because you never have a different doc-version than the actual code (since the docs are generated FROM the code itself).
But this also doesn't allow to manually edit those pages like a wiki...
I am new to contributing to projects but i can try to think about some way of solving this problem in a nice way. But this highly depends on the maintainers choice if those ideas are ok.

If, with the knowledge you now have about how those pages are generated, you have some idea yourself, i would be really happy to read it.
The docs are "ok" most times, but i have to also admit, that they are not easy to read and lack for example having multiple examples per function to better understand differnt usages of it.

**Comment by Aarbel** [comment]
Thanks a lot for your help @720degreeLotus !

One example for more readable doc:
**BEFORE**
![image](https://user-images.githubusercontent.com/25119847/55063441-44ad0c80-5078-11e9-800c-26b77802bcd0.png)


```
weirdCar.updateOne({$inc: {wheels:1}}, { w: 1 }, callback);
```
In this case `document` seems not specified, so very hard to understand which document `updateOne` is updating...
Moreover we don't know what `{ w: 1 }` is for, when i try to reach `options` clicking `Model.updateOne`, the destination is this link : https://mongoosejs.com/docs/api.html#query_Query-setOptions and i can't see a `"{ w: …}"` option (it's still a mystery). 


**AFTER**
```JS
####Example:

	// weirdCar Collection
    [
        …
        { _id: 765765, wheels: 2},
        { _id: 865766, wheels: 6},
    ]

    weirdCar.updateOne({ _id: 765765 }, { $inc: {wheels : 1} }

    // Output
    [
        …
        { _id: 765765, wheels: 3},
        { _id: 865766, wheels: 6},
    ]
```
You can also put links for `doc` `options` and `callback`, and also `Query`
http://usejsdoc.org/tags-inline-link.html
