### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by jakeleventhal** [Automattic/mongoose#7658]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After running my application for anywhere from 10 minutes to several hours (random), i get the following error.
```
2019-03-29T00:21:23.830925217Z { MongoNetworkError: connection 2 to mongo:27017 timed out
2019-03-29T00:21:23.830961540Z     at Socket.<anonymous> (/api/node_modules/mongodb-core/lib/connection/connection.js:259:7)
2019-03-29T00:21:23.830967832Z     at Object.onceWrapper (events.js:285:20)
2019-03-29T00:21:23.830971634Z     at Socket.emit (events.js:197:13)
2019-03-29T00:21:23.830975624Z     at Socket.EventEmitter.emit (domain.js:481:20)
2019-03-29T00:21:23.830979463Z     at Socket._onTimeout (net.js:447:8)
2019-03-29T00:21:23.830983157Z     at listOnTimeout (timers.js:327:15)
2019-03-29T00:21:23.830986466Z     at processTimers (timers.js:271:5)
2019-03-29T00:21:23.830989901Z   name: 'MongoNetworkError',
2019-03-29T00:21:23.830993263Z   errorLabels: [ 'TransientTransactionError' ],
2019-03-29T00:21:23.830996918Z   [Symbol(mongoErrorContextSymbol)]: {} }
```

I am getting this error many times in a row, for connection 0, 1, 2, 3, & 4

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 11.7.0
mongo docker image tagged from March 28, 2019 01:49 AM
mongoose 5.4.2

My options that I am passing in are:
```json
{
   keepAlive: true,
   useCreateIndex: true,
   useNewUrlParser: true
}
```

**Comment by jakeleventhal** [comment]
Update, I removed the keepAlive param and added 
```javascript
socketTimeoutMS: 300000 // Timeout after 5 minutes
```

This solved my problem but now within a few minutes of running my server, many users aren't able to fetch routes that require connecting to mongoose. I imagine the threads are all taken up? How can I solve this?

**Comment by vkarpov15** [comment]
This issue usually happens because you have a very slow query. The socket times out after a query runs for more than socketTimeoutMS, so bumping socketTimeoutMS just lets your slow queries run longer. I'd take a close look at your queries, add some middleware to track how long they're running, and add some indexes to speed up slow queries.

**Comment by jakeleventhal** [comment]
@vkarpov15 
Would using cursors would solve my problems? something like this
```
const cursor = Order.find({})
      .addCursorFlag('noCursorTimeout', true)
      .cursor()
      .eachAsync(async (order) => {
        await sleep(10000);
        console.log('order);
      });
```

And do i need the addcursorflag line?

**Comment by vkarpov15** [comment]
@jakeleventhal that should help. The 'noCursorTimeout' flag may be necessary depending on how long your `eachAsync()` runs because [MongoDB times out inactive cursors after 10 minutes of inactivity](https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/#closure-of-inactive-cursors). Depending on your [`batchSize`](https://mongoosejs.com/docs/api.html#query_Query-batchSize), Mongoose may call your `eachAsync()` callback several times before pulling more documents from the MongoDB server, so I'd recommend putting `noCursorTimeout: true` if you expect your `eachAsync()` callback to take more than a couple seconds.

**Comment by felixsy** [comment]
Am getting this error after a request, however, I disconnected
I tried to connect but it refuses to connect but returns
Error: connection timed out

**Comment by vkarpov15** [comment]
@felixsy please open a new issue with code samples.
