### ISSUE TITLE
Mongoose Can't Connect To Replica Set in Docker-Compose

### ISSUE THREAD

**Issue by patientplatypus** [Automattic/mongoose#7705]
**Do you want to request a *feature* or report a *bug*?**

I would like to report a bug.

**What is the current behavior?**

I am trying to connect to a replica set and I keep getting: 

```
MongoDB connection error: { MongoError: no secondary found in replicaset or invalid replica set name
    at /var/www/back/node_modules/mongodb-core/lib/topologies/replset.js:649:11
    at Server.<anonymous> (/var/www/back/node_modules/mongodb-core/lib/topologies/replset.js:357:9)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at /var/www/back/node_modules/mongodb-core/lib/topologies/server.js:508:16
    at /var/www/back/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
``` 

The mongoose database is a dockerized database, but other than that should have no surprises. I have exhausted almost every other possibility in my debugging that I now wonder if this could be an error in how mongoose connect works (I filed one recently for the go-drivers so I'm wondering if the docs are current).

**If the current behavior is a bug, please provide the steps to reproduce.**

Please find my write up of attempting to connect to a mongoose replica set here: 

https://stackoverflow.com/questions/55637808/mongoerror-no-mongos-proxy-available-when-connecting-to-replica-set

**What is the expected behavior?**

That I can connect to my dockerized replica set.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

 "mongoose": "^5.4.19",

**Comment by patientplatypus** [comment]
Here is another example of the same pattern that seems to exhibit the same issue: https://gist.github.com/patientplatypus/e48e6efdcc9f0f1aa551cc8342d0f2f3

**Comment by patientplatypus** [comment]
On further research it may be related to this bug (_opened in 2016_) https://github.com/Automattic/mongoose/issues/4596

**Comment by vkarpov15** [comment]
Can you connect using the mongo shell? https://docs.mongodb.com/manual/mongo/ . Also, are mongo1-mongo3 resolvable names both inside and outside the docker container? Also, it is very strange that [this docker-compose file](https://github.com/yeasy/docker-compose-files/blob/master/mongo_cluster/docker-compose.yml) specifies 2 mongodb instances running v3.2 and 1 running v3.0 - is this intentional?

Also, why are you specifying the autoReconnect option? You might want to [read up on managing connections](https://thecodebarbarian.com/managing-connections-with-the-mongodb-node-driver.html).
