### ISSUE TITLE
Query casting guide

### ISSUE THREAD

**Issue by teolag** [Automattic/mongoose#7789]
I want to find documents in my collection using an array of firstNames. If I do it in plain MongoDB the documentation says i should use $in. But when I use Mongoose, it seems like $in is unnecessary.

### Setup:
```js
const Person = mongoose.model('person', new mongoose.Schema({
  firstName: {type: String, required: true},
  lastName: {type: String, required: true}
})

await Person.create([
  {firstName: 'Pelle', lastName: 'Larsson'},
  {firstName: 'Kalle', lastName: 'Jansson'},
  {firstName: 'Lotta', lastName: 'Nilsson'}
])

const wantedFirstNames = ['Pelle', 'Lotta']
```

### Find wantedPersons without using $in:
```js
const wantedPersons = await Person.find({firstName: wantedFirstNames})
// Returns two matching documents
```

### Find wantedPersons using $in:
```js
const wantedPersons = await Person.find({firstName: {$in: wantedFirstNames}})
// Also returns two matching documents
```

Can anyone tell me if it is OK to skip $in or if these two examples does something different. Is this documented somewhere?

**Comment by vkarpov15** [comment]
We need to make a note of this in the docs. In Mongoose, the two queries you specified are equivalent. Mongoose converts `Person.find({firstName: wantedFirstNames})` to `Person.find({ firstName: { $in: wantedFirstNames } })` because `firstName` has type `String` in your schema.

You can confirm this by turning on [Mongoose debug mode](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-set).

**Comment by teolag** [comment]
Great! Thank you for your answer. And great tip to enable debug mode!
