### ISSUE TITLE
Update the Mongo array of objects

### ISSUE THREAD

**Issue by bilal68** [Automattic/mongoose#7805]
Following is my schema

const userTimings = new Schema( {

    working_hours : [{
        type: Array,
        user_timings_start:String,
        user_timings_end:String
    }],
    name : { type: String, require: true },
} );
I am trying to update the working_hour array user_timings_start using following query

const userTimings = await UserTimingsModel.findOneAndUpdate(
      { _id: _id },
      {
        $set: {
          "working_hours.$.1":'10:00',
        }
      },
      {
        new: true
      }
    )
but it gives me "he positional operator did not find the match needed from the query."
any help would be appreciated

**Comment by vkarpov15** [comment]
In order to use the `$` (positional operator) in `"working_hours.$.1":'10:00'` in your update, you need to include `working_hours` in your filter as well. You'll either want to do something like:

```javascript
UserTimingsModel.findOneAndUpdate({ _id, 'working_hours.type': 'foo' }, { $set: { 'working_hours.$.user_timings_start': 42 } })
```

Or, if you want to update _all_ `user_timings_start` properties, you'll want to use the [all positional operator](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-array-filters.html)

```javascript
UserTimingsModel.findOneAndUpdate({ _id }, { $set: { 'working_hours.$[].user_timings_start': 42 } })
```

**Comment by bilal68** [comment]
@vkarpov15 thanks
