### ISSUE TITLE
Trying to access the bulkWrite session to validate entries that depend on the sequencing 

### ISSUE THREAD

**Issue by saadshahd** [Automattic/mongoose#7819]
I'm trying to access the **bulkWrite** session so I could validate sequential data entries
aka:

```js
[
  insertOne: {
    document: { idx: 1 }
  },

  insertOne: {
    document: { idx: 2 }
  },

  insertOne: {
    document: { idx: 3 }
  }
]
``` 

in the pre-validate hook I'm trying to get the previous point based on the **idx** order

so, for example, inserting `{ idx: 2 }` isn't valid until we insert `{ idx: 1 }` before it.

I'm trying to `findOne().session()` but I don't get `{ idx: 1 }` when pre-validating `{ idx: 2 }`

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**

**NodeJS**: v11.12.0.
**MongoDB**: v4.0.9.
**Mongoose**: v5.5.9

**Comment by Fonger** [comment]
According to the mongoose [spec](https://mongoosejs.com/docs/middleware.html), in pre-validate, `this` always refers to the single document that is being validated.

Maybe we can a new middleware for `bulkWrite` so that you can call `.pre('bulkWrite')` and `this` refers to the whole parameter(insertOne, updateOne...etc) passed into bulkWrite (NEW FEATURE).

For now, you need to validate yourself before calling bulkWrite.

> I'm trying to findOne().session() but I don't get { idx: 1 } when pre-validating { idx: 2 }
I think you mean `this.$session()` here in `pre('validate', function(){...})`?

**Comment by saadshahd** [comment]
> I think you mean this.$session() here in pre('validate', function(){...})?

I'm trying to find in the session ` findOne().session(this.$session())` but I don't get the new documents that just got added by the previous bulkWrite operation

**Comment by saadshahd** [comment]
@Fonger Hey, any news?

**Comment by vkarpov15** [comment]
The session won't help you with `bulkWrite()` - as far as Mongoose is concerned, `bulkWrite()` is one operation and there's no way to see what docs MongoDB has successfully inserted thus far. In order to do this, you should do a `for` loop:

```javascript
// Docs is an array of { idx: 1 }, { idx: 2 }, ...
for (const doc of docs) {
  await Model.create({ idx: 1 });
}
```
