### ISSUE TITLE
[improvement] always return a promise even a callback used, see a use case

### ISSUE THREAD

**Issue by xxyyzz2050** [Automattic/mongoose#7826]
```
function connect(callback){
  //calback(error,ok)
 let promise = new Promise(resolve => resolve(connection));
if(callback && typeof callback=="function"){
     promise = promise
            .then(connection=>{callback(null,connection); return connection;}) //we returned the connection object for the next .then() in the chain
            .catch(error=>callback(error))
 }

return promise; 
}

```

usage:
```
connect((error,db)=>{if(error)console.error("failed"); else console.log("connected")})
    .then(db=>db.model('user',{name:String}))
```

is equivalent to:
```
connect()
  .then(db=>{console.log("connected"); return db})
  .catch(err=>console.error("failed"))
  .then(db=>db.model(...))
```

**Comment by vkarpov15** [comment]
Unfortunately I'm going to have to mark this as a won't fix. We explicitly made it so that Mongoose doesn't return a promise if a callback is specified in 5.0.0: https://github.com/Automattic/mongoose/blob/master/History.md#500-rc0--2017-12-28 and don't see any reason to go back. Mixing promises and callbacks leads to unbearable spaghetti code in our experience.

You can listen to [connection events](https://mongoosejs.com/docs/connections.html#connection-events) if you want to use promises, but print a message when connection succeeds or fails:

```javascript
mongoose.connect().then(db => db.model());

mongoose.connection.on('connected', () => console.log('connected'));
mongoose.connection.on('error', () => console.log('error'));
```
