### ISSUE TITLE
Documentation: Guide for Update Validators does not list all update operations

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#7845]
https://mongoosejs.com/docs/validation.html#update-validators

As can be seen in the text for that section, it does not list all update operations. In fact, update() is considered deprecated and updateOne(), updateMany() or findOneAndUpdate() seem to be the correct queries to use.

In addition to this, I was confused that pre/post validate hooks are not called even though `runValidators: true` is set to true for an updateOne() operation. That might be expected behavior however. The reason for this confusion was that the text in the section pasted above, it sounds like since the update operations can support validation, the validation middleware would be registered and run before e.g. the updateOne middleware (i.e. the same that validation middleware normally gets placed as a pre-save hook).

**Comment by vkarpov15** [comment]
You're right about missing update operations, thanks, will fix that.

Pre/post validate hooks aren't called because `pre('validate')` and `post('validate')` are middleware for the [`Document#validate()` function](https://mongoosejs.com/docs/api.html#document_Document-validate). Update validators don't call that function because there's no document when running update validators, just isolated schema paths.
