### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8080

### ISSUE THREAD

**Issue by rayabhisek22** [Automattic/mongoose#7861]
I installed mongoose on my project. The code was this.
```
```
const mongoose = require('mongoose');
mongoose.connect('mongodb://127.0.0.1:8080/test', {useNewUrlParser: true});

mongoose.connection.once('open',function(){
  console.log("Connection established!");
});
```

```
And it showed the error.

**(node:47700) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
(node:47700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async fun
ction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not hand
led will terminate the Node.js process with a non-zero exit code.**

**Comment by thernstig** [comment]
@rayabhisek22 This is due to that your `mongoose.connect('mongodb://127.0.0.1:8080/test', {useNewUrlParser: true});` fails most likely since your MongoDB instance has not started. `mongoose.connect()` returns a Promise, see here: https://mongoosejs.com/docs/api.html#mongoose_Mongoose-connect

You thus have to use a .catch on the returned promise to avoid the warning.
