### ISSUE TITLE
Merging key values v5.0.14 vs v5.4.15

### ISSUE THREAD

**Issue by venkateshwarlu-bavandla** [Automattic/mongoose#7884]
```javascript
var mongoose = require('mongoose')

var options = {discriminatorKey: 'kind'};

var eventSchema = new mongoose.Schema({lookups: {
  type: [
    {
      name: { type: String }
    }
  ]}}, options)



var Event = mongoose.model('Event', eventSchema);

// ClickedLinkEvent is a special type of Event that has
// a URL.
var ClickedLinkEvent = Event.discriminator('ClickedLink',
  new mongoose.Schema({lookups: {
    type: [
      {
        hi: { type: String }
      }
    ]},url: String}, options));

var clickedEvent =
  new ClickedLinkEvent({lookups: [
    {
      hi: 'address1',
      name: 'address2',
    }], url: 'google.com'});

console.log(clickedEvent)
``` 

When i run above code with V5.0.14
Output:
```javascript
{ _id: '5cff48fd1a01210f7034d7fe',
  kind: 'ClickedLink',
  lookups:
   [ { _id: '5cff48fd1a01210f7034d7ff',
       hi: 'address1',
       name: 'address2' } ],
  url: 'google.com' }
```
But when i run the same code with v5.4.15 i got different out put

```javascript
{ _id: '5cff485dab07fe0da353edc0',
  kind: 'ClickedLink',
  lookups: [ { _id: '5cff485dab07fe0da353edc1', hi: 'address1' } ],
  url: 'google.com' } 
```
For achieving same behavior should i need to do anything more on v5.4.15.

**Comment by vkarpov15** [comment]
This proved to be a very challenging issue. It wasn't particularly hard to find the root cause of the discrepancy, it was the fix for #7200, https://github.com/Automattic/mongoose/commit/a4633fd304ccc8159ddd4b03d9e102c224cabf47 .

But figuring it out so that merged schemas actually set getters correctly proved very tricky. Turns out we need to recompile all child models after we merge the discriminator schemas to make sure getters get set correctly. Fix will be in 5.6.1 :+1:
