### ISSUE TITLE
Remove lodash from dev dependencies

### ISSUE THREAD

**Issue by rvillane** [Automattic/mongoose#7972]
Latest mongoose, version 5.6.4 is using [loadash 4.17.11](https://github.com/Automattic/mongoose/blob/master/package.json#L51) that is impacted by [CVE-2018-16487](https://nvd.nist.gov/vuln/detail/CVE-2018-16487)

Loadash v4.17.13 has corrected this security vulnerability https://www.npmjs.com/package/lodash/v/4.17.13

**Comment by vkarpov15** [comment]
Fixed in master. However, lodash is a dev dependency for us, so if you `npm install mongoose` you don't get any version of lodash, so this is a non-issue.

**Comment by vkarpov15** [comment]
Looks like GitHub recently started sending security warnings for dev dependencies. That means we'll need to refactor our dev dependencies to avoid getting inundated with these sort of non-issues. In this commit, I removed lodash entirely and just left `lodash.isequal` and `lodash.isequalwith` because we have a couple tests that specifically test lodash integration.
