### ISSUE TITLE
mongoose connection not close.

### ISSUE THREAD

**Issue by ketankanhasoft** [Automattic/mongoose#7994]
I have saas based application and have multiple database, my backed is in node js and fronend is in reactjs. Based on api request I need to connect database and do operations. I have found that connections which are opened from API, it's not closed and it's opened forever so that count of connections will be more than 50,000 . And because of this my application is slow or sometime it's down until i restart node applications.

**Comment by mhombach** [comment]
I'm not 100% sure you have described your architecture correct.
You have a backend and a frontend. The frontend will use http-requests to your backend.
HTTP-requests are nothing that "stays open". You send a request, you get a response, that's it and everything is done.
So the connection, that stays open, has nothing to do with your frontend.
On your backend-side you have to look at how how are opening a connection from the nodeJS application to your database.
In your case i guess you are opening a database-connection when an api-requests comes in. This is really bad and you want to avoid that.
Move the "db-connect" code-segment to somewhere else in your code, that is executed when the app stars. This way you only open one connection the whole time.
You can try to create a clean way of closing the db-connection then if your application shuts down, but you could also use the connection-timeout on the database to just let it close connections that are considered "dead" because of X hours of inactivity.
Try this and report back, if this fixed your problem :)

**Comment by vkarpov15** [comment]
It sounds like you're creating a new connection for every API request. That is incorrect. [Please read the connection docs](https://mongoosejs.com/docs/connections.html).

Next time, please follow the issue template.
