### ISSUE TITLE
Mongoose queries returns raw result sometimes

### ISSUE THREAD

**Issue by ashishlal91** [Automattic/mongoose#8020]
I do not why but sometimes when I use spread syntax with mongoose returned object I get raw data. However I get the data in `_doc` but what is the reason behind this. Can I get pass any option to get the true data.

Here is the example 

```
const data = await Model.findOneAndUpdate({ })
const object = { ...data, token: "abcdefghifjklelkjf" }
console.log(data)
```

I get this

```
41:
$__: {strictMode: true, selected: {…}, shardval: null, saveError: null, validationError: {…}, …}
$init: true
$locals: {}
errors: {undefined: {…}, files: {…}}
isNew: false
_doc: {status: "Finished", isOnHold: false, requirements: Array(0), files: Array(0), reportFileIds: Array(1), …}
__proto__: Object
```

**Comment by Fonger** [comment]
You can either use [`lean() in query`](https://mongoosejs.com/docs/tutorials/lean.html) or use [`doc.toObject()`](https://mongoosejs.com/docs/api/document.html#document_Document-toObject) to solve this. Mongoose return decorated document, you can't directly use it in spread.


For example

```js
const object = { ...data.toObject(), token: "abcdefghifjklelkjf" }
```

**Comment by Ncifra** [comment]
That is because as mentioned by @Fonger you are being returned the mongoose decorated document, and when trying to assign a value by using spread, you are actually assigning to the mongoose document a property that is not defined in the schema. Your way would work if `token` was in the schema definition (I assume you have it not defined in the schema), so you would need first to get an actual Object as @Fonger explained the two cases.
