### ISSUE TITLE
Throw an error in POST validate Hook

### ISSUE THREAD

**Issue by alexcaglairi** [Automattic/mongoose#8049]
i'm using Mongoose 5.5.10 with Sails Js 1.2.2 and i have a problem validating a model in a post validate hook.

In my controller i have a code like this:

```
try {

.....

books.validate();

...

} catch (err) {

....

}
```
In my Book model, after the normals statements about validation (that works perfectly), i add a post validation hook:

```
bookSchema.post('validate', function(doc,next) {

  sails.log('** HOOK POST VALIDATE **');

  next(new Error('test error'));

});
```
I have tried many examples found online but I can't generate an error that leads the controller to enter into the catch block...

I need to generate an error in the post validate that generates an exception seen as a validation error.

How can I do?

**Comment by Ncifra** [comment]
The problem in your code may be due to the fact that the way you call `validate()` it returns a promise (you don't use the [callback](https://mongoosejs.com/docs/api.html#document_Document-validate)), but you are using try/catch blocks instead of the promise's own `catch()` method. If you want to use it that way you will have to use async/await:

```
try {

.....

await books.validate();

...

} catch (err) {

....

}
```

But make sure that the function containing the above try/catch block is an `async` one.

**Comment by vkarpov15** [comment]
@Ncifra is right, the [`validate()` function is asynchronous and returns a promise](https://mongoosejs.com/docs/api/document.html#document_Document-validate), so you need to `await`.
