### ISSUE TITLE
Question - what is used as the secondary sorting criteria 

### ISSUE THREAD

**Issue by sl2016** [Automattic/mongoose#8056]
**Do you want to request a *feature* or report a *bug*?** - Question

**What is the current behavior?**
I am trying to sort on a numerical column from MongoDB. However, there are multiple records with the same value.It does sort the data based on specified numerical column, but it also uses the second column to sort data in case there are records with same value.

Would you be able to specify how sorting is performed in above scenario?

**Comment by Ncifra** [comment]
According to this it should be somewhat random and not reliable to always have the same result:
https://docs.mongodb.com/manual/reference/glossary/#term-natural-order

**Comment by vkarpov15** [comment]
If you want to sort by `name` and then by `age` if names are the same, do `User.find().sort({ name: 1, age: 1 })`

**Comment by GlennyDC** [comment]
Hi @vkarpov15 

I don't know if this is the right place but I would like to ask how it is possible to maintain the correct sorting behaviour when specifying an object as the sort parameter to sort on multiple document fields.

How can `User.find().sort({ name: 1, age: 1 });` always return the documents first sorted on `name` and, if there are multiple documents with the same `name`, later on `age`? I don't understand how this is possible since JS objects don't maintain the order of properties. By reading [this source code](https://github.com/Automattic/mongoose/blob/master/lib/query.js#L3687), I must conclude that the order of the sort object is undetermined. 

Of course this is not the case when passing an array of arrays as parameter to `sort` (the docs don't specify this), like this: 
```js
User.find().sort([
  ['name', 1],
  ['age', 1]
]);
```

Can you clarify how this works?

Kind regards

Glenny

**Comment by vkarpov15** [comment]
[JS objects do maintain the order of properties as of ES6](https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/). So object key order isn't really a concern in modern Node.js apps.

You can use the array syntax, but it isn't necessary.
