### ISSUE TITLE
Support SSL option for mongoose

### ISSUE THREAD

**Issue by christkv** [Automattic/mongoose#813]
Need to be able to support the ssl option for the driver so mongoose can connect to a ssl enabled mongodb replicaset or single server

see 

https://github.com/christkv/node-mongodb-native/tree/master/test/auxilliary

for usage

**Comment by SavePointSam** [comment]
For anyone that lands here today, the configuration has changed slightly since this original issue. For both `mongoose.connect` and `mongoose.createConnection`, the server options are at the root of the options object as briefly described in the description of the options parameter.

```
[options] «Object» passed down to the MongoDB driver's connect() function, except for 4 mongoose-specific options explained below.
```

All driver connection options are available [here](http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html). As an updated example using Mongoose v5.4.3:

```diff
const readServerConfiguration = async () => {
  // logic to read out instance configuration from file, environment vars, etc.
};

const establishMongoConnection = async (connectionDetails) => {
  try {
    await mongoose.connect(
      connectionDetails.uri,
      {
        useNewUrlParser: true,
+       ssl: true,
        user: connectionDetails.user,
        pass: connectionDetails.password,
      },
    );
  } catch (error) {
    console.log(error);
  }
};

const startServer = async () => {
  const serverConfiguration = await readServerConfiguration();

  await establishMongoConnection(serverConfiguration.mongoConnectionDetails);

  // perform other server startup work
};

startServer();
```

**Comment by vkarpov15** [comment]
Thanks @SavePointSam :+1:
