### ISSUE TITLE
conditional $lookup when foreignField is a part of an  object  in array 

### ISSUE THREAD

**Issue by albertyou2** [Automattic/mongoose#8194]
My "teacher" collection looks like  that :

```
{
    _id:'123456789',  
   name : "Alex",
   ...
}
```

my "course" collection  looks like  that :

```
{
    _id:'xxxxxxxx', // course id
  teachers : [
       { _id:"123456789", name:"Alex"} // teacher who will teach this course,
   ]
   ...
}
```

I want to  query teachers and courses belong to  this teacher at the same time . So i choose aggregation ,the code looks like this : 

```
let aggregateConditon = [
        { $match:{
          _id : '123456789',
        }},
        {$lookup: {
           from: "courses",
           let: { "tId": "$_Id" },
           pipeline: [
             { $match: {
                $expr: {
                       $cond: [ 
                           { $and : [ 
                              { $eq: ["$teachers._id", "$$roleId"] },
                              { $gte: [ "$startTime",new Date(start) ] },
                              { $lte: [ "$startTime",new Date(end) ] } ]},
                              1,0]
               }],
               as: "teachCourses"
        }]
```

But the result of  teachCourses is always empty.
I found that if the "teachers" field  is a string not an array ,the query will work.
Does any one has met this problem? Any suggestion?
Thanks !!!

**Comment by vkarpov15** [comment]
Hard to make an exact guess since lots of code is omitted, but here's a few suggestions:

1) You need to define every property prefixed with `$$` in your `$expr` in your `let`, see: https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-lookup-expr

2) Get rid of the `$cond` and `$and`, they are unneccessary.

3) Simplify. No need to do a separate sub-pipeline unless you really need to eke out some extra performance, otherwise you can just filter out courses whose `startTime` doesn't match in Node.js.

**Comment by keffybansal** [comment]
@albertyou2 I am facing the same issue, result is empty if I do conditional lookup on a foreign field which is present in array. How did you resolve this?

**Comment by keyur1994** [comment]
> @albertyou2 I am facing the same issue, result is empty if I do conditional lookup on a foreign field which is present in array. How did you resolve this?

If you want to do conditional lookup with the array field then first you need to unwind that array field as conditional lookup is not working like normal lookup.
