### ISSUE TITLE
Schema.isModified not always accurate for subschema paths

### ISSUE THREAD

**Issue by quinnlas** [Automattic/mongoose#8223]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
With a schema like so:
```
const secondLevelSchema = new Schema({
  id: Number,
  text: String
})

const topLevelSchema = new Schema({
  secondLevel: {
    type: secondLevelSchema
  }
}
```
If you create a new topLevelItem and set one of the properties of secondLevel but not the other,
for instance:
`new TopLevelModel({ secondLevel: { text: 'example' } })`

then you will have the following strange behavior for the other property:
```
topLevelItem.isModified('secondLevel.id') //true
topLevelItem.secondLevel.isModified('id')) //false
```

**What is the expected behavior?**
both values should be false, since the id has not been modified

**Comment by vkarpov15** [comment]
We fixed it so that both `topLevelItem.isModified('secondLevel.id')` and `topLevelItem.secondLevel.isModified('id'))` return `true`. The reason this behavior is that `new TopLevelModel({ secondLevel: { text: 'example' } })` sets `secondLevel`, so `secondLevel` is modified and therefore all of its children are modified as well. This is because `isModified()` exists primarily to help `save()` figure out what paths were updated.
