### ISSUE TITLE
Stages for updates

### ISSUE THREAD

**Issue by campanagerald** [Automattic/mongoose#8225]
I saw in official MongoDB docs that you can use aggregate on update. How can we do this in mongoose. Thanks.

https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/#stages-available-for-updates

**Comment by vkarpov15** [comment]
Unfortunately this is a more significant undertaking than we thought. In order to work around the fact that Mongoose currently doesn't support pipelines in `updateOne()`, you need to use `Model.collection.updateOne()` to bypass Mongoose's casting. We're working on a fix and should have one out in the next 6 weeks :+1:

**Comment by florianbepunkt** [comment]
@vkarpov15 Will this fix also allow for aggregation updates in Model.updateMany? The mongodb driver allows for this. Thank you.

**Comment by vkarpov15** [comment]
@florianbepunkt yes it will. The caveat is that Mongoose will **not** cast properties aggregation pipelines, even in `updateMany()`. So if you choose to use aggregation update stages, you're on your own for casting values.
