### ISSUE TITLE
Support `lean` option for `Model.insertMany()`

### ISSUE THREAD

**Issue by khaledosman** [Automattic/mongoose#8234]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`MyModel.insertMany(...).lean is not a function`

**What is the expected behavior?**
`insertMany()` and `deleteMany()` should support `lean()` and `select()` options similar to other Model functions to improve performance

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v10.14.1, Mongoose v5.7.4, MongoDB v4.0.10

**Comment by khaledosman** [comment]
hmm thanks, insertMany returns the inserted documents though that's why I got confused, aren't the returned documents coming from Mongo or is it the list of documents originally passed through?

**Comment by vkarpov15** [comment]
@khaledosman with `insertMany()` it is the original list of documents passed in. We'll add a `lean` option to `insertMany` to bypass validation though - right now `insertMany()` hydrates all documents passed in for validation.

As a workaround, you can do `MyModel.collection.insertMany()` instead.

As for `deleteMany()`, there's no real point to supporting `lean()` or `select()` because `deleteMany()` doesn't return any documents.

**Comment by khaledosman** [comment]
sounds good! thanks

**Comment by vkarpov15** [comment]
Fixed by #8507
