### ISSUE TITLE
find() for huge amount of data

### ISSUE THREAD

**Issue by nik72619c** [Automattic/mongoose#8270]
Is there any way to find lakhs of data using  mongoose. I have around 2 lakhs of records and I wish to obtain all of them in order to do some processing on it and return the processed result.

The approaches I figured out on the net were:-
1. lean() which would return a POJO instead of a document object
2. streams
3. cursors
Streams seemed to be a good fit but its data event triggers every time when it fetches the record. So I cannot write my logic inside of it.
Please suggest any other technique which is used today.

**Do you want to request a *feature* or report a *bug*?**
No

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node:- 12.7.0
mongoose :- ^5.2.6
MongoDB:- latest

**Comment by vkarpov15** [comment]
Use [`lean()`](https://mongoosejs.com/docs/tutorials/lean.html) and [`eachAsync()` with cursors](https://thecodebarbarian.com/cursors-in-mongoose-45). `eachAsync()` is nice because you can pass it an async function and Mongoose will wait for the async function to finish before pulling the next document.

You can also use `lean()` and [async iterators with cursors](https://thecodebarbarian.com/whats-new-in-mongoose-53-async-iterators)
