### ISSUE TITLE
Gettng back results with $numberInt

### ISSUE THREAD

**Issue by ajmas** [Automattic/mongoose#8309]
**Do you want to request a *feature* or report a *bug*?**

Unexpected behaviour

**What is the current behavior?**

Getting back results of form:

We have one of our development database displaying a field in the following form. Mongo CLI also sees the same:

```
"height": {
   "$numberInt": "72"
},
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

```
"height": 72,
```

Trying to establish if there is an option in mongoose to 'flatten' the response and what the cause of the issue might be. I did get told by one person that it is normal and it is 'mongo extended JSON', but that isn't useful when that isn't the way we expect to see our data.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

 - mongoose 5.7.7 
 - mongod v4.0.12
 - nodejs v10.16.0

**Comment by vkarpov15** [comment]
[MongoDB extended JSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#bson.Date) is useful because JSON only supports a subset of the types you can store in MongoDB. For example, MongoDB can store ints, but in JSON there's no way to distinguish between 72 as a floating point number and 72 as an integer.

There's no reason to store extended JSON in MongoDB - I would recommend migrating your data to fix cases where your data uses extended JSON. Extended JSON is only useful for transferring strict type information in cases where you're transferring data in JSON, like [Express responses](https://masteringjs.io/tutorials/express/json).

**Comment by ajmas** [comment]
We weren’t actually using Extended JSON, but it somehow appeared that way. Wondering if it was a side effect of a DB upgrade?

**Comment by vkarpov15** [comment]
What sort of db upgrade? I don't think it's possible for a mongodb or mongoose upgrade to cause this.

**Comment by vimalprakashts** [comment]
https://github.com/Automattic/mongoose/issues/8309#issuecomment-552125801

Yes, Happing to me after upgrade to new mongo db.

**Comment by vkarpov15** [comment]
@vimalprakashts please open a new issue and follow the issue template
