### ISSUE TITLE
Get model name in post save hook in global plugin

### ISSUE THREAD

**Issue by einicher** [Automattic/mongoose#8376]
I want to use a global plugin to trigger on save events on every model. I have just one problem: how to determine which model i actually just saved:

```
mongoose.plugin((schema, options) => {
	schema.post('save', (doc, next) => {
		console.log(doc, this, doc.constrcutor, schema, schema.constrcutor)
		next();
	});
});
```
Neither this, nor doc, schema or schema.constructor seem to know to which model they belong to. doc.constructor is undefined. What do I miss?

**Comment by AbdelrahmanHafez** [comment]
`doc.constructor` refers to the Model that created this document.

If you want the model name instead of the actual constructor you could get it from `doc.constructor.modelName`

The reason you're not getting much from the `this` variable is because you're using an arrow function which [lexically binds this](https://hackernoon.com/javascript-es6-arrow-functions-and-lexical-this-f2a3e2a5e8c4).

Here's an example of a plugin that adds ` Sam` to all names after creation. Notice how we're using `function () { ... }` instead of an arrow function. You could in this example use `doc` instead of `this` as they both refer to the same object.

```js
const assert = require('assert');
const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.connect('mongodb://127.0.0.1/test', { family: 4, useCreateIndex: true, useFindAndModify: false, useNewUrlParser: true, useUnifiedTopology: true, poolSize: 10 });

mongoose.plugin(function (schema) {
  schema.post('save', async function () {
    const newName = `${this.name} Sam`;
    await this.constructor.updateOne({ _id: this._id }, { name: newName });
  });
});



const User = mongoose.model('User', new Schema({ name: String }));

async function run () {
  const createdUser = await User.create({ name: 'Hafez' });

  const user = await User.findOne({ _id: createdUser._id });
  assert.equal(user.name, 'Hafez Sam');
}

run().catch(console.error);
```

**Comment by vkarpov15** [comment]
You have a typo, `doc.constrcutor` -> `doc.constructor`
