### ISSUE TITLE
database names cannot contain the character '.'

### ISSUE THREAD

**Issue by matamune94** [Automattic/mongoose#8377]
My code
`mongoose.createConnection('mongodb://127.0.0.1:27017/tv,mongodb://127.0.0.1:27017/users', { useNewUrlParser: true, useUnifiedTopology: true, useCreateIndex: true, useFindAndModify: false });`

and my error 
`MongoError: database names cannot contain the character '.'`
I was doing something wrong ?
version: 5.7.12

**Comment by AbdelrahmanHafez** [comment]
Because the code you have tries to connect to a database called `tv,mongodb://127.0.0.1:27017/users`, and this is an invalid MongoDB database name.

Seems like you're trying to connect to multiple DBs. Please refer to this [Stack Overflow answer](https://stackoverflow.com/a/19475270) which refers back to the [docs](https://mongoosejs.com/docs/connections.html#multiple_connections)

**Comment by vkarpov15** [comment]
Thanks @AbdelrahmanHafez  :+1:
