### ISSUE TITLE
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated

### ISSUE THREAD

**Issue by 46353658** [Automattic/mongoose#8391]
Hi there,

I'm experiencing the following:

`DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

This is what I'm trying:

```
const uri = process.env.ATLAS_URI;
mongoose
  .connect(uri, {
    useUnifiedTopology: false,
    useNewUrlParser: true,
    useCreateIndex: true
  })
  .then(() => console.log(`DB connected!`))
  .catch(err => {
    console.log(`DB Connection Error: ${err.message}`);
  });

```
If I change to `useUnifiedTopology: true`
then I just catch a timeout error:
`DB Connection Error: Server selection timed out after 30000 ms`

I am using Mongoose 5.7.13, MongoDB Atlas (which I think ties up to Mongo version 4.0.13) and node v13.1.0.

Hitting the endpoint with a GET request via postman just hangs and my app does not behave as expected.

Please help. Let me know if you require further info.

Thank you.

**Comment by AbdelrahmanHafez** [comment]
Can not reproduce. Could you try with a different URI and see if the problem still occurs?

```js
const mongoose = require('mongoose');

mongoose
  .connect('mongodb://127.0.0.1:27017/test', {
    useUnifiedTopology: true,
    useNewUrlParser: true,
    useCreateIndex: true
  })
  .then(() => console.log('DB connected!'))
  .catch(err => {
    console.log(`DB Connection Error: ${err.message}`);
  });
```

logs
```
DB connected!
```

mongoose v5.12.0
Node v13.2.0 (and 12.3.0)
MongoDB V4.0.4
Windows 10 x64

**Comment by chonz0** [comment]
Same as @46353658 here
Works OK in localhost but same issue when using Atlas

@AbdelrahmanHafez please note the URI

**Comment by AbdelrahmanHafez** [comment]
@chonz0 
I tested using Atlas in https://github.com/Automattic/mongoose/issues/8433#issuecomment-566774590 and things worked correctly for me as well.

Seems like there is an issue with some ISPs blocking Atlas for some reason. In the following comment @ruslanguns has fixed the bug by changing his DNS to Google's DNS (8.8.8.8). https://github.com/Automattic/mongoose/issues/8433#issuecomment-566829129 

Could you test connecting to your database via mongoose on your server and show me the logs? We got a couple of issues regarding Atlas connection, not sure it exactly is a mongoose issue, I would love to find the root cause.
