### ISSUE TITLE
findOneAndUpdate decrement value with rule value > 0

### ISSUE THREAD

**Issue by car1ot** [Automattic/mongoose#8426]
`
const somedata = await db.User.findOneAndUpdate({ uid: ws.user.publicData.uid }, { $inc: { balance: -1000 } }, {
	runValidators: true,
	upsert: false,
	new: true,
}).lean();
`

`
const UserSchema = new mongoose.Schema({
	uid: { type: Number, unique: true, required: true, },
	balance: { type: Number, min: 0, default: 0, required: true },
},
{ timestamps: true });
`

Validator doesnt work

**Comment by vkarpov15** [comment]
[Update validators ignore `$inc`](https://mongoosejs.com/docs/validation.html#update-validators-only-run-for-some-operations) because there's no way we can validate the current state of the document without resorting to [update pipelines](https://www.mongodb.com/blog/post/coming-in-mongodb-42-pipeline-powered-updates-and-more-expressive-queries), which are only supported in MongoDB 4.2.
