### ISSUE TITLE
i am facing this same issue

### ISSUE THREAD

**Issue by Navdeep-bains** [Automattic/mongoose#8569]
this error is showing in command prompt :-
the options [useUnifieldTopology] is not supported
(node:9292) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

this is my connection with constructor
mongoose.connect(' ',{useUnifieldTopology:true,useCreateIndex:true,
useNewUrlParser:true}).then(() => console.log('db connected'));

**Comment by achillesoo7** [comment]
Hey,
By default, mongoose shows this deprecation warning because Mongoose 5.7 uses MongoDB driver 3.3.x, which introduced a significant refactor of how it handles monitoring all the servers in a replica set or sharded cluster.

You can get rid out of this warning by writing a simple line: mongoose.set('useUnifiedTopology', true);

For more information please refer to the mongoose documentation, you can find a detailed explanation of it over there.

https://mongoosejs.com/docs/deprecations.html

**Comment by vkarpov15** [comment]
https://mongoosejs.com/docs/deprecations.html#useunifiedtopology
