### ISSUE TITLE
Subdocument _id always generated when using schema.add in global plugin

### ISSUE THREAD

**Issue by bwgjoseph** [Automattic/mongoose#8589]
**What is the current behavior?**

Subdocument `_id` will always be generated if the plugin is added at global but the same does not happen if added at schema level

**If the current behavior is a bug, please provide the steps to reproduce.**
See Github [mongoose-schema-add-issue](https://github.com/bwgjoseph/mongoose-schema-add-issue) repo `README.md` for more info

**What is the expected behavior?**

Subdocument `_id` should not be generated if `_id` is set to `false` in the subdocument when plugin is loaded as global

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
mongoose: 5.8.12,
mongodb: 4.2.1,
nodejs: 10.15.3 (also tested in v12)
```
---

Also, is there any way to know if it is a child schema? This way, I also also prevent `_id` from adding to subdoc. This is a separate question from the original issue posted above.

```
const addId = function init(schema: Schema) {
    // something like
    // if (!schema.isSubDocument) then
    schema.add({
        _id: {
            type: String,
            default: () => Math.random().toString(36).substring(7),
        }
    })
};
```

**Comment by bwgjoseph** [comment]
Hi @vkarpov15, I have the github repo given. Am I missing something?

**Comment by vkarpov15** [comment]
@bwgjoseph yeah, repro scripts should be in JavaScript (not TypeScript), and should be single scripts or a couple files, not large GitHub repos with dozens of dependencies. We try to simplify complex repro scripts when we have time, but haven't gotten to it yet for this one.

You can disable running global plugins on child schemas with the [`applyPluginsToChildSchemas` option](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-set). There isn't a way to check whether a schema is a "child schema" currently, because the same schema can be used as both a top-level schema and a child schema.

**Comment by vkarpov15** [comment]
As far as I can tell, this is expected behavior. Mongoose runs global plugins on all schemas, including embedded ones, so registering `addId` as a global plugin will add ids to nested schemas.

You can opt out of that by setting the [`applyPluginsToChildSchemas` option to `false`](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-set).

```javascript
mongoose.set('applyPluginsToChildSchemas', false);
```

**Comment by bwgjoseph** [comment]
Hi, thanks for the clarification.

Would like to know if there is any option / possible that allows me to set `applyPluginsToChildSchemas` to `false`, yet at the same time allow opt in for certain schema when defining individual schema?

So like 

```
mongoose.set('applyPluginsToChildSchemas', false);

// later on

// This is a child schema
new Schema({
    title:  String, // String is shorthand for {type: String}
    author: String,
}, { _id: true });
```

**Comment by vkarpov15** [comment]
You would have to explicitly call [`schema.plugin()`](https://mongoosejs.com/docs/api/schema.html#schema_Schema-plugin) on that schema.

**Comment by bwgjoseph** [comment]
That works! Thanks
