### ISSUE TITLE
May be wrong link url in docs

### ISSUE THREAD

**Issue by Gruzchick** [Automattic/mongoose#8599]
![image](https://user-images.githubusercontent.com/13402010/74590207-037e6c00-503f-11ea-8d5e-85f489f48be2.png)

**Comment by JamesRamm** [comment]
I just came across this. It links to this tumblr site, which gives a 404:
https://aaronheckmann.tumblr.com/post/48943525537/mongoose-v3-part-1-versioning

The bad link is also used a second time when warning the user to keep versioning on unless they know what they are doing. 
I was able to discover what I believe is the same blog here:
http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html

I would suggest putting this information directly in the mongoose documentation, since it is relatively key information explaining what versioning is (which is a mongoose only concept, not mongodb)
