### ISSUE TITLE
Unable to delete record from mongodb server using node.js

### ISSUE THREAD

**Issue by nehakumar99** [Automattic/mongoose#8610]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by nehakumar99** [comment]
![Screenshot (160)](https://user-images.githubusercontent.com/60687333/74935341-19f54080-540e-11ea-8e66-c31a03816350.png)
![Screenshot (161)](https://user-images.githubusercontent.com/60687333/74935353-1c579a80-540e-11ea-84a0-94b3d7ce9742.png)



In the terminal it showing record is deleted but it still exists in the database

**Comment by nehakumar99** [comment]
![Screenshot (160)](https://user-images.githubusercontent.com/60687333/74935474-50cb5680-540e-11ea-84ca-e724a2f82769.png)

**Comment by nehakumar99** [comment]
![Screenshot (162)](https://user-images.githubusercontent.com/60687333/74935535-69d40780-540e-11ea-8acc-415325928433.png)

**Comment by louisnow** [comment]
DeleteOne will delete exactly one document even if there are many matches in the database.
So if you have two items with the same name and call deleteOne, only one of them gets deleted.
If this isn't the case, then maybe your delete query is wrong.
It would also help if you post the code as text instead of taking screenshots. There's an insert code button in the formatting bar on github. Also this is more of a homework/help question than a mongoose issue. Use stackoverflow instead and try reading the documentation carefully.

**Comment by vkarpov15** [comment]
WIthout code samples there's no good way to debug this. I don't see any obvious errors in your API endpoint but without more information there's no way for me to help.
