### ISSUE TITLE
Handle callback error when no  callback must trow Error

### ISSUE THREAD

**Issue by emaza** [Automattic/mongoose#8753]
Hi, 
I am using mongoose 5.9.7
I think I found a bug in handleCallbackError function
when I am not usung callback becouse i`m using promise whith "await" I think It must throw error when for example ther is no conecction or some other error. 

// for example whith no  conecction or conection closed
```
try {
  await Entity.findOne({ type: 'foo' })
} catch (error) {
 // error expected
}
```

I think could be fixed in this line:
https://github.com/Automattic/mongoose/blob/a0f7330f682c4247fd476cee212ac748f0b2dfda/lib/model.js#L4827

from that:  `if (callback == null) {`
to this:  `if (callback === null) {`

I see that there is some similar issues but they are closed or are very old
https://github.com/Automattic/mongoose/issues/1641
https://github.com/Automattic/mongoose/issues/2935
https://github.com/Automattic/mongoose/issues/3273
https://github.com/Automattic/mongoose/issues/5500

Thanks

**Comment by lineus** [comment]
@emaza 

[Mongoose buffers commands until a connection is made. ](https://mongoosejs.com/docs/connections.html#buffering)

In other words, by default, mongoose will not throw an error, or reject a promise, or return an error in a callback when performing a crud operation without a connection. 

You need to set the mongoose option `bufferCommands` to false in order to provoke an error when calling a Model method like `findOne` without a connection.

Here is an example that you can run and see the behavior change by changing the value of bufferCommands from true to false:

### 8753.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('bufferCommands', true); // true by default
const { Schema, connection } = mongoose;
const DB = '8753';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };


const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

let i = 0;

async function run() {
  try {
    console.log(`entering try #${++i}`);
    let found = await Test.findOne({});
    console.log(`found: ${found.name}`);
    return mongoose.disconnect();
  } catch (e) {
    console.error(`entering catch #${i}`);
    assert.ok(e && e instanceof Error);
    console.error('received error: ', e.message);
    await mongoose.connect(URI, OPTS);
    await connection.dropDatabase();
    await Test.create({ name: 'test1' });
    await run();
  }
}

run();

```

### Output with `bufferCommands === true`
```
$ ./8753.js
entering try #1
$
```

### Output with `bufferCommands === false`
```
$ ./8753.js
entering try #1
entering catch #1
received error:  Cannot read property 'findOne' of null
entering try #2
found: test1
$
```

I think it would be nice if the error message was more clear, ie. calling a model method when   bufferCommands === false and no connection exists, we could throw a more specific error before even attempting to call a method on the non-existent native collection.

`TypeError: Cannot read property 'findOne' of null` 
would become something like 
`NoConnOpError: Cannot perform db operations without a connection when bufferCommands is false.`

**Comment by emaza** [comment]
This clarifies all my doubts. I close the topic

Thanks so much @lineus
