### ISSUE TITLE
aggregate queries not populating the id field, only populating _id field

### ISSUE THREAD

**Issue by Nik-Novak** [Automattic/mongoose#8784]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If a query is performed as an aggregate query, the returned document(s) do not have id fields populated, they only have the _id field populated. Although its `find` counterparts do.
Why is this important? Many downstream technologies either do not allow fieldnames beginning with a underscore or highly discourage it. Also the user should avoid extra complexity such as looping through and reassigning all `_id` fields to `id` fields as this adds time to the operation that should be as minimized as possible (query). Also for applications that expect the promise to be returned, there is no place to actually manually loop and reassign names to fields.
**If the current behavior is a bug, please provide the steps to reproduce.**

Normal behaviour working as intended:
```
let filter = {}
let test = await DBModel.find(filter).limit(5)
console.log(test[0]._id) //prints 5e72b2c81b66d914a7687c13
console.log(test[0].id) //prints 5e72b2c81b66d914a7687c13
```
id field not being populated on aggregate query:
```
let test = await DBModel.aggregate([{ $match:filter }, { $sample:{size:5} }]);
console.log(test[0]._id) //prints 5e72b2c81b66d914a7687c13
console.log(test[0].id) //prints undefined   <-------- THIS IS THE ISSUE
```
**What is the expected behavior?**
test[0].id should print the same thing as test[0]._id in both cases
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node:v12.14.1
Mongoose:^5.9.7
MongoDB:mongo:4.2.3-bionic

**Comment by AbdelrahmanHafez** [comment]
This happens on regular find/findOne as a virtual getter which is [assigned by default](https://mongoosejs.com/docs/guide.html#id) because we know how the result looks like.

There is no way for us to know what the aggregation result would look like, so we don't do much work on aggregation results (virtual getters or casting) nor casting the stages.

**Comment by Nik-Novak** [comment]
Makes sense, thanks.

**Comment by vkarpov15** [comment]
The workaround is to manually hydrate the documents coming out of your aggregate() call:

```javascript
const docs = await DBModel.aggregate([{ $match:filter }, { $sample:{size:5} }]).
  then(docs => docs.map(doc => DBModel.hydrate(doc)));
```

Mongoose hydrates query results, but **not** aggregate results, because aggregation can change the shape of returned documents.

See hydrate docs: https://mongoosejs.com/docs/api/model.html#model_Model.hydrate
