### ISSUE TITLE
Error MongoTimeoutError: Server selection timed out after 30000 ms to connect MongoDB Atlas

### ISSUE THREAD

**Issue by matheushlv** [Automattic/mongoose#8796]
**Do you want to request a *feature* or report a *bug*?**
I can't run the app on Heroku with the mongodb database. Configure the IP for anywhere, username and password, the message is "MongoTimeoutError: Server selection timed out after 30000 ms" with the message "at=error code=H12 desc="Request timeout" method=GET path="/"  dyno=web.1 connect=1ms service=30009ms status=503 bytes=0 protocol=https".

**What is the current behavior?**

I can't run view o app on Heroku, but on localhost it's OK.

**If the current behavior is a bug, please provide the steps to reproduce.**

Execute command: "git push -u heroku master" and show the message of the title this issue.

**What is the expected behavior?**
Successfully connected with MongoDB Atlas and show the app on Heroku.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v12.16.2
Mongoose: 5.8.3.
MongoDB(Atlas): 4.2.5.

**Comment by vkarpov15** [comment]
How exactly did you "configure the IP for anywhere"? This could very well be a case of incorrect IP whitelisting on Atlas.

Also, are you using the `mongodb+srv` url? If so, try using the non-srv url.

**Comment by ivssh** [comment]
What is the basic difference between using the ```mongodb``` vs ```mongodb+srv``` url?

**Comment by Necrolynn47** [comment]
I followed up on threads similar to this since I'm having the same problem. I removed +srv from the connection string but the server selection timed out after 30000ms problem still persists. Initially, it was only coming in the New Connection page, but I could successfully enter my ID and password in the Fill in collection fields manually option. But now, even that option is suffering from the same timeout problems.

I looked up on several forums, and there does seem to be an option of increasing the timeout limit. Problem is, that happens only on the query builder part, which cannot be accessed until the timeout problem resolves. 

As I'm typing, I tried to add another IP address (suggested through this link https://stackoverflow.com/questions/60431996/mongooseerror-mongooseserverselectionerror-connection-monitor-to-52-6-250-2). This actually seems to work, and my compass is showing the relevant sets of databases now. Maybe you can try this out.

**Comment by vkarpov15** [comment]
@ivssh we've seen some cases where ISPs block `+srv` URLs.

**Comment by matheushlv** [comment]
Hi, I have an error syntax in environment variable "NODE_ENV", thank you very much for your help!
