### ISSUE TITLE
Allow `schema` as a schema path name

### ISSUE THREAD

**Issue by songguangyu** [Automattic/mongoose#8798]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When i set schema name `schema`, 
![image](https://user-images.githubusercontent.com/6869168/79321677-4a54e900-7f3e-11ea-8e59-85a2de3fca93.png)

mongoose throw err 
![image](https://user-images.githubusercontent.com/6869168/79321430-f0ecba00-7f3d-11ea-8206-f40725ef9f10.png)

`mongoose/lib/schema.js` line 528

![image](https://user-images.githubusercontent.com/6869168/79321525-17aaf080-7f3e-11ea-9e6c-a2d2c9d20961.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

`
const schema = new Schema({
  'schema': { type: String, default: '{}'},
});
`
**What is the expected behavior?**
I can set name `schema` in Schema
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose version 5.4.7
5.9.9 alse have this problem 
https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L645
Nodejs version 12

**Comment by AbdelrahmanHafez** [comment]
https://mongoosejs.com/docs/api.html#schema_Schema.reserved

**Comment by songguangyu** [comment]
@AbdelrahmanHafez Thanks for you answer, I am working on service migration. If the schema field already exists in the original database, how should I deal with this situation?

**Comment by AbdelrahmanHafez** [comment]
In that case I would rename the schema field into a different field name.
I've always found [thesaurus](https://www.thesaurus.com/browse/schema#) quite helpful in finding synonyms.

**Comment by songguangyu** [comment]
@AbdelrahmanHafez  Maybe another mongo client is a better solution.

**Comment by AbdelrahmanHafez** [comment]
I can't make that choice for you, depending on the effort of renaming the field, and the features mongoose provides. See what outweighs what, and make your decision.

Perhaps @vkarpov15 has a better idea.

**Comment by songguangyu** [comment]
@AbdelrahmanHafez thanks!

**Comment by vkarpov15** [comment]
Some path names unfortunately do conflict with existing methods and properties. However, there are ways for us to work around this. I'll keep this open for a future release.

**Comment by JatinRanka** [comment]
@vkarpov15 Can I take up this issue to work on?

**Comment by vkarpov15** [comment]
@JatinRanka sure :+1:

**Comment by Edu93Jer** [comment]
Hi, @vkarpov15  I am a newbie to this project and would like to contribute it; do you think you can put me in the right direction, please?

**Comment by vkarpov15** [comment]
@Edu93Jer sure. The general idea is that several methods in `lib/document.js` relies on `this.schema` to get the document's schema, which is why `schema` isn't allowed as a path name. We would need to refactor `lib/document.js` to ideally rely on a [symbol](https://masteringjs.io/tutorials/fundamentals/symbol) instead of 'schema', but we could get the same result by changing the name of the 'schema' property on documents to '$__schema' or something similar.

**Comment by Edu93Jer** [comment]
@vkarpov15 when you say "changing the name of the 'schema' property on **_documents_** to '$__schema' " you mean in all the documents or just where the property is added, because I just did this, and the issue works well. (Line 592)
<img width="324" alt="Capture12" src="https://user-images.githubusercontent.com/61852327/100816239-48776180-340b-11eb-89e3-7c70946f0db1.PNG">

**Comment by vkarpov15** [comment]
That's one step. But the reason why `reserved.schema` is set is that Mongoose documents assume that `this.schema` is the schema belonging to the model that this document is an instance of. For example, here: https://github.com/Automattic/mongoose/blob/645a45bc6b87b1581149db49532a9366e434db9b/lib/document.js#L104 .

Any change to `reserved.schema` also means we need to change all the places in `lib/document.js` where we use `this.schema`.

**Comment by vkarpov15** [comment]
In `lib/model.js` and `lib/document.js` there's a lot of places we use `this.schema`. We should use `this.$__schema` instead internally.
