### ISSUE TITLE
FR: .execPopulate(pathOrConfig) to do populate(pathOrConfi).execPopulate() in one shot

### ISSUE THREAD

**Issue by dandv** [Automattic/mongoose#8839]
I often find myself writing

    await Model.find(...).populate(pathOrConfig).execPopulate();

When chaining is not needed, that could be shortened to

```js
await Model.find(...).execPopulate(pathOrConfig);
```

which would call `.populate(pathOrConfig)` then `.execPopulate()`.

**Comment by AbdelrahmanHafez** [comment]
So, I just checked, the only `execPopulate(...)` that exists is `Document.prototype.execPopulate`.

In mongoose v6.0 you will not need to use execPopulate(...), `populate(...)` itself will be a promise, this change has [already been implemented](https://github.com/Automattic/mongoose/commit/2fe9077b8f16b7c794574f76b444d888536596d5) because of https://github.com/Automattic/mongoose/issues/3834
