### ISSUE TITLE
DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set  to false are deprecated

### ISSUE THREAD

**Issue by AashishShri** [Automattic/mongoose#8886]
DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set
 to false are deprecated

 const mConnect = await mongoose.connect(mongoUri, {
      useFindAndModify: false,
      useCreateIndex: true,
      useUnifiedTopology: true,
      useNewUrlParser: true,
    });
I am using 
mongod --version
db version v3.6.3
 node -v         
v11.15.0

 npm -v 
6.7.0
mongoose.version
5.9.10

but still i getting same issue? is there mongod version issue or something else.?

**Comment by AbdelrahmanHafez** [comment]
Welcome @AashishShri 
Check the deprecation section in the docs: https://mongoosejs.com/docs/deprecations.html

**Comment by AashishShri** [comment]
> Welcome @AashishShri
> Check the deprecation section in the docs: https://mongoosejs.com/docs/deprecations.html

Hi @AbdelrahmanHafez I saw this link but still, I m facing issue

**Comment by AbdelrahmanHafez** [comment]
Does settings these options using `mongoose.set` **before** creating a connection fix the warnings?

```js
  mongoose.set('useNewUrlParser', true);
  mongoose.set('useFindAndModify', false);
  mongoose.set('useCreateIndex', true);
  mongoose.set('useUnifiedTopology', true);
```

**Comment by AashishShri** [comment]
> Does settings these options using `mongoose.set` **before** creating a connection fix the warnings?
> 
> ```js
>   mongoose.set('useNewUrlParser', true);
>   mongoose.set('useFindAndModify', false);
>   mongoose.set('useCreateIndex', true);
>   mongoose.set('useUnifiedTopology', true);
> ```

yes, I already did these things. see the above example. same code is not working with mongodb3 but it's working with mongodb4.

**Comment by vkarpov15** [comment]
Are you using any other npm modules that use mongodb, like connect-mongodb-session or connect-mongo? Run `npm list | grep "mongo"` paste the output please.

**Comment by AashishShri** [comment]
I solved this problem  to add this code in jest file by using :

const mongoUri = await mongoServer.getUri();
    await mongoose.connect(mongoUri, {
        useFindAndModify: false,
        useCreateIndex: true,
        useUnifiedTopology: true,
        useNewUrlParser: true,
    }).then(() => {
        console.log(`MongoDB server started at ${String(mongoUri)}`);
    });

**Comment by akosbalazs** [comment]
This is an actually bug in Mongoose. The documentation at https://mongoosejs.com/docs/deprecations.html says that one should be able to pass `useFindAndModify` through the connection options in order to set it to false, but sadly it doesn't work:

https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L614

The code sets `this.config.useFindAndModify` whereas it should set `this.base.options.useFindAndModify`. This is also true for `useCreateIndex`,  `autoCreate`, and `autoIndex`. I see that `useFindAndModify` has been removed, in that case the code (and the corresponding documentation) in `connection.js` should still be updated to reflect this as well as for the other cases. If agreed, I can probably do  quick PR.

**Comment by lineus** [comment]
@akosbalazs the following script shows that passing the `useFindAndModify` option in the connection options does effect which method is used and the associated deprecation warning.

### 8886.js
```js
#!/usr/bin/env node
'use strict';

const useFindAndModify = Boolean(process.argv[2]);

const assert = require('assert');
const mongoose = require('mongoose');
assert.strictEqual(mongoose.version, '5.9.13');
let tested = 0;

mongoose.set('debug', function(model, method) {
  if (method === 'insertOne') {
    return;
  }
  if (useFindAndModify) {
    assert.strictEqual(method, '_findAndModify');
  } else {
    assert.strictEqual(method, 'findOneAndUpdate');
  }
  tested++;
});

const { Schema, connection} = mongoose;
const DB = '8886';
const URI = `mongodb://localhost:27017/${DB}`;

const OPTS = {
  family: 4,
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useFindAndModify
};

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  await Test.findOneAndUpdate({ _id: doc._id }, { name: 't1' });
  assert.strictEqual(tested, 1);
  console.log('All Assertions Pass.');
  await connection.close();
}

run();

```

### output with `true`
```
issues: ./8886.js true
(node:73462) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify
All Assertions Pass.
issues:
```

### output with `false`
```
issues: ./8886.js 
All Assertions Pass.
issues: 
```

**Comment by akosbalazs** [comment]
Thanks for the test. It might be something recently fixed as I still get the warning with version 5.8.9 (I have `^5.8.9` specified in my `package.json`, probably my lockfile prevents it from upgrading). I should've tried with a newer version I guess.

```
$ npm list mongoose
└── mongoose@5.8.9
$ node mongoose.js true
(node:22500) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#-findandmodify-
All Assertions Pass.
$ node mongoose.js false
(node:22684) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#-findandmodify-
All Assertions Pass.
```
So I get the warning no matter what. If I modify your script slightly to print out what Mongoose thinks the option is set to right after the connect call:
```
[...]
  await mongoose.connect(URI, OPTS);
  console.log(mongoose.get('useFindAndModify'));
  await connection.dropDatabase();
[...]
```
I get `undefined` in both cases so the option does not get propagated correctly.

**Comment by lineus** [comment]
`node mongoose.js false` is the same as `node mongoose.js true`

**in my example above I don't pass in any options in order to elicit the false value**

by passing in the string false, you are setting it to true.

### shell output
```
issues: node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> Boolean('false')
true
> 
```

**Comment by akosbalazs** [comment]
Good catch, without passing `false` it indeed works as expected. I skimmed over that part because I really didn't expect this syntax. However, it doesn't invalidate my points about:

* the documentation at https://mongoosejs.com/docs/deprecations.html#findandmodify being wrong about suggesting to use `mongoose.connect(uri, { useFindAndModify: false });`
* the code I pointed to in my first comment being wrong because it apparently tries to set this option using the syntax as suggested by the documentation in the wrong place. Since this option has been removed in the meantime I guess it doesn't matter much but the same pattern is repeated for other options.

When running your script without any parameters `mongoose.get('useFindAndModify')` still returns `undefined` (although the warning is indeed gone) so I would suggest there is still something fishy going on as the option isn't propagated correctly.

**Comment by lineus** [comment]
@akosbalazs 

**`mongoose.get()` returns the value of global option, so you won't see the connection specific option there.**

Setting the `findOneAndModify` connection option can't overwrite the global option because mongoose allows multiple connections per mongoose instance. One connection should never be allowed to implicitly effect the options of the other connections. 

Therefore the code you pointed to is correct, as the connection option should and is only applied to that specific connection.

**Comment by akosbalazs** [comment]
Thanks for the clarification regarding `mongoose.get()`, I skipped over that indeed.

However, I was still confused why your example program worked and my application didn't so I dug deeper into the code and realised that I was using a _different_ connection implicitly because I used `connection.useDb()`. Still confused thinking that this new connection should inherit the properties of the original connection I looked at the code that "clones" the connection and indeed, the line copying the `config` object was missing. It seems this bug was fixed very recently in mongoose as well:

https://github.com/Automattic/mongoose/commit/883c30b2b044457c63dbafa4012c1da969ea5915

If I patch my local mongoose install with this line (actually the fixed version which is in master now) everything works as expected.

**Comment by SchalkvanDyk** [comment]
> Does settings these options using `mongoose.set` **before** creating a connection fix the warnings?
> 
> ```js
>   mongoose.set('useNewUrlParser', true);
>   mongoose.set('useFindAndModify', false);
>   mongoose.set('useCreateIndex', true);
>   mongoose.set('useUnifiedTopology', true);
> ```
