### ISSUE TITLE
[BREAKING CHANGE] drop support for Document#model(...)

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8915]
re #8914 #8899

Currently, documents have a `model(...)` method:
```js
  const userSchema = new Schema({ });
  const User = mongoose.model('User', userSchema);

  const doc = new User();

  // will throw if schema has `model` field.
  doc.model('User') === User; // true;
```

I couldn't find it mentioned anywhere in the docs, nor could I trace the code responsible for its assignment. We should either:
A) Drop supporting `doc.model(...)` and advise people to use `mongoose.model(...)` instead.
B) Keep it, but add: `model` as a schema reserved word.

I am leaning towards option A. @vkarpov15 thoughts?

**Comment by andreialecu** [comment]
I'm actually using this. I didn't know it's undocumented, as it exists in `@types/mongoose`.

It's extremely tricky to get access to `mongoose.model` in my use case, because I'm using NestJS and typegoose and dependency injection. I'd have to pass the proper instance of `mongoose` deep to a bunch of methods, and add another parameter.

Once #8946 is resolved I could start open sourcing my GraphQL to Mongoose deep population package, which I think could be useful to a bunch of people.

Some spaghetti WIP code below:

![image](https://user-images.githubusercontent.com/697707/81216614-df9a4900-8fe3-11ea-88ea-9c38881b005d.png)
