### ISSUE TITLE
question regarding mongoose transaction sessions - endSession()

### ISSUE THREAD

**Issue by linus-hologram** [Automattic/mongoose#8936]
Hey there,

what happens if I create a session and try to run a transaction that fails - will the session automatically be closed when I use the `withTransaction` helper?

**Here's an example:**
```
var transactionSession = await connectionManager.authConnection.startSession()
await transactionSession.withTransaction(async (tSession) => {
    throw new Error("This is my test error!") // error occurs 
})

await transactionSession.endSession() // won't be executed as the await above throwed
```

**The mongoose docs state the following:**

> The session.withTransaction() helper handles:
> 
> - Creating a transaction
> - Committing the transaction if it succeeds
> - _**Aborting the transaction if your operation throws**_
> - Retrying in the event of a transient transaction error.

I know that the transaction is being aborted if my operation throws. But what about the established session? Will it be disbanded as well? Is there some sort of background code that runs  something similar like `transactionSession.endSession()` in the background?

This is extremely important for me to know as - if mongoose does not automatically take care of closing the sessions - I have to manually do so by wrapping everything in a try-catch-finally block.

What even would be the consequences of not closing the established session? Would it cause the database to be locked or something?

I would be very thankful if I could get some clarification on this topic.

Thanks in advance :)

**Comment by vkarpov15** [comment]
Mongoose on its own doesn't run `endSession()`, you're responsible for doing that on your own. However, keep in mind that MongoDB automatically closes sessions after 30 minutes, so you're unlikely to have a lot of sessions open at any given time unless you have a very high traffic system.

I did some digging and I haven't been able to find any documentation on what can happen due to too many open sessions. I ran into [this old MongoDB server issue](https://jira.mongodb.org/browse/SERVER-22752), but it appears I can create 120000 dangling sessions without any problems on MongoDB 4.2.3:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();
  const Model = mongoose.model('Test', Schema({ name: String }));
  await Model.createCollection();

  for (let i = 0; i < 120000; ++i) {
    console.log(i);
    const session = await mongoose.startSession();

    await session.withTransaction(async () => {
      await Model.create([{ name: 'foo' }], { session });
      throw new Error('Oops!');
    }).catch(() => {});
  }

  console.log('Done');
}
```

I would recommend you close your sessions manually just to de-risk. But I don't know of any negative consequences of having too many sessions open.

**Comment by Zack-Heisnberg** [comment]
i am not sure what version you have check , i understand this is old but for all new users there is no need to end session this is done automatically now


![image](https://github.com/Automattic/mongoose/assets/69718435/d7feb14d-3920-4fbe-89ed-366e89107875)
