### ISSUE TITLE
Problem with findByIdAndUpdate with mongoose and typescript

### ISSUE THREAD

**Issue by NervenCid** [Automattic/mongoose#8965]
**Do you want to request a *feature* or report a *bug*?**

BUG 

**What is the current behavior?**

I get this error;

Argument of type 'string | object | Readable | Buffer' is not assignable to parameter of type 'MongooseUpdateQuery<Pick<IUser, "_id" | "username" | "fullname" | "password" | "comparePassword">>'.
  Type 'string' is not assignable to type 'MongooseUpdateQuery<Pick<IUser, "_id" | "username" | "fullname" | "password" | "comparePassword">>'.
    Type 'string' is not assignable to type 'DotAndArrayNotation<any>'.ts(2345)

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the line:

const updatedUser = await User.findByIdAndUpdate(request.params.id, request.payload);

it puts problem with the parameter " request.payload"

**What is the expected behavior?**

No errors, in fact i should force data type any making something like this

const newData: any= request.payload;
const updatedUser = await User.findByIdAndUpdate(request.params.id, newData);

But i don't know if it is a bug, it don't take "request.payload" directly

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.** 
Node.js version: 12.16.2
Mogoose: 5.9.13

<!-- You can print `mongoose.version` to get your current version of Mongoose: 5.9.13

**Comment by andreialecu** [comment]
Mongoose doesn't have typescript types directly, they come from a third party, so any typescript issues should be reported to https://github.com/DefinitelyTyped/DefinitelyTyped

Based on the error though, it seems your `request.payload` is a `string` instead of an `object`, so you probably forgot to `JSON.parse(request.payload)`.

**Comment by NervenCid** [comment]
Thank you for your answer and sorry for my english

**Comment by vkarpov15** [comment]
@andreialecu is right in that you should report an issue with DefinitelyTyped because Mongoose doesn't maintain TypeScript bindings currently. But based on what I can tell from your code there isn't really much you can do: if `request.payload` comes in over the network, there's no way for TypeScript to typecheck it. You'd need to use something like [archetype](https://www.npmjs.com/package/archetype) to make sure the types are correct.
