### ISSUE TITLE
2dsphere indexing not working and manual indexing works partially

### ISSUE THREAD

**Issue by Sarav-S** [Automattic/mongoose#8981]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Following is my user schema 

```
const userSchema = new mongoose.Schema({
    /*...*/
    location: {
        type: { type: String },
        coordinates: [Number],
    },
    /*...*/
});

userSchema.index({ location: "2dsphere" });
```
I created 100 users with same lat and lng. When I performed the following query 

```
User.aggregate([
    {
        $geoNear: {
            near: {
                type: "Point",
                coordinates: [lng, lat]
            },
            distanceField: "dist.calculated",
            maxDistance: 2,
            spherical: true
        }
    }]);
```

I received `'no geo indices for geoNear'` error. So, with MongoDB compass, I manually created index for location field. Then when I performed the above query I received all users. Which is fine. And then again I created 100 more users. When I performed search again, I'm receiving only newly created users results along with 6 users from the first set I had created.

My questions are as follows

    1. Why userSchema.index({ location: "2dsphere" }); didnt create index in the first place?
    2. Why am I receiving only few records even when all lat and lng are same?

**If the current behavior is a bug, please provide the steps to reproduce.**
1. First create 100 users and query using aggregate. You'll see get all results
2. Create second set of 100 users and query again using aggregate. Now you'll see only few first set users and many second set users.

**What is the expected behavior?**
It should return all 200 users

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node : 12.16.3
MongoDB: 4.0.3
Mongoose: 5.8.11

**Comment by vkarpov15** [comment]
1) You need to `await User.init()` to wait for the index to finish building. You normally don't have to do this in production because once the index is built, you don't need to rebuild it. But if you're testing and dropping the database between tests, you need to wait for the index build to finish, and `await User.init()` is the easiest way to do that.

2) [`$geoNear` has a limit of 100 documents by default in MongoDB 4.0](https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear/)
