### ISSUE TITLE
Cast using multiple discriminators if query filter has $or with different discriminator keys

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9018]
On casting for filters, mongoose should look for each field on the calling schema, if it's not found, mongoose should attempt to find it on one of the children discriminators and cast according to it.

Here's a demonstration of the desired result.

### 9018.js
```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');


const walletSchema = new Schema({
  // userId: Number,
  // branchId: Number,
  amount: Number
});

const Wallet = mongoose.model('Wallet', walletSchema);
Wallet.discriminator('UserWallet', new Schema({ userId: Number }));
Wallet.discriminator('BranchWallet', new Schema({ branchId: Number }));


const filter = Wallet.findOne({ userId: '1' }).cast();

assert.equal(typeof filter.userId, 'number');
assert.equal(filter.userId, 1);

console.log('All assertions passed.');
```

### Output
```
AssertionError [ERR_ASSERTION]: 'string' == 'number'
```

### Use case

Our frontend sends filters on a `wallets` collection via `req.query`, which has two child discriminators, `UserWallet` and `BranchWallet`. On the admin dashboard, I pass that `req.query` directly to mongoose, the issue is that when the frontend sends `branchId: '1'` they get no results because the value is not cast to number.

I'd like to keep those APIs backwards-compatible, while still splitting my model into two children. The only issue is that now users need to specify `__t` on `req.query`, so that it will cast according to the **whole filter** discriminator schema as per #8881, what I am recommending here is if:
A) no `__t` key is present.
B) field is not found on the current schema

then: look at discriminators originating from current model, and cast according to first matched schemaType.

The way I overcome this now is by adding `branchId` and `userId` to my base schema, even though I don't want to add them to base model documents, I just want to be able to filter by them and get casting.

**Comment by vkarpov15** [comment]
Unfortunately I can see this behavior getting pretty messy - what happens if multiple discriminators have different schema types for the same path? How do we determine if two schema types are different for the purposes of casting? First matched schematype is interesting, but then you're dependent on the order discriminators are defined, which sounds somewhat surprising.

Here's an alternative possibility: what about:

```javascript
Wallet.findOne({ $or: [{ ...req.query, __t: 'UserWallet' }, { ...req.query, __t: 'BranchWallet' }] })
```

We would need to make Mongoose smart enough to handle casting each `$or` according to `__t`, but that looks like the path of least resistance for supporting executing one query casted according to multiple discriminator schemas. What do you think @AbdelrahmanHafez ?
