### ISSUE TITLE
Default fields in embedded document are overwritten with undefined

### ISSUE THREAD

**Issue by vitorhnn** [Automattic/mongoose#9039]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Passing undefined as a value to a key in a embedded document causes Mongoose to first set the key to its default value and then to overwrite it with undefined
**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
it('Sets default when passing undefined as value for a key in a nested subdoc (gh-9039)', function () {
  const Test = db.model('Test', {
    nested: {
      prop: {
        type: String,
        default: 'some default value'
      }
    }
  });

  return co(function* () {
    const doc = yield Test.create({ nested: { prop: undefined } });
    assert.equal(doc.nested.prop, 'some default value');
  });
});
```

**What is the expected behavior?**
See the provided test

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 14.2.0
Mongoose: 5.9.15
MongoDB: 3.6.17

**Comment by AbdelrahmanHafez** [comment]
I think this is by design, many people would count on mongoose to set a field to the default if the value provided to it is `undefined`. If you'd like to bypass the default by explicitly setting the value to unknown, `null` is the correct option. 

`null` is known (explicit) unknown, `undefined` is unknown unknown.
