### ISSUE TITLE
Can not update return value from mongonose 

### ISSUE THREAD

**Issue by anjneeksharma** [Automattic/mongoose#9072]
Hi,

I am hitting monogdb 2 times using graphql 
  response1  is a result of first graphql find result
 response2 is result of second graphql find result

now i want to update response1['createdby']=response2['createdby']    this i am not able to do.
 response1['createdby']   is a string and response2['createdby'] is a object.

**Comment by AbdelrahmanHafez** [comment]
Mongoose documents are not plain JavaScript objects, they have special setters and getters for internal purposes.

You'll need to use [lean](https://mongoosejs.com/docs/tutorials/lean.html) in order to be able to modify the document, or convert it [toObject()](https://mongoosejs.com/docs/api.html#document_Document-toObject).

**Comment by anjneeksharma** [comment]
Great thanks @AbdelrahmanHafez  it worked for me.

**Comment by AbdelrahmanHafez** [comment]
Happy to help
