### ISSUE TITLE
*bug* - Schema default value behaves fautly on update

### ISSUE THREAD

**Issue by MatheusFerreira71** [Automattic/mongoose#9182]
**Do you want to request a *feature* or report a *bug*?**
*bug* report

**What is the current behavior?**
The schema default value does not work well when using findByIdAndUpdate() or create(). One example is, I need to create a new Date() on my createdAt field whenever a document is created, but every time I create a document the value of the field is equal to the new Date() of the moment I started the express server. Other example is when I want to update 'visualizacao' = field with findByIdAndUpdate(), but when I check the document the field still with its default value 0. My field definitions are: 
createdAt: {
        type: Date,
        required: true,
        default: new Date
    },
visualizacao: {
        type: Number,
        default: 0,
        required: true,
    },

**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce you'll need to create a schema with the specifications above and create two documents with a http request, I used express to create the routing. To reproduce the second error you'll need to findByIdAndUpdate() a document changing the value of 'visualizacao', you'll se that the value allways is 0.

**What is the expected behavior?**
When a document is created the created at is the new Date() from that creation moment, and when updated, the 'visualizacao' field changes to the value I passed.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js === 12.16.3
Mongoose === 5.9.20
MongoDB === 4.2.6
If needed - Express === ~4.16.1

**Comment by AbdelrahmanHafez** [comment]
Welcome @MatheusFerreira71 

As to the date issue, you're setting the default to be `new Date()` which is evaluated on the schema compilation to the date where you first run the app, and that's considered the default. What you want to do is to set the default to a function that returns the value you want, and mongoose will execute that function whenever a new document is created.

```js
const userSchema = new Schema({
  createdAt: {
    type: Date,
    required: true,
    default () {
      return new Date();
    }
  }
});

// or

const userSchema = new Schema({
  createdAt: {
    type: Date,
    required: true,
    // we're passing the function **without** executing it
    default: Date.now
  }
});
```

[This section](https://mongoosejs.com/docs/defaults.html#default-functions) explains how to set default values as functions in schema types.


As to the `findByIdAndUpdate` you're probably not passing in the `new` option. Instead of:
```js
const document = await User.findByIdAndUpdate(userId, { visualizacao: 1 });
```

Use:
```js
const document = await User.findByIdAndUpdate(userId, { visualizacao: 1 }, { new: true });
```
Read more on [`findOneAndUpdate`](https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate) and the options it accepts.

### Bonus tip
You don't need to add `createdAt` and `updatedAt` manually like that, mongoose provides [a cool option](https://mongoosejs.com/docs/guide.html#timestamps) that makes this a lot easier.

Just pass `{ timestamps: true }` as a second parameter and you're good to go.

**Comment by MatheusFerreira71** [comment]
Thanks for the tips, Man. See ya.
