### ISSUE TITLE
findOneAndUpdate doesn't work on nested arrays

### ISSUE THREAD

**Issue by Gazorpazo0rp** [Automattic/mongoose#9192]
I'm using mongoose v5.9.20
and Node v12.14.0
I have a problem with updating a document that looks like this:
```
{
_id:"xyzdon'tcare",
username:"john",
examTrials:Array[
    {
        trialId:"x1",
        examId:"y",
        currentQuestion:0,
        questions:Array[
            {ques1 Object},
            {ques2 object}
        ]
    },
    {
       // another object, exam trial
    }]
} 

```
here's my request handler:
```
app.post('/updatetrialsession',authenticateJWT ,(req,res)=>{
        console.log(req.body.questionIdx)
        User.findOneAndUpdate({
            username: req.user.username
          }, {
               $set: {'examTrials.$[elem1].questions.$[elem2]' : req.body.question,
                    'examTrials.$[elem1].currentQuestion':req.body.questionIdx+1
                   }
          }, {
               arrayFilters: [{'elem1.trialId': req.body.trialId }, {'elem2': req.body.questionIdx}]
          }).then(res=>{
              console.log("updated")
          })
    })

```
expected behaviour:
currentQuestion is updated and question object is updated.

The behaviour I get:
only currentQuestion updates, question object is NOT. 

how can I solve this?

**Comment by vkarpov15** [comment]
I think you're making a mistake with how you're using [array filters](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-array-filters.html). If I'm reading your code correctly, you intent `req.body.questionIdx` to be the index in the `questions` array that you're updating. `{'elem2': req.body.questionIdx}` means you're creating an array filter for questions that are _strictly equal_ to `req.body.questionIdx`, which will never match since questions are objects and `req.body.questionIdx` is a number.

I think this is what you mean to do instead:

```javascript
User.findOneAndUpdate({
            username: req.user.username
          }, {
               $set: {`examTrials.$[elem1].questions.${req.body.questionIdx}` : req.body.question,
                    'examTrials.$[elem1].currentQuestion':req.body.questionIdx+1
                   }
          }, {
               arrayFilters: [{'elem1.trialId': req.body.trialId }]
          })
```

You can read more about array filters here:

https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-array-filters.html
https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/#position-nested-arrays-filtered
