### ISSUE TITLE
Model.hydrate() is losing array fields.

### ISSUE THREAD

**Issue by typicalnerd** [Automattic/mongoose#9209]
**node@14.5.0**
**mongoose@5.9.21**

# Problem
Mongoose loosing array fields after calling save on hydrated document.

# Scenario:
1. Hydrate object without array field;
2. Save the document;
3. Mongoose setting empty array (?).

# Repro script:

``` js
const mongoose = require('mongoose')

const Model = mongoose.model('Model', new mongoose.Schema({
    field: { type: String },
    array: { type: [String] }
}))

async function bootstrap() {
    await mongoose.connect('mongodb://localhost:27017/mongoose-issue')
    mongoose.set('debug', true)

    // just create a new document
    let d = await Model.create({ field: 'test', array: ['1', '2', '3'] })
    console.log(d) // { field: 'test', array: ['1', '2', '3']}

    // hydrate document and save
    d = await Model.findById(d.id).select({ array: 0 })
    d = Model.hydrate(d.toObject())
    console.log(d.modifiedPaths) // []
    await d.save() // Mongoose: models.updateOne({ _id: ObjectId("5f031f081813ca7588ee685a"), __v: 0 }, { '$set': { array: [] }, '$inc': { __v: 1 } }, { session: null })

    // get fresh document
    d = await Model.findById(d.id)
    console.log(d) // { field: 'test', array: [] } – empty array instead of ['1', '2', '3']

    return mongoose.disconnect()
}

bootstrap()
```

**Comment by vkarpov15** [comment]
As written, overwriting the array is expected behavior because, by calling `hydrate(doc.toObject())`, you're losing the projection. Arrays automatically get a default value of `[]`, so `hydrate()` sets the default value, and then `save()` persists that default.

Workarounds:

1) Overwrite the automatic default value:

```javascript
const mongoose = require('mongoose')

const Model = mongoose.model('Model', new mongoose.Schema({
    field: { type: String },
    array: { type: [String], default: void 0 } // <-- make array `undefined` by default
}))
```

2) In 5.9.24 we'll support passing the projection in to `hydrate()` as the 2nd param, so you can pass `{ array: 0 }` to `hydrate()` to make the new Mongoose document aware of the original projection.

```javascript
d = await Model.findById(d.id).select({ array: 0 })
d = Model.hydrate(d.toObject(), { array: 0 })
```

Followup question: why are you using `hydrate()` immediately after `find()`? `findById()` already hydrates the document for you. I understand this code is an example and isn't necessarily indicative of how your code works, I'm just curious as to how you stumbled across this issue.

**Comment by typicalnerd** [comment]
Sorry for the late response, we are using [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) pattern. So we are always converting these raw objects to Document and backward.
