### ISSUE TITLE
reset properties of sub-document.

### ISSUE THREAD

**Issue by mleiver** [Automattic/mongoose#9251]
**Do you want to request a *feature* or report a *bug*?**
Bug

I have the following schema

```js
const schema = new mongoose.Schema({
  property: String,
  subDocument: {
    property1: String,
    property2: Number,
  },
});

module.exports = mongoose.model('Product', schema);
```

I want to update the sub-document, but if I change one property, I want the others to be reset. I would expect that to be the expected behavior as mentioned in [this][1] related issue.

Once I have a document instance:
```js
const document = new ProductModel({
  property: 'Hello',
  subDocument: {
    property1: 'world!',
    property2: 1234
  }
});

await document.save();

document.set({
  subDocument: {
      property1: 'new string'
    }
});

await document.save();

console.log(document);
```
What I get back:
```js
{
  property: 'Hello',
  subDocument: {
    property1: 'new string',
    property2: 1234
  }
}
```

I'd expect property2 to be reset.

How can I manage this? According to the related issue, it should be the correct behavior because I'm implicitly resetting the other fields, but I don't know if it changed in more recent versions.

[1]: https://github.com/Automattic/mongoose/issues/3875

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 12.18.2
Mongoose 5.9.23

**Comment by vkarpov15** [comment]
Unfortunately this behavior is inconsistent between nested properties and subdocuments. If you define your schema as shown below:

```javascript
const productSchema = new Schema({
  subDocument: new Schema({ property1: String, property2: Number })
});
```

You'll get your desired behavior: `document.set({ subdocument: { property1: 'foo' } })` will set `property2` to undefined.

On the other hand, if you define your schema as shown below, with `property1` and `property2` as nested properties rather than properties of a subdocument:

```javascript
const productSchema = new Schema({
  subDocument: { property1: String, property2: Number }
});
```

You'll get the behavior you described. We're planning on changing this behavior in 6.0 (see #9121) to be consistent with the subdocument behavior.
