### ISSUE TITLE
Trying to find after match in reference doesn't work

### ISSUE THREAD

**Issue by DreamplaySE** [Automattic/mongoose#9279]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Trying to find a parent document by matching to a child which is referenced in a reference array does not yield any results. For example:

Parent Model/Schema: 
```javascript
{
    Children: {type: ObjectID, ref: "Child"}
}
```

Child Model/Schema:
```javascript
{
    Data: String
}
```

`Parent.find({"Children.Data": "String in child"}).then((result) => console.log(result))`

Response: null

**What is the expected behavior?**
`Parent.find({"Children.Data": "String in child"}).then((result) => console.log(result))`
Response: Parent Instance

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.9.24, NodeJS 12.18.2, MongoDB 4.2.8.

**Comment by vkarpov15** [comment]
This is expected behavior in Mongoose. If you want to filter by `Children.Data`, you should [denormalize](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-3) `Children.Data`, or use [`$lookup`](http://thecodebarbarian.com/node-perspective-on-mongodb-3.2-$lookup-$sample.html)
