### ISSUE TITLE
pass default blank value to ObjectID

### ISSUE THREAD

**Issue by indraraj26** [Automattic/mongoose#9294]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
Is there any way to set default value objectID to ''. If i set '' i get error of cast test something. There are so many reference in other schema too. It is not good solution to check populate each time in controller and pass blank based whether user is selected or not.
```
test: {
		type: Schema.Types.ObjectId,
		ref: 'user',
              default: ''
},
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Someway to set default value to '' if nothing is passed to ref

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
Can you please elaborate on your use case a little more? What should `default: ''` do for ObjectIds?

**Comment by indraraj26** [comment]
I am having third party service they need to empty string if nothing is selected from UI. I see we cant pass default: '' since ObjectIds is not datatype of String. 
Main reason why i am asking 
```
It is not good solution to check populate each time in controller and pass blank based whether user is selected or not
``` 
Is there any better solution than checking populate at controller level and pass empty string ?

**Comment by vkarpov15** [comment]
We don't allow `''` as a valid value for ObjectIds by default. I'd recommend instead you write a custom transform, which sets null ObjectIds to `''` when you convert a Mongoose document to a [POJO](https://masteringjs.io/tutorials/fundamentals/pojo), like using `toObject()` or [`toJSON()`](http://thecodebarbarian.com/what-is-the-tojson-function-in-javascript.html). 

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = Schema({
    myId: {
      type: mongoose.ObjectId,
      transform: v => v == null ? '' : v
    }
  });
  const Model = mongoose.model('Test', schema);

  const doc = new Model();
  console.log(doc.toJSON()); // { _id: 5f2b095b59c4c21922d978f0, myId: '' }
}
```

Transforms let you get data in the correct format for the third party service without actually storing `''` in your database.

That being said, if you're sure you need to store ObjectIds as empty strings rather than undefined by default, you can use [custom casting](https://mongoosejs.com/docs/tutorials/custom-casting.html) to make empty string `''` considered a valid ObjectId as shown below. Keep in mind that `myId` will be a blank string when you save `doc` to the database.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const castObjectId = mongoose.ObjectId.cast();
  mongoose.ObjectId.cast(v => v === '' ? v : castObjectId(v));

  const schema = Schema({
    myId: {
      type: mongoose.ObjectId,
      default: ''
    }
  });
  const Model = mongoose.model('Test', schema);

  const doc = new Model();
  console.log(doc); // { myId: '', _id: 5f2b0b8c03f30c1b7c64adec }
}
```
