### ISSUE TITLE
support of readPreference=secondary connection option

### ISSUE THREAD

**Issue by ThomasDupont** [Automattic/mongoose#9295]
**Do you want to request a *feature* or report a *bug*?**

Possible bug report

**What is the current behavior?**

The get query never ended (infinite loop) when the readPreference=secondary is past on connection URL

**If the current behavior is a bug, please provide the steps to reproduce.**

Use a multi replica (as Mongo cloud), pass the readPreference=secondary in the connection URL

Try to find some object
With mongoose@5.7.13 => works fine
With mongoose@5.9.26 => infinite loop

On connection with 5.9.26, the reconnected event is triggered

**What is the expected behavior?**

Get the result on both version

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node 12, MongoDb 3.5.9

**Comment by vkarpov15** [comment]
This issue was introduced in Mongoose v5.9.17, should be fine with Mongoose v5.9.16. The fix will be in v5.9.27.

As far as I can tell, this issue is due to a change in how events are emitted by the mongodb driver in v3.5.8. Haven't been able to wrap my head around exactly what changed on the mongodb driver side, but this fix looks like it fixes the issue consistently and patches what looks like a bug in Mongoose.

**Comment by ThomasDupont** [comment]
Hello,

Thanks
I will use the 5.9.16 version while 5.9.27 is released
