### ISSUE TITLE
Deprecated indexing error in mongoose

### ISSUE THREAD

**Issue by MuhammedBeraKoc** [Automattic/mongoose#9306]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

It gives the error "(node:72792) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead." even if I set the option useFindAndModify to true. I tried to downgrade to 5.8. That didn't solve the problem but made it worse.

**If the current behavior is a bug, please provide the steps to reproduce.**

\<Model>.findOneAndUpdate(\<query>,\<replace>,\<callback>) gives the error.

**What is the expected behavior?**

Not giving any DeprecationWarning.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

*Node*: v14.5.0
*Mongoose*: 5.9.27
*Could not find mongoDB version and not installed it in local machine*

**Comment by LudwikJaniuk** [comment]
I think you need to provide more details for this to be an actionable issue. If mongoDB is not installed, how do you even expect mongoose to work, since you don't have a database to connect to? If I use `findOneAndUpdate`, I don't see any deprecationwarning like you're saying, so probably it's necessary to do something more specific to reproduce it. Could you explain what exactly it is you do?

Preferrably, provide a complete reproducing script that I could run on my computer with mongo installed.

**Comment by vkarpov15** [comment]
The deprecation warning is about creating indexes, so you also need to do mongoose.set(‘useCreateIndex’, true) as well: https://mongoosejs.com/docs/deprecations.html
