### ISSUE TITLE
SRV URIs blocked by muri in Mongoose v4

### ISSUE THREAD

**Issue by joshua-barnett** [Automattic/mongoose#9326]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When creating a `mongoose` connection using a `mongodb+srv://` URI the following error occurs (thrown by `muri`).

```
Error: Invalid mongodb uri "mongodb+srv://my.mongodb:27017". Must begin with "mongodb://"
```

https://github.com/aheckmann/muri/blob/1.3.0/lib/index.js#L28

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const uri = 'mongodb+srv://my.mongodb:27017';
mongoose.createConnection(uri);
```

**What is the expected behavior?**

It should work because the underlying MongoDB driver used by Mongoose v4 is capable of SRV, its just prematurely blocked by parsing the URL with `muri`.

- `mongodb@2.2.34` (https://github.com/Automattic/mongoose/blob/4.13.20/package.json#L27)
- https://github.com/mongodb/node-mongodb-native/blob/v.2.2.34/lib/url_parser.js#L18

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- `mongoose@4.13.20`
- `node@12.18.3`
- `mongodb@4.4.0`

**Comment by samtsai15** [comment]
Here is Node.js driver compatibility table. Maybe not support `mongodb@4.4.0 `?

https://docs.mongodb.com/drivers/node/compatibility

**Comment by vkarpov15** [comment]
We consider this a non-issue because [MongoDB Atlas only supports MongoDB 3.6 or later](https://docs.atlas.mongodb.com/cluster-config/mongodb-version/), and [Mongoose 4.x only supports MongoDB 2.4 - 3.4](https://mongoosejs.com/docs/compatibility.html). So even if we allowed `+srv` URLs in Mongoose 4.x, you couldn't use Atlas anyway.

In order to use Atlas, you need to upgrade to Mongoose 5.
