### ISSUE TITLE
Post-find hooks do not run when using for await ... of syntax

### ISSUE THREAD

**Issue by CensoredUser** [Automattic/mongoose#9345]
**Do you want to request a *feature* or report a *bug*?**

**Bug**

**What is the current behavior?**

When using the `for await ... of` syntax on a `Model.find()` query, the post-find hooks are not executed.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
(async function () {
  await mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true, useUnifiedTopology: true});

  class CatSchema extends mongoose.Schema{
    constructor(attrs = {}, opts = {}) {
      super(attrs, opts);
      this.post('find', async (results) => {
        results.forEach(result => {
          result.name = `Transformed ${result.name}`;
        });
      })
    }
  }

  const Cat = mongoose.model('Cat', new CatSchema({
    name: String
  }));


  const kitty = new Cat({ name: 'Zildjian' });
  await kitty.save();

  for await (const cat of Cat.find({})) {
    // Post find does not run
    // Output: "Zildjian"
    console.log(cat.name); // <-- THIS SHOULD BE "Transformed Zildjian", BUT IS "Zildjian"
  }

  // Post find does run
  // Output: "Transformed Zildjian"
  Cat.find({}).then(cats => cats.forEach(cat => console.log(cat.name)))
})();
```

**What is the expected behavior?**

Post-find hooks are executed no matter how `Model.find` is executed. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose version: 5.10.0
Node version: v12.18.1
MongoDB version: 4.0.8

**Comment by vkarpov15** [comment]
We will consider this for a future minor release. Right now this is expected behavior because, when we implemented this feature, we believed that skipping post hooks was more intuitive since `find()` wasn't "done" when you get one `cat`.

However, your example makes a good point: there isn't a good way for us to support `post('find')` hooks that transform the results when using [async iterators](http://thecodebarbarian.com/whats-new-in-mongoose-53-async-iterators.html). The only reasonable workaround right now would be to refactor the transformations in `post('find')` into a [method](https://mongoosejs.com/docs/guide.html#methods) on `CatSchema` and call that method explicitly in your `for` loop.
