### ISSUE TITLE
Feature request, non persistent models

### ISSUE THREAD

**Issue by skiv71** [Automattic/mongoose#9395]
Hi, I'm using mongoose purely to validate my insert / update data, because I really like the model / schema implementation, but I prefer to use my own library (via native mongodb) for all other interactions (sorry).

I've found that my on the fly model / schema creation / calling *.validate() leads to duplicate / overwrite model errors.

I sort of assumed, if I tried to define the same model with the same schema (but still new Schema(...) it would return the same, but it still produces the error.

On reading, I've found (and tested) that deleting the actual compiled models fixes this, but would it be possible to have an option to make the model non persistent?

Failing that, a way to call validate on the proposed db data before creating the actual model which has the db / mongodb methods?

**Comment by vkarpov15** [comment]
This sounds like an interesting use case. Why are you recreating the same model with the same schema repeatedly? Ideally, you only create models when your app starts, because creating a model is a pretty heavy process.


Can you please provide some code samples that demonstrate what you're trying to do?
