### ISSUE TITLE
Website Copyright does not appear to exist

### ISSUE THREAD

**Issue by Reelix** [Automattic/mongoose#9430]
At the bottom of https://mongoosejs.com/ you have  
  
> Copyright 2011 LearnBoost.  
  
Attempting to verify this over at https://cocatalog.loc.gov/, it does not seem that "LearnBoost" is a legitimate Copyrighted entity.   
  
Has your Copyright expired, or is it registered through an alternate governing body?

**Comment by vkarpov15** [comment]
It is most likely expired, currently the Mongoose IP belongs to Automattic because they acquired the company formerly known as LearnBoost. We haven't updated it because we don't have the legal expertise or connections at Automattic to confirm the details.

Is the copyright inconsistency causing problems for you?

**Comment by Fonger** [comment]
https://github.com/Automattic/mongoose/blob/master/LICENSE.md still says

> Copyright (c) 2010 LearnBoost dev@learnboost.com
