### ISSUE TITLE
Make $parent() an alias for parent() on documents and subdocs

### ISSUE THREAD

**Issue by jnardone** [Automattic/mongoose#9455]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure.  I am trying to create a virtual.

This virtual is in a subschema and needs access to the parent schema.  BUT the subschema has a field named `parent`. 

Is there another way to access the parent without changing the schema?

**What is the current behavior?**

The function is overwritten with the field value.

**What is the expected behavior?**

There is a less conflicting way to reference the function to get the parent schema.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 14.11.0
mongoose: 5.10.5, 5.10.2

**Comment by vkarpov15** [comment]
Below is a script that demonstrates the issue as I see it:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const childSchema = Schema({ name: String, parent: String });
  childSchema.virtual('parentName').get(function() {
    // Throws `TypeError: this.parent is not a function`
    return this.parent().name;
  });

  const parentSchema = Schema({ child: childSchema, name: String });
  const Parent = mongoose.model('Parent', parentSchema);

  const doc = new Parent({ name: 'foo', child: { name: 'bar', parent: 'baz' } });
  console.log(doc.child.parentName);
}
```

There are a couple of workarounds:

1) Use `ownerDocument()` instead of `parent()`. 

```javascript
  const childSchema = Schema({ name: String, parent: String });
  childSchema.virtual('parentName').get(function() {
    return this.ownerDocument().name;
  });
```

The `ownerDocument()` function gets the top-level document rather than the parent document, but that doesn't matter if you don't have more than 1 level of nesting.

2) Access the `parent()` function from the subdocument constructor:

```javascript
  const childSchema = Schema({ name: String, parent: String });
  childSchema.virtual('parentName').get(function() {
    const parentDoc = mongoose.Types.Subdocument.prototype.parent.call(this);
    return parentDoc.name;
  });
```

I think for the next release we should make `$parent()` an alias for `parent()`. We should also make `Parent.parent(this)` work to minimize the likelihood of conflicts.
