### ISSUE TITLE
Mongoose SubDocument Expiry

### ISSUE THREAD

**Issue by malenchelon** [Automattic/mongoose#9461]
I Wrote Something Like this in model

```const mongoose = require("mongoose");

const storyinSchema = new mongoose.Schema({
  storyid: { type: String, required: true },
  createdAt: { type: Date, default: new Date(), expires: "1m" },
  image: { type: String },
});

const userSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  username: {
    type: String,
  },
  email: {
    type: String,
    required: true,
  },
  password: {
    type: String,
  },
  stories: [storyinSchema],
});

const User = mongoose.model("User", userSchema);

exports.User = User;```


but this is not expiring the stories after every minute

**Comment by vkarpov15** [comment]
Unfortunately that's not how [MongoDB TTL indexes](https://docs.mongodb.com/manual/core/index-ttl/) work. `expires` is just a shortcut for creating a TTL index, and a [TTL index will delete the whole document](https://stackoverflow.com/questions/48791202/ttl-mongo-for-specific-entry-array), not a subdocument. I'm not certain how MongoDB picks which element's `expires` wins out, but that doesn't matter because TTL indexes aren't able to pull elements out of an array.

You're better off either splitting stories off into a separate collection, or expiring stories yourself using something like [node-schedule](https://www.npmjs.com/package/node-schedule).
