### ISSUE TITLE
upsert does not trigger validation

### ISSUE THREAD

**Issue by bwgjoseph** [Automattic/mongoose#9494]
I am trying out `upsert` command and it does not seem to trigger validation (on initial create). I have tried with `runValidators` but it doesn't seem to work too. From what I read, and (trying to) figure out, I thought that since 4.0, it does trigger using `runValidators` or did I understand wrongly?

Here's a repo

```js
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  // tried this doesn't work
  // mongoose.set('runValidators', true);

  await mongoose.connection.dropDatabase();

  const schema = new Schema({
      name: String,
      description: String,
      xInfo: {
          type: String,
          required: true,
      },
      yInfo: {
        type: String,
        required: true,
      }
  })

  const newDoc = {
      name: 'name',
      description: 'new desc'
  }

  const Model = mongoose.model('Test', schema);
  await Model.findOneAndUpdate({ name: 'name' }, newDoc, { runValidators: true, upsert: true });

  console.log('Done', await Model.findOne(), new Date());
}
```

The current output is that the document gets created. My expected outcome is that it should throw validation error that `xInfo` and `yInfo` is required, and therefore, doc will not be created since (in a way) this `create` and not a `update`. If there is an existing doc, then the expected outcome is that the operation will pass.

Using `mongoose: 5.10.9`

**Comment by vkarpov15** [comment]
This is expected behavior because update validators only run on paths that are specified in the update: https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths.

As a workaround, you can validate `newDoc` using the [`Model.validate()` function](https://mongoosejs.com/docs/api/model.html#model_Model.validate) before updating.

**Comment by bwgjoseph** [comment]
Hi @vkarpov15,

Sorry, I don't quite understand how it exactly works.

How do I make it validate for whole doc if it's create, and validate for the updated path if it's gonna be updated?

Since I'm running `upsert` command, I would only pass in the query as such

`await Model.findOneAndUpdate({ name: 'name' }, newDoc, { upsert: true });`

When do I pass in the validate portion? If I place it one line before the above, it will always validate based on the whole doc. Thing is I don't know when it would be a create/update since I'm using `upsert`

Hope I'm making sense of what I'm trying to do

Thanks!

**Comment by vkarpov15** [comment]
@bwgjoseph unfortunately we don't have any way to work around that because Mongoose doesn't know whether it will be a create or update either, so we can't run conditional validation based on whether an insert will happen.

Your best bet is to validate the entire doc using `await Model.validate(newDoc);` before running the upsert. `Model.validate()` also supports listing out the paths to validate if there's paths you want to skip.

**Comment by bwgjoseph** [comment]
Alright, I will try out using `validate` as you mentioned. 

Thanks alot!
