### ISSUE TITLE
Mongoose creating conflicting _id´s

### ISSUE THREAD

**Issue by Knniff** [Automattic/mongoose#9500]
**Do you want to request a *feature* or report a *bug*?**
Bug, probably.

**What is the current behavior?**
When using .insertMany() after a few Inserts I get a BulkWriteError: E11000.

I tried it multiple times with deleting the db and collection between tries.
I also updated to the newest mongoose after a few tries.

The exact error is: "BulkWriteError: E11000 duplicate key error collection: leaguebackend.participants index: _id_ dup key: { _id: ObjectId('5f968a633ac38504ef41fe7f') }"
The model in question is this: https://github.com/Knniff/leaguebackend/blob/add-match-functionality/league/participant.model.js
The code with the inserts: https://github.com/Knniff/leaguebackend/blob/add-match-functionality/league/match.service.js
This is the db-connection: https://github.com/Knniff/leaguebackend/blob/add-match-functionality/_helpers/db.js
**If the current behavior is a bug, please provide the steps to reproduce.**
Every time i run the project the problem reoccurs.

**What is the expected behavior?**
The _id key should be generated by mongoose or mongo and shouldn't conflict with itself.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongo: Atlas Version 4.2.10
Mongoose: "mongoose": "^5.10.10"
Node: v14.8.0

**Comment by vkarpov15** [comment]
The issue is that [`participantsToBeSaved` is a global variable here](https://github.com/Knniff/leaguebackend/blob/e5a9571acc8e58f285b4635b1b91a633ba6ae86e/league/match.service.js#L15) because you didn't explicitly define it using `let/const` and you're not using [strict mode](https://masteringjs.io/tutorials/fundamentals/strict#referenceerror-for-undeclared-variables). Because you're not using `await`, `saveParticipants()` runs in parallel and you end up trying to `insertMany()` the same doc multiple times.
