### ISSUE TITLE
Schema options declared as new Schema are deleted.

### ISSUE THREAD

**Issue by CatsMiaow** [Automattic/mongoose#9517]
- Node.js v12.19.0
- mongoose v5.10.12

```ts
connection.model('Test', new Schema({
  _id: { type: String, required: true, trim: true },
}, { collection: 'servers' }));
```
When the model was declared in the form above, the `collection` options were not applied.

https://github.com/Automattic/mongoose/blob/4abfb9557ab9715bff1819010e699f0f58c0ebac/lib/index.js#L489-L491
When I followed the mongoose source, the schema was initialized above.
It was confirmed that the `schema instanceof Schema` failed, so I tried to print the log.

https://github.com/Automattic/mongoose/blob/4abfb9557ab9715bff1819010e699f0f58c0ebac/lib/index.js#L472-L473

```ts
Mongoose.prototype.model = function(name, schema, collection, skipInit) {
  console.log(typeof schema, schema.constructor.name, schema instanceof Schema);
  //= object Schema false
```
In the model declaration, `new Schema()` was performed, but `false` was output in `schema instanceof Schema`.

**Comment by CatsMiaow** [comment]
This problem occurs when the mongoose modules of `connection` and `new Schema()` are different.

```js
project
+-- node_modules
|   +-- mongoose
|   +-- common-package
|   |   +-- node_modules
|   |   |   +-- mongoose
```

```ts
import * as mongoose from 'mongoose';
import { mongoModel } from 'common-package';

const mongo = mongoose.createConnection();
mongoModel(mongo);

// common-package
import { Schema } from 'mongoose';

export function mongoModel(connection) {
  connection.model('Test', new Schema({
    _id: { type: String, required: true, trim: true },
  }, { collection: 'servers' }));
  
  return connection;
}
```
The reason for doing this is to share a common mongoose model across different projects.

**Comment by vkarpov15** [comment]
Do both `project` and `common-package` use the same version of Mongoose? I ran your code and it looks like it works fine as long as both projects use `>= 5.10.8`, because #9449 fixes this issue.

Also, as discussed in this issue: https://github.com/Automattic/mongoose/issues/9449#issuecomment-702322763, I recommend making `common-package` list Mongoose in `peerDependencies` rather than as a dependency. It is exceedingly difficult for us to make sure that Mongoose v5.10.x can handle schemas from potentially different versions of Mongoose.

**Comment by CatsMiaow** [comment]
Yes I use the same version.
I solved it by moving mongoose from common-package to peerDependencies.
Thank you for answer.
