### ISSUE TITLE
I updated one document by updateOne, and he returned { n: 0, nModified: 0, ok: 1 }, but actually the record was updated

### ISSUE THREAD

**Issue by lsc949982212** [Automattic/mongoose#9560]
I updated one document by updateOne, and he returned { n: 0, nModified: 0, ok: 1 }, but actually the record was updated, There's only a very small chance of this problem

**Comment by AbdelrahmanHafez** [comment]
Hello @lsc949982212 

Can you please provide a reproduction script? Here's an example of a reproduction script: https://github.com/Automattic/mongoose/issues/9330#issuecomment-674905943

**Comment by lsc949982212** [comment]
await User.updateOne({},{},null,(err, effect)=>{
  // effect {n: 0, nModified: 0, ok: 1}
  //The problem above only arises in callback
})

const r = await User.updateOne({},{})

// r: {n: 1, nModified: 1, ok: 1}
//There is no problem using this method

**Comment by AbdelrahmanHafez** [comment]
[You shouldn't be mixing callbacks with async/await](https://mongoosejs.com/docs/queries.html#queries-are-not-promises), because using callbacks with async/await will execute the `updateOne` operation twice, you should always prefer async/await over callbacks to avoid [callback-hell](https://blog.avenuecode.com/callback-hell-promises-and-async/await) and have better code readability.

So it's either
```js
// no `await` here
User.updateOne({},{},null,(err, effect)=>{
// effect {n: 0, nModified: 0, ok: 1}
//The problem above only arises in callback
});
```

or
```js
// with `await` but no callback.
const r = await User.updateOne({},{})
```
