### ISSUE TITLE
How to realize multi level chain call

### ISSUE THREAD

**Issue by LeonYanghaha** [Automattic/mongoose#9591]
I think mongoose  ```find``` function is very good, it can ```Cat.find({name:"leon"}).populate("path").sort({"field": - 1}).skip (0).limit (10).lean();```  this chain call is very easy to use, but now I have a problem. I want to encapsulate the find function myself. How can I encapsulate it? I don't know how to encapsulate it. I know ```return this```  is a good idea, but what should I return here? I want someone to give me some ideas? Thank you for your help.

This is my code now. What should I do next. How can I write it?

```typescript

 async find(options: Object, populate?: string) {

    if (!populate) {
      return await this.mappingModel(meta.collections).find(options);
    }

    if (typeof populate === "string" && populate !== "") {
      return await this.mappingModel(meta.collections).find(options).populate(populate);
    }
    throw Error("Multi level chained calls are not supported ");
    // TODO 2020/11/27 15:09    How to realize multi level chain call
  }



```

**Comment by AbdelrahmanHafez** [comment]
It's a good idea to encapsulate 3rd libraries code with your own code, it helps with testing, and makes things easier if you want to change libraries in the future.

Assuming `this.mappingModel(meta.collections)` returns a mongoose model, you could do the following.

```ts
module.exports = {
  async find({ filter, populate, skip, limit, sort }) {
    return await this.mappingModel(meta.collections)
      .find(filter)
      .populate(populate)
      .skip(skip)
      .limit(limit)
      .sort(sort);
  }
};
```

Notice how the code doesn't do any checks for whether populate/skip/limit/sort are present or not, because mongoose is smart enough to ignore the `.populate` if it's passed an empty value, same goes for the rest of the chain.

I am not sure what you mean by "multi level chain call", can you elaborate on that?

**Comment by LeonYanghaha** [comment]
Your answer is very good, perfectly solved my problem. Thank you.

**Comment by AbdelrahmanHafez** [comment]
Happy to help.

**Comment by vkarpov15** [comment]
It sounds like you might be looking for [custom query methods](http://thecodebarbarian.com/mongoose-custom-query-methods.html), that lets you add custom helpers like so:

```javascript
catSchema.query.byName = function(name) {
  return this.find({name: name}).populate("path").sort({"field": - 1}).skip(0).limit(10).lean();
};
```

You can then use `byName()` with chaining, like `Cat.find().byName('leon').select('name path')`
