### ISSUE TITLE
New version 5.11.0 error

### ISSUE THREAD

**Issue by sumit-dcpl** [Automattic/mongoose#9613]
The new version 5.11.0 has removed some of the methods of mongoose. We are getting an error as we have put "mongoose": "^5.9.21" in package.json. We had to modify it to   "mongoose": "~5.9.21" to make it run.

Please look into this issue. As many developers will face the same.

Thanks in advance.

**Comment by jugaldb** [comment]
Hi @sumit-dcpl  please follow the thread at https://github.com/Automattic/mongoose/issues/9606

**Comment by vkarpov15** [comment]
@sumit-dcpl can you please open a new issue and follow the issue template? "new version 5.11.0 has removed some of the methods of mongoose" is too vague to be actionable, especially since we haven't removed any methods.

**Comment by orgalaf** [comment]
Just a note that might help if you are still stuck on this or on #9606 .
Removing the @types/mongoose installation and relying on the built in bindings works.
In my case it didn't work initially because because I had left over types installed in a higher directory (it's a monorepo) and tsc was catching that. Once found and deleted everything works perfect.
