### ISSUE TITLE
Backporting Typescript for v3, v4 and older v5's minors

### ISSUE THREAD

**Issue by acrilex1** [Automattic/mongoose#9625]
**Do you want to request a *feature* or report a *bug*?**
This is a critical bug.

**What is the current behavior?**
Any type definitions for plugins (for example mongoose-paginate-v2) using mongoose in @types are broken with v5.11 because even if a developper removes @types/mongoose from their package.json and delete the node_modules, the package will still be required.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Install mongoose v5.11.1
- Watch the mess of TypeScript errors
- Remove @types/mongoose and node_modules
- Everything works fine
- Install @types/mongoose-paginate-v2 or a similar package (any package depending on @types/mongoose)
- Watch the mess of TypeScript errors once again

**What is the expected behavior?**
Types should be back-ported to mongoose v3, v4 and older v5's minors so that @types/mongoose can be phased out and other types fixed (see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49902 for the issue in DefinitelyTyped).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v12.16.1
Mongoose v5.11.1
MongoDB v4.4.2 (latest stable version)

**Comment by kaznovac** [comment]
this is not a problem of the mongoose library itself, provided declarations are in conflict with published and that's why typescript complains

in your example `@types/mongoose-paginate-v2` depends on `@types/mongoose` which creates duplicate declarations.

providing types declarations for v3 and/or v4 versions will not solve the issue you're experiencing; we need to fix the https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose-paginate-v2

**Comment by acrilex1** [comment]
I closed this issue as work need to be done in DefinitelyTyped.
