### ISSUE TITLE
BUG: Cannot query for parent as a schema field

### ISSUE THREAD

**Issue by postama** [Automattic/mongoose#9645]
Bug Report

If you attempt to query for a schema field with the field name `parent` there is a TypeScript error

**Steps to reproduce.**
```
import mongoose from 'mongoose'

const TestSchema = new mongoose.Schema({
  parent: {
    type: mongoose.Schema.Types.ObjectId
  }
})

type Test = {
  parent: mongoose.Types.ObjectId
}

type TestDocument = Test & mongoose.Document

const model = mongoose.model<TestDocument>('Test', TestSchema)

const result = model.find({
  parent: new mongoose.Types.ObjectId()
})
```

Results in Error:
```
No overload matches this call.
  The last overload gave the following error.
    Type '_ObjectId' is not assignable to type 'Condition<string | (ObjectId & (() => Document))>'.
      Type '_ObjectId' is not assignable to type 'ObjectId & (() => Document)'.
        Type '_ObjectId' is not assignable to type '() => Document'.
          Type '_ObjectId' provides no match for the signature '(): Document'.ts(2769)
```

**What is the expected behavior?**
If parent is a field on the document, it should be queryable. I know `parent` has some other meaning with a subdocument referencing it's parent. I think that may be interfering here.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 10.20.1 
Mongoose: 5.11.3
MongoDB: 4.4 (not relevant, code isn't executing)

**Comment by vkarpov15** [comment]
This is one of those unfortunate issues where TypeScript isn't sufficiently flexible. Technically Mongoose documents have a `parent()` function for consistency with subdocuments, but we allow users to overwrite that function with their own properties because Mongoose doesn't use `parent()` internally and we try to avoid reserved words.

We'll remove the `parent()` definition from our `Document` class for now.
