### ISSUE TITLE
Typings: id property not being picked in LeanDocument<>

### ISSUE THREAD

**Issue by ktutnik** [Automattic/mongoose#9657]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When document converted using `toObject()` the `id` property is missing. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```typescript
const user = await UserModel.findById()
const lean = user.toObject()
console.log(lean.id) //<--- compile error
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.11.4

**Comment by vkarpov15** [comment]
This is somewhat messy because Mongoose documents have a virtual `id` property, so we don't have a good way to check whether there's a user-defined `id` that we should include in lean documents, or whether we should exclude it because it is a virtual. We'll just add `id` to LeanDocuments by default to unblock this issue.
