### ISSUE TITLE
Understandable and documented errors

### ISSUE THREAD

**Issue by MrZyr0** [Automattic/mongoose#9707]
**Do you want to request a *feature* or report a *bug*?**
A feature

**What is the current behavior?**
For now, when you make a request using mongoose and an error occurs, you get an "er" object.
The information in this object seems inconsistent.
Sometimes you have an error code, sometimes not, and you don't always have a human-readable string to describe the error.

**What is the expected behavior?**
Standardize the code for all possible errors and, if possible, a standardized object structure with a human-readable error description.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- Node v14.15.0
- mongoose v5.11.7
- Atlas MongoDB in the cloud (free cluster)

**Comment by vkarpov15** [comment]
The error codes come from the MongoDB server itself, but in certain cases Mongoose errors out before sending anything to the MongoDB server. So that's why it's inconsistent: just the nature of a codebase that talks to another very different codebase. We recommend using [error handling middleware](https://thecodebarbarian.com/mongoose-error-handling.html#:~:text=Mongoose%204.5.,set%20up%20the%20correct%20middleware) to transform error messages into formats that make sense for your app.
