### ISSUE TITLE
Error Handling Middlewares and TypeScript

### ISSUE THREAD

**Issue by gregooroo** [Automattic/mongoose#9745]
From docs [LINK](https://mongoosejs.com/docs/middleware.html#error-handling-middleware)
```js
schema.post('save', function(error, doc, next) {
  if (error.name === 'MongoError' && error.code === 11000) {
    next(new Error('There was a duplicate key error'));
  } else {
    next();
  }
});
```
There is no "code" property inside NativeError:

```js
    post<T extends Document = DocType>(method: 'validate' | 'save' | 'remove' | 'updateOne' | 'deleteOne' | 'init' | RegExp, fn: (this: T, err: NativeError, res: any, next: (err?: CallbackError) => void) => void): this;
```
in previous versions this error parameter had type ``mongodb.MongoError``.

**Comment by vkarpov15** [comment]
I'd argue this type definition is correct because the `error` parameter to error handling middleware isn't necessarily a `MongoError` instance. It could be a Mongoose `ValidationError` or potentially even a native Node.js error.

You can work around this by doing `if (error.name === 'MongoError' && (error as MongoError).code === 11000)`
