### ISSUE TITLE
Query referenced collection by id

### ISSUE THREAD

**Issue by ahmedHusseinF** [Automattic/mongoose#9770]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
typescript throws a bunch of errors

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
import { Schema, model, Document } from 'mongoose';

class UserDoc extends Document {
  name: string;
}

class PostDoc extends Document {
  author: UserDoc;
}

const userSchema = new Schema({ name: String });
const User = model<UserDoc>('User', userSchema);

const postSchema = new Schema({
  author: {
    type: Schema.Types.ObjectId,
    ref: User,
  },
});
const Post = model<PostDoc>('Post', postSchema);

Post.findOne({
  author: { _id: authorId }, // <- typescript error
  // OR
  author: authorId, // <- typescript error
});


```

**What is the expected behavior?**
can query refs by id only

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 14.15.4
mongoose: 5.11.10
mongodb: 4.4.2

**Comment by BorntraegerMarc** [comment]
I think in this case mongoose is correct and your code doesn't reflect the truth IMO. The PostDoc should look like this:
```ts
class PostDoc extends Document {
    author: UserDoc | ObjectId;
}
```

Because when you call `findOne` the `PostDoc` will not be populated and thus mongoose will just return the ObjectId.

I guess you wanna populate `author` actually. For more info see here: https://mongoosejs.com/docs/populate.html

---

PS: `Post.findOne({ author: { _id: authorId }});` will never work because you can't query like this. Use `Post.findOne({ author: 'authorId' });`

---

This issue can be closed IMO

**Comment by vkarpov15** [comment]
I took a closer look and @BorntraegerMarc is right, the issue is that `PostDoc` is defined incorrectly :+1:
