### ISSUE TITLE
debug connections and mongodb events

### ISSUE THREAD

**Issue by talr1** [Automattic/mongoose#9804]
**What is the current behavior?**
I'm facing with many sporadic socket hangs from my app container which I highly suspect is related to connections to atlas,
but I don't have a way to verify it. maybe an issue with connections timeouts, or too many requests that cant be handled by the pool...

I wanted to add more logging around mongdb events especially related to 'Connection Pool Monitoring' which was introduced in Node.js driver 3.5.0, like : 

- connectionPoolCreated
- connectionPoolClosed
- connectionCreated
- connectionReady
- connectionClosed
- connectionCheckOutStarted
- connectionCheckOutFailed
- connectionCheckedOut
- connectionCheckedIn
- connectionPoolCleared

I can see also that I can listen only to the events that mongoose listen to, i assume some of them are not namely the same as the one the driver expose.

some events are captured and handled by mongoose by are not emitted to the user, like SDAM events

is there a way to listen to the driver events?

is there a better way to analyze these kind of issues?

Thanks

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.10.19
NodeJs: 12.x

**Comment by vkarpov15** [comment]
Here's how you can listen to those events:

```javascript
'use strict';
  
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  mongoose.connection.getClient().on('connectionCheckOutStarted', ev => console.log('Got', ev));

  const schema = Schema({ name: String });
  const Test = mongoose.model('Test', schema);
  await Test.create({ name: 'test' });
}
```

See [`getClient()` docs](https://mongoosejs.com/docs/api/connection.html#connection_Connection-getClient). The `getClient()` method gives you a reference to the underlying MongoDB driver connection, so you can bypass Mongoose and talk to the driver directly.

**Comment by pritchardtw** [comment]
@vkarpov15 By the time you can access the client and add event listeners the client has already dialed and initialized connection pools so you miss events. Is there a way to hook into the client events before the initial connection is made?

**Comment by vkarpov15** [comment]
@pritchardtw you're unlikely to miss any meaningful events because Mongoose doesn't let you send any operations until connection is established. But that being said, you can always skip the `await` in `await mongoose.connect()` and just register event handlers as follows:

```
   mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  mongoose.connection.getClient().on('connectionCheckOutStarted', ev => console.log('Got', ev));
```

So that will register event handlers in the same tick of the event loop as initial connection.

**Comment by pritchardtw** [comment]
@vkarpov15 My use case is for metrics where I am tracking how many connections I have to each host in the replicaset. 
Forgive my naivete with the event loop, as written above are you not racing the initial connection? I am interesting in the `ConnectionReadyEvent` and `ConnectionCreatedEvent`.

I have worked around this by creating a mongodb client with the mongodb node driver and instrumented that before connecting. Then I connect via the mongodb client and pass it to the mongoose `connection` object via `setClient`. It is not necessarily that simple because I need to restructure my app to not use the default mongoose connection ([export schema vs export models](https://mongoosejs.com/docs/connections.html#multiple_connections)) now that I am creating a connection and passing a mongodb client. So there is still more work for me to do to transition to that model to totally instrument in an obvious way before any connections truly establish.

I will explore your suggestion, but it also seems like it could be nice to have a way to capture the mongodb client via mongoose api to enable instrumentation before any connections begin without needing to understand the event loop nuance highlighted above. It's non obvious that is what the outcome is in your proposed solution.
