### ISSUE TITLE
[IDEA] Support local and remote field selection in Schema

### ISSUE THREAD

**Issue by scucchiero** [Automattic/mongoose#9868]
When marking a field as `selected: false` you can't access it (obviously) because is not fetched.
I ran into this use case tho and thought could be a good idea to expand the functionally of select to enable fetch but remove the key after constructing the model. Thus, enabling the following.

```
const MySchema = new Schema(
  {
    username: {
      type: String,
      required: true,
    },
    password: {
      type: String,

     // this is the proposal
      select: {
          virtual: true
       }
    }
  },
  {
    toJSON: {  virtuals: true },
    toObject: { virtuals: true },
  },
);

ShowSchema.virtual("hasPassword").get(function() {
  return !!this.password
 })
```

Thoughts?

**Comment by vkarpov15** [comment]
The issue here is that you're trying to load `password`, but make sure `password` doesn't end up getting sent to the user. That's what [transforms](https://alexanderzeitler.com/articles/mongoose-tojson-toobject-transform-with-subdocuments/) are for.

Also, storing `password` on a user document is generally an antipattern: https://thecodebarbarian.com/thoughts-on-user-passwords-in-rest-apis
