### ISSUE TITLE
MongoDB related all discord bot commands are lagging, not working or taking 3 minutes+ time to respond

### ISSUE THREAD

**Issue by SurgicalCrow** [Automattic/mongoose#9932]
Not only 1 command, all the mongoDB related commands are not working, lagging or taking too much time to respond etc. This has been happening with me only in my 1 public discord bot since last night (24 hours ago). 

I don't know, what would be the solution?

**Note, I don't have any kind of error in my console :(**

Information:
**I use Mongoose@ 5.10.18 version**

**Comment by SurgicalCrow** [comment]
??????????///

**Comment by vkarpov15** [comment]
Sorry but this is not nearly enough information to be actionable. "All commands are slow" can be caused by any number of issues, including changes in your code, sudden spikes in usage, or network issues.

Here's a blog post about likely causes of performance issues: https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs,
