### ISSUE TITLE
Warning: Accesing non-existent property 'MongoError' of module exports inside circular dependency

### ISSUE THREAD

**Issue by VyrekXD** [Automattic/mongoose#9935]
v5.11.16
![image](https://user-images.githubusercontent.com/65917996/107898496-78f67400-6f01-11eb-86a0-525dc18a40ab.png)

**Comment by axelvaindal** [comment]
I have the same warning when I update mongoose to the version mentioned.
Rolled back to `5.11.11` to fix it.

**Comment by vkarpov15** [comment]
This is an issue with the underlying MongoDB node driver. Follow #9900 for updates.

**Comment by Luxcium** [comment]
I am not sure but introducing a <kbd>duplicate</kbd> tag could be useful (I was not sure if the <kbd>seen</kbd> tag was to serve the same purpose)

**Comment by vkarpov15** [comment]
@Luxcium what benefit would such a tag provide? Not saying you're wrong, we had such a tag in the past, but we removed it because we didn't see a reason to use it.

**Comment by Luxcium** [comment]
I was looking for the answer to a problem and my impression was that a duplicate would have been added linking the similar issues together with the messages that includes a reference... but I don't know if I am right or wrong... In my perception it could be useful to see other issues when, as an example, doing a google search and landing on a closed issues (because of an other similar issue is already open) or for posterity after all are closed... it's my impression that I am right but maybe my opinion is wrong or maybe it's good but not applicable in the context of your project... Maybe 🤔 I misunderstand the purpose of such tag 🏷 and I would like to have your opinion in order for me to review mine, both in a general context and in the specific context of your project... But only if such explanation is relevant and not time consuming for you...
