### ISSUE TITLE
Given the type 'T & Document', can't type the object returned by .toObject() as T

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Automattic/mongoose#9944]
I don't know if it is a bug. It seems to be so. I can tell you it worked with v5.10.11. It doesn't work anymore with v5.11.16

Given this piece code

```typescript
function transformOne<T>(document: T & Document): T {
  return document.toObject();
}
```

the compiler complaints as follows

```
Type 'Pick<Pick<_LeanDocument<T & Document<any>>, "_id" | "__v" | "id" | Exclude<keyof T, "$ignore" | "$isDefault" | "$isDeleted" | "$isEmpty" | "$isValid" | ... 46 more ... | "$isSingleNested">>, Exclude<...> | ... 2 more ... | Exclude<...>>' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'Pick<Pick<_LeanDocument<T & Document<any>>, "_id" | "__v" | "id" | Exclude<keyof T, "$ignore" | "$isDefault" | "$isDeleted" | "$isEmpty" | "$isValid" | ... 46 more ... | "$isSingleNested">>, Exclude<...> | ... 2 more ... | Exclude<...>>'.ts(2322)
```
My `tsconfig.json` is as follows

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}
```

**Comment by vkarpov15** [comment]
This is because `@types/mongoose` returned `any` from `toObject()`, which is not necessarily correct. In v5.11.x we make `toObject()` infer the type the returned object should have based on the schema, but that seems to cause problems for the design pattern you mentioned, even though `T` should be equivalent to `LeanDocument<T & Document>` in the above example.

We'll add a generic parameter to `toObject()` to allow you to overwrite the returned type, like this: `return document.toObject<T>();`
