### ISSUE TITLE
Model buffering takes more than 10000ms for `findOne` operation

### ISSUE THREAD

**Issue by kingsley-einstein** [Automattic/mongoose#9965]
**Do you want to request a *feature* or report a *bug*?**

Possibly a bug.

**What is the current behavior?**

Buffering takes more than 10000ms and this has an impact on app usage. The error message is `Operation wallets.findOne() buffering timed out after 10000ms`.
This error is intermittent (i.e it comes and goes).

**Comment by IslandRhythms** [comment]
Just from reading it seems maybe you need to use async await but I can't say more until you elaborate more and provide a script of what you are doing.

**Comment by kingsley-einstein** [comment]
> Just from reading it seems maybe you need to use async await but I can't say more until you elaborate more and provide a script of what you are doing.

I'm using async await. It was working well initially. Here's what I'm doing:

```ts
async getWallet(privateKey: string, publicKey: string): Promise<Wallet> {
    const encPrivateKey: string = Tokenizers.encryptPrivateKey(
      privateKey,
      publicKey
    );
    // Below find utilizes the indexing created on encryptedPrivateKey field
    // and is way faster than linear search on whole collection
    const encWallet: mongoose.Document & {
      encryptedPrivateKey: string;
      encryptedWallet: string;
    } = (await this.model
      .findOne({
        encryptedPrivateKey: encPrivateKey
      })
      .lean()) as mongoose.Document & {
      encryptedPrivateKey: string;
      encryptedWallet: string;
    };
    const encryptedWallet: string = encWallet.encryptedWallet;
    const decryptedWallet: Wallet = Tokenizers.decryptWallet(
      encryptedWallet,
      privateKey
    );
    return Promise.resolve(decryptedWallet);
  }
```

**Comment by henrispkl** [comment]
I'm having the same problem using `deleteMany` in a test with Jest (and TypeScript). Tried to change to `deleteOne` and the same error occurs. I've also found that since January a lot of people on StackOverflow have been getting this buffering timed out error when trying to do operations. The Mongoose version I'm using is `5.11.15`, but I've also tried with `5.11.8`.

Here's my test file
```typescript
import { Post } from '@src/models/post';

describe('Posts functional tests', () => {
  beforeEach(async () => {
    await Post.deleteMany({});
  });
  describe('When creating a new post', () => {
    it('should create a new post', async () => {
      const newPost = {
        title: 'A new post',
        content: 'Post content',
      };

      const response = await global.testRequest.post('/posts').send(newPost);
      expect(response.status).toBe(201);
      expect(response.body).toEqual(expect.objectContaining(newPost));
    });
  });
});
```
And here's my the model file.

```typescript
import mongoose, { Document, Schema } from 'mongoose';

export interface IPost extends Document {
  title: string;
  content: string;
  tags?: string[];
}

const PostSchema: Schema = new Schema(
  {
    title: {
      type: String,
      required: true,
    },
    content: {
      type: String,
      required: true,
    },
    tags: {
      type: [String],
    },
  },
  { timestamps: true }
);

export const Post = mongoose.model<IPost>('Post', PostSchema);
```

If I remove the `beforeEach` my test works perfectly, without the `MongooseError: Operation `posts.deleteMany()` buffering timed out after 10000ms` error, but I want to clear the database when testing.

I've also tried using `builkWrite`, the same problem occurs.

**Comment by kingsley-einstein** [comment]
Please it's urgent that I get a response to this. It is really frustrating and is resulting in a bad user experience. The problem was gone hours ago but is back to haunt me.

**Comment by vkarpov15** [comment]
This error message is due to Mongoose thinking it isn't connected to the database. You can prevent Mongoose from throwing this error by disabling buffering: `mongoose.set('bufferCommands', false)`, see https://mongoosejs.com/docs/guide.html#bufferCommands. However, if the issue is due to issues connecting to MongoDB, you'll just get a ServerSelectionError instead of a BufferTimeoutError.

My recommendation is to disable buffering and see if that helps. If it does, then this is a Mongoose bug and I'll need some more information to track it down.

@henrispkl please make sure you carefully review our docs on testing with Jest: https://mongoosejs.com/docs/jest.html . Jest is filled with unpredictable footguns, and your code makes it seem like you're running into one of them: setting up your Mongoose connecting in `globalSetup`

**Comment by tomgrossman** [comment]
@vkarpov15 
It looks like a `mongoose` issue since it started only after upgrading to the latest version, it may be the new `3.6.4` native driver bug as well?

Anyway, after disabling buffering with `mongoose.set('bufferCommands', false)`, it throws this error at the startup of the apps:

> Cannot call mails.findOneAndUpdate() before initial connection is complete if bufferCommands = false. Make sure you await mongoose.connect() if you have bufferCommands = false

Now I understand that I need to use `await`, but I'm using the `createConnection` and not `connect` method in order to support multiple connections. But `createConnection` returns an mongoose connection object and not a promise. So how can I implement `await` here?

**Comment by vkarpov15** [comment]
@tomgrossman you can just do `await mongoose.createConnection(...)`. Mongoose connections are partially thenable - they have a `then()` function until initial connection either succeeds or fails, so it's safe to do `await mongoose.createConnection()`.

Just keep in mind, in 6.x it'll be `await mongoose.createConnection().asPromise()`

**Comment by mariohmol** [comment]
I have the same issue, on my local machine works but not on the server. 
The Mongodb on server has been used by express, but when I run a node script to manage the database directly gives me this error.

It connects, but when I try to do a .find() it gives me the buffer error..
Did try everything proposed here with no sucess...

is any previous version working? tested a lot under 5.X but same behaviour, works local but not when runs in the server
