### ISSUE TITLE
What can I do if I can't complete a large number of queries before returning the results?

### ISSUE THREAD

**Issue by 2456844450** [Automattic/mongoose#9971]
```
let guilds = [];

records.forEach(async(val, index) => {
  let { server_id: guild } = val;
  let result = await GuildModel.findOne({ _id: guild._id }).populate(
    "channels"
  );

  guilds.push(val.server_id);
});
return res.status(200).json(guilds);
```
I want guilds to be returned after they have been pushed, but the result is that they are returned first.

**Comment by AbdelrahmanHafez** [comment]
Welcome @2456844450

The reason  you're not getting the results as expected is due because records.forEach(...) is synchronous and `res.status(...).json(...)` does not wait till the results come from MongoDB.

You would need to tell JS to wait until the documents are received from Mongo, then send the response.

```js
let guilds = [];

await Promise.all(records.map(async(val, index) => {
  let { server_id: guild } = val;
  let result = await GuildModel.findOne({ _id: guild._id }).populate(
    "channels"
  );

  guilds.push(val.server_id);
}));

return res.status(200).json(guilds);
```

This would work, but it's suboptimal because you'd be calling the database many times when you can get all the guilds with a single call.

The following tells MongoDB to find all the guilds with an array of ids.
```js
const guildsIds = records.map(record => record.val.guild);
const guilds = await GuildModel.find({ _id: { $in: guildsIds } }).populate('channels');

return res.status(200).json(guilds);
```

**Comment by 2456844450** [comment]
Thank you, your answers were very clear and detailed. Not only did it teach me how to use mongoose but it also gave me a new understanding of asynchronous and synchronous. I really appreciate you taking the time to answer my questions. Thank you from the bottom of my heart.

**Comment by AbdelrahmanHafez** [comment]
I am more than happy to help.
