### ISSUE TITLE
Generic Document causes compilation error when querying

### ISSUE THREAD

**Issue by NicolaasVB** [Automattic/mongoose#9989]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
Using a generic property in an interface that extends Document causes compilation errors when querying
This worked just fine in version 5.10.19 using @types/mongoose

**If the current behavior is a bug, please provide the steps to reproduce.**
```typescript
import { Document, Model } from 'mongoose';

interface CommonInterface<T> extends Document {
    something: string;
    content: T;
}

async function findSomething<T>(model: Model<CommonInterface<T>>): Promise<CommonInterface<T>> {
    return model.findOne({something: "test"}) // <= causes error listed below
        .exec();
}
```

Error I'm getting:
```
Argument of type '{ something: string; }' is not assignable to parameter of type '_FilterQuery<_AllowStringsForIds<Pick<Pick<_LeanDocument<CommonInterface<T>>, "_id" | "__v" | "id" | "something" | "content">, Exclude<"_id", FunctionPropertyNames<CommonInterface<T>>> | Exclude<...> | Exclude<...> | Exclude<...> | Exclude<...>>>>'.
  Type '{ something: string; }' is not assignable to type '{ [P in keyof _AllowStringsForIds<Pick<Pick<_LeanDocument<CommonInterface<T>>, "_id" | "__v" | "id" | "something" | "content">, Exclude<"_id", FunctionPropertyNames<CommonInterface<T>>> | Exclude<...> | Exclude<...> | Exclude<...> | Exclude<...>>>]?: P extends "_id" ? [...] extends [...] ? Condition<...> : Condition...'.ts(2345)
```

**What is the expected behavior?**

This shouldn't give compilation errors.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
Mongoose: 5.11.18
```

**Comment by ShadiestGoat** [comment]
Hm... Although I'm no expert, but could you be searching for `FindOneById()`?

**Comment by NicolaasVB** [comment]
I'm sorry, I just tried to give an as small as possible example that made my case. I'll edit it to be a bit more clear.

That being said, findOneById is pretty much the same as findOne({_id: ...}) so it should still work (and it did in 5.10.x)

**Comment by vkarpov15** [comment]
I'm not 100% sure why this is happening, I opened up an issue with TypeScript. The difference is due to our `FunctionPropertyNames` helper, which tries to strip out all function properties to avoid showing query helpers in autocomplete, but it doesn't seem to work correctly when you're looking at a generic function parameter. Here's an example in TS playground:

https://www.typescriptlang.org/play?ssl=26&ssc=4&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgMIHsC2n0gJLjTxIA8AKgHzIDeAUMsgM5YRgAWoA5gFxNhRcA3PWQJckcAH5eZYQF9htUJFiIUAMXToaIkHEwRejfkNpzatMAE8ADhoCuIBGGC4AClHR2o1gHL6IRnIqAF4dBgBtAGlkUGQAawgrdBhkMgBdXgAGZAgADwkAE0ZkAAoARmQAMjTo9IBKZElkEAgAN2hkXlKyOtyCiBBi5HVHZ1cQJuQY3laOqHqzCMTk1IzFaztkAGVoYDgAG2AALzgAIwOIDy9oF0Dg5DCAeUxgMBIMbFwCFWIIYIANCMxi53J5vH4AkFKBQNrYUABZdCFCAHB5hOgMGCgQpPVrdMC8XYCQ4nc6Xa4Q4D3SiNEJUNroYCFeSKGAgibIADu6Cg8QA6m82PyoHAbN5gqUcCiDrwkTLgvVeIzmeFkNLUQA6bFDPEQUrUJgsdhcXgAckgxjNyDk9XkFgA9AAqdlOUGTHl8wXsEVi7wAJilyNRcuDaM06AoSuQKsKao1B21OL1BqNBhNIB4yAtgTA1tt8idDqAA

Any help on this front would be appreciated. As far as I can tell, the easiest workaround is to just add `& any` to FilterQuery: `export type FilterQuery<T> = _FilterQuery<DocumentDefinition<T>> & any` but we'd rather avoid doing that.
